### PR TITLE
High dpi monitors support

### LINKED ISSUE #920: hi-dpi support: Screen Size Problem
Hello; I recently downloaded OpenToonz after having it be recommended to me. However because my laptop's pixel density is quite large it has caused all of the icons and such to be super small, and it is very hard on my eyes to see.

Is there a way to increase the UI size? The picture attached to this post shows how it looks on my end.

opentoonz screen size

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR fixes #920 
The same problem can be reproduced with normal monitors, by setting the scale factor to larger value in `"Display>Set custom text size(DPI)"` for Win7 or `"Display>Change the size of text, apps, and other items"` for Win10.

I confirmed that this PR works with no further problems in OSX (on Macbook pro A1502) as well.

Please note that image resources used in the software are still not suitable for high-DPI monitors. IMO they should be replaced with SVG in the future.

**UPDATE**
Note that the function `QApplication::setAttribute(Qt::AA_EnableHighDpiScaling)` introduced in this PR is available with Qt 5.6 or newer.

**UPDATE**
This PR will take care #65 as well.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by turtletooth** [comment]
Thanks for doing this.  I recently got a Wacom Mobile Studio which has a 4K resolution on a 15 inch screen.  This will be very helpful.

**Comment by shun-iwasawa** [comment]
Jenkins again

> I recently got a Wacom Mobile Studio which has a 4K resolution on a 15 inch screen. This will be very helpful.

@turtletooth I envy you .. :smile: ! I checked this PR with my Wacom Mobile Studio **13**. It works almost fine except that a little artifact appears near the menu bar.

**Comment by shun-iwasawa** [comment]
Changed to WIP as I found some glitch for OSX

**Comment by turtletooth** [comment]
I was just about to look at this too.  I'm setting up a build environment on the Wacom.  Have you done this?  I am going to try VS Community 2017.

**Comment by shun-iwasawa** [comment]
Thanks! I saw the viewer black out on launch but it seems to be separate (and critical) problem reported in #1143 . Let me check a little further.
I have not set up the build environment on the Wacom yet. I just copied binaries for checking the behavior.

**Comment by shun-iwasawa** [comment]
I found that the rendering problem still exists in the color model, the flipbook and the style editor (i.e. other QGLWidgets panels). I'll fix them right away.

> It works almost fine except that a little artifact appears near the menu bar.

I think this glitch occurs by the same cause.

**Comment by shun-iwasawa** [comment]
Almost done.  Jenkins

**Comment by turtletooth** [comment]
Is this ready to check?

**Comment by shun-iwasawa** [comment]
@turtletooth Yes, please!
In this PR I've done as follows:

- Create a new class `GLWidgetForHighDpi` inheriting `QGLWidget`, which redifines `width()` , `height()` and `rect()` in order to consider the device-pixel ratio. SceneViewer, ImageViewer and HexagonalColorWheel use this class.

- Added `AA_EnableHighDpiScaling` and `AA_UseHighDpiPixmaps` attributes to scale the UI and to get smoother icons on high dpi monitors.

- Font sizes are set with pixels, instead of points to get the same appearance on high dpi monitors.

- Introduced a new key `HighResolutionCapable=true` to `info.plist` for OSX build, in order to get smooth text on retina displays.

Thanks.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
LGTM.  Thanks for the update @shun-iwasawa

**Pull request merged**
