### PR TITLE
Changed default resolution to 1920 x 1080

### PR DESCRIPTION
**Pull request by turtletooth**
The current default resolution doesn't reflect modern video.  1920 x 1080 is a much more standard resolution.  I also added the DCI 2K and DCI 4K resolutions to the resolution profiles.

### CODE REVIEW

**Comment by kogaki** [comment]
Jenkins, confirm this.

**Comment by turtletooth** [comment]
This should take care of #327 and #330

**Comment by kogaki** [comment]
Jenkins, again

**Comment by kogaki** [comment]
Confirmed. 
There's no reason to stick to `768 x 576`. Thanks!

**Pull request merged**
