### PR TITLE
Fix filmstrip renumber issues

### LINKED ISSUE #1581: Renumbering issue
To recreate- 
- Create a level with a handful of frames:

preinsert
- Save
- Close OpenToonz (This is important)
- Reopen the scene
Insert a blank frame in the middle somewhere, a frame is lost:
inserted

I have tried to look into this but can't quite figure out what is going on.

### PR DESCRIPTION
**Pull request by manongjohn**
This PR fixes #1581 

There were 2 issues contributing to this issue:

1) The simplelevel->renumber() automatically updates the icon image cache so when an invalidateIcons() was called, it removed the updated image from the cache. Later when it loads, since the image was not in the cache, it went to the original level file for the image, thus loading the wrong one.

FIX: Removeed unnecessary calls to invalidateIcons() that followed a simplelevel->renumber();

2) When renumbering an image that was not cached, nothing would happen, so when loading the image later, it went to the original level file for the image and loaded the wrong one.

FIX: Attempt to pre-load the icon image before renumbering to ensure it is there.

### CODE REVIEW

**Comment by turtletooth** [comment]
@manongjohn What do you think about just removing the commented lines?

**Comment by manongjohn** [comment]
@turtletooth Done. :)  Thanks for reviewing.

**Comment by turtletooth** [comment]
@shun-iwasawa I've checked this and it seems to fix the issue.  Would you mind calling Jenkins on this?  Or would you like to review it?

**Comment by shun-iwasawa** [comment]
Thank you @manongjohn for the fix and thank you @turtletooth for reviewing.
It is fine if you find this seems to be OK.

Jenkins

**Comment by turtletooth** [comment]
LGTM.  Thanks @manongjohn for the fix.

**Pull request merged**
