### PR TITLE
Enable sending files to Trash in Browser on Linux

### PR DESCRIPTION
**Pull request by martinvanzijl**
Allows sending files to the Trash (recycle bin) from Browser windows on Linux. Demo below, shows me deleting a file and then restoring from the Trash in Ubuntu:

linux-delete-file-demo-after

This works for me on Ubuntu 18.04, but I'm not sure about other Linux distributions. Is anyone else able to test?

### CODE REVIEW

**Comment by martinvanzijl** [comment]
Also, this currently only works for deleting files from the home (local) drive. I haven't implemented deleting from external drives yet, and this will just print a warning to the console: "Deleting files on external drives in Linux is not implemented yet."

**Comment by RodneyBaker** [comment]
Could use a Linux user to test and render feedback on this.
Looks good from here thus far.

cc:  @pojienie

**Comment by pojienie** [comment]
I can confirm that it works on Artix Linux.

**Comment by RodneyBaker** [comment]
Thanks @pojienie 
And thank you Martin!

**Pull request merged**
