### PR TITLE
Add Mojo for MyPaint brushes

### PR DESCRIPTION
**Pull request by RodneyBaker**
Add the Mojo for MyPaint directory and brushes

### CODE REVIEW

**Comment by turtletooth** [comment]
@RodneyBaker can you submit another PR from a different branch?  You can just use "git checkout -b mojo" from the master branch and it will work.  I don't think I should merge your master branch in.

**Comment by RodneyBaker** [comment]
Thanks for your patience with me Jeremy (and everyone).
I should retire from programming because I so easily get lost in the variables but I hoping for a breakthrough.  ;)

To Do:
Create a proper branch
Use git checkout -b mojo from a new PR to get everything in line for merging

A question:
I have two PRs (one for the licensing and a spelling correction and then the primary PR at add the brushes.  Surely I can merge those two PRs into one so that I only need to submit one for merging.  Any tips for that?

If anyone has pointers to useful tutorials on github usage that will be appreciated (I'll google).  
I dove into the deeper end of the pool without learning how to swim first.

**Comment by turtletooth** [comment]
@RodneyBaker That makes sense.

Here's what to do.  Open Git Bash if you are ok with the command line
Navigate to the OpenToonz folder you are using for these PRs
And do:
git checkout patch-2 // checkout the license brancj
git merge master // combine the changes you currently have in your master branch
git push origin patch-2 // push the changes back to github (assuming origin is the name of the remote for github)

If you need help, let me know.

**Comment by turtletooth** [comment]
When you do the git merge master command, it may open vim (or a text editor) to create a new commit
If that happens, enter:
(escape key) // switch to command entering mode
:x // with the colon, save and exit command
enter

**Comment by RodneyBaker** [comment]
Got it.  Thanks Jeremy!  I'll settle in and give it a shot later today.
I use to love the command line back in the DOS days when I thought everything could be created via a batch file.  :)

**Pull request closed without merging**
