### PR TITLE
Linux support for tsound (SDL2), from pr #51

### PR DESCRIPTION
**Pull request by ideasman42**
Credit goes to François Revol for this work.

### CODE REVIEW

**Comment by kogaki** [comment]
Jenkins, confirm this

**Comment by kogaki** [comment]
SDL2 is under zlib license. So it seems ok to include them in thirdparty directory (if needed). https://www.libsdl.org/license.php

**Comment by shun-iwasawa** [comment]
Implement with SDL seems to be a reasonable solution. LGTM

**Comment by shun-iwasawa** [comment]
@ideasman42 
Thank you for a lot of improvements you have made to the software. 
You have brought consistent steps for realizing the Linux build, and moreover great benefits for other OS versions.
We'll be happy if you could contribute OpenToonz continuously and would like to assign you as a committer.
Let's improve OpenToonz together :-)

**Comment by ideasman42** [comment]
Thanks @shun-iwasawa, I'll still do PR's for anything I'm unsure of.

**Pull request merged**
