### PR TITLE
adding norwegian bokmal l10n blank files

### PR DESCRIPTION
**Pull request by Savraska2**
Request by Weblate user kingu (Allan Nordhøy)

### CODE REVIEW

**Comment by jrhyme** [comment]
@Savraska2 Would like to translate the new points of the program into Russian, there are many of them)

**Comment by Savraska2** [comment]
@jrhyme I guess will be a new easy way to do this soon.

**Comment by RodneyBaker** [comment]
Thank you @Savraska2
LGTM

**Comment by manongjohn** [comment]
Someone needs to generate the `qm` files and create create the appropriate folder in `stuff\config\loc` otherwise they won't be accessible.

Also, probably needs to be included in #3340

**Comment by Savraska2** [comment]
.qm files will be generated after full or partial translation into Norwegian.

**Pull request merged**
