### PR TITLE
Fix qt mac workflow action

### PR DESCRIPTION
**Pull request by janimatic**
Fixed mac build (github workflow action).
A distraction because seeing the mac build fail everytime distracted me... (i don't use mac os)
* Fixed Qt instal on mac using https://github.com/jurplel/install-qt-action
see this usefull command generator :
https://ddalcino.github.io/aqt-list-server/
* Added qtscript module
* Removed deprecated ninja argument 
* Raised c++ version to 17
* There maybe some redundant informations but it works fine...

### CODE REVIEW

**Comment by janimatic** [comment]
Strange, but this fails on OT's repo wihle successful in my own fork (with c++17 and also with c++14) .
Might it be due to a workflow cache issue ?
Should we remove the cache optimisations from workflow_macos.yml ?
```
    - uses: actions/cache@v1
      with:
        path: /Users/runner/.ccache
        key: ${{ runner.os }}-${{ github.sha }}
        restore-keys: ${{ runner.os }}-
```
that would explain Qt linker errors in OT repo actions https://github.com/opentoonz/opentoonz/actions/runs/8825147654/job/24229511327?pr=5425

**Comment by janimatic** [comment]
arm64  Qt : This is a recent problem with the addition of M1 macs everywhere.
Even the high quality Conan Python package manager fixed that only recently https://github.com/conan-io/conan-center-index/issues/10777 
Arm64 didn't exist before... They added a qmake argument ```'QMAKE_APPLE_DEVICE_ARCHS="arm64"'``` meaning we have to build Qt from scratch in the mac github workflow...

**Comment by janimatic** [comment]
And all this build fine in my own fork !!!
https://github.com/janimatic/opentoonz/actions
it may be because the github workfow use no M1 mac ?

**Comment by janimatic** [comment]
* Switched back to using brew, because it's the only way to get correct mac binary packages of Qt (support arm64 and x86-64
* Switched back to c++17 because this is requiered by Qt 5.15.2 (when using brew!?)
* Uninstalling qt6 that might be installed by the opencv brew package, before installing qt@5
to resolve conflicts ```error: definition of type 'QStringList' conflicts with type alias of the same name``` 
https://forum.freecad.org/viewtopic.php?t=63253
* brew uninstall qt > Error: Refusing to uninstall /opt/homebrew/Cellar/qt/6.7.0_1  because it is required by opencv, pyqt and vtk, which are currently installed.
* brew uninstall --ignore-dependencies qt
* Now the c++17 removed binary_finction template...
error: no template named 'binary_function' in namespace 'std'; did you mean '__binary_function'?
 '__binary_function' declared here
using __binary_function = __binary_function_keep_layout_base<_Arg1, _Arg2, _Result>;
It seems they where nice and kept a backward compatibility layer (as usual)...
* same for unary_function > __unary_function

**Comment by manongjohn** [comment]
> * Removed deprecated ninja argument

I think this was the only thing needed to allow macOS action builds to work again.

MacOS builds without issue using Qt 5.15 compiling with C++11.

**Comment by janimatic** [comment]
> 5
hello John, ok thanks for the tip, i am struggling with this... i'll try your suggestion.
Pretty irrational though to get Qt saying that it requieres c++17 for exemple... etc...
I am not getting it for the moment..

**Comment by janimatic** [comment]
@manongjohn  @RodneyBaker 

* In addition to removing the obsolete ninja argument,

* All the arm64 issues might be due to 
`runs-on: macos-latest` :
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

replacing with
`runs-on: macos-12`
fixes it...
That would explain inconsistancies while the workflow_macos.yml didn't change, since latest behavior change over the time...

* Still i think FindQt5 needs a minimal fix (I didn't retry without that change since i switched to macos-12) :
`        cmake ../sources -G Ninja -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DQT_PATH=$(brew --prefix qt@5)/lib -DQt5_DIR=$(brew --prefix qt@5)/lib/cmake/Qt5 -DCMAKE_PREFIX_PATH=$(brew --prefix qt@5)/lib/cmake/Qt5  -DWITH_TRANSLATION=OFF
`

* I've just created a new branch with those minimal changes in my fork 
https://github.com/janimatic/opentoonz/actions/runs/8832347086/job/24249480116
that builds successfully.
But my fork has always worked anyway regarding the workflow_macos.yml, 
that's something i don't understand...
Might there be a configuration repo specific outside of the yaml files ?
So i am not yet 100% confident...

* I am submiting a new pr with those minimal changes, and we'll see how it build in this repository...
This one (Fix qt mac workflow action) could be renamed something like  **mac arm64 & c++17 support** ...
as it could be usefull in the future...

**Comment by janimatic** [comment]
hey @RodneyBaker i noticed that you just restarted this mac job ,
but i think
`CMake Error at CMakeLists.txt:383 (CMAKE_IGNORE_PATH): Unknown CMake command "CMAKE_IGNORE_PATH".`
should really be fixed first..
It should be easy, with replacing
`cmake_minimum_required(VERSION 2.8.11)`
by something like
`cmake_minimum_required(VERSION 3.28.1)`
in toonz/sources/CMakeLists.txt

**Comment by manongjohn** [comment]
Can you please close this PR, for now, and work this out in your fork so we are not spammed by every little commit change you make?

Reopen it or create a new PR once you have it worked out.

Additionally, once you figure it out, please squash your commits.

**Comment by janimatic** [comment]
> Can you please close this PR, for now, and work this out in your fork so we are not spammed by every little commit change you make?
> 
> Reopen it or create a new PR once you have it worked out.
> 
> Additionally, once you figure it out, please squash your commits.

In my fork all this worked from the begining, like i told you
Anyway i just doing this to help i don't have a mac...
I think i will stop

**Comment by janimatic** [comment]
Since the other pr is working on mac M1, i am closing this for now.
It was interesting 
to discover that switching to c++17 isn't a problem at all (just needs some ifdefs for unary_function > __unary_function and binary_function > __binary_function ), 
and to understand the various mac build problems more deeper...

**Pull request closed without merging**
