### PR TITLE
Fix fx schematic display issues

### LINKED ISSUE #964: Schematic:  Wrong display nodes with click on "Reorder Nodes"
I record my screen, [watch here](https://drive.google.com/open?id=0B9wCH2-wDK31U1RZWTdRRUx2S3M).

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40069114-bug-wrong-display-nodes-when-click-on-reorder-nodes-inside-fx-schematic-window?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2318: Missing Nodes In FXSchematic
### Issue Summary

I have lost my nodes in FX Schematic
### Screenshot or Video Reference

this would be a pic of an empty box or a video of me scrolling in an empty box
### Steps to Reproduce

not exactly sure but seems to be some combo of 1)taking things in/out of sub-xsheets 2)grouping/ungrouping in FXschematic 3)clicking "reorder node"
### Expected Results

For one of the tools to get my nodes back into view sized reasonably

### Actual Results

I cant find the nodes in this particular sub x sheet, none of the helper buttons work either(reorder, zoom to fit etc) i am either zoomed out or in way to far on some weird spot.  (i can go on a mission to get these nodes visible again but this is an issue.

related to this issue perhaps, the "reorder nodes" breaking layout in FX schematic sometimes(so u cant see output and xsheet anymore) and also to issue of sometimes when opening group the group opens to cover everything in the viewport.

1.totally missing nodes(no buttons work to get into view)
2.opening group expands to cover entire viewport making everything unclickable
3."Reorder Nodes" button sends xsheet and output nodes impossibly far to the right.(clicking reorder usually doesnt work.....saving >close/reopen >then click reorder... usually does work)

*sometimes the stage schematic has issues like above but the reorder node button seems to work better than it does when in FXschematic.

p.s. I run into the above issues very frequently. lots of closing program and reopening hoping that clicking reorder nodes will work and i willnt have to reconnect or explode/collapse things to fix schematic
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

### LINKED ISSUE #2421: Exploding/Opening macro node sometimes causes all nodes to be stacked
### Issue Summary
As the title describes, Macro FX nodes may sometimes seem to lose the positions of their child nodes.

### Screenshot or Video Reference

image
Left: The issue | Right: Expected

### Steps to Reproduce
1. Place a macro FX node
2. Choose 'Open Macro FX' or 'Explode Macro FX'
There is a chance that all of the nodes will be stacked on top of each other.

I have not found a way to trigger this behavior consistently, at this time, it appears to be random; even when placing two of the same Macro FX in a row, one may open correctly and the other may not.

Notes:
One an instance of a Macro FX opens as a stack, it is **guaranteed** to continue to do so.
This applies in cases such as; closing & reopening, cut & pasting, copying & pasting (all pasted nodes will be afflicted), and reloading the scene.

Repeat steps 1 & 2 for each Macro FX you have, some may exhibit the issue while some may not:
image
Here the 'Outline' Macro FX did not open correctly while the 'Fire 1' Macro FX did this time.

### System Information
1.2.1 (Nov 26 2018)
Windows 10
I7 5820l
16gb ddr4
GTX 980 4gb

Let me know if you need more information

### PR DESCRIPTION
**Pull request by manongjohn**
This PR fixes #2318 and fixes #2421 as well as fixes #964 where reordering fx nodes results in nodes so far apart you only see a white line.

PR #2318 is a result of a combination of a few issues: 1) All the nodes are in a group, 2) Fx still linked to empty columns, and 3) An internal calculation issue.  The nodes reordering far apart issue stems from the internal calculation issue.

Corrected the issue as follows:
1) Fixed calculation issue

Whenever calculating the position of the node, there were a few places that were not accounting for a node's position being `TConst::nowhere` so offset adjustments from current location moved it from `TConst::nowhere` to a position that was not visible or easily reachable in the viewer. 

Where appropriate, added logic to check if current position is `TConst::nowhere` and skip the offset adjustment.

2) Reset all nodes to `TConst::nowhere` for all Fx nodes just prior to reordering to ensure the node was not previously adjusted erroneously from nowhere.

NOTE: This PR will not automatically fix existing scenes with these issue upon opening because node positions are stored in the .tnz file.  Users with this issue would need to reorder the nodes and likely need to fit to window to get it to display properly.

### CODE REVIEW

**Comment by manongjohn** [comment]
@shun-iwasawa Looks like OS X builds are having issues QT path issues again.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Regarding the macro fx issue #2421 , the stacking behavior seems to be resolved. However the `Open Macro Fx` seems to open its content at away from the node position. Please try the following operations:

1. Create macro fx with RMB menu of the Fx Schematic.
1. Right click the macro fx node and select `Open Macro Fx` .
1. The fx is opened away from the node position, it seems to be always at just above the Xsheet node.
1. Close the macro fx, move the node and open it again. Now the node opens at the correct position.

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
Now it works fine! Thank you so much @manongjohn for the fix! LGTM

**Pull request merged**
