### PR TITLE
Fix lip sync extend to end

### LINKED ISSUE #3218: Importing a Lip Sync file doesn't start or end with the correct 'rest' drawing
This is a small issue and one that I can work around. However, it should be an easily fixed issue.

Importing a lip sync file using the menu item: Xsheet > Apply lip sync data to column, correctly uses the 10 drawings I've selected in the dialog, but if my lip sync info doesn't start on frame 1, it adds drawing #9 in those frames. It should add drawing #10, the rest frame. Likewise, at the end of the animation, it adds a single frame of drawing #9 or if you tick the box at the bottom of the dialog (Extend rest drawing to end marker), it extends drawing #9 to the end, when it should use drawing #10.

Here's the dialog showing that drawing 10 is the rest drawing:

LipSyncModal

### System Information
I'm on Windows using version 1.4

### PR DESCRIPTION
**Pull request by turtletooth**
Fixes #3218

Fixed the icon size in the lip sync popup window 
and fixed extend rest drawing to end.

### CODE REVIEW

**Comment by turtletooth** [comment]
Note, this only works for Morevna or version 2.0.  Version 1.0 doesn't set a rest frame at the beginning.

**Comment by gab3d** [comment]
@turtletooth
sorry, 2.0 of what software? 🙄

**Comment by turtletooth** [comment]
Jenkins

**Comment by DarrenTAnims** [comment]
Thank you Mr Turtle. That's amazing

**Comment by shun-iwasawa** [comment]
Jenkins

**Pull request merged**
