### PR TITLE
Tahoma2D porting (Dec 11, 2020) by artisteacher, jeremybullock and manongjohn

### LINKED ISSUE #1717: RGB Picker Tool side effect of zoom/skew
At first I thought that this thing happens only in OTX, but it turned out that in the Morevna Edition the same bug.
Try to play this bug in OT 1.2 (I have not installed it):
1.Use some non-standard vector fill.
2. Switch to the RGB Piker Tool.
3. For some reason now, this tool has the ability to zoom, which can deform even the camera.
ezgif-3-a9859e5d2e

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/53422742-rgb-piker-tool-has-a-side-effect-of-zoom-gif?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2566: Some windows cannot adapt to show extra settings.
### Issue Summary
1. While using OpenToonz UI in any other language than English, the **Output** settings window can't correctly show the **Other Settings** section.
(i.e. it can't seem to correctly accomodate the extra content in the available space, or expand the window)
If the window bottom border is manually expanded, the settings finally get to show correctly.

2. This same problem happens also in the File > Convert... options window, when trying to convert to TLV (this time it happens even in English).

### Screenshot or Video Reference
output
convert

Windows (any)
OpenToonz 1.x

### LINKED ISSUE #3068: [Proposal] Preferences:  Move options to Saving category
@shun-iwasawa @manongjohn 
I'll copy this proposal from #2543 here, to gain visibility...

Move backup saving preferences to the Saving category.
This reorganization would, both, unclutter the General section, and find a more logical place for these options too:

imagen

imagen

### LINKED ISSUE #3136: (Proposal) Rename Preferences > Interface > Icon Size as "Level Strip Icon Size"
Icon Size, from an outside perspective, sounds like all the icons in OpenToonz should change with it. However, what it changes is the icons in the Level Strip. To make this clearer to beginners, the "Icon Size" setting should probably be renamed to "Level Strip Icon Size"

### LINKED ISSUE #3189: On Macs Resize Brush Tool Still Shows Ctrl+Alt
### Issue Summary
On Windows, the option in Preferences > Tools that says "Use Ctrl+Alt to Resize Brush" makes sense, but on Macs this should show Cmd+Option (is there a shorter term for Option?) as that's what you press to resize the brush

### Screenshot or Video Reference
Screen Shot 2020-03-28 at 11 07 20 PM

### System Information
* **OpenToonz Version**: March 28th Nightly
* **Operating System**: macOS Catalina 10.15.4
* **CPU**: Quad Core i5
* **Memory**: 8 GB LPDDR3

### LINKED ISSUE #3459: Function Curves window does not update after switching between curves.
**Describe the bug**
If you switch between the segments of the curves using the buttons, then when you select another curve, the selected segment is not displayed in the window until you move the cursor over the window.

ezgif-7-c8be4e00665b

**Device Information:**
Windows 8.1

### LINKED ISSUE #3488: Crash when exploding sub-xsheet containing audio level.
**Describe the bug**
The explosion of a sub-xsheet containing an audio file is so powerful that it even destroys the program.

**To Reproduce**

1. Collapse audio level
2. Explode obtained sub-xsheet

ezgif-3-256e99162eea

**Device Information:**
 - OS: Windows 8.1
 - OpenToonz Version: latest

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will port several bug fixes done in Tahoma2D as follows:
- tahoma2d/tahoma2d#164 Fix override warnings
  by @artisteacher 
  I reverted `OpenGlPainter::onRasterImage()` to resolve error in OT.
- tahoma2d/tahoma2d#186 Make tabbing through color fields easier
  by @jeremybullock
- tahoma2d/tahoma2d#194 Fix crash on exploding sub xsheet with only sound
  by @jeremybullock
  Note that this PR was not enough to resolve the crash in OT so I did additional fix in the subsequent commit.
  This fixes #3488 
- tahoma2d/tahoma2d#226 Fix RGB picker offset
  by @jeremybullock
  This fixes #1717 
- tahoma2d/tahoma2d#240 Do not remove unused styles 0 and 1 on default palettes (partially)
  by @manongjohn 
  I ported only the part for protecting the style # 1 of the normal level palette since OT does not have the default palette feature.
- tahoma2d/tahoma2d#258 Fix issues reported in OpenToonz
  by @jeremybullock
  Note that for #3189 the option was just removed in Tahoma2D so I added a fix in another way. I haven't tested the fix in MacOS, though..
  Regarding #2566 the dialogs becomes with fixed size in Tahoma2D (since it always work in pixels?). In OT they need to be adjustable in size so I made a fix in another way. The fixes are done in the Convert Popup and the Level Settings Popup. ~~The Output Settings Popup already seems to work properly without the fix.~~ (Sorry! I forgot to check the output settings in non-English environment and confirmed that the problem remains. I'll tackle with it.)
  This fixes #3189 , fixes #3136 , fixes #3068 , fixes #3459 and fixes #2566 .

Thank you @artisteacher , @jeremybullock and @manongjohn !

### CODE REVIEW

**Comment by RodneyBaker** [comment]
@shun-iwasawa While the Github Actions (Windows) build passed all checks the downloaded file fails to run due to missing zstd.dll and brotlidec.dll files.  These appear to relate to compression and decoding/decompression but... not sure.

In other news:  The regular windows appveyor article for this PR works great!
Thanks!

It would be good for others to test the Github Action artifacts for Mac and Linux as well.

**Comment by artisteacher** [comment]
> Note that for #3189 the option was just removed in Tahoma2D so I added a fix in another way. I haven't tested the fix in MacOS, though.

This works fine on macOS & makes it consistent with how shortcuts are displayed in the menu:
Screen Shot 2020-12-13 at 9 59 31 PM

It would be great if the display of the shortcuts in the "Configure Shortcuts" window used the symbols too, instead of being Windows specific.

**Comment by shun-iwasawa** [comment]
@RodneyBaker Thank you for letting me know the error of missing libraries. I found that `Qt5Core.dll` is depending on `zstd.dll` since the default algorithm for resources compression has been changed from zlib to zstd in the latest Qt. And `Qt5Multimedia.dll` is depending on `brotlidec.dll` . I'll look into it.

@artisteacher Thank you for verifying the fix in macOS version. 
> It would be great if the display of the shortcuts in the "Configure Shortcuts" window used the symbols too, instead of being Windows specific.

Yes, indeed. I'll check if it can be done in the same way.

**Comment by RodneyBaker** [comment]
Thank you @shun-iwasawa for porting over all these bug fixes.
And for the appropriate modification where necessary.
Much appreciated!

**Pull request merged**
