### PR TITLE
touch control optional

### PR DESCRIPTION
**Pull request by shun-iwasawa**
#1579 
This PR will make the touch control optional in the preferences (added to "Drawing" category).
With this option being disabled `SceneViewer::gestureEvent()` and `SceneViewer::touchEvent()` will not be called and some controls will be caught by mouse event instead.
As there is a case that the touch control doesn't work properly with trackpad, I set this option to `false` (disabled) by default in OSX. 
Sorry @turtletooth for not notifying it earlier.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
@shun-iwasawa Would you be willing to make this a command that can be toggled with a shortcut?  I can see instances where it would be nice to use touch to pan, but then use the selection tool, animate tool, or control point editor with touch.

**Comment by shun-iwasawa** [comment]
OK, let me see.

**Comment by artisteacher** [comment]
Thanks for resolving this so quickly! A shortcut would be great, I do really appreciate some of the touch gestures. Also, is it possible that it’s the one finger pan specifically that’s stopping the tools from being functional with a mac touch pad - since one finger is used to trigger normal actions on the trackpad? Could there be a preference where people could choose between 1 or 2 fingers for panning?

**Comment by shun-iwasawa** [comment]
Moved the option from the preferences to toggle menu in the menu bar ( in Edit menu in the Default menu bar ). Now it can be assigned shortcut key.

Jenkins again

**Comment by ernesttx** [comment]
Thank you for making this optional. I am using a Surface Book and the pen starts drawing and then about 2 seconds in, it switches to 'pan' the drawing. So, it is not specifically a touchpad issue. 
When I use the button on the pen, I can draw without any issues. But, as you can imagine, drawing this way is quite annoying. I'll test out and let you know. And just for the record, I commend everyone involved with development for doing a fantastic job of bringing features and fixes to this software. Thank you.

**Comment by shun-iwasawa** [comment]
@ernesttx 
I disabled the touch control by default on Windows, in order to avoid occurrence of the problem on a new user.

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by turtletooth** [comment]
Tested and LGTM.  This can be merged when Jenkins finishes.

**Comment by turtletooth** [comment]
Thanks @shun-iwasawa for this!

**Pull request merged**
