### PR TITLE
(WIP) Fix crash when pressing Ctrl+X while moving a line (#2148)

### PR DESCRIPTION
**Pull request by martinvanzijl**
Fixes the crash that occurs when pressing Ctrl+X while moving a line (#2148). The selected line will now be cut as expected upon pressing Ctrl+X.

NOTE: I have not solved the Ctrl+Z issue yet.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by manongjohn** [comment]
I can confirm this fixes the issue when you use Ctrl+X (cut), but I can duplicate this crash when using DEL (delete) or even Ctrl+Z (undo) to undo the stroke.  Basically anything that causes the stroke to disappear while in the middle of moving the selection will cause this to crash.

**Comment by shun-iwasawa** [comment]
I think triggering command with shortcut key while dragging with tool tend to cause an unexpected result.
We should probably think of rather general resolution, like filtering shortcut events if the current tool is in dragging or in busy state, than adding a patch to every command on an ad hoc basis.

**Comment by martinvanzijl** [comment]
I made some further progress on this. It now also handles the scenario where you press Delete while moving the line, use Undo/Redo shortcuts (Ctrl+Z) or open a dialog (e.g. with Ctrl+N). 

However, it may be easier to simply disable these shortcuts in "SceneViewer::event" while the tool is busy with a mouse-drag. Any votes?

**Comment by RodneyBaker** [comment]
@martinvanzijl  Something appears to have gone very wrong here.
365 commits?  700+ documents changed?

**Comment by manongjohn** [comment]
Seems the commit history on your branched got messed up somehow. Not sure what you did to cause it. 

I've done this on occasion when I pull in the latest OT master into my working branch and somehow remerge existing commits again.

It's also causing conflicts so this PR wont build. Needs to be fixed.

**Comment by martinvanzijl** [comment]
@RodneyBaker @manongjohn Yes, I thought it seemed odd...

I think I'll make a new PR altogether and see if I can copy over the conversation history.

**Comment by martinvanzijl** [comment]
Closing this PR since I somehow messed up the commit history.

New PR is #2912.

**Pull request closed without merging**
