### PR TITLE
Improve sound quality for playback and scrubbing on Linux

### PR DESCRIPTION
**Pull request by morevnaproject**
This improves sound quality for playback and scrubbing on Linux. Possibly affects other platforms.

This pull completes fix for #1097.

Testing binaries available as of OpenToonz Morevna Edition 1.2.0.3 - https://morevnaproject.org/2018/08/18/opentoonz-morevna-edition-1-2-0-3-released/

### CODE REVIEW

**Comment by artisteacher** [comment]
Playback and scrubbing quality are significantly improved in MacOS too. Thanks so much for this!

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by artisteacher** [comment]
On a related note, after reordering or cutting part of an audio level, the playback does not update until the scene has been reopened (except when playing through the column header)  #1739

**Comment by shun-iwasawa** [comment]
Travis CI w/ Linux gcc compiler claims the following error:

```
/home/travis/build/opentoonz/opentoonz/toonz/sources/common/tsound/tsound_qt.cpp:185:84: error: no matching function for call to ‘QObject::connect(QPointer<QAudioOutput>&, void (QAudioOutput::*)(), TSoundOutputDeviceImp::play(const TSoundTrackP&, TINT32, TINT32, bool, bool)::__lambda0)’
       QObject::connect(m_audioOutput, &QAudioOutput::notify, [=](){ sendBuffer(); });
                                                                                    ^
```

I still have no idea why this error arose.

**Comment by ave4** [comment]
I tested this patch. He corrected the problem of a jerky sound under linux.

My personal repository with a patch: https://github.com/ave4/opentoonz

**Pull request merged**
