### PR TITLE
Various typo and translation of source comments + whitespace tweaks

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by RodneyBaker** [comment]
@luzpaz In considering that this PR won't likely be merged before v1.6 release...

I'm not entirely sure how to best collaborate on a set of commits in a PR but given that there are quite a few other typos still in the code perhaps we can add them to this PR?   I'm referring to non-code typos such as those in commentary and in non-program areas of the UI.  I recently ran across one in the effects that I thought had been fixed but is not.

If you are able and willing perhaps we could collect those 'trivial' typos in this PR and fix them all at once.

Note that I am not opposed to merging this PR as is... just anticipating more typos PRs to come.

**Comment by luzpaz** [comment]
I understand your hesitancy. IMHO, to keep things fresh (avoid code rot) it would make more sense to merge the changes now. I circle back to check on typos from time to time and when I do I also translate source comments here and there. The translation of the italian comments to english is a herculean effort :sweat_smile: it requires technical understanding of the code too. I'm doing little bits here and there from time to time. Do you mind ? Or shall I stop?

**Comment by luzpaz** [comment]
One last tiny trivial things, I found a source typo in a variable, see ef11047
Changed `samplesReaded` to `samplesRead`  
I was tempted to also correct `bytesReaded` to `bytesRead` but saw that the latter is used elsewhere in the code and I was worried about this change causing a code conflict of some sort

**Comment by RodneyBaker** [comment]
I will defer to @shun-iwasawa on merging PRs that aren't of high priority.
My hesitancy to merge non essential PRs is solely based on the fact the v1.6 release candidate has just been published.
There are a number of PRs waiting to be merged after release of v1.6 at the end of this month and I see no reason why this PR should ideally also be one of those.

I personally don't have any problem with updating italian comments although I would imagine best coding practice might recommend updating the comments only when code related to that commentary is also updated.  But...

You are doing good work in fixing typos and updating comments and I'd hate to see you stop.  
In my estimation, the timing of this PR is just not ideal for immediate merger given the status of v1.6 release and the trivial nature of the typos.

**Comment by luzpaz** [comment]
> I personally don't have any problem with updating italian comments although I would imagine best coding practice might recommend updating the comments only when code related to that commentary is also updated. But...

Agreed. And that's what I was aiming for when hunting for typos. 

> You are doing good work in fixing typos and updating comments and I'd hate to see you stop.
In my estimation, the timing of this PR is just not ideal for immediate merger given the status of v1.6 release and the trivial nature of the typos.

Thanks! Totally understand. Whatever works for y'all. No pressure, of course. Thank you for everything y'all do!

**Comment by gab3d** [comment]
@luzpaz 
good job!

some tweaks on the translations:

*permette di calcolare varie grandesse sul poligono della regione, come l'area, il baricentro, il perimetro...
per usarla si deve sottoclassare la classe virtuale TRegionFeatureFormula specificando la formula della grandezza da calcolare.*
-->
allows you to calculate various measurements on the polygon of the region, such as area, center of mass, perimeter...
to use it, you must subclass the virtual class by specifying the formula of the measurement to be calculated.


*bordi arrotondati*
-->
rounded edges


*faccio una copia di m_path per poi usarla per la resizeIcons()*
-->
make a copy of m_path to be able to use it for resizeIcons ()

**Comment by luzpaz** [comment]
Thanks @gab3d. Any chance you can push those changes to my branch (so I don't need to go hunt for them in the code). If not, I'll hunt them down and change them myself.

**Comment by RodneyBaker** [comment]
I should add here that in a perfect coding world... which we will never be in but it's good to have an ideal to strive for... there wouldn't be any comments as the code would speak for itself.

If/when we are updating comments (or translating comments) we should consider if rather than update/translate can the comment be removed entirely because:  1) the related code... and therefore the comment... is no longer required  2) the related code that lead to the comment is resolved.

As Uncle Bob might say, comments are often added to indicate a failure to implement adequate code.

I do think we need reliably good ways to document code... we need to study it deeply and thoroughly... especially for the purpose of those learning how to program Opentoonz given the source code available.  Ideally however, that particular documentation should not be via the comments.

**Comment by luzpaz** [comment]
This is more a philosophical argument that I'm sure different programmers feel differently about. I'm feeling pretty neutral about it (but again, I'm not a coder) :stuck_out_tongue:  Whatever you decide to do, I'm cool with.

**Comment by RodneyBaker** [comment]
I have been staring at this with an eye to merge as the changes are trivial but I haven't convinced myself to ignore the voice in my head that recommends waiting.  ;)

I stated before I would defer to @shun-iwasawa for merging prior to v1.6 release so perhaps best to stick with that.

**Comment by luzpaz** [comment]
@gab3d I've made the requested changes you asked for in 63cba86  
JFYI, in the future consider using the Github interface to mark the areas in the code that you're referring to. It took a while to find those code snippets you mentioned :sweat_smile:

**Comment by luzpaz** [comment]
rebased

**Comment by RodneyBaker** [comment]
Thanks for you patience with this @luzpaz.
LGTM

**Pull request merged**
