### PR TITLE
Extend Previous Cell to Selection command

### PR DESCRIPTION
**Pull request by manongjohn**
This PR introduces a new action/command that allows you to select 1 or more cells in the xsheet (in either xsheet or timeline mode) and extend the hold on the last filled cell before it, up until either the next filled cell or the end of the selection. 

extend_prev_cell

This does not work on are Sound Levels or any level that is currently locked.

Feel free to suggest a better label for this command. :)

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
What do you think the purpose of this command? As far as I can see, this would be useful for filling up the xsheet after drawing frames with the `Enable auto-stretch frame` preference option being OFF. Right?

Anyway, I like your implementation separating undo instances for each segment. It's simple and clever :+1: 

Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by manongjohn** [comment]
@shun-iwasawa Yes, that was the main inspiration for this feature. I had always planned on creating this after that PR and finally figured out how I wanted to implement it.

**Comment by shun-iwasawa** [comment]
Well, I think I will name this command in Japanese as `空コマを埋める` (= Fill in empty cells) .

**Comment by manongjohn** [comment]
Hmm. I kind of like that better. Let me change the label

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM Thank you @manongjohn for the useful feature!

**Pull request merged**
