### PR TITLE
Theme Fixes for v1.4

### PR DESCRIPTION
**Pull request by konero**
No changes to C++ files at all, only user config stylesheets.

---

This fixes some things in the stylesheets, I intended this to be for v1.4.

**All themes**
- adds style to the QProgressBar
- adds focus to QComboBox
- redesigns indicators to make them easier to work with
- adds text hover to radio buttons
- adds highlight for disabled items in the menu (for keyboard navigation)
- styles the !editable QComboBox properly (the font picker for example)
- fixes Palette icons border
- fixes Style Editor first tab child placement
- allows the Style Editor sliders to go even thinner before they auto-hide

**Light theme**
- adds a focus color border to controls like other themes
- color balances the x-sheet and file viewer
- brings back special text color for folders in the browser window (dark blue)
- add round edges to scroll bar handles

**Dark theme**
- boost contrast for input fields and context menu
- radio buttons now match checkbox style
- x-sheet color balancing (for onion skin bar)

---

New QProgressBar style, it uses the same concept as the play bars.

prog1

Editable QComboBox. You can also see the new focus color for light theme.

lightfont

New indicator design, crisper icons, checkboxes:

checknew2

For radio buttons, I made it so the text string has a hover effect like checkboxes have, I also made sure the currently selected option has no hover effect as it's exclusive:

radiobuttonnew2

Disabled item menu, since at the moment OpenToonz doesn't skip disabled items on focus this allows easier keyboard/shortcut remote navigation.

disableitem

New contrast for the dark theme.

image

This is how thin the color sliders can go now, before and after:

colorslider

---

You can use them now by downloading the QSS pack below.

**Download:** [QSS_New.zip](https://github.com/opentoonz/opentoonz/files/4058323/QSS_New.zip)

### CODE REVIEW

**Comment by gab3d** [comment]
Nice changes. Thanks!!

**Comment by artisteacher** [comment]
I love the thinner color sliders. On macOS, I'm not seeing the radio/checkbox styles pictured above, the green render progress, nor the disabled menu item highlighting. The menu highlighting is probably not surprising since OpenToonz on macOS uses a native menu.

**Comment by konero** [comment]
@artisteacher That's strange, I tried the zip and it's fine for me. You can try this one (I'll add it to the top post too) just in-case..

[QSS_2020-1-13.zip](https://github.com/opentoonz/opentoonz/files/4053962/QSS_2020-1-13.zip)

**Comment by shun-iwasawa** [comment]
@artisteacher 
I think you need to copy files from `stuff` folder to the folder specified as `TOONZROOT` in [SystemVar.ini](https://github.com/opentoonz/opentoonz/blob/master/toonz/install/SystemVar.ini) to see the changes. 
( The default location is `/Applications/OpenToonz/OpenToonz_stuff` ) 
On my end I confirmed it works both on Windows and macOS.

Thank you @konero for the nice modifications ! LGTM

**Comment by artisteacher** [comment]
@shun-iwasawa - Weird. I did a clean install with new stuff folder & I'm still not seeing these updates. I haven't changed anything in SystemVar.ini. Usually just replacing the QSS files in the qss folder is enough to make the changes display...

**Comment by shun-iwasawa** [comment]
@artisteacher 
Did you test the changes with the nightly build? If yes, I'm sorry but I just found that the recent Jen.kins for macOS builds were failed for some reasons:
image
The last attempt seems to be finished successfully an hour before. So can you please try installing again with the current nightly build?

**Comment by artisteacher** [comment]
@shun-iwasawa - thanks! Now it works.

**Pull request merged**
