### PR TITLE
Add Camera Capture command to full menu bar (OSX)

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR adds Camera Capture command to the full menu bar which is used in OSX version.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
#584 also fixed this.

**Comment by shun-iwasawa** [comment]
@turtletooth Oh, I didn't aware of it. Thank you for point out!
Then I will close it and review your PR right away.

**Comment by turtletooth** [comment]
Thanks.  It takes care of a few more things, but that is in there.

**Pull request closed without merging**
