### PR TITLE
RGB sliders behaving like CSP/Krita, Hex editbox and various bugfixes

### PR DESCRIPTION
**Pull request by justburner**
This PR is mainly to give a new look at RGB sliders and color preview.

Image

- Changed background colors in RGB slides to behave like CSP/Krita.
- Changed handle to look more modern, similar to Tahoma2D (Thanks @konero for the SVGs).
- Fixed weird behaviors of the sliders by removing QSlider hack and implementing custom handling.
- Changed how color preview looks, now MyBrush icons are centered with current color as the background. No more ugly stretching!
- Added Hex edit-box to quickly get and set colors from text, must be enabled by clicking the bottom-right 3-lines icon, the placement of this widget is different from Tahoma2D.
- Hex edit-box accepts typing HTML colors and more! It can be configured with `colornames.txt` files.
- Clicking on the current style color preview will apply color.
- Bugfixes in regard to style index handling.

**Accepted Hex input formats:**
- `#RRGGBBAA` - Tahoma2D supports this
- `#RRGGBB` - Tahoma2D supports this
- `#RGBA` - Shorthand hex color
- `#RGB` - Shorthand hex color
- `#VV` - Non-standard, useful for gradients
- `#V` - Non-standard, useful for gradients

It will outputs `#RRGGBB` on opaque color or `#RRGGBBAA`.

**Custom color names tables:**
The default table is stored in `<OT_STUFF>/configs/colornames.txt` and is a XML format file.
If you want to add your own names is recommended to write them to user profile folder so it won't be affected by any future updates: `<OT_STUFF>/profiles/layouts/settings.<USERNAME>/colornames.txt`

Important: Name entries in file must have no spaces!
Anyway spaces in the Hex edit-box are ignored so you can write `Sky Blue` to mention `skyblue` color.
Unicodes are supported for names, make sure you save the file as "UTF-8" only, this can be tested by using `レッド` resulting in red color.
OpenToonz must be restarted if changes to the files are made while the app it's running.

Example `colornames.txt` in user settings folder:
```XML
<colors>
  <!-- color name is not case-sensitive and must have no spaces, items on bottom takes priority -->
  <color name="test">#808080</color>
  <color name="anothertest">#C0C0C0</color>
</colors>
```
User will be able to use `test`, `anothertest` and even `another test` in the Hex edit-box.
Sadly there's no editor build-in in OpenToonz to manage user entries.

**Performance implications:**
I've did performance testing with my medium-end PC and a slower low-end PC, i couldn't tell any performance impact between with and without this patch.
It seems the sliders painting barely affects CPU time compared to other events behind a style change. 🤔

### CODE REVIEW

**Comment by RodneyBaker** [comment]
@shun-iwasawa This PR is looking good to me.
Over to you for any concerns with regard to production and workflow for Japanese studios.
I don't see any obstacles at the moment.

**Comment by shun-iwasawa** [comment]
Thank you @justburner ! 
Let me ask ink&paint staffs in our studio if the proposed UI can replace the conventional one or the conventional one should be kept as optional. In the latter case, I'll try to modify so based on your PR. 
Sorry for the trouble, but altering UI needs to be done carefully for us as we are in the middle of production.

**Comment by justburner** [comment]
No problem @shun-iwasawa :)
If is needed i can add some settings in preferences that can enable/disable some of this changes.
I'm thinking to add a `Style Editor` category in the future for making user color names editable inside the program and likely some other customization so might as well add the category sooner if required.

While you're at it, feel free to ask around and add some Japanese general use entries into the color names list ;)

**Comment by konero** [comment]
Works really nice!

I had your test build on my machine when someone else used it, they thought the arrows were a bit small (I'm indifferent). I'll post the arrow size he would have preferred here in any case for discussion.

image

SVGs: [Arrows_Big.zip](https://github.com/opentoonz/opentoonz/files/7879959/Arrows_Big.zip)

**Comment by shun-iwasawa** [comment]
Thank you @justburner , it seems that they would like to keep appearance of the color slider as-is since they are familliar with the conventional one. I'm preparing PR for making it optional (and with small modification in layout). It's almost done and I will post it tomorrow. 

Anyway, they are thankful for the fix in this PR that the handle is now at the edge of slider when the value is set to the minimum/maximum!

**Comment by gab3d** [comment]
@justburner thanks!
- Hex colors are really useful!
- Stretched style previews were always annoying to me. Thanks for that too!
imagen
Style previews were originally meant to be stacked one above the other (as shown in the image above), so they were not as wide as they are now. When OT changed its placement to be side-by-side, it changed its proportions to be wider, then to stretch to the panel size, and that never coped well with the original design.
Now at least their content it won't be stretched, and that's a great thing!

Perhaps we could explore alternative locations for these thumbnails in the editor, where they could be, again, stacked?

**Comment by justburner** [comment]
Thanks everyone for the feedback! 👍 

> Works really nice!
> 
> I had your test build on my machine when someone else used it, they thought the arrows were a bit small (I'm indifferent). I'll post the arrow size he would have preferred here in any case just to add to the discussion.
> 
> image
> 
> SVGs: [Arrows_Big.zip](https://github.com/opentoonz/opentoonz/files/7879959/Arrows_Big.zip)

@konero So they want the Tahoma2D sized one? lol, I thought mine was still quite big in comparison to the CSP and Krita ones.
I couldn't put the handles lower than they are, it's already positioned on the very bottom. In order to put them any lower ALL padding and widgets around have to be tweaked. I don't even think Jeremy bothered doing that on Tahoma2D, he just made the gradients bar smaller to create that illusion.

@shun-iwasawa If you're taking over the PR can you please add and set the settings into a new 'Style Editor' category? Shoving this stuff into another very busy category will prevent me to add a few things i have planned in the future.

@gab3d That's up to @shun-iwasawa now. 😄

**Pull request merged**
