### PR TITLE
Fix brushes marker and hatch (Raster Brushes)

### PR DESCRIPTION
**Pull request by andeon**
Just a fix to horizontal angle of the "hatch brush" for consistent strokes and increased brush size of the "marker brush" to fill areas and shapes by default easily.

https://user-images.githubusercontent.com/11843239/129254826-b90db47f-952e-40fa-92a6-a6d6212552d7.mov

Don't test this on fresh Windows Build Artifact (Actions) I believe that mypaint lib is outdated.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Thank you @andeon for the brush updates/fixes.

cc:  @shun-iwasawa for the report concerning possible outdated mypaint library resource (REF:  #4027)

**Comment by JPUser1** [comment]
@andeon I like the Theme you are using would you be open to sharing the .qss  ?

**Comment by andeon** [comment]
> 
> 
> @andeon I like the Theme you are using would you be open to sharing the .qss ?

There you go! https://github.com/andeon/opentoonz-themes

**Comment by JPUser1** [comment]
@andeon Thanks!

**Pull request merged**
