### PR TITLE
(WIP) Makes all Command Bar Icons SVG

### LINKED ISSUE #3128: Some Command Bar Icons are Pixelated
### Issue Summary
On the Command Bar, some icons appear pixelated on screen, with the exception of text-based ones like 1's, 2's, and 3's. There are some other exceptions I've noticed too, namely the three New Level buttons. I've attached an example.

### Screenshot or Video Reference
Screen Shot 2020-03-03 at 12 08 13 PM

### Steps to Reproduce
Use a high resolution display (this becomes pretty noticeable to me because I'm using a high-resolution 2560 x 1600 display.)

### Expected Results
All icons show up at native resolution

### Actual Results
Some Command Bar icons show up pixelated

### System Information
* **OpenToonz Version**: 1.4.0
* **Operating System**: macOS Catalina
* **CPU**: Quad Core i5
* **Memory**: 8 GB LPDDR3
* **Graphics Card**: 
* **Graphics Tablet**:

### PR DESCRIPTION
**Pull request by MrBlockCat**
Fixes #3128

This also undoes the undoing (yes) of .gitignore ignoring .DS_Store, which is a file Macs place all over, making GitHub annoying to use on a Mac if it isn't ignored. The reason this does that is that I somehow undid the commit that made it so GitHub ignored .DS_Store on this branch instead of my own branch. Sorry!

Before this can be merged, whatever code references toolbar_arrow.png will have to be changed to reference toolbar_arrow.svg. I don't know all the places the icon is used, but at least the Tool Bar, Command Bar, and XSheet Toolbar use it. My guess is there's some unified location in the code that deals with all three (and maybe other places too) overflowing, and if that's the case, only that unified location would probably have to be updated to support toolbar_arrow.svg.

### CODE REVIEW

**Comment by manongjohn** [comment]
Note sure what you're doing but you're causing a very messy commit history.

I would also avoid submitting changes directly from your master. You should be creating and using branches to submit PRs.

Not sure what others do, but here's what I normally do

1. Forked my repo from OpenToonz master (1x)
2. Cloned my repo locally (1x unless I foobar'd and have to start over)
3. To start a new change, I always create a new "working" branch from my master first.
    I always keep my master in sync with OpenToonz master, I never directly add my PR or any changes to my master. This way I always start new branches with what OT has as it's base.
4. Make and commit my changes to the "working" branch.
5. Push the new "working" branch and changes to Github
6. Create a PR from my "working" branch to opentoonz/master and wait for review and approval
7. After the PR is merged or when I feel it is necessary to before starting a new set of changes, I will sync my master with OT's master by doing the following
  - git checkout master
  - git pull https://github.com/opentoonz/opentoonz.git master
  - git push origin master

Next time I start a new branch, my master will start from a relatively clean copy of the OT master, including changes other people have made.

**Comment by manongjohn** [comment]
I would suggest setting up your build environment so you can test your changes and builds locally instead of blindly submitting changes.

The instructions for setting up a macOS build environment is pretty straight forward and you have the option to build using normal command line, or if you want a IDE environment to develop in, the instructions also explains how to configure and build using Xcode.

**Comment by MrBlockCat** [comment]
Both checks failed because opentoonz/toonz/sources/toonz/toonz.qrc had some references to the PNGs instead of SVGs still. That part I should be able to fix at least! Maybe these checks'll be able to tell me where the toolbar_arrow is used too...

**Comment by manongjohn** [comment]
I would strongly suggest you rebase this on top of OT master to remove the unnecessary commits and straighten out the commit history.

**Comment by MrBlockCat** [comment]
The checks passed despite toolbar_arrow.svg not being coded in, unfortunately, so I'll still need help finding where toolbar_arrow.png was used. Also, I'll rebase this as soon as I figure out how!

**Comment by MrBlockCat** [comment]
I'm gonna start over with this PR, on a fresh branch. I agree, this somehow got messy! I'll also split off the .DS_Store thing into its own branch since that'll become much easier to do. To the build environment, I agree, I'll probably just set one up.

**Pull request closed without merging**
