### PR TITLE
Unify all scrollbars to same style and fix background by turtletooth (slightly modified)

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is based on the PR #874 by @turtletooth .
This takes care of the issue #754.

I just modified the width of scrollbar (from 18 pixels to 16 pixels) and resized the images in order to make them not to be shrink-resampled.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
BTW- @shun-iwasawa What is the difference between the mac and normal qss?  Also, do you have time to look at #725?  My students use it all the time and it is a timesaver for us.

**Comment by shun-iwasawa** [comment]
@turtletooth  In Toonz Harlequin, only the mac qss applies "Lucida Grande" font for some widgets. In OpenToonz there is no difference between the mac qss and the normal one (font type is set in `main.cpp` and is used throughout the application). I think it is OK to be unified.

OK, I'll review #725 next.

Jenkins

**Comment by turtletooth** [comment]
LGTM.  Thanks @shun-iwasawa for the update.

**Pull request merged**
