### PR TITLE
Touch Screen Controls

### PR DESCRIPTION
**Pull request by turtletooth**
This adds touch screen controls to the viewer.
One finger drag to pan
Pinch to zoom in/out
Two finger twist to rotate
Double tap to fit to viewer.

### CODE REVIEW

**Comment by bobbybutterfly** [comment]
i would prefer one finger drag to pan (like in Clip Studio)
two finger pan (like in sketchbook pro) leads to accidentally drawn strokes, if one of the two fingers touches the screen first.

**Comment by openanim** [comment]
@turtletooth Oh thanks, It will really help! As suggested by @bobbybutterfly , is not it possible to have 1 finger for the pan? Optional if other prefers 2 fingers. Personally, I prefer CSP approach, it's much better with a finger. In any case thank you for having realized it.

**Comment by openanim** [comment]
Anyway if it works with a finger, with two fingers it should also work :)

**Comment by bobbybutterfly** [comment]
@turtletooth thanks, touch Support for OT will be great.
(TV-Paint users are begging unsuccesfully for touch for years now)

one more suggestion: "snap" for horizontal Position when twist rotate (-1, 0 and 1 degree)
in Toonboom Storyboard pro 5 for example it is kind of impossible to rotate your board back to exact horizontal Position, because it has no snap support like CSP

**Comment by turtletooth** [comment]
Quick question for those who have used the other apps. Once you trigger an action, does it lock to that action or can you do pan rotate and zoom all at once. This currently let's you do all at once, but it makes it hard if all you want to do is pan for example, not too also trigger one of the other actions.

**Comment by turtletooth** [comment]
The reason I did two finger pan is that at certain angles using my surface pro I rest my pinky instead of my whole palm and that would trigger a pan. I'll look into making an option but I can't promise anything. I did disable finger painting with this so there shouldn't be a risk of accidentally using a tool with a finger.

**Comment by bobbybutterfly** [comment]
touchuse
@turtletooth this a a screenshot of CSP; if this button is activated, you have the one finger pan, else the two finger pan.
There is a Website: surfaceproartist.com and
i know that a lot of People there complain about two finger pan in Sketchbook
(on the other site nowbody complains about one finger pan in CSP)

I just tested my paint progs with following results:
- painter 2018: pan or zoom or rotate; only one at a time
- CSP: also
- Sketchbook pro: pan and zoom and rotate; all actions together possible

i personally like the "only one at a time"-behavior a bit more. it seems more precise.

**Comment by openanim** [comment]
For painter, moho we can do it. Photoshop also for zoom and rotation at the same time. CSP no, it's one action at a time. It is also the only one, for whom it is a finger for the panoramic. If you can, making this option will be a good bonus, it's really flexible to use on csp, but it's already great to be able to use tactile gestures.

**Comment by openanim** [comment]
@bobbybutterfly I just saw your post, so I think they changed to painter because previously we could do all the actions zoom pan rotation at the same time, the work plan gave me the impression of a flying leaf, which moved too much in all directions.

**Comment by bobbybutterfly** [comment]
@openanim or maybe its in the preferences. I am on a Surface 3 and had to choose "RTS-Realtime-Stylus" and "Windows-Multitouch" in Preferences/Tablet
are you on a Wacom?

"flying leaf" nails it. Ist just to much movement.
rotate, move, scale: one at a time, its also the standard use in 3D-Programs, for a reason

**Comment by openanim** [comment]
yes, I'm on a cintiq wacom and you are probably right. I never tested it preferences. :)

**Comment by turtletooth** [comment]
Alright - so I made some changes.  Here is what we have now:
One finger pan.
Two fingers for zoom or rotate, but only one at a time.
There is a slight delay to see which movement is going to win over the other at the beginning, but once a the program decides whether to zoom or rotate, controls are pretty smooth.
Double tap still fits to the viewer.

I'm hesitant to add anything to the preferences since we run the risk of preferences overload.

The only thing I couldn't figure out was snapping the rotate back to zero, since I couldn't figure out how to actually get the current rotation out of the viewer's affine.  Double tap will take care of resetting rotation for now.

**Comment by artisteacher** [comment]
Will this impact touchpad performance at all? Right now 2 fingers work to zoom but a pinch motion is more standard, at least for Apple products.

**Comment by RodneyBaker** [comment]
Looking forward to trying this on my touch screen/ monitor.  :)

**Comment by turtletooth** [comment]
I added three finger drag for undo and redo.

**Comment by blurymind** [comment]
are we getting closer to the possibility of #755  :D

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
@turtletooth 
It works fine on my MobileStudioPro.
On OSX, I tried using Magic Trackpad 2 and faced a problem: After rotating or zooming with the trackpad, the viewer seems to be disabled to show right-click menu.
I'm not sure if it is related to this PR, but please give me some time to investigate.

**Comment by turtletooth** [comment]
If OSX is posing a problem, I could make this Windows only for now.

**Comment by shun-iwasawa** [comment]
@turtletooth I tested in the previous version and confirmed that the similar problem happens as well. I think it is the separate issue with this modification.

**Comment by shun-iwasawa** [comment]
LGTM Thank you @turtletooth for adding the nice feature!
I think I need to overhaul the tablet behavior on OSX.

**Comment by artisteacher** [comment]
It looks like this is definitely causing problems in OS X with trackpads. Since only one finger is used for normal navigation on a trackpad, I keep unintentionally triggering the 1 finger pan which makes it really difficult to keep the focus where I need it to be in the viewer. The pan movement is sometimes very delayed. The two finger twist to rotate doesn't seem to be working. Also, now I can't get the hand tool to work at all.

On a positive note, I really love the double tap to fit to viewer.

**Comment by RodneyBaker** [comment]
Routine review of old issues and PRs.
This PR resolves #67

**Pull request merged**
