### PR TITLE
"Organize palette" and "Update colors by using picked position" features for the workflow using raster level as a color model

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will partially introduce the demanding features listed in the issue #690 

- When converting images to TLV, the “Autopaint for Lines” option will be activated by default for the initial color styles which are added for self-color lines.

- Added "Organize palette" option to the style picker tool. With this option, the picked style from the color model will be automatically moved to the first page of the palette.

- When picking style with the "Organize palette" option activated, picked position will be memorize in the style data in order to maintain link between styles and the raster color model. The picked position will be displayed in the status bar of Style editor, and the indicator will be shown in the style chip in Palette if the picked position is set.

- Added “Update colors by using picked position” command in the context menu of Color model. Colors will be picked from the color model by using the picked position memorized in each style.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
Can one of the admins verify this patch?

**Comment by turtletooth** [comment]
I'm not an expert in this workflow, but I did test it a little bit and it seemed to work as intended.  I can merge this if you are ok with my lack of expertise in this area.

**Comment by shun-iwasawa** [comment]
@turtletooth sorry for my late reply and thank you for testing the feature. Yes, it is very Japanese-animation-workflow-oriented... But it is important for improving efficiency of our ink&paint work and I believe that this feature will (at least) not harm other workflows. Could you please merge this? Thanks!

**Pull request merged**
