### PR TITLE
Fix for Pen Glitch on Mac

### PR DESCRIPTION
**Pull request by turtletooth**
#756

The way that tablet detection was handled for tool events was a little sloppy.
I performed more careful checks about whether an event is from a tablet or mouse and which event type it is.

### CODE REVIEW

**Comment by artisteacher** [comment]
Thanks so much! Does this have any impact on the menus becoming greyed out and inaccessible during prolonged tablet use - part of #618?

**Comment by turtletooth** [comment]
Checked on Windows.  Appears to work correctly there too.

**Comment by turtletooth** [comment]
@artisteacher I don't think this has anything to do with the menus, but I have no idea really.  These past two PRs are the first time I've done any development on the mac.  And it has been painful.  The mac I have that can actually run Sierra is the last model that Apple allows to run Sierra - and it is slow.

**Comment by artisteacher** [comment]
I do think something related to the tablet input causes the menus to become disabled. Have you run into this yourself? It is most likely to happen when there is a vector level in the scene (even if not actively selected) and autosave is on. It is similar to when the startup or about popups is open and (with the exception of services, the hide options, and search) the menus are inaccessible. Though with the tablet menu glitch, "show tab bar" and "enter full screen" are also still accessible. In this case trying to close out of OT with the close button (the red x), gives an alert sound. It's like the program thinks something is active and is waiting for input. 

The other frequent tablet issue distorts the beginning of brushstrokes after a tablet has been used and disconnected #1058.

Anyways, thanks for tackling some of the mac specific issues despite the slow computer! The fixes you've been working on are really necessary to make using OT on a mac more feasible.

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you very much for tackling this problem.
I tried the PR and found that the problem still seems to occur.
I've modified and posted another PR #1360 . Please check if it will solve the problem.

**Pull request closed without merging**
