### PR TITLE
Additional Translations for v1.5

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR updates the translation files for last-minute changes before releasing the next version.

Here are updated .ts files:
[translations.zip](https://github.com/opentoonz/opentoonz/files/6252622/translations.zip)

Please note that some status words of Canon DSLR camera (listed in [canon.cpp](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/stopmotion/canon.cpp#L1357-L1848) ) are not included in this PR as it needs big change.

@beeheemooth @pafri @gab3d @jcome 
There are several new words in `toonz.ts` and `toonzqt.ts` . other ts files are not changed.
Thank you!

### CODE REVIEW

**Comment by beeheemooth** [comment]
Done.
[russian.zip](https://github.com/opentoonz/opentoonz/files/6253196/russian.zip)

**Comment by gab3d** [comment]
@shun-iwasawa 
Spanish update.
Thanks for all the fixes in these last weeks! :))

[spanish.zip](https://github.com/opentoonz/opentoonz/files/6254021/spanish.zip)

**Comment by shun-iwasawa** [comment]
I'll merge this for preparing RC2. Other languages can be updated during RC2 period. Thank you!

**Comment by gab3d** [comment]
@shun-iwasawa 
Sorry, I just found that when you used the Help > Report a bug... command (in Spanish UI), the dialog's text was so long that it went off the screen.
So I just modified it to make it fit in two lines.

[spanish_fix.zip](https://github.com/opentoonz/opentoonz/files/6255338/spanish_fix.zip)

**Comment by jcome** [comment]
@shun-iwasawa: Chinese Translations updated in pull request #3862. thanks.

**Comment by toybrand** [comment]
1. I want to know how to open the .ts file.
2. Do you have a separate .ts file document editor?

I can't use WordPad because the Korean alphabet is broken.

**Comment by shun-iwasawa** [comment]
@toybrand 
https://github.com/opentoonz/opentoonz/blob/master/CONTRIBUTING.md#translations
**Qt Linguist** is a tool for translation with .ts files. 

You can download Qt Linguist via official [Qt online installer](https://www.qt.io/download-qt-installer) or there seems to be some third-party download sites for only downloading Qt Linguist ( like [here ](https://github.com/lelegard/qtlinguist-installers/releases) , [here](https://github.com/thurask/Qt-Linguist/releases), etc.  I haven't tested though).

**Comment by toybrand** [comment]
[korean.zip](https://github.com/opentoonz/opentoonz/files/6286641/korean.zip)
It is a Korean translation.

**Pull request merged**
