### PR TITLE
Linux ifdef and defines

### PR DESCRIPTION
**Pull request by ideasman42**
Preprocessed changes from Linux branch.

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins, test this.

**Comment by skitaoka** [comment]
Jenkins, test this, again.

**Comment by skitaoka** [comment]
Jenkins, sorry?

**Comment by kogaki** [comment]
Jenkins

**Comment by janisozaur** [comment]
Can you specify how Jenkins tests this and how is it different from Travis? Are there logs available for inspection anywhere? Could you perhaps unify travis and Jenkins versions?

**Comment by skitaoka** [comment]
Jenkins, worked in local environments, generates an installer package (same as nightly one) for validation test. We will prepare public CI environments.

**Comment by skitaoka** [comment]
LGTM

**Pull request merged**
