### PR TITLE
(WIP) Translation korean

### PR DESCRIPTION
**Pull request by haminu0108**
Translate toonz.ts in Korean

### CODE REVIEW

**Comment by haminu0108** [comment]
Their's no qm file now. It's a prototype.

**Comment by shun-iwasawa** [comment]
Thank you @haminu0108 for tackling with the Korean translation! Looking forward to having other `.ts` files   completed as well.

**Comment by RodneyBaker** [comment]
@haminu0108 Is help still needed in getting this finalized?
This PR is still pending and hopefully will be included in the next release.

**Comment by RodneyBaker** [comment]
@shun-iwasawa  It looks like @haminu0108 is no longer with us as there has been no activity on github since over a year ago.  I can confirm that the majority but not all of the toonz.ts file appears to have been translated and a sampling of the language is accurate according to google translate.

It would be nice to have Korean language added to the v1.3 release but at this time it looks like the most we could do is add the initial content of the toonz.txt file.

As such, recommend pursuing Korean language translation in 2019 development cycle.

**Comment by RodneyBaker** [comment]
I believe even non Korean speakers can get this translation 70 to 80 percent of the way to the finish line.
As this is an important addition going into v1.4 I'm thinking of self assigning.

The important part of this would be to have a native Korean reader/speaker do the final review prior to going final.

**Comment by manongjohn** [comment]
I have been working with someone on Discord who translated all the files into Korean.

I found some inconsistacies which I've asked him to review and fix. I am just waiting for his feedback and will be submitting and alternate PR.

**Comment by RodneyBaker** [comment]
Outstanding new @manongjohn  Thanks!

**Comment by RodneyBaker** [comment]
Closing.  PR #2825 implements the Korean language UI.

**Pull request closed without merging**
