### PR TITLE
Camera Capture fixes

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR fixes some problems and add some improvements to the camera capture feature.

- Camera is unloaded (released) on closing the camera capture dialog. (#707)
- Added "No camera" item to the camera combo box as the initial state. The selected camera name will be stored in the user env file and will be reproduced next time. (#626)
- When you type and change the level name (i.e. not using the "next level" arrow button), frame number edit will be set back to 1 automatically in order to start capturing from the first frame.
- Fixed bug as follows: Let's say capturing a level A frame 1, if the level A does not exist in the x-sheet but the file +extras/A.0001.png does exist, a level "A_1" is unexpectedly created without any warnings.
-  When you capture the image with the frame number which is already captured, OpenToonz will just replace the content of the existing cell and will not create a new cell.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Can one of the admins verify this patch?

**Comment by turtletooth** [comment]
@shun-iwasawa I'm having an issue when I close and reopen the window.  It releases the camera as it should, but when I reopen the window I can't get the camera back unless I change the resolution of the camera to retrigger it.

**Comment by shun-iwasawa** [comment]
@turtletooth Fixed. Thank you for the good catch!

Jenkins

**Comment by turtletooth** [comment]
Looks like the windows build stalled.  This is ready to be merged after a new Jenkins.

**Comment by shun-iwasawa** [comment]
@turtletooth  We are transferring Jenkins to a new computer and there might be a flaw in some settings. Thank you for your patience.

Jenkins again

**Comment by shun-iwasawa** [comment]
Try another settings.

Jenkins again

**Comment by turtletooth** [comment]
LGTM.  Thanks @shun-iwasawa for the fixes.

**Pull request merged**
