### PR TITLE
Port to vs2015

### PR DESCRIPTION
**Pull request by JosefMeixner**
I have ported opentoonz to VS 2015. It will probably not make sense at this time to move to it, but there are two commits, the first are only source changes which should be portable and the second one are all the binaries. I only built the 64bit variants of the files (release and debug).

The source changes are rather small, I had to remove `cprintf` in openblas, VS 2015 for some reason didn't link with it defined, so now `printf` is used instead. The other change was in `toonz/sources/toonz/cleanuppopup.cpp`, Microsoft for some reason decided to add a second set of `count` functions into containers so bind didn't resolve it. I substituted it with a small lambda.

Building QT is rather straight forward, only the OpenGL-setting has to be changed to `desktop`, I had no luck with the default setting of `dynamic`, it caused collisions between GLEW and QtGL. And you need ICU (forget the web pages saying differently), UIC doesn't compile without.

### CODE REVIEW

**Comment by janisozaur** [comment]
How about https://github.com/opentoonz/opentoonz/issues/69 ?

**Comment by JosefMeixner** [comment]
I am absolutely for it, it takes ages to upload the built binaries and having them everywhere is terrible. But I don't think I am able to do this currently. I would prefer to wait until it is fixed here and then also fix my branch. I will comment in #69.

**Comment by turtletooth** [comment]
Josef- 
This is somewhat off topic- but do you know how to get a debug setup working for OpenToonz in VS?  I have to build a release and try and crash it.  I can't seem to get the debugger set up right in VS for OpenToonz.

**Comment by JosefMeixner** [comment]
I use the target `RelWithDebInfo`, that is a release target with debugging info. I always start opentoonz from VS and have no problem this way to use it or debug it.

**Comment by turtletooth** [comment]
> I use the target RelWithDebInfo, that is a release target with debugging info. I always start opentoonz from VS and have no problem this way to use it or debug it.

Is that a CMAKE change I need to make or a flag I set in VS?  I'm still learning.

**Comment by skitaoka** [comment]
This PR was merged by https://github.com/opentoonz/opentoonz/pull/544.

**Pull request closed without merging**
