### PR TITLE
Fix for sierra scrub crash

### PR DESCRIPTION
**Pull request by turtletooth**
#978 
The Sierra Core Audio code (not the OpenToonz code) appears to have a known bug.  This fix bypasses the Core Audio implementation and uses Qt audio for playback.  

@shun-iwasawa I left the original code in case a Mac update fixes it and if performance is better with the Core Audio.  In my limited testing, performance appeared similar.

I don't mind taking out the original code if this seems to work fine.

### CODE REVIEW

**Comment by turtletooth** [comment]
@shun-iwasawa Based on your work with the mac font issue, I went ahead and also removed the old code from this PR.  I suppose if we need it, it is in the git history.

The code in txshsoundcolumn could be useful on all platforms, not just windows to make sure that we get a format that is playable on the device.  I could take out the mac check if you agree.

**Comment by artisteacher** [comment]
I'm really looking forward to this being merged!

**Comment by morevnaproject** [comment]
We have same problem with Linux build. I wonder if your fix can help us as well. ^__^

**Comment by turtletooth** [comment]
@morevnaproject I don't see why it wouldn't work.  My solution uses straight Qt audio (with OpenToonz built in audio converter) to find supported audio formats and play them.

**Comment by morevnaproject** [comment]
Yes, I will test that. Thank you! ^__^

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
@turtletooth 
I tested the PR in OSX Sierra 10.12.4
For now it crashes when you do either one of the following operations:

- Click the speaker icon in the sound column's header in order to preview-play the whole column.

- Left drag the right side area (with horizontal stripes) of the sound column in order to specify the range for preview-playing.

**Comment by turtletooth** [comment]
Thanks for catching that @shun-iwasawa .  I was so focused on scrubbing, I forgot to check those options.  I think I fixed it.

**Comment by shun-iwasawa** [comment]
Confirmed the fix. Thank you @turtletooth !
Travis claims error with Linux build. I have no doubt it is not because of this PR itself, but please give me some time to investigate. Thank you for your patience.

**Comment by turtletooth** [comment]
@shun-iwasawa Is this ready to merge?

**Comment by shun-iwasawa** [comment]
@turtletooth Sorry for keep you waiting! Please let me try Jenkins again just in case.

**Comment by shun-iwasawa** [comment]
LGTM Thank you @turtletooth for the fix.

**Pull request merged**
