### PR TITLE
Enable Column's Color Filter on Vector Levels and on Rendering

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR enhances the Column's Color Filter feature in 2 points as follows:

- Now the color filter is available in Vector Levels

- Color filter and opacity settings of camera stand view can be applied to rendered result as well, by enabling `Enable Column Color Filter and Transparency for Rendering` option in the Scene Settings.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
@turtletooth Can you please take a look on this in your free moments?

**Comment by shun-iwasawa** [comment]
Conflict resolved. Jenkins again

**Comment by shun-iwasawa** [comment]
Conflict resolved. Jenkins again

**Comment by shun-iwasawa** [comment]
@turtletooth 
I'm terribly sorry for hasten you, but could you please let me know whether you had already started looking into this? If not, please forgive me to ask another developer ( it would likely be @masafumi-inoue ) for reviewing, as some Japanese animation studio would like to use this feature soon.

**Comment by turtletooth** [comment]
Works well.  LGTM.
Thanks @shun-iwasawa

**Comment by shun-iwasawa** [comment]
Thanks! @turtletooth

**Pull request merged**
