### PR TITLE
Added Commands to Flip Viewer Horizontally and/or Vertically

### PR DESCRIPTION
**Pull request by turtletooth**
#482 
This doesn't have default shortcuts set, but the options are in the shortcut manager.

### CODE REVIEW

**Comment by openanim** [comment]
@turtletooth I made a similar request from the forum, I didn't know that's was already requested, thank you to do it and sorry for the duplication.

**Comment by bobbybutterfly** [comment]
why not a button to flip objects horizantally.
In cut out style animation it would be really helpful to flip head or body around.
scaling each object negative by hand is tideous

**Comment by turtletooth** [comment]
@bobbybutterfly That would be a separate feature request.  You can make those on the Google Group page.  Good idea though.  This feature is more for hand drawn work.

**Comment by bobbybutterfly** [comment]
@turtletooth ok, thanks, i just put this on the Google Group

**Comment by blurymind** [comment]
very useful!Thank you @turtletooth :)

**Comment by RodneyBaker** [comment]
I confirm that this works great.
For the moment I've assigned Ctrl + Right Arrow to horizontal flip and Ctrl +Up Arrow to vertical flip.
Occasionally I'll forget what I assigned and use Ctrl +Left Arrow and Ctrl + Down Arrow but because the results are immediately seen on the screen it doesn't take me long to remember again.


Note to self:  Do not remove USB with OTX on it and then try to enter the shortcut preferences in the instance of OTX you inadvertently left open on you computer... that will likely result in a crash.  ;)

**Comment by blackwarthog** [comment]
I think will be good to add some kind of label about current flip state. For example at the top of scene view near the zoom percent.

**Comment by shun-iwasawa** [comment]
@turtletooth 
I found a problem as follows:
When one of the flip options is activated, zooming in/out the viewer with mouse wheel causes strange scale factor displayed on the title bar ( like `Zoom : -2147483648%` ). And pressing the zoom In/Out shortcut key causes crash.
Thank you for adding the useful feature.

**Comment by turtletooth** [comment]
Thanks @shun-iwasawa I fixed those and a couple other glitches I found along the way.

**Comment by shun-iwasawa** [comment]
@turtletooth The problem seems to be fixed in the camera stand view but still remains in the 3D View. It doesn't crash but the strange zoom factor appears.

**Comment by turtletooth** [comment]
@shun-iwasawa The zoom factor isn't shown on 3d view for the viewer.  Would you be opposed to removing the zoom factor for the Combo Viewer in 3d view?  The zoom factor doesn't seem to actually reflect the zoom anyway.

**Comment by shun-iwasawa** [comment]
@turtletooth 
> The zoom factor isn't shown on 3d view for the viewer.

In the Viewer the zoom factor appears on 3D view when there is no current level.
Anyway I agree with you to hide the zoom factor on 3D view, both for the Viewer and the ComboViewer.

Related to this, I found that scale marks of the Ruler (on the top and left side of the viewer, NOT the Ruler Tool) disappears on the "flipped" 3D view. It's not a critical as the Ruler will scarcely be used in the 3D view.

**Comment by turtletooth** [comment]
I think I got it now.  Thanks for the help @shun-iwasawa

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
LGTM Thank you @turtletooth for the nice feature !

**Comment by artisteacher** [comment]
It could also be helpful to have these commands added to the viewer's context menu.

**Pull request merged**
