### PR TITLE
Fix touch controls for touchpad and stylus issue by artisteacher (modified)

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is based on #1914 by @artisteacher .

I modified it to obtain device type properly.
Please note that this is WIP as I have not checked either on touch screen or on touch pad yet.

### CODE REVIEW

**Comment by artisteacher** [comment]
Never mind, it wasn’t working as is earlier but now is working just fine.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by masafumi-inoue** [comment]
LGTM

**Pull request merged**
