### PR TITLE
Update .ts files and Japanese translations

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for the issue #835 
Also added Japanese translations for latest features.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by jcome** [comment]
Could someone help to merge this pull, I would like to update Simplified Chinese translation in the coming days. 

Thanks

**Comment by shun-iwasawa** [comment]
Updated. Jenkins again

**Comment by shun-iwasawa** [comment]
@masafumi-inoue could you please review this PR?

**Comment by masafumi-inoue** [comment]
@shun-iwasawa 
LGTM

**Pull request merged**
