### PR TITLE
Timeline height and keyframe area adjustments

### PR DESCRIPTION
**Pull request by manongjohn**
This PR addresses #2261 and #2262 by the following:

- Increased the height of the timeline layers

image

With the increased height, I also increased the height of the dragbar so the height matches the width of the xsheet dragbar.  Hopefully this will make it a bit easier to target with a pen.

**NOTE**: This does not mean this is the end of cell/column dragging conversation! It's merely to help for now in case it takes a while to find an agreeable dragging method.

Additionally, the increased height actually makes the timeline a bit easier on the eyes to look at.

- Narrowed the activation area for key frame selection

I narrowed the active selection area around where the keyframe icons and white lines are. Coupled with the increased height, this should allow for slightly better click/right-click access to target the cell rather than the keyframe icons/lines with a pen.

- Update: Added thumbnail into timeline

With the increased height, it made for a better area to display a thumbnail

image

With the addition on thumbnail
1) Sound icon moved to thumbnail area
2) Filter color icon moved to thumbnail area

Additionally, made a Config button dropdown just for the Sound volume control, removing it from the thumbnail/name areas.  This change was made for all layouts except the "Classic" view since there is no config button. It should be noted that volume setting < 100 will change the Camera Stand Visibility icon similar to changing Opacity on other columns.

image

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by manongjohn** [comment]
@shun-iwasawa Sorry for the last minute changes if you started reviewing this.  Unless you have some change requests, I don't think I have any further changes for this PR.

@turtletooth I'm always glad to hear the timeline is being used and has brought a positive working experience to OT. 

@artisteacher It's funny, I didn't realize how much I missed the thumbnail until after I added it to the timeline and working on some animations. Definitely makes identifying a column a little quicker than trying to read names all the time. :)

**Comment by turtletooth** [comment]
I tested this tonight.  Works really well.  It's nice to have a thumbnail for the columns again.  There's part of me that hates to lose some of the vertical space for more columns, but it's probably a worthwhile trade off in order to have the thumbnail - especially for someone like me who forgets to label his columns.

As far as dragging, with the way that OT shows its keyframes, using the header dragging method is still probably the best.  

BTW - I don't know if this is practical, but would it be possible for columns to show the name of the level on the column instead of Col1, Col2. . . ?

**Comment by manongjohn** [comment]
@turtletooth I know that suggestion or something similar has been requested and debated before, with no real agreeable solution.

Thinking about it a little more, though, I guess we could add a preference to default the Column name to just display the filename of the 1st level in the column, similar to how the thumbnail is chosen, but not actually name the column that.  If it is an empty column, it will remain Col#.  If the user has overridden the column name, that will display instead. 

This would basically just be a visual replacement. Any logic that references its name would still get Col# or whatever the user named the actual column.

It would likely need to also change in the Schematic Viewers, Function Editor and anywhere else Col# is displayed for consistency and visual reference. I would likely handle this in a separate PR if we want to go ahead and do this.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Thank you @manongjohn for the improvement ! LGTM

**Pull request merged**
