### PR TITLE
Updated rooms for consistency

### PR DESCRIPTION
**Pull request by turtletooth**
This provides more room for the tool bar and tool options bar.  Fix for #583

### CODE REVIEW

**Comment by blurymind** [comment]
Can you make a screenshot :)

**Comment by turtletooth** [comment]
Of course.

new_basics

And smaller: 
new_basics_small

Before, the tool option bar didn't go all the way across, which works fine for large displays, but on smaller displays, you lose visibility of some options.

In fact, I just checked the other rooms, and it's inconsistent.  I think I will update the other rooms for consistency.

**Comment by blurymind** [comment]
It would be amazing if we could get more space for those sliders in the
options bar. Why are the drop down lists before "miter" eating up so much
horizontal space. This is madness xD

**Comment by blurymind** [comment]
wastedhspace
should I file this as a bug report? :) @shun-iwasawa

**Comment by blurymind** [comment]
https://github.com/opentoonz/opentoonz/issues/593
https://github.com/opentoonz/opentoonz/issues/594

This seems to be a persistent problem with the options toolbar

**Comment by shun-iwasawa** [comment]
@blurymind 

> should I file this as a bug report? :) @shun-iwasawa 
You can almost fit another slider in the wasted (yellow space)

Please check if the style sheets in $TOONZCONFIG/qss are updated. Note that they will NOT be overwritten if they already exist (since they might be customized by users).

**Comment by blurymind** [comment]
@shun-iwasawa thank you - that fixed it! :)

**Comment by turtletooth** [comment]
- Made the tool option bar across the entire top.
- Made the tool bar fill the side
- Changed Pltedit to Palette
- Added Pencil Test to Scan & Cleanup menu

@shun-iwasawa The first time the program is loaded, the Pencil Test doesn't show up in the menu, but it shows up after that.  Why is that?

**Comment by turtletooth** [comment]
> The first time the program is loaded, the Pencil Test doesn't show up in the menu, but it shows up after that. Why is that?

Figured it out for a different PR I'm working on.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM

**Pull request merged**
