### PR TITLE
Toonz Palettes folder now working and has 3 starter palettes

### PR DESCRIPTION
**Pull request by turtletooth**
The Toonz Palettes folder didn't exist before in stuff/studiopalette and so the folder in OT just did nothing.  I thought the name Global Palettes was more descriptive so I changed it and also added 3 starter palettes:
Basics - just a handful of basic colors to get beginners started
Skin - a wide variety of skin tones
Variety - the cleanup_default palette that was in studiopalette

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
For now this branch conflicts to master branch since we applied clang-format on v1.0.3 release.
Sorry to trouble you but could you please apply clang-format (with [toonz/sources/.clang-format](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/.clang-format)) to your PR or rebase your commits to the current master?
Thank you for your contributions.

**Comment by turtletooth** [comment]
Fixed for 1.0.3

**Comment by kogaki** [comment]
Thank you for your really fast response !!

**Comment by kogaki** [comment]
Jenkins, confirm

**Comment by kogaki** [comment]
Jenkins

**Comment by turtletooth** [comment]
Glad to help.

**Comment by shun-iwasawa** [comment]
LGTM

**Comment by shun-iwasawa** [comment]
@turtletooth 
Thank you for your many contributions.
We'll be happy if you could improve OpenToonz continuously and would like to assign you a committer right.
Let's improve OpenToonz together :-)

**Comment by turtletooth** [comment]
@shun-iwasawa Thank you very much.  It has been a lot of fun helping to make this awesome software better.  You have all been very helpful and it makes me excited and proud to see how far this software has come in such a short time.

**Pull request merged**
