### PR TITLE
Translation Files (.TS) Update for V1.2.1

### PR DESCRIPTION
**Pull request by shun-iwasawa**
Now features for v1.2.1 is frozen.
This PR just updates TS files for all languages in preparation for the new version.

It is much appreciated if @gab3d , @morevnaproject , @jcome , @haminu0108 and other contributors could update translation based on this.

### CODE REVIEW

**Comment by masafumi-inoue** [comment]
LGTM

**Comment by jcome** [comment]
@shun-iwasawa do we have a deadline for the translation? I am going to do Chinese next week.

**Comment by shun-iwasawa** [comment]
@jcome 
Thank you for your kind proposal on Chinese translation! 
I'm thinking of releasing the next version on Monday, June 18.
Please comment to #2036 if you need more time to finish translation.
Also please make sure to follow the latest master branch since more translatable texts are added recently.

**Comment by flaviohr** [comment]
Hello, I was made a brazilian portuguese translation
that's on my repository.

**Pull request merged**
