### PR TITLE
Fix for FFmpeg renders wrong range if previous exported range was bigger 

### PR DESCRIPTION
**Pull request by turtletooth**
To duplicate:
1. Create a scene with 10 frames and render it using Ffmpeg
2. Render the scene again only choosing frames 1-5
3. The export uses the previous export to get its image info from and renders the previous range.

### CODE REVIEW

**Comment by ideasman42** [comment]
Shouldn't this be moved into a method?
*(easy to miss some extension if this is copy-pasted all over)*.

`bool usesFfmpeg = type == "gif" || type == "mp4" || type == "web"`

Also, please squish corrective commits.

**Comment by turtletooth** [comment]
> Shouldn't this be moved into a method?
Probably.  Please don't merge this until #826 is merged and I will use the method I created there for this.

**Comment by turtletooth** [comment]
Moved the change into a function.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Confirmed the fix. @turtletooth thank you!
LGTM

**Pull request merged**
