### PR TITLE
Store the toolbar state (expanded / shrinked) in user's env file

### PR DESCRIPTION
**Pull request by jcome**
this PR is for #392

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Thank you for the PR.
I think the state (expanded / shrinked) of the toolbar should be stored in user's env file in order to reproduce the previous state when you launch the software.

**Comment by jcome** [comment]
Agree with you. Let me try, it is my first time to have a close look at the source.

**Comment by shun-iwasawa** [comment]
Great! 
FYI, declaring TEnv::IntVar enables storing/retrieving integer values from user's env file. You can see existing sources as a reference such as [menubar.cpp](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/menubar.cpp) ,[brushtool.cpp](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/tnztools/brushtool.cpp) , [dvitemview.cpp](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/toonz/dvitemview.cpp) etc. 

Note that you need to include "tenv.h".

**Comment by jcome** [comment]
Thanks.
it works, [https://youtu.be/0burrGG1VrM](url)
And once the changes have cleaned up, I push to the branch for a review

**Comment by jcome** [comment]
@shun-iwasawa , changes is pushed now, llease have a look. Thanks.

**Comment by shun-iwasawa** [comment]
For now this branch conflicts to master branch since we applied clang-format on v1.0.3 release.
Sorry to trouble you but could you please apply clang-format (with [toonz/sources/.clang-format](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/.clang-format)) to your PR or rebase your commits to the current master?
Thank you for your contributions.

**Comment by jcome** [comment]
@shun-iwasawa  
rebased commits to the current master.

**Comment by shun-iwasawa** [comment]
Thanks! I'll check it.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by skitaoka** [comment]
Commits in this PR are merged by https://github.com/opentoonz/opentoonz/pull/460.

**Pull request closed without merging**
