### PR TITLE
Fix version control issues

### LINKED ISSUE #2618: File level Version Control status and options not showing on most files
### Issue Summary

After setting up and configuring Version Control, I pushed a project to SVN repository which marked all the files in the project as Read-Only (expected). 

When looking at the files in OT's browser, most files do not have the Version Control icon and more importantly, do not have the context menu options allowing us to "Edit" and unlock the files. You cannot work on those files from within OT without first going outside of OT and using SVN tools/commands to unlock them.

The only files that appear to have the icon and context menu are sequenced files (.tif, .png, .mesh).  Scene file and other image files like vector/toonz raster are not.

Additionally, if I "Edit" the sequenced files to work on them, the files no longer show up as version controlled, though at least they are unlocked and editable.

### Screenshot or Video Reference

After pushing to remote:

image

### Steps to Reproduce

1) Installed SVN and created remote repository

Tools: Tortoise SVN w/ command line options installed
Repo: https://svn.riouxsvn.com/otprojects  on (https://riouxsvn.com) 

2) Configured the versioncontrol.xml and permissions.xml per documentation

My`<localPath>` is set to to my Project Root folder (i.e C:\OpenToonzProjects) so all new projects could be pushed to repo.

3) Connected my localRepo to my Project Repo using Tortoise SVN tools
4) Configured OT to use Version Control, then quit and restart
5) Created a new Project/scene in C:\OpenToonzProjects with several different image file types.
6) Opened OT's File Browser and navigated to the Version Control folder 
7) Push all changes to SNV repo.
I verified my commit was found on remote repo.  Also verified all files were locked and could not be edited.
8) Navigated to files in the Version Controlled folder. Only sequenced files have Version Control status and context menu.  Scene file, vector/toonz raster/palette files do not have any version controls. Furthermore, all these files are currently locked (marked Read-Only) and cannot be editted any more.
9) Located sequenced files then Right-clicked and selected Version Control -> Edit
After I click on "Edit" button, the Version Control status icon and context menu commands disappear from the file.  But the files are at least editable.

### Expected Results

Ability to use Version Control on all project files from within OT as described in the documents

Here is a mocked up version of what I expect to see under a version controlled project:

image

### System Information
* **OpenToonz Version**: Verified on 1.0 to present
* **Operating System**: Windows 7 & 10

### PR DESCRIPTION
**Pull request by manongjohn**
This PR does the following:

**Fixed Issues**
1) Fixes #2618 - The issue with sub-folders not being tracked by version control

With SVN 1.7, the move to only using 1 meta data folder at the root of local repo made OT stop tracking the sub-folders. I added logic that walked up the directory tree looking for the presence of a `.svn` folder to determine if it is under SVN control.

2) Fixes issue with `svn propget` command throwing warnings and errors

Some SVN version changed `propget` to throw warnings and errors if the property you are trying to get does not exist. In OT's case it was checking for `partial-lock` and would throw errors if it didn't find it. This would caused some commands to not work right.  

Replaced `propget partial-lock` with `proplist` and used existing logic to find the `partial-lock` value and use it if found.

3) Fixes shifted List display for versioned file in OT' browser.

When the version control icon was shown in the List display, the text that followed was always shifted right. Added logic to account for the icon width, when present, and shifted the text back

4) Fixes crash when it attempts to save a read-only palette file

Added logic to throw an exception when studio palette is read-only and a save operation tries to update it to prevent a crash.

5) Fixed errors with 'Get Revision'

Corrected logic or improperly trying to get revisions on files without specifying extension which resulted in svn errors. 

6) Fixed Edit Frame Range logic not creating temp files for .pli and .tlv files.

Edit Frame Range logic was not creating temp files which is needed to allow update of specific frame ranges when 2 people were working on the same Toonz Vector and Toonz Raster file at the same time.

7) Fixed crash when writing partial lock temp files

When the temp file for partial locked files was written, the LevelUpdater for the temp level would close and reset TXsheetLevel to nulls causing a crash when it tried to determine if there were temp hooks that needed to be written out.  For me this was a consistent crash on Win7, but random on Win10.  Added logic to increase the smart object reference count of the temp TXsheetLevel so it wouldn't immediately destroy the level when the LevelUpdated closed.

8) Fixed reading svn status for partial locked files when loading after startup.

When loading a scene and/or a level with a partial lock without going through the File browser, the svn status of partial locked files was not being read in and applied. This was because the VersionControl instance was not initialized with user credentials at startup so it can't determine who owns which frames.  Added logic to initialize the VC instance with the repo specific user credentials based on the path of the file, in case there are multiple repos set up.

**Enhancements**
1) Added the `Unlock` menu item on `Locked` files, allowing one to unlock a file if they want to release it without making any changes.

2) Re-prioritized svn status displayed in OT browser because some statuses were blocking others which prevented user from performing certain actions.

3) Show raster and mesh frames as locked in Level strip when the underlying files are marked as read-only on the OS like other level types.

4) Enable version control refresh when File browser starts so when you click on the version controlled folders, they will automatically refresh if permissions warrant it.

### CODE REVIEW

**Comment by manongjohn** [comment]
@shun-iwasawa I was trying to test out some of OT's version control to see what other SVN changes might have impacted how OT uses it and I have some questions

1) "Edit Frame Range..." option

"Edit Frame Range" makes sense for sequenced files like .tif, .png, etc, since each frame is an individual file, and each file can be locked for editing.  2 people can work on a level without clobbering each other's work.

I see code was purposefully added to work with .pli and .tlv files.  How is this supposed to work with Toonz Raster and Toonz Vector levels since it's only 1 file? If 2 people lock and edit a different frame in the same level, the 2nd person to commit changes will get a commit error because their file is old.  In addition to that, "Edit Frame Range" on .pli and .tlv files does not lock the files for editing keeping them in a read-only state so changes made to the level won't even save.

Am I missing something on how this option should be used for .pli and .tlv files?

2) "Some files that you want to edit are currently opened. Close them first."

Can't use "Edit" and some other functions while the file is open in the current scene.

Is there a particular reason we shouldn't allow some of the Version Control options to do that? I think "Edit" should be allowed if you are working on a scene and realize you need to edit a level that is currently not locked for editing. Would be a hassle to have to close the scene just to lock the file for editing.

Please advise.

**Comment by shun-iwasawa** [comment]
@manongjohn
Thank you for tackling with reverting the version control feature!

First of all, in Studio Ghibli we did not use the version control  so I omitted it from the file browser UI in Toonz Ghibli Edition. Therefore I haven't investigated or tried it before and am unfamiliar with it.

> How is this supposed to work with Toonz Raster and Toonz Vector levels since it's only 1 file? 

I don't know whether it is related with the "Edit Frame Range..." option, but at least TLV file can be edited by multiple users at the same time.
Imputing different range of frames in "Load Subsequent Level" field in the Load Level popup enables multiple users to work on and overwrite single Toonz Raster level.
I haven't tested whether PLI can be handled with the same manner.

> Is there a particular reason we shouldn't allow some of the Version Control options to do that?

I'm sorry but I currently have no idea with it.

**Comment by artisteacher** [comment]
I can't edit TLV files on 2 computers at the same time when loading different ranges (using a shared server as the project location).  Everything loads just fine. Once I've saved on one computer, if I try to save on the other, I get a warning:
> path/scene.tnz can't rename file!

I've gotten a few crashes trying this. Then when I try to open the scene again, I get a warning that the prior save was critically interrupted. The exact same thing happens with vector levels.

If I try to save just the level after making changes, I get a similar warning that OT "can't delete file"

**Comment by manongjohn** [comment]
@shun-iwasawa Thanks for the information.  Well that certainly explains why there are a number of issues I've come across and why a lot of things just don't seem to make any sense or work like I would expect.

I didn't know that about loading TLV files. That's a neat feature.  I confirmed I can do that with the TLV file, but it doesn't appear to work with PLI files when I tried it. That could be a future enhancement.

Either way, i don't think svn supports that feature right. I will play around with it a bit more, but likely will need to disable it for pli and tlv files.

**Comment by gab3d** [comment]
@manongjohn 
According to OT's SVN [manual section](https://opentoonz.readthedocs.io/en/latest/using_the_version_control.html#editing-files), the Frame Range option should work in both *Toonz* level types. 

> The Edit Frame Range command is available as well to edit only the needed frames of a Toonz animation level. This way different users can work at the same time on different frame ranges of the same animation level.

**Comment by manongjohn** [comment]
@artisteacher That, in part, sounds like a permission issue.  Depending on who initially created the file, that user will be the only one who has full access to it. Anyone else would depend on the group/world privileges and would only be able to update it if granted write access appropriately.

As part of testing version control, I have run into issues with OT crashing when it attempts to write to a read-only file. I've fixed the 1 case i know about.

**Comment by manongjohn** [comment]
@gab3d I've been trying to get that to work, but with how svn is currently implemented, that information is not true.  It does technically mark at frames as being in a locked state, but the level file is still read-only from the operating system side.  So even if you could draw on those frames in OT the changes will never save to the file.

In addition to that, when I did a small work around to make the file editable on the 2 different machines with different ranges locked for editing, the 1st machine committed the changes successfully, but the 2nd machine failed to commit because it detected the file changed and blocked it.  There is no way to merge them from OT's svn controls.  For now, that feature absolutely does not work like it says it should.

**Comment by gab3d** [comment]
@manongjohn 
I understand.
Are you able to check if that feature really works in Toonz 7.1 as the manual says?

**Comment by manongjohn** [comment]
@gab3d I just downloaded Toonz 7.4 (15day trial) and set it up for Version control.  It unfortunately has the same bug that OT has. When I Edit Frame Range on a level, draw in the frame and try to save the level, Toonz goes into an infinite loop. I have to kill the application or eventually it crashes.  This means I can't tell if it will work or not as described.

I do see it Edit Frame Range still leaves the file marked as Read-Only.  What Toonz does with that I can't tell because of the bug.

**Comment by konero** [comment]
@manongjohn Yeah Toonz SVN was garbage and I put that politely, just remove it maybe, nobody used it that I know. Everyone seems to use [Shotgun](https://www.shotgunsoftware.com/) or [Tactic Open-source](https://southpawtech.com/tactic-open-source/), they're full featured content management interfaces.

I personally use Tactic since it's free, it has a learning curve unfortunately but oh well, it's simple to setup. You can build a pipeline and then users can just mark which processes have been completed, if something needs review, ruff, tie-down, paint, comp, etc and displays the storyboard image for the shot and works across every software.



Screenshot is from this video that explains it: https://www.youtube.com/watch?v=y00iu0qXWwQ

**Comment by gab3d** [comment]
@manongjohn 

> When I Edit Frame Range on a level, draw in the frame and try to save the level, Toonz goes into an infinite loop. I have to kill the application or eventually it crashes. This means I can't tell if it will work or not as described.

Could this be due to you working with a newer version of SVN, that works differently than the intended/supported version? 🤔

**Comment by gab3d** [comment]
@manongjohn 
also, are you on Windows or Mac?

**Comment by manongjohn** [comment]
Windows and no, there is a bug in the code that has nothing to do with svn directly.

Fyi, I test with svn 1.6.17 and 1.12.0. I tried to test with svn 1.5.6 but it wouldn't work because of an svn option that OT is using that doesn't exist in that version. Not sure why the manual even says it works with 1.5. Perhaps ot used to but options added later broke stuff.

**Comment by manongjohn** [comment]
@konero Yeah, I was rather surprised how bad this is when I started looking into it. Someone was looking at using it as a backup strategy and was having issues. I was curious so I decided to play with it and....well...good or bad...now I'm fixing some of it. :)

With the few changes I am making, it's still not the greatest, but it will at least be usable for something.

**Comment by gab3d** [comment]
@manongjohn 

> Not sure why the manual even says it works with 1.5. Perhaps ot used to but options added later broke stuff.

mmm... nope, I'm afraid that text comes unaltered from the Toonz 7.1 User Guide PDF.

I understand there seems to be a bug there (somewhere) that prevents the "partial lock" of files from working. But what is weird to me is to think that Toonz developers had created a system that is advertised in the user guide and that have absolutely no expectations of being able to work. It makes no sense. They imagined it all?  🤔 
Perhaps we could ask someone at Digital Video about this one. Not even about OT, but about how to make it work with their own Toonz 7.4 trial. With a bit of luck that could shed some light here too...

**Comment by artisteacher** [comment]
@manongjohn - it could definitely be a permissions issue, though I was signed in on both computers & was the one to create the files.

**Comment by manongjohn** [comment]
Fixed the issue with Edit Frame Range not working as expected.  Seems the temp file needed to coordinate that feature was not being generated.  After fixing it, it worked like a charm for both PLI and TLV.

**Comment by RodneyBaker** [comment]
Outstanding!  You are discovering some very interesting things about Toonz
file formats (PLI and TLV).
Much appreciated. :)

**Comment by gab3d** [comment]
@manongjohn 
clap clap clap...
you're the man! ㊗️

**Comment by gab3d** [comment]
@manongjohn 
Please tell me in what way should we update the manual explanations about setting up SVN, for best results, and I'll do it. 👍

**Comment by manongjohn** [comment]
The only thing that I can say that needs to be updated is that as of right now all OT versions (1.0 - 1.3) will only work with SVN 1.6.

Once this PR goes in, that nightly forward and the next official OT release will work with 1.6 - 1.12 (current).

**Comment by jpturcotte** [comment]
Outstanding work!

**Comment by gab3d** [comment]
I've finally managed to configure a SVN server to be able to test this and get some up-to-date screenshots for including in the [Manual page](https://opentoonz.readthedocs.io/en/latest/using_the_version_control.html#id5).

While at it, I've found some things that I'd like to comment here:

- I could not commit new files (i.e. files created in OT or imported into the project) using the **Put** command from OT. I could select them and use the Put command on them, and that seemed to work (no error message), but it wouldn't do the job. So I had to manually do it from the SVN client. Perhaps was something wrong on my side of things (I have SVN 1.7.9 working against an online server from sliksvn.com).

- I've got an error while trying to **Put** a specific scene file to the repository, was something regarding the scene icon. It worked well when I used the **Put** command on the entire project folder, though.
put_error

- Some dialogs, (**Get**, **Put**, **Edit Frame Range**) failed to adjust to an appropriate size when opened. 
error_framerange

- **Get Revision** dialog doesn't display the file icons, but a question mark. The text is hardly readable on light rows. There's too much difference between light and dark row background colors. And the window is not resizable.
get_revision

- **Comment** text input field background on all dialogs is the same as the main dialog background, giving the impression of an informative text, rather than a data entry field.
edit

**Comment by manongjohn** [comment]
@gab3d  Thanks for testing

> I could not commit new files (i.e. files created in OT or imported into the project) using the Put command from OT.

I have no problems committing with the Put command on newly added files created in OT, provided I use Put on the individual files or the immediate folder it is in. I confirmed the commits registered in my online repo (riouxSVN.com). 

I do notice if I use Put at the project root level, it does not allow you to pick new files in any sub folders, only those that changed.  I will look into that.

> I've got an error while trying to Put a specific scene file to the repository, was something regarding the scene icon.

Perhaps this is related to your other issue?  If you can find steps to easily duplicate it, please let me know.  

By any chance, are there .svn folders in any of your sub folders of your project? For SVN 1.7, there should only be 1 at the project root folder. If there are any others, they should be deleted.

I'll look at fixing the display issues. Was debating putting that in a different PR. I wanted to primarily fix functionality with this PR.

**Comment by gab3d** [comment]
@manongjohn 
ok, thanks. Perhaps I'm doing something wrong...
I'll check things on my side and make another try.

> By any chance, are there .svn folders in any of your sub folders of your project? For SVN 1.7, there should only be 1 at the project root folder. If there are any others, they should be deleted.

That seems to be ok: just one .svn folder at the root directory. 👍

**Comment by manongjohn** [comment]
@gab3d Where did you get your 1.7.9 SVN command line installer? I want to see if i can duplicate your issues with the version you are using in case there is something odd with 1.7.9.

I have tested both 1.6 and 1.12 and they were able to Put with no issues. I even tried Putting then scene icon specifically. The svn error messages you are seeing are from svn, not OT so not sure why you are having trouble but will see if I can duplicate.

**Comment by gab3d** [comment]
@manongjohn 
Sorry, now I see it's really SVN 1.7.18
(Previously I had 1.7.9 but I had to upgrade TortoiseSVN (to v1.7.15  x64 ) to get its command line tools installed, so I ended up with SVN 1.7.18).
You can get it [here](https://osdn.net/projects/tortoisesvn/storage/Archive/1.7.15/Application/).
Thanks!

**Comment by ave4** [comment]
Is it possible to use git instead of svn, at least in a purely theoretical way?

**Comment by RodneyBaker** [comment]
@ave4 Yes, it's possible. Some discussion has occurred about using GIT in lieu of SVN and as I recall @manongjohn did a little research in that direction.  
It would be a considerable development effort.

**Comment by manongjohn** [comment]
I believe, in theory, you can use git instead of svn, however there are a few features of SVN that OT uses that are not inherently in git:

- File locking: 

Needed to prevent changes to files currently being edited by someone else.

I feel this is important because you can't merge file changes from multiple users to 1 image file (i.e png files). Merging code changes in git is one thing. Merging drawing changes is something different. Without this, 2 people working on certain file types will cause conflicts and someone's work will wind up being lost or have to be redone.

File locking appears to have been initially introduced into git-lfs. Would need to do more research into it.

- File Property setting/unsetting: 

Needed for logical messaging and locking of frame ranges so multiple people can edit different parts of the same level.

There is support in OT for multiple people editing specific frames in toonz vector and toonz raster levels and merging them together. This feature of SVN, in conjunction with file locking, helps to coordinate that in OT.

There are .gitattributes, but this file does not appear to be updatable by some git command as far as I can tell. 

- File/repo status and property output in XML format

Needed to easily digest SVN output and set statuses within OT appropriately.

If anyone has better insights into git and how to best replicate these SVN features, let me know.

**Comment by gab3d** [comment]
@ave4 
> 
> Is it possible to use git instead of svn, at least in a purely theoretical way?

I'd ask what the benefits of using GIT over SVN would be, in the context of OpenToonz?
Because frankly, I find SVN to be much simpler than GIT. 
So if it's just for the sake of using a "cooler", more trending, version control system, without any tangible benefits, well... I'd just keep SVN and save that efforts for more needed features.

In any case, what I'd dedicate some time to, would be to make SVN configuration even simpler, by including in the Preferences > Version Control section a way to add a SVN repository path and user data. So even more people could try the benefits of using it.
But that's just me... 😉

**Comment by gab3d** [comment]
@manongjohn 
One other problem I've found, that I forgot to mention in my report above, is that when an svn project is the current project, the **Project Settings...** dialog is not able to show it, and shows *sandbox* instead as current project).

Also (this is not a bug, but rather an annoying/distracting behavior), when doing right-click over any folder in the File Browser the folder collapses or expands (this also happens when clicking on the circle to the left of a project folder, to select a new current project).
This unintended collapsing/expanding action usually changes the on-screen positions of the folders, moving the item you just clicked away from the mouse pointer.

**Comment by gab3d** [comment]
@manongjohn @shun-iwasawa 

...and another thing, that is more of a question than a bug report.

At the top part of the **New Project** dialog, what is usually displayed are the defined Projectroot folders, so that a new project can be created under one of them. 
But for SVN repositories it shows, not just the repository root, but the whole folder structure.
To me that's confusing, but is it right to be that way?

Sin título

**Comment by manongjohn** [comment]
@gab3d 

Not sure how you have your project root folders and SNV set up.  I have one of my Project Root folders as the root of my SVN so that every new project and file I create underneath it is subject to SVN control. My projects show up properly in Project Settings and Startup dialogs when I select them. 

At any rate, my other PR will likely fix that "sandbox" issue you have because it currently thinks its not under a known project root folder. 

I agree that right-click is a pain. It is is an inherent issue with the control in that room. I'm not going to fix that with this PR and will likely fix that separately.

**Comment by gab3d** [comment]
@manongjohn 
Ah... ok, I haven't set the svn directory as a project root (it doesn't say so in the manual instructions).
This solved the problem where **Project Settings** dialog don't show the current project if it is an svn folder, and showed sandbox instead.

What still persists is the **New Project** dialog showing sub folders of defined project roots ...and (now that I've defined the svn folder as project root) also showing the svn folder duplicated: 🤔 
Sin título


> At any rate, my other PR will likely fix that "sandbox" issue you have because it currently thinks its not under a known project root folder.

great! 👍 

> I agree that right-click is a pain. It is is an inherent issue with the control in that room. I'm not going to fix that with this PR and will likely fix that separately.

that'd be really great! thanks!!

Finally, I'm wondering if it wouldn't be convenient to rename **Project root** to **Projects root**, because it could lead users to think this is the root of a certain specific project, and not the root directory where to create several new projects. 🤔

**Comment by RodneyBaker** [comment]
Merging this as @shun-iwasawa has stated he is unfamiliar with SVN usage with Opentoonz.
If there are still any outstanding areas to address we should be able to identify them and get them fixed.

**Comment by ave4** [comment]
Found an interesting git extension that has file locking.
https://github.com/git-lfs/git-lfs/wiki/File-Locking

**Pull request merged**
