### PR TITLE
Fix raster paste crash

### LINKED ISSUE #1730: Copy/paste crash between frames
I find that I can copy and paste raster art from frame to frame. However, if I spend a couple of minutes in between pasting to make adjustments to a frame and then continue pasting I consistently get a crash. It's as if something goes wrong with the image stored in the clipboard.

EDIT: Just to clarify, duplicating entire frames isn't the problem, it's copying part of an image selected with the selection tool.

(Opentoonz 1.2, Windows 10)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/53744346-copy-paste-crash-between-frames?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by manongjohn**
This PR fixes #1730 

When attempting to paste a raster selection while the current focus is the scene viewer canvas, if there isn't an image in the frame already, a new blank image will be created for the frame so it will have something to paste into.

Note: When autocreation is disabled, no blank image will be created and the paste will not do anything.

### CODE REVIEW

**Comment by manongjohn** [comment]
@shun-iwasawa Per the log, build failed due to "The build stopped unexpectedly because of an unexpected logger failure".  Any way I can restart the Appveyor build without having to commit something like the Travis builds?

**Comment by shun-iwasawa** [comment]
@manongjohn 
I restarted AppVeyor build this time.
According to [this](https://www.appveyor.com/docs/team-setup/) it seems to be possible to make collaborators to have appveyor permissions... I'll take a look.
Until then, I think only way to trigger AppVeyor rebuild by yourself would be to close & re-open PR.

**Comment by shun-iwasawa** [comment]
@manongjohn 
Unfortunately, I couldn't find a way to invite collaborators to GitHub team without inviting the organization.
Instead, I sent a invitation to your personal e-mail address for directly assigning you the AppVeyor role.
Can you please check e-mail, accept the invitation, try to login AppVeyor and then check if you can re-build OpenToonz PRs?

**Comment by manongjohn** [comment]
@shun-iwasawa I can now see options to rebuild PR's for AppVeyor builds. Thank you!

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
Confirmed the fix. Please note that #2364 will fix a small problem related to this PR.
LGTM Thank you @manongjohn !

**Pull request merged**
