### PR TITLE
Add Swap Colors Button to Gradient Fxs

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will add a button to Fx settings which will swap gradient colors.

Related to the addition, this PR also includes the modifications as follows:
- Made the button labels ( `Copy RGB: ** > **` and `Swap ** and **` ) translatable.
- Made the button actions undo-able.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Works great.  Thanks also for the code commenting.

**Comment by gab3d** [comment]
@shun-iwasawa 
>     * Made the button labels ( `Copy RGB: ** > **` and `Swap ** and **` ) translatable.

great!
so, just a question: Can FX settings UI be translatable?
...I was under the impression that it wasn't the case. 🤔

**Comment by shun-iwasawa** [comment]
@gab3d 

> Can FX settings UI be translatable?

Not yet. They are currently set in `$StuffFolder/config/current.txt` .
I agree it would be better to be translatable with Qt Linguist like other UI texts (I don't want to make `current_es.txt` or `current_ja.txt` for that!).
Even if it becomes translatable, I think we'll need to prepare a way to obtain original English names because currently they are used in expression.

**Comment by gab3d** [comment]
I understand, yes. It'd be the right way to do it.
Thanks!

**Pull request merged**
