### PR TITLE
Issue #1130 - tfarm binaries into .app folder

### PR DESCRIPTION
**Pull request by damies13**
set CMAKE_RUNTIME_OUTPUT_DIRECTORY path for OSX so that when
add_subdirectory() calls add_executable(), the binaries know where they
need to be written so they are bundled into the mac .app folder

### CODE REVIEW

**Comment by damies13** [comment]
The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by damies13** [comment]
Issue #1130 - tfarm binaries into .app folder

**Comment by shun-iwasawa** [comment]
@damies13  Just a quick note that I failed to build this PR properly. Is this needed to include another fix in advance, such as #1140 ?

**Comment by damies13** [comment]
@shun-iwasawa I don't believe this PR has any dependancy, It seemed to build successfully with the automated builds. The only thing this PR does is change the CMAKE_RUNTIME_OUTPUT_DIRECTORY variable in the makelist file so that the command line utilities (including the tfarm binaries) get created inside the .app contents folder for the mac build. without this the get created but because they are outside the .app folder the get missed in the packaging of the mac version.

I realise that the command line utilities could just be added to the package separately by scripts, but putting them inside the .app folder is more inline with how mac applications are usually packaged, so I think this is probably best.

Out of curiosity what did the build fail on?

Dave.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
@damies13 
I'm so sorry for my too late response and thank you so much for tackling with tfarm+OSX issue.
I noticed that in both Jen.kins and my OSX environment the build fails just after the message like as follows: 

> \> Linking CXX executable OpenToonz_1.1.app/Contents/MacOS/OpenToonz_1.2.app/Contents/MacOS/OpenToonz_1.2

As you can see, a string `Contents/MacOS/OpenToonz_1.2` is doubled and tried to link the executable with wrong path.

Based on this PR I'll post another PR with small fix, which copies executables `tcomposer` and `tcleanup` into `OpenToonz_1.1.app/Contents/MacOS` after build, just like `lzocompress`.

**Comment by shun-iwasawa** [comment]
#1993 is merged. Thank you @damies13 for this !

**Pull request closed without merging**
