### PR TITLE
Add the guide to older/nightly installers

### PR DESCRIPTION
**Pull request by kogaki**

### CODE REVIEW

**Comment by justinclift** [comment]
Cool, that's a good idea. :smile:

**Comment by justinclift** [comment]
As an idea for future improvement, using a date stamp with the nightly builds can be very useful for people.  eg:

* OpenToonz-20160415.pkg
* OpenToonz-20160416.pkg
* OpenToonz-20160417.pkg
* OpenToonz-20160418.pkg
* OpenToonz-20160419.pkg
* OpenToonz-20160420.pkg
* OpenToonzSetup-20160415.exe
* OpenToonzSetup-20160416.exe
* OpenToonzSetup-20160417.exe
* OpenToonzSetup-20160418.exe
* OpenToonzSetup-20160419.exe
* OpenToonzSetup-20160420.exe

When something that used to work in OpenToonz unexpectedly doesn't any more, a person can try out the builds from various dates to find out when the break happened (and report it).  That makes it a lot easier for the developers to investigate, as only the commits from that day are the likely cause.

Here is an example of a nightlies directory for another popular Open Source project, if that helps:

&nbsp; &nbsp; http://nightlies.sqlitebrowser.org/osx/

**Comment by 3Rton** [comment]
Yes please!

**Comment by blurymind** [comment]
datestamps would make it easier to track any possible regressions

**Comment by kogaki** [comment]
Thaks all for your suggestion. We are now planing to release every builds per PRs :+1:

**Comment by kogaki** [comment]
We experimentally started to archive every builds <https://github.com/opentoonz/opentoonz_nightlies/releases>

**Pull request merged**
