### PR TITLE
Improve vector stroke selection

### PR DESCRIPTION
**Pull request by manongjohn**
This PR addresses #2775 by allowing users to select a vector stroke anywhere the stroke is drawn, accounting for thickness, not just from a fixed distance from the center line.

The fixed distance from center line is still used for 0 thickness lines or anything thinner than the fixed distance.

Caveat: Picking the right stroke where multiple strokes overlap may require moving closer to the center line or a clear section of the stroke you want.

### CODE REVIEW

**Comment by artisteacher** [comment]
This will be so helpful! Thank you.

**Comment by RodneyBaker** [comment]
I've been staring at this one for a few days and I'm not seeing a whole lot of difference although I saw some.  Part of this might relate to the fact that I've never felt vector lines were particularly hard to select before.  Perhaps that's because I learned to select closer to the ends?  (unsure)

Is it the subtle difference that is the change here?

I've looked at the code repeatedly and the only thing that comes to mind is that perhaps the selection area hot zone could be increased by a factor of 2.  (again unsure)
I'll do some more side by side comparisons this and previous releases.

Aside:  In the original issue #2775 one aspect of that discussed the shape being selected by clicking on/selecting its fill.  I don't think this PR attempts to implement that portion and if not just want @artisteacher to know.

**Comment by manongjohn** [comment]
Make sure your lines are very thick or zoom in to make the lines appear wider.   To truly see it, zoom in a lot or make the lines extremely thick, then try to grab the line closer to the edges.

**Comment by artisteacher** [comment]
At least on a Mac, the difference is very obvious (assuming a thick or very zoomed in stroke). It's significantly easier to select a stroke this way. I don't particularly need to select by clicking on the fill as long as strokes are easy to select.

**Comment by RodneyBaker** [comment]
Calling this one good.  The obvious areas for me is where the thinnest parts of the line are easily selected via this release.

LGTM

**Pull request merged**
