### PR TITLE
(WIP) CPP check multiple changes

### PR DESCRIPTION
**Pull request by rozhuk-im**
Various changes suggested by cppcheck

### CODE REVIEW

**Comment by rozhuk-im** [comment]
I will cleanup and rebase it later, also some changes better to revert.

**Comment by RodneyBaker** [comment]
I'll recommend this PR be considered for merger directly after v1.5's release... given a little time for feedback to roll in to make sure no immediate patches are required.   This will allow adequate breathing space and maximum time post v1.5 release to address any unintended consequences without concern for users that have downloaded the v1.5 release.  Then with all things complete users can happily be directed to the lastest nightly release containing the clean code generated with this PR.

Thoughts?

**Comment by RodneyBaker** [comment]
@rozhuk-im With v1.5 initial release now out this is an ideal time for the huge undertaking of this PR.
Can you run the CCPcheck process again with the current code of the v1.5 release to build upon that new foundation?

Thanks!

**Comment by RodneyBaker** [comment]
Closing.  Now would be an ideal time to rerun CPP check and refactor based on results.

**Pull request closed without merging**
