### PR TITLE
Disable onionskin during playback

### PR DESCRIPTION
**Pull request by turtletooth**
This disables onion skin during playback by default.

It can be allowed during playback via preferences, but will still honor the current state (on/off).  

onionskinplayback

### CODE REVIEW

**Comment by turtletooth** [comment]
#486

**Comment by blurymind** [comment]
@turtletooth you are a damn hero! This has bugged me for so long. :D

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM

**Pull request merged**
