### PR TITLE
Fix conflicts (Remove license and edition defines and code)

### PR DESCRIPTION
**Pull request by skitaoka**
https://github.com/opentoonz/opentoonz/pull/184

- Fix conflicts

This PR follows https://github.com/opentoonz/opentoonz/pull/290.

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins

**Comment by adamearle** [comment]
Hi Mate

I notice that Toonboom is intergrated into the "Tatic Pipeline" though i am
not completely sure if this is actually open source.

Can you confrim this? This would be something that could be really kool to
use with openToonz is if it is perhaps also intergrating

Natron, Krita, Audacity, Gnu Cash, etc, etc, etc.

Links:


   1. http://www.southpawtech.com/
   2. https://github.com/Southpaw-TACTIC/TACTIC
   3. http://www.southpawtech.com/resources/recent-headlines/
   4.
   https://www.toonboom.com/news/toon-boom-animation-acquires-tactic-studio-southpaw-technology
   5.
   https://channel9.msdn.com/Blogs/PartnerApps/Azure-Hosts-Southpaw-Technologys-Content-Creation-Solution
   6. http://natron.fr/
   7. https://krita.org/
   8. http://www.audacityteam.org/
   9. https://www.gnucash.org


*Adam Earle*

<MrAdamEarle@Gmail.com>

**Comment by skitaoka** [comment]
Jenkins, again.

**Comment by kogaki** [comment]
@adamearle Thank you for your information, but that's completely out of topic. I recommend you to ask any questions on user forum <https://groups.google.com/forum/#!forum/opentoonz_en>. We should discuss on code-related problems on pull requests.

**Comment by kogaki** [comment]
LGTM. Thanks, @ss23 @skitaoka

**Pull request merged**
