### PR TITLE
Fix Main Window Full Screen Mode

### LINKED ISSUE #2215: Full Screen: Black combo viewer
### Issue Summary
when I am using opentoonz, I goes to fullscreen then viewer go black

### Expected Results
 I expected it to be normal

### Actual Results
 program's viewer goes black

### System Information
* **OpenToonz Version**: 1.2 and 1.2.1 and lastest relases
* **Operating System**: win 10
* **CPU**: quad i5 core
* **Memory**: 6 gp
* **Graphics Card**:intel 4000
* **Graphics Tablet**:

### LINKED ISSUE #2796: Toggle Main Window's Full Screen Mode (Black)
### Issue Summary

Style Editor and Viewer become black, When I click on menus, I can't see the drop-down menu.

For back to the normal screen I need to use shortcut  Ctrl+` , In my case, When I back to the normal screen, Style Editor change size.

### Screenshot or Video Reference

When I click on "Toggle Main Window's ..." You see everything become black in gif (just in gif). When I click on menus you  just see drop-down menu. But I see OT windows and panels in my screen and I can't see the drop-down menu.

Toggle Main Window's Full Screen Mode don't work good

I don't know why Print Screen button and OBS can't capture ok in this OT screen mode. I take a photo with my phone from my monitor.

Toggle Main Window's Full Screen Mode don't work good

### Steps to Reproduce

1. Go to Window > Toggle Main Window's Full Screen Mode (or use shortcut  Ctrl+` ).

2. Style Editor and Viewer become black, And menus don't work.

### System Information
* **OpenToonz Version**: 1.3 stable, NB `55a5931`
* **Operating System**: Windows 7
* **CPU**: Intel Core  2 Duo
* **Memory**: 4 GB
* **Graphics Card**: NVIDIA GeForce 9600 GT

### PR DESCRIPTION
**Pull request by manongjohn**
This PR fixes #2796 and fixes #2215

There is a known Qt limitation concerning Full Screen mode on Windows system.

The suggested workaround was only applied to the Image viewer to allow it to go to full screen. I applied the same workaround to the main window to fix the full screen issue.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
With the initial testing I got excited because it appeared to be a full fix.
I did however run into one problem which hopefully you'll be able to repeat and decipher.

- Firstly, going to Full screen mode works.  Thank you for that!
I haven't used full screen mode much in the past but with this fix I'm sure to use it more as a default.

Issue with restarting in Full Screen Mode
- When leaving Opentoonz in Full Screen and then restarting Opentoonz appears to begin to work in full screen mode but upon dispatching the Startup Popup all of the menus lock up and the various viewers go to black.  If I turn off the Startup Popup Opentoonz opens immediately to the locked menus and black viewers.

Note that I can escape the full screen lockup via shortcut key and then things return to normal.  So the current fix works well... just not after a restart in Full Screen mode.

I'll continue to test this to see if any specific solutions present themselves.

**Comment by manongjohn** [comment]
@RodneyBaker Thanks for testing. Should be fixed now.  I moved the change I made earlier in the initial setup of the main window so that the workaround is already activated when setting up the fullscreen mode at initial startup.

**Comment by RodneyBaker** [comment]
Works great @manongjohn Thanks for the immediate fix!

**Comment by RodneyBaker** [comment]
Merging this as several people are waiting on the fix.

**Pull request merged**
