### PR TITLE
Fix straight line regressions

### LINKED ISSUE #4968: Mypaint Geometry tool and  TLV Raster shift for Straight line Bug.
### Description

Mypaint Geometry and TLV Raster and Raster Brush shift for Straight line is Broken in the Latest nightly build due to the new Assistant Perspective tool merge.

### Steps to Reproduce

1. try to use the Geometry rectangle tool with Mypaint.
2. try to use the shift for straight line Brush feature with Mypaint in Raster TLV, also Mypaint Raster brush has the same shift for straight line problem.

### Expected Behavior

the Mypaint Brush shift should let u maker straight lines and the Geometry tool should work with Mypaint brushes. 

### Screenshots, Video & Crash Logs

_No response_

### OpenToonz Version

1.7

### OpenToonz Version Information

current Nightly build

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR fixes #4968 .
Now the class `MyPaintToonzBrush` seems to need the 4th argument of the constructor `interpolation` being set to `true` in order to work properly.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Thanks for the timely fix @shun-iwasawa 
Much appreciated!

**Comment by openanim** [comment]
@shun-iwasawa I don't know if it's intentional, but in case it hasn't been brought up, there's been a difference in the behavior for creating lines with modifiers on the standard raster level since this fix was merged. Isn't too annoying but just to mention :

Now, the line is affected by the same behavior found on the guide assistant. This gives an effect of very slight offset when u look it from a distance, although I suppose there isn't any. 

Also, a different observation when activating "camera box" from the view menu for color when on the xsheet.

With toonz raster level the level seems to work as expected. But after testing this PR #5039  it seems that it will resume this new behavior after the merge.

https://github.com/opentoonz/opentoonz/assets/29790512/a5715a47-1d18-4505-9aa8-edcc58d58072

**Comment by blackwarthog** [comment]
Hm... I thing it is not shift. Just line pained with two colors - black and white (black at left, white at right). So line will be visible on any back ground. On the white background you see the left part of line.

**Comment by openanim** [comment]
@blackwarthog 

Thanks for the detailed explanations :)

**Pull request merged**
