### PR TITLE
Remove LibJpeg & add jpeg-turbo package in the thirdparty folder

### LINKED ISSUE #3733: JPEG Crash
@shun-iwasawa In https://github.com/opentoonz/opentoonz/issues/3597#issuecomment-786281563 you mentioned problems with JPEG. I installed a bunch of nightlies, and narrowed it down to this PR #3721 since the problems started to occur.

➡️  https://github.com/opentoonz/opentoonz_nightlies/releases/tag/nightly_3e3ab5100ce5d2bdb9c9179f992884f001f5e46c

On Discord @beeheemooth mentioned that he was getting a crash trying to render a single JPEG. I confirm the crash. There's also a crash trying to load a thumbnail for any JPEG file in the File Browser.

_Might also be #3719, but there's no nightly build, I tested the AppVeyor and it was fine though, I can't get it to crash, just to note._

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This fixes #3733 .

This PR removes LibJpeg from the `thirdparty` folder and introduce `turbo-jpeg` (v2.0.6) package together with pre-built libraries.
Jpeg libraries will be replaced by ones in the `turbo-jpeg` package so that it won't cause crash when using along with turbo-jpeg.

Please note this change affects only Windows builds. For other OS, LibJpeg is obtained separately via package managers and the crash does not seem to occur in the first place.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Will merge this to get this into the hands of those itching to test.
Thanks @shun-iwasawa!

**Comment by RodneyBaker** [comment]
@shun-iwasawa   I am (still) getting a crash upon attempting to render to jpg format with the latest nightly.
Double checking to see if I've missed something on my end and am using a different release...

**Comment by shun-iwasawa** [comment]
@RodneyBaker Thank you for testing! I confirmed that the nightly release is updated and worked OK now.

**Comment by konero** [comment]
I can't get it to crash anymore, thanks! All problems I experienced was solved. 👌

**Pull request merged**
