### PR TITLE
Multilingual support for FX browsers

### PR DESCRIPTION
**Pull request by allphfa**
# Modify this file with multi lingual support:

$opentoonz/shuff/config/current.txt

### for example：

```
<stringtable>
  <item>"addFx"   "プラス"   </item>
  <item>"addFx.value"  "値"   </item>
   .....
  <item>"blendFx.value"  "値"  </item>
</stringtable> 

```

### FX browser translation needs to be added manually:

```
<stringtable>

  
  <item>"Background"  "背景"   </item>
  <item>"Blur"   "はっきりしない"   </item>
  <item>"Distort"  "歪んだ"   </item>
   .....
  <item>"Shaders"  "シェーダー"   </item>
   .....
</stringtable> 

```

### CODE REVIEW

**Comment by githob605608886** [comment]
Modify this file with multi lingual support

$opentoonz/shuff/config/current.txt

for example：

```
<stringtable>
  <item>"addFx"   "プラス"   </item>
  <item>"addFx.value"  "値"   </item>
   .....
  <item>"blendFx.value"  "値"  </item>
</stringtable> 

```

Sorry, I don't understand GIT. I submitted it with vs2017's git, so I repeated it many times

**Comment by githob605608886** [comment]
# HasUILabel causes the plug-in to not use translation
> $opentoonz/toonz/sources/include/tparam.h
> Other documents are modified by the translation of the support, does not affect the use

# About DWANGO plug in the finished
> for example：
> ```
> <stringtable>
>  <item>"DWANGO_BlurCurlNoise"   "ファジーカールノイズ"   </item>
>  <item>"DWANGO_BlurCurlNoise.gain"  "閾値"   </item>
>   .....
>  <item>"DWANGO_BlurCurlNoise.debug"  "デバッグ"  </item>
> </stringtable> 
> ```

**Comment by RodneyBaker** [comment]
Initiating a review of old PRs to see which ones are still active and/or being worked.

@allphfa  Can you confirm the status of this PR?

**Comment by RodneyBaker** [comment]
Closing as abandoned.
Will reopen as necessary.

**Pull request closed without merging**
