### PR TITLE
Use `unique_ptr` instead of `auto_ptr`

### PR DESCRIPTION
**Pull request by skitaoka**
- replace std::auto_ptr<> to std::unique_ptr<>
- apply clang-format

### CODE REVIEW

**Comment by kogaki** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins

**Comment by Hi-king** [comment]
Looks Good

**Comment by kogaki** [comment]
LGTM

**Pull request merged**
