### PR TITLE
Refactoring: Unify Viewer and Comboviewer base classes

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR wil unify the `SceneViewerPanel` and the `ComboViewerPanel` classes and make them to be the subclasses of a `BaseViewerPanel` base class, because most of the source code is identical.

### CODE REVIEW

**Comment by artisteacher** [comment]
Does the viewer have any performance benefit over the combo viewer? The combo viewer just seems so much more flexible, since visibility of the tool options and toolbar can be toggled on and off. I guess I just wondered if there's a reason we have both?

**Comment by RodneyBaker** [comment]
Posting intent to merge as everything looks good here.

**Comment by RodneyBaker** [comment]
Thank you @shun-iwasawa for the refactoring of viewer base classes.
LGTM

**Comment by RodneyBaker** [comment]
@shun-iwasawa I don't see it in the code for this PR but we recently lost the default setting that turns on the Frame Slider for the Viewer.  I plan to search it out but perhaps you'll know exactly where to look for it.

It does NOT appear to me that this PR turned the default option off but this is me starting the search...

**Pull request merged**
