### PR TITLE
add clean-up at the end of SceneViewer::contextMenuEvent for OSX

### PR DESCRIPTION
**Pull request by tomosu**
fixed problem reported in https://github.com/opentoonz/opentoonz/issues/115 and https://github.com/opentoonz/opentoonz/issues/73 .

### CODE REVIEW

**Comment by kogaki** [comment]
I feel this approach is a little bit confusing because view-related method `contextMenuEvent` clean-ups control-related members (`m_mousebutton` etc ...). If there's no other solutions, it is ok to merge. But here are my suggestions

1. Cleaning-up control-realted members might be done *first* in the `contextMenuEvent`, not *last*
2. Plz add some comments on the code (e.g. `cleaning-up after right button click`)

**Comment by tomosu** [comment]
Thank you for your comment.
I reflected your suggestions to sceneViewerEvent.
Please check this.
https://github.com/opentoonz/opentoonz/pull/152/commits/cb0b4d066f8838728e5ba23944c95c6e29f14ec6

**Comment by kogaki** [comment]
LGTM

**Comment by xenogenesi** [comment]
I've a patch for linux which fake a release event, apparently on linux and on macosx the release event is lost handling the contextMenuEvent

**Comment by xenogenesi** [comment]
posted on #51 

> About #73 / #115, if someone want to give a try to [this](https://github.com/xenogenesi/opentoonz/commits/fix-contextmenu-release-event) (also on mac)

**Comment by kogaki** [comment]
@xenogenesi Great. Your solution looks more reasonable. Could you create the another PR so that we can test and merge smoothly ?

**Pull request merged**
