### PR TITLE
Fx Pass Through

### PR DESCRIPTION
**Pull request by turtletooth**
This is for #1346 

This is an fx that does nothing except pass through what is sent to it.
Exciting huh?

pass

premacro

postmacro

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Nice.  This looks handy.  

The introduction of this node got me thinking that all nodes should have a 'pass through' function and it turns out they in fact appear to have that functionality via turning on/off.  So, I learned several somethings here.  :)

**Comment by shun-iwasawa** [comment]
Nice feature. It would better to have an original appearance in the schematic in the future.
Jenkins

**Comment by 2dvision** [comment]
Is it possible add multiple node to Fx PassThrough input? It is useful if user want add one FX for multiple node.

mutiple input node

**Comment by shun-iwasawa** [comment]
LGTM Thank you @turtletooth for addition.

**Pull request merged**
