### PR TITLE
Brush package optimized for OpenToonz

### PR DESCRIPTION
**Pull request by andeon**
Some brushes builded and optimized for OpenToonz raster levels

prev

I put a red border line on the brushes that don't work at Toonz Raster Levels,  just an attempt to flag them.

### CODE REVIEW

**Comment by artisteacher** [comment]
Leafs should be Leaves. It would be great to have an indicator for brushes that won't work on toonz raster levels.

**Comment by andeon** [comment]
> 
> 
> Leafs should be Leaves. It would be great to have an indicator for brushes that won't work on toonz raster levels.

I fixed it, thank you!

**Comment by RodneyBaker** [comment]
Very nice addition @andeon 
LGTM

**Comment by RodneyBaker** [comment]
@andeon Just a note of thanks for these brushes.
I'm really enjoying using them.

**Pull request merged**
