### PR TITLE
Fix for Pen Glitch on Mac by turtletooth (modified)

### LINKED ISSUE #756: Tablet incorrectly detects hovering as touching on MacOS
Opentoonz 1.1.1 does not work with my 27QHD cintiq and mac OS el capitan. It believes the pen hovering above the screen is touching the screen and making a line. It constantly freaks out and thinks I'm scribbling all over the screen when I'm really just hovering above. 

This makes OpenToonz unusable.

screen shot 2016-08-24 at 7 31 30 pm

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will fix #756, based on the PR #1304 by @turtletooth .

After investigation, I found that this problem was a combination of multiple issues related to Qt and the tablet behavior:

### THE MAIN CAUSE OF THE ISSUE
On OSX, there is a critical problem that `SceneViewer::mousePressEvent` is unexpectedly called when LEAVING the stylus pen.  When the pen approaches next time, it causes unwanted stroke drawn while hover-moving of the pen.
So, I added a function to force initializing such irregular mouse press ( `resetTabletStatus()` ) which will be called when `QEvent::TabletLeaveProximity` is detected. 
**NOTE**: For now `QEvent::TabletLeaveProximity` will NOT be detected on Windows. See [QTBUG-53628](https://bugreports.qt.io/browse/QTBUG-53628).

### OTHER PROBLEMS
There were some other problems detected as follows:

* On OSX, drawing with the stylus pen causes one of the following. I couldn't find any obvious condition. It seems to be chosen randomly.
  * Firstly `tabletEvent` and secondly `mousePress/Move/ReleaseEvent` are called. (It is in the majority of cases on Windows)
  * Only `mousePress/Move/ReleaseEvent` is called. (It seems to be reported on Qt4, but not confirmed on Qt5. See [QTBUG-26532](https://bugreports.qt.io/browse/QTBUG-26532) .)
  * Only `tabletEvent` is called.
* so, I separated the actual process from `mousePress/Move/ReleaseEvent` and enabled to call from `tabletEvent`. 

* The current Qt seems to fail to catch the Wacom's button binding properly with `QTabletEvent->button()` when pressing middle or right button (using the side buttons of the stylus pen) . So, in such case I set `m_tabletEvent = FALSE` and let the `mousePressEvent` to work.

* (It is specification rather than a problem.) When drawing with the stylus pen, `tabletEvent` seems to called more often than `mouseMoveEvent`. So I used a timer in order to limit the function  `onMove()` to be called in 50 fps (20msec interval) in maximum. 

I checked lightly both on Windows & Mac OSX (using Wacom Intuos Art CTH-690). Hope someone would doublecheck the modification and   availability on Linux as well.

If the issue will be settled with this PR, I would like all the bounty to be granted to @turtletooth  for tackling this problem. I'm already paid for working on OpenToonz and this PR is based on his work.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
Thank you @shun-iwasawa for your work on this.  You are incredibly thorough and your code is beautifully commented.  I apologize for missing the items you found.  You did a great job.

I currently don't have access to the Mac that I used to build the original fix.  Are you comfortable with me testing on PC, to make sure that everything works there, and then merging so those with Macs can test the nightly builds?

**Comment by shun-iwasawa** [comment]
>I currently don't have access to the Mac that I used to build the original fix. Are you comfortable with me testing on PC, to make sure that everything works there, and then merging so those with Macs can test the nightly builds?

Your suggestion is reasonable and will fulfill the original purpose of nightly build. Please merge if you confirmed that there is no problem on Windows. Thanks!

**Comment by jpturcotte** [comment]
Thank you both so very much! I am sure this will be a godsend for Mac users.

**Comment by artisteacher** [comment]
Thanks! I'm really looking forward to testing out all the mac specific fixes.

**Comment by turtletooth** [comment]
@shun-iwasawa I have tested this and it appears to work fine on Windows.  As soon as the conflicts are resolved, I'll do a quick check again and it is ready to be merged for testing.

**Comment by shun-iwasawa** [comment]
@turtletooth Resolved conflicts.

**Comment by turtletooth** [comment]
Windows seems to work fine with these changes.  LGTM.

**Comment by turtletooth** [comment]
@shun-iwasawa This was merged before Jenkins was run.  Does that have any effect on the nightly builds?  @artisteacher is still seeing bugs, but your fix seems very thorough.

**Pull request merged**
