### PR TITLE
Fix alias crashes

### LINKED ISSUE #1227: Crash when accessing alias folders in Browser
When using the browser room to navigate to a file outside of the stuff folder (ie. Downloads or etc.), inside of My Computer are 2 paths. The first allows you to eventually navigate to the desired folder. If you try to access Macintosh HD, inside of Volumes (the 2nd path), there is an immediate crash. 
screen shot 2017-05-25 at 8 57 33 pm

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/45585007-crash-when-accessing-alias-folders-in-browser?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by artisteacher**
This fixes #1227 and #984 by removing the alias directories and files (symlinks) from the File Browser for Mac and Linux OS.

### CODE REVIEW

**Comment by turtletooth** [comment]
Great work @artisteacher - Thanks for this.

**Comment by manongjohn** [comment]
I wonder if this should be expanded to include LINUX systems for someone who might have somehow defined a symbolically linked directory on their system.  I'm guessing they would have the same issue.

**Comment by artisteacher** [comment]
@manongjohn, would that just be a matter of switching the if else statements? If windows, keep original filters, else original filters + no symlinks...

**Comment by manongjohn** [comment]
Yes. That should suffice.

**Comment by shun-iwasawa** [comment]
@artisteacher  Thank you for reporting and tackling with this!

Sorry for responding this so lately, but I found that the same crash can be reproduced on Windows as well by clicking a shortcut item in the file tree.

[QTBUG-23927](https://bugreports.qt.io/browse/QTBUG-23927) which you mentioned in #1227 seems to be due to a bug in QuaZip according to the [comment](https://bugreports.qt.io/browse/QTBUG-23927?focusedCommentId=353000&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-353000). In the Description it also says 
> for normal symlinks this works perfectly .

Please let me investigate further on this and post an alternative PR, which will fix crash keeping SymLink available.

**Comment by artisteacher** [comment]
No problem, thank you for looking into this. It would definitely be preferable to keep the symlinks available.

**Pull request closed without merging**
