### PR TITLE
(WIP) Adding *BSD support

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
Hi :-) any opinion ?

**Comment by devnexen** [comment]
Hi @shun-iwasawa @manongjohn ... any chance it gets cherry picked or committed ? :-)

**Comment by RodneyBaker** [comment]
This PR could use someone to review and assist with taking BSD support all the way to the finish line.

**Comment by devnexen** [comment]
Ah yes one year later most likely some conflicts arise :-) will see how to resolve them.

**Comment by RodneyBaker** [comment]
@manongjohn can you give this a Jenkins/Travis refresh?
While others more knowledgeable than me will need to review the actual code... passing the Travis check appears to be the primary issue with this PR going forward.

cc:  @shun-iwasawa

**Comment by manongjohn** [comment]
Retriggered but still failing. The changes made for compiling on BSD is causing Linux and macOS builds to fail.

In the case of Linux, it's failing to find the SuperLU libraries. For macOS there are some compiling issues.

**Comment by RodneyBaker** [comment]
Thanks for the update and info @manongjohn 
It does look like adding BSD support will likely slip to the 2020 development cycle.
@devnexen We'll keep this PR open unless you prefer to shut it down.

**Comment by RodneyBaker** [comment]
Closing to take this off the radar for v1.4.
Hopefully we can add BSD and other support in 2020 development cycle.

**Pull request closed without merging**
