### PR TITLE
New Theme

### PR DESCRIPTION
**Pull request by turtletooth**
Updated theme based on the current dark theme.  Styled closely to @konero suggestions with a few tweaks.

Note:  This only changes what can be styled through qss.  Other icons and styles that are not available through qss will need to be another PR.

Overview:
theme_window

Tool Options:
theme_options

Output Settings:
theme_output

Cleanup Settings:
theme_cleanup

Style Editor:
theme_style_with_change

You can try it here:
[dark.zip](https://github.com/opentoonz/opentoonz/files/778596/dark.zip)

Unzip and place in your OpenToonz stuff folder in config/qss/

### CODE REVIEW

**Comment by turtletooth** [comment]
@artisteacher Would you be willing to try this on the mac and see how it looks?

**Comment by artisteacher** [comment]
I really like the rounded corners and flat look. I think there are a couple places that could be adjusted a little.
Sometimes the background of the header area does not have enough contrast with the surroundings.
screen shot 2017-02-16 at 7 29 57 am
I wonder if it would be helpful to have a tad more contrast to separate the toolbar visually - especially as there are such strong darks elsewhere in the theme.
screen shot 2017-02-16 at 10 20 01 am
The stye editor has greatly improved clarity but needs some refinement (though these are preexisting issues). The #StyleEditorTab (line 419) looks like it has a size or positioning issue which results in the gap in the border. The color slider labels get too compressed so that the labels can be unreadable. Adding min-height:12px; inside of the style #colorSliderLabel, #colorSliderField (lines 505-506) would resolve that issue. The text inside the buttons gets cut off if the style editor is too narrow. There may be a better solution, but setting min-width:34px; inside of #StyleEditor QPushButton (line 407) is a quick way to prevent the text being cut off.
screen shot 2017-02-16 at 7 20 09 am
The level palette has the same border gap as the style editor, but only when there are colors in the palette.
screen shot 2017-02-16 at 8 44 00 am
If the function editor is too short, the text gets cut off in the interpolation area. Min-height would be helpful for all of the labels there. I haven't been able to find that area in the qss so far.
screen shot 2017-02-16 at 8 46 32 am
There is a lot more green than there used to be - which is actually really nice. Fewer colors often results in better color harmony. I wonder if some of the red areas would work in green instead - unless there is a rational behind the red.
screen shot 2017-02-16 at 8 49 54 am
screen shot 2017-02-16 at 8 50 00 am
Looking at them altogether, I think some of the greens could complement each other more.
screen shot 2017-02-16 at 8 59 37 am
I may have more feedback after spending a little more time with the theme, but I definitely like this direction. I hope some of the fantastic icons from @konero get integrated at some point.

**Comment by Agnyy** [comment]
image
image

**Comment by turtletooth** [comment]
I made most of the changes you suggested.  I left the toolbar color as I couldn't find a change that looked better and convention for most programs is that the toolbar has the same background as the rest of the UI.  

Some of the green colors you pointed out aren't accessible via qss and will need to be changed in the code.  That is something to look at later.

I plan on submitting PRs for the other icons based on @konero suggestions.

If you wouldn't mind checking again, here are the updates:
[dark.zip](https://github.com/opentoonz/opentoonz/files/781417/dark.zip)

**Comment by artisteacher** [comment]
Thanks for making the changes! The style editor is so much better! 

The border for the style editor & levels palette really needs to be 2px for the groove effect to work. With just one pixel, you get this:
screen shot 2017-02-17 at 7 17 51 am
Due to how colors are adjusted for a groove style, the color really needs to be something close to #8f8f8f.
screen shot 2017-02-17 at 7 17 13 am
With #8f8f8f, you can see the color is just a hair off but is pretty close. I think there was a pr that mentioned the area being matched is hardcoded? Since a lighter and darker value of the selected color  is what displays, it is tricky to figure out an exact match - if it is even possible.
screen shot 2017-02-17 at 7 19 29 am
The entire interpolation area still gets compressed if the function window is too short. I still haven't had luck finding that in the qss. Do you know if it is in the qss?
screen shot 2017-02-17 at 7 43 41 am
As far as the toolbar goes, I agree with leaving the background color. Some of the rooms just have significantly stronger contrast on the right that it skews the visual balance a little. Not a huge deal - more a nitpicky detail.  

Speaking of nitpicky details, if it is possible to adjust the border color of the fields to something slightly more subtle like #3d3d3d, I think it would be worth considering.
screen shot 2017-02-17 at 7 52 15 am
In the cleanup area, some of the lock icons are buttons and others are not. For continuity, it might be helpful to stick with one approach or the other.
screen shot 2017-02-17 at 8 20 51 am
screen shot 2017-02-17 at 8 20 45 am
Lastly, it looks like all the dropdowns have blue as the hover state.
screen shot 2017-02-17 at 8 27 30 am
I'm glad that the icons will be updated later on. I'll look forward to seeing that change come through.

**Comment by Agnyy** [comment]
How do you remove this line?

**Comment by Agnyy** [comment]
I would like to see something like that. 
2c_amulponk

**Comment by Agnyy** [comment]
I am inquisitive to do it, but it looks yet moist. 
pvxenpsx8s8

**Comment by Agnyy** [comment]
I speak English very bad. But if you can help me, I'll be very happy.

**Comment by Agnyy** [comment]
Thank you ))))

**Comment by turtletooth** [comment]
@artisteacher - Thanks for the feedback

The border on the tabs I made 1px in preparation for the PR about moving the line color to qss.  This will allow for only one line color needed.  I made the style solid instead of grooved.

I haven't been able to find the function interpolation part either.  

The field border color was based off of a design that @konero made in #750.  I actually like the slightly less subtle version here to give a visual indicator that the user can interact there.

I was able to fix the look of the locks and the dropdowns.

You can try it here:
[dark.zip](https://github.com/opentoonz/opentoonz/files/784204/dark.zip)

**Comment by turtletooth** [comment]
@Agnyy That line is in #DockSeparator

**Comment by turtletooth** [comment]
The new icons are in #1050.  More icon PRs will be coming soon.

**Comment by konero** [comment]
@turtletooth Perhaps you could rework how QDockWidgets are separated in the code. Instead of #DockSeparator I think it would be better to style widgets by giving _them_ a border or at least putting in some classes and wrappers to make it possible in QSS so the original themes remain supported.

I tried doing it a few months back but for some reason I couldn't globablly style them, each widget had to be styled independently. Maybe you can figure it out though, I'm very rusty with C++.

The Style Editor window has a hard-coded black outline attached to it somewhere if you look closely, it's a very ugly placement IMO as it offsets the widget to everything else.

Here's a mockup for what I mean, close to what Toon Boom / Maya use.

ot_v1_001

Sorry for being off-topic, but the widget separators looks to be a PITA no matter what theme is going to be used.

**Comment by turtletooth** [comment]
@konero I fixed the style editor line in #1053

**Comment by turtletooth** [comment]
@konero I made the widgets frameable in #1054

Here is example qss that makes it work for theming:

```
TDockWidget, #StyleEditor {
	border: 1px solid lighten(@m_baseBG, 10);
}

#toolBar {
	border-right: 2px solid lighten(@m_baseBG, 10);
}
```

The Style Editor was stubborn and required its own tag, and the toolbar has a weird issue that the right border only shows up with a border of 2px - which displays as 1px.

**Comment by MousLast** [comment]
Very cool if such a design. 
image 
image 
image 
image

**Comment by MousLast** [comment]
then everyone will want to use the program. 
image 
image 
image

image

**Comment by FrameScool** [comment]
need a beautiful topic for Opentoonz. as these. 
image
image
image
image

**Comment by adamearle** [comment]
Nice clean mate I love it. Can only hope this gets picked up opentoonz 
interface is crap its one of the reasons why its not adopted at the 
studio yet where i work.

Adam

**Comment by turtletooth** [comment]
Changed to WIP.  I'm going to play with the color scheme @konero had in his screenshot.  I like having the negative space (the separators) be the darkest part- let me see how it works here.

**Comment by RodneyBaker** [comment]
>  opentoonz interface is crap

I"m sure the developers that worked hard to create that interface appreciate that highly constructive feedback.  ;)

**Comment by adamearle** [comment]
Yeah i look it wasn't the greatest comment I have ever given here, but 
has the interface updated since the release of opentoonz?

Isn't it good to know that studios won't adopt it because it is crap and 
should be updated. There have been alot of great UI designs on here have 
any of them introduced yet?

while i am in my early pre work rant simply horizontal timeline will 
make artist feel more comfortable and studios for that matter.

Honestly I am not saying anything new here.

As for the the UI there IMO there is alot wrong with it in its current 
state that could be tweaked to make it much easier on the eyes to look 
at instead of being so distracting.

I have to go to work we can continue later. Perhaps include an image of 
the current UI and we can talk about it.
but honestly alot of great work has already been suggested.

Adam

**Comment by Agnyy** [comment]
How do you like it?
image

**Comment by adamearle** [comment]
So i gather the team around to take a look and basically said make it look
more adobe or  the new maya

beyond i asked what are the quick fixes they said pretty much as i think
the contrast in the button are to distracting creating to much visual noise

so everyone pretty much said as long they can adobe/ maya/ krita dark
themes pretty close than it should help the reduce the contrast of the noise

Again i would like to add that there has been loads of great new designs
put forward and i am not saying anything that no one else has already said
and what i have said.

so i would suggest see if you can dredge up those people and get them
talking to toegeter.

*Adam Earle*


*Phone:* 0431799431

*Google Hangout: * MrAdamEarle@Gmail.com

*Email:* MrAdamEarle@Gmail.com

**Comment by turtletooth** [comment]
I made the negative space the darkest part, played with some other contrast areas, adjusted the text to appear cleaner, fixed the spacing on the pencil test popup and a few other tweaks.

Here is a screenshot:
new_theme_2


@shun-iwasawa This is based off of the current darkest theme.  Do you have any interest in replacing that theme or simply adding an additional theme?

**Comment by turtletooth** [comment]
BTW- Here is the latest for anyone who wants to try it out:
[dark.zip](https://github.com/opentoonz/opentoonz/files/789178/dark.zip)

**Comment by artisteacher** [comment]
I really love the darker negative space in the most recent version of this theme. I know that some people still have a really negative view of the interface, but I think this theme paired with several of the upcoming pr's (new icons, more being style-able in qss, and the toggle-able xsheet/horizontal timeline) is going to result in a great interface. This is a process, and great progress has been made and is continuing to be made. Thanks for all the time consuming work. It may be unpaid but it certainly is appreciated!

@turtletooth thanks for the explanations. It will be great to be able to modify that distracting line in the style editor and levels palette. It's interesting, I took a look on a newer screen and liked the field border color a lot. Just be aware that on some older screens the contrast can be a little exaggerated. 

It might be nice for the white line at the bottom of the color sliders to be slightly darker.
screen shot 2017-02-21 at 8 39 43 pm

I'm really looking forward to seeing all of the different pieces come together!

**Comment by adamearle** [comment]
WOAH this just keeps getting better and better doesn't it. Well done
brother.

What's else are you thinking about tweaking

Ad







On 21 Feb 2017 16:40, "Jeremy Bullock" <notifications@github.com> wrote:

I made the negative space the darkest part, played with some other contrast
areas, adjusted the text to appear cleaner, fixed the spacing on the pencil
test popup and a few other tweaks.

Here is a screenshot:
[image: new_theme_2]
<https://cloud.githubusercontent.com/assets/4576381/23152118/012f3df4-f7bd-11e6-9ed8-6beabc8ba50d.JPG>

@shun-iwasawa <https://github.com/shun-iwasawa> This is based off of the
current darkest theme. Do you have any interest in replacing that theme or
simply adding an additional theme?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/opentoonz/opentoonz/pull/1043#issuecomment-281250411>,
or mute the thread

**Comment by adamearle** [comment]
Just something to try out  everything in red is pretty much a border 
that possibly could be removed.

Also sroll bar bevels to search bar bevels might best if they are the 
same highlight colors if you leave them in.


Ad

**Comment by turtletooth** [comment]
> What's else are you thinking about tweaking
It's mostly icons now and fine tuning here and there.

Adam, I'm sorry, but I didn't understand your last comment.  I'm not sure what red or search bars you are referring to.

**Comment by turtletooth** [comment]
>  I took a look on a newer screen and liked the field border color a lot.

I actually brought it down a touch based on your feedback.

**Comment by tin2tin** [comment]
That looks brilliant. Especially getting rid of the dated 3D look on buttons and widgets makes OT look so much more modern and inviting. 

Thank you for all the time you put into improving OT!

**Comment by turtletooth** [comment]
Here are the new viewer icons with the new theme:
new_icons

**Comment by adamearle** [comment]
Hi mate

The red line are the boarder of different section of the interface that 
could potentially just be completely removed

Also the scroll bars look  correct
However the "name/search field boxes" look like they might be using a 
higher contrast than the rest of the UI so they standout IMO way to much

Adam

**Comment by adamearle** [comment]
Ahhh I hav been posting images from gmail acount. Did you get any of them?

Adam

**Comment by turtletooth** [comment]
No.  Sorry.

**Comment by adamearle** [comment]
opentooz just an idea

**Comment by turtletooth** [comment]
The whitest lines are removed in another PR.  I did darken the fields a touch in the most recent changes, but I do think that in general the visual cues of outlines tell the user that there is something to interact with there.  I don't want to go so far that users no longer realize that they should have tried clicking somewhere.

**Comment by adamearle** [comment]
It might be worth taking another look how Adobe and Autodesk deal with these thin white lines? And see how their users interact. I know that blender has a really kool flatty them that I wish was dark perhaps something similar will happen with opentoonz by removing some of the suggested elements.

IMO user still would be able to work things out. If you're really worried about it perhaps a very grayed out watermark can be added in similar to googles search?

Again these are just ideas to be thrown around by people and discussed. Do we ever really leave beta?

**Comment by turtletooth** [comment]
@shun-iwasawa I think this is pretty much done.  I'd like to hear what you think.

**Comment by shun-iwasawa** [comment]
It looks nice and I believe it will attract users who are familiar with the current flat UI. Thank you @turtletooth , @konero & all the contributors to this new style!
I understand there still are many opinions and TO-DOs for the new style, but I think it can be improved afterwards.

@turtletooth , could you please rebase all the commits into one before I will merge this PR?
And could you please list the other PRs which are related to this and I should review next? Thanks!

**Comment by konero** [comment]
@turtletooth Should I still submit my theme as a PR? I meant to do it awhile ago now. If you give me a day or two I'll see if I can get it up.

IMO I don't like the back-end of the original too much, since it lacks any reusable/component structure. Also there is no need to maintain three independent theme files. The way I built my theme is I laid all the windows out into their own separate layout/partial files, all color properties use variables instead of hard-coded values, which is the _Sass way_ of doing themes I guess.

You can output the gray48 theme by just using a few variables, instead of maintaining an independent layout file which is essentially a clone anyway. LESS is cascade, so any variables that come last are king.

```
@import 'main'; // import layout
@img-url: '../default/imgs/white'; // set img path
@bg: #303030; // set bg color
```

If you want your new feature to use tabs, I built two tab components that can be used.
```
#NewFeature {
  &:extend(.tabs.round all); // round style (classic)
  or
  &:extend(.tabs.flat all); // flat style (adobe)
}
```

Round:
theme_prev2

Flat:
theme_prev3

I added a lot of UI signals that got requested; tool highlighting and checkboxes in the context menus, focus events, console play tool bars the same height, swapped title bars in widgets that display no info to handles and gave text in the title bar some much needed margin.

theme_prev

Some people kept bugging me for a light theme, there is one guy here who really can't stand how dark After Effects is. One day when the sun was shining through his window, you can hear him rage because he can't see the screen, so he always uses light themes in Avid etc. :laughing:

theme_prev5

You can see the checkbox signal here for checkable items.

You could port your theme through the platform really quick with just a few variables @turtletooth.

```
// ----------------------
// Turtletooth's Theme
// ----------------------

@import '../main';
@img-url: '../default/imgs/white';
@bg: #303030;
@selection-bg-color: green;
@selection-bg-color-secondary: lighten(@bg, 10%);
@button-bg-color: darken(@bg, 5%);
@button-border-color: lighten(@bg, 10%);
@title-bg-color: lighten(@bg, 10%);
```

turtle_theme_prev

etc.

**Comment by blurymind** [comment]
Would be cool if we could set it so opentoonz checks the hardware clock at
startup and loads with light or dark theme depending on wether its dark
outside

**Comment by turtletooth** [comment]
@konero I would like to see yours and see how you have set it up.  If it is easier to maintain in the long run it could be a good direction to go.  You have also done some work I neglected in implementing a light theme.  Thanks for all your work.

@shun-iwasawa If you could look at PRs #1053, #1054, #1034, #1035, #1050 sometime, they are all related to themes and UI.  Thanks.

**Comment by shun-iwasawa** [comment]
@turtletooth  Merged #1053, #1054, #1034 and #1035 . #1050 is not yet merged as it seems to have some discussion remains and has file conflicts.

@konero Thank you for preparing the submission of new theme. Will it be based on this PR or a separate one? I mean, is it OK to merge this PR now or should I wait your improvement? Thanks!

**Comment by konero** [comment]
@shun-iwasawa I'll submit it as a new PR since it's a very different backend to this one. I hope to have it up by the end of today. It should be OK to merge this PR if @turtletooth is happy.

I do have one issue to point out with this PR though, the FlipSlider handle is opaque when it needs to be transparent, so the render color shows through the handle during preview. I know it's probably difficult to see since both 'NotStarted' and 'Started' states are similar in color. Try setting **qproperty-startedColor** to 'lime' and hit render/preview in a scene using the gray48 or gray72 themes and you should spot it.

It's a very difficult UI component to get right (I had a lot of trouble with it) since in preview mode the FlipSlider bar turns white making it very difficult to see depending on your design. In the end, I use the original slider handle and just toned down the white accents on it. I also put a transparent white overlay on it so it stands out when not in preview mode.

flipmarker

render-signal

**Comment by VidelXi** [comment]
With this theme I get the same problem with text alignment on Linux/Mac as https://github.com/opentoonz/opentoonz/pull/1109#issuecomment-287572901.

**Comment by shun-iwasawa** [comment]
Sorry for my late response, I'll merge this PR.
I understand that the PR #1112 by @konero will also improve the UI in organized approach - I hope they are integrated at a certain point.
Thank you @turtletooth !

**Pull request merged**
