### PR TITLE
[WIP] Using 'fabs' instead of 'abs'

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for #923
@ideasman42 and @Xenobus  thanks again for pointing this.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by ideasman42** [comment]
Mightn't it be better to use `std::abs` instead of `abs/fabs/fabsf`... etc.

For example, in this patch `(float)(fabs(offset)` in this patch should really use `fabsf` (since its operating on floats, doing float -> double -> float cast is redundant, although the compiler may optimize it out its still confusing).

Using `std::abs` may be better overall to avoid unintended type coercing.

**Comment by shun-iwasawa** [comment]
That's make sense. I'll work on this after releasing the next version.

**Comment by jpturcotte** [comment]
Any update on that?

**Comment by RodneyBaker** [comment]
Took a quick look at this report...

As std::abs is overloaded for both signed integer and floating point types it does appear appropriate to replace both abs and fabs with std::abs in the source.

Aside:  The use of abs instead of fabs (or vice versa)... integer versus float... may directly relate to several bugs, crashes and abnormal calculations where data appears to be rounded, truncated or simply wrong.  As a wild speculation it might also result in additional/unnecessary processing.

**Comment by RodneyBaker** [comment]
Because of #3226 this PR may no longer be needed.

**Comment by RodneyBaker** [comment]
Closing as this should be implemented by #3226

**Pull request closed without merging**
