### PR TITLE
Spanish UI - quick fix

### PR DESCRIPTION
**Pull request by gab3d**
Sorry, @shun-iwasawa  I know this PR still has all the history, but it was pulled beforehand, so I think I still need to make this PR to be able to start a new branch from safe zone.

Thanks.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
This PR seems to have no file changed from the current master.

**Comment by shun-iwasawa** [comment]
@gab3d Is it OK to close this and review the newer PR #1519 ?

**Comment by gab3d** [comment]
@shun-iwasawa yes please.

**Comment by shun-iwasawa** [comment]
OK, closing this

**Pull request closed without merging**
