### PR TITLE
Maximize Pane where mouse is shortcut

### PR DESCRIPTION
**Pull request by turtletooth**
I added the ability to set a mouse shortcut to maximize the pane where the mouse is.  For example, if the mouse is in the xsheet, clicking ` (back tick) will make the xsheet maximized.  The same works for the scene viewer and the palettes. . .
This should take care of #335 

Edit-
I added the ability to maximize an entire room with Ctrl + `
This is #336 

These shortcuts can be changed of course

Demos:
https://youtu.be/80EF-2QG-gE

https://youtu.be/3ykJ-88BftI

### CODE REVIEW

**Comment by blurymind** [comment]
This is very cool! Does the same shortcut also minimize a maximized pane? In most other software this action is a toggle

**Comment by turtletooth** [comment]
This is a toggle.  I also took care of #336 now too.

**Comment by blurymind** [comment]
Awesome. Hope this gets merged soon :D thank you!  It makes using the
software way more comfortable

**Comment by shun-iwasawa** [comment]
For now this branch conflicts to master branch since we applied clang-format on v1.0.3 release.
Sorry to trouble you but could you please apply clang-format (with [toonz/sources/.clang-format](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/.clang-format)) to your PR or rebase your commits to the current master?
Thank you for your GREAT contributions.

**Comment by turtletooth** [comment]
Updated for 1.0.3

**Comment by turtletooth** [comment]
@shun-iwasawa Thank you for inviting me to be a committer.  Does that change the way that I should handle my PRs?  T

**Comment by shun-iwasawa** [comment]
@turtletooth Sorry for my late reply. Regarding your PRs, we would like you to wait for a review by another committer. It is much appreciated if you could review and merge PRs posted by other committers. Thank you.

**Comment by turtletooth** [comment]
Newer version by @shun-iwasawa

**Pull request closed without merging**
