### PR TITLE
Enable debug build

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for enabling debug build with the current master branch.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by skitaoka** [comment]
LGTM

**Comment by turtletooth** [comment]
How do I use this?  When I choose debug I get a cannot find the file specified error on \opentoonz\build\x64\debug\ALL_BUILD

I would love to be able to debug but right now only can build, test, build, test . . .

**Comment by turtletooth** [comment]
Apologies in advance for my ignorance on setting up debugging.

**Comment by turtletooth** [comment]
Ok, I feel like an idiot because I did not have OpenToonz set as the startup project in VS.  But now I get an error that it can't find glut32.dll.  Any thoughts?

**Pull request merged**
