### PR TITLE
Update tanslation files for v1.6

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR updates the translation (.ts) files for all languages to the latest version.

Just in case, here is a zip version of ts files needed to be translated:
[translations.zip](https://github.com/opentoonz/opentoonz/files/8105700/translations.zip)

@gab3d @deruji @jcome @morevnaproject @beeheemooth @Savraska2 @haminu0108 @pafri @kimpd
Again & again, your cooperation on updating translation is highly appreciated!
You can either post a PR or just upload the translated .ts files here. Thank you.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Thank you @shun-iwasawa!

**Comment by gab3d** [comment]
@shun-iwasawa 
Spanish translation files (TS and QM)
[spanish.zip](https://github.com/opentoonz/opentoonz/files/8122369/spanish.zip)

**Comment by age3rcm** [comment]
opentoonz was never translated to portuguese-brasil?

**Comment by jcome** [comment]
@shun-iwasawa 
Chinese translation for V1.6 as attached, I have difficulty to post PR this time. 
Hope it is not too late, thanks. 
 
[OTZ_Chinese.zip](https://github.com/opentoonz/opentoonz/files/8238975/OTZ_Chinese.zip)

**Comment by jcome** [comment]
@shun-iwasawa 
Chinese translation for V1.6 as attached, I have difficulty to post PR this time. 
Hope it is not too late, thanks. 
 
[OTZ_Chinese.zip](https://github.com/opentoonz/opentoonz/files/8238975/OTZ_Chinese.zip)

**Comment by toybrand** [comment]
[korean.zip](https://github.com/opentoonz/opentoonz/files/8385461/korean.zip)
Thank you.

**Comment by RodneyBaker** [comment]
Thanks @toybrand (aka kimpd)
@shun-iwasawa Hopefully there is still time to get this into the v1.6 release.

**Pull request merged**
