### PR TITLE
Fix Save Default Settings command to save format properties to project settings

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR fixes the issue #878

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
Jenkins again!

**Comment by shun-iwasawa** [comment]
Jenkins one more

**Comment by turtletooth** [comment]
Tested and this seems to work well.  Ready to be merged after Jenkins.

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by turtletooth** [comment]
LGTM.  Thanks @shun-iwasawa

**Pull request merged**
