### PR TITLE
Use QGLWidget instead of QOpenGLWidget

### PR DESCRIPTION
**Pull request by skitaoka**
- PlaneView
- ImageViewer
- HexagonalColorWhell

QGLWidget is obsolete. cf. http://doc.qt.io/qt-5/qglwidget.html

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins

**Comment by kogaki** [comment]
It works fine. LGTM

**Comment by skitaoka** [comment]
Fix https://github.com/opentoonz/opentoonz/issues/253

**Pull request merged**
