### PR TITLE
Enable Undo for Editing Styles

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will enable undo for the following operations regarding style editing:

- Changing color of the style with the `Auto Apply` toggle button being ON
- Toggling the Autopaint option both by clicking the checkbox in the settings panel and by the shortcut key.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by gab3d** [comment]
This is great! 
...one of those seemingly small changes that really improves a lot the daily workflow.
Thanks!

**Comment by turtletooth** [comment]
Once the conflicts are resolved.  This is ready to be merged.  Tested and it seems to work well.  LGTM.

**Comment by shun-iwasawa** [comment]
Conflicts resolved. 
Jenkins again

**Comment by turtletooth** [comment]
Going to merge this even with mac on travis being typical.  Thanks @shun-iwasawa for the addition.

**Pull request merged**
