### PR TITLE
Replace fx fixed sized buttons with minimum size hint

### LINKED ISSUE #1459: "Insert" and "Add" button strings in the FX browser appear truncated when translated.
The title says it all.
When translating those strings into longer words, they appear truncated.

Thanks!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/48975891-insert-and-add-button-strings-in-the-fx-browser-appear-truncated-when-translated?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by flurick**
Fixes #1459 the last one in milestone 2022 :)

### CODE REVIEW

**Comment by RodneyBaker** [comment]
It's not clear to me why Appveyor tests didn't pass and there isn't anything in the code change that would seem reasonable to cause the failure of checks.

Perhaps it just timed out.

**Review by konero — CHANGES_REQUESTED** [review]

**Comment by RodneyBaker** [comment]
Posting intent to merge although there is no rush if anyone wishes to provide additional validation or feedback,
@konero -- must assume with the implementation of your suggestion the PR is now good for you.

**Comment by konero** [comment]
Sure? I didn't really test it so OP should confirm whether it still works after making the change.

**Comment by flurick** [comment]
image
image
Good enough? Or the button margins could be like 1px smaller

**Comment by RodneyBaker** [comment]
Thank you @flurick for the button size adjustment.
LGTM

**Pull request merged**
