### PR TITLE
Thirdpirty binaries should be ignored by git

### PR DESCRIPTION
**Pull request by kogaki**
`lzo` and ``tiff  are ignored in the same manner as `glew`, `jpeg`

### CODE REVIEW

**Comment by kogaki** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins

**Comment by ideasman42** [comment]
Shouldn't these be absolute paths? ( see: http://stackoverflow.com/questions/6168736 ),
the existing ones as well as the new paths.

**Comment by kogaki** [comment]
Thanks, I prettified them.

**Comment by kogaki** [comment]
Jenkins

**Pull request merged**
