### PR TITLE
Support German translation

### PR DESCRIPTION
**Pull request by skitaoka**
* https://github.com/opentoonz/opentoonz/pull/113
* fix https://github.com/opentoonz/opentoonz/issues/275 for all languages

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins

**Comment by kogaki** [comment]
With older OSX and git, it need to set `git config --system core.precomposeunicode true` to handle composed UTF-8 (e.g. `ñ`).

**Comment by kogaki** [comment]
Now it works correctly in my OSX with the setting above.
pasted image at 2016_05_27 12_30 pm
Thanks @deruji @natowi @skitaoka for your continuous contributions !!

**Pull request merged**
