### PR TITLE
Linux support for tsound (SDL2) and tfont (Qt), from pr #51

### PR DESCRIPTION
**Pull request by ideasman42**
Linux support for tsound (SDL2) and tfont (Qt), from pr #51 

Note that these files don't have license headers, but neither do OSX and Windows files here.

Credit goes to François Revol for this work.

### CODE REVIEW

**Comment by kogaki** [comment]
Wow. This must solve another problem! In windows and OSX, we use depricated software for sound and font. You might solved them altogether. Really really thanks.

**Comment by ideasman42** [comment]
Yes, both are portable, so once they're in, nothing against checking on using them from other platforms :)

**Comment by kogaki** [comment]
#370 will be solved

**Comment by kogaki** [comment]
@ideasman42 This is so great PR. If you don't mind, please divide this into two PRs, for `tsound` and for `tfont`. If you can do, we can merge this in less time.

**Comment by ideasman42** [comment]
Done: #466 #467

**Comment by artisteacher** [comment]
Will this functionality be added for OS X? :)

**Comment by ideasman42** [comment]
What functionality exactly? Can't OSX play sounds?

**Pull request closed without merging**
