### PR TITLE
Fix studio palette paths caching

### LINKED ISSUE #4510: Project pallette for cutout rig bases bug
### Description

if you make a cut-out rig base and try to make different color versions for different characters, the pallette used is still the same from the last cutout rig base project

out
[Nova pasta (2).zip](https://github.com/opentoonz/opentoonz/files/9398165/Nova.pasta.2.zip)

### Steps to Reproduce

explained in .gif

### Expected Behavior

each project pallette is used from its own folder

### Screenshots, Video & Crash Logs

_No response_

### OpenToonz Version

1.6

### OpenToonz Version Information

_No response_

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

_No response_

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR (hopefully) fixes #4510 .
Caching the studio palette paths for enahancing the pallette search was done in #3559 , but I missed to clear the cache when switching the project. I think this is a probable cause of #4510 . Sorry for the trouble!

### CODE REVIEW

**Comment by RodneyBaker** [comment]
@age3rcm This one is for you.
Will press forward with merging but still very interested in feedback.

**Comment by age3rcm** [comment]
if i change color and click to save pallette, it saves across all copied projects

**Comment by age3rcm** [comment]
ball2_ pallete_bug_base __OpenToonz_1 6 OpenToonz_aslxhBSTK8
(original project)
ball_ pallete_bug_base __OpenToonz_1 6 OpenToonz_kU51WpWwCM
(copied project on windows explorer with project pallete with different color style)

**Comment by age3rcm** [comment]
About_OpenToonz OpenToonz_gS1O6kSeyp
version

**Comment by age3rcm** [comment]
exporting the original project to make a new project using the "file menu" drop-down does not export the pallette for the new project, still using the original project pallette

**Comment by age3rcm** [comment]
image
i have "deleted" the projects folder and made another one but empty
saved the pony rig project on another folder.
when i did open the scene on the starting window, changed project, there was an style pointed to a color from an unknown pallette, and when i tried to save the pallette after modyfying it, i got this error message

**Pull request merged**
