### PR TITLE
Use ninja on appveyor

### PR DESCRIPTION
**Pull request by janisozaur**
This provides a bit faster builds and saner error messages.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
It's not surprising to see a conflict with the appveyor .yml file here as this is a proposal to update that file.

See also @janisozaur's previous recommendation to add ninja to Travis builds and the accompanying request for more information on benefits of adding ninja.  REF:   #1705

**Comment by manongjohn** [comment]
There is a conflict on this PR that needs to be resolved.

**Comment by RodneyBaker** [comment]
Adding ninja for appveyor and travis builds appears to be slipping to 2020 Development Cycle.

**Comment by RodneyBaker** [comment]
Closing (for now) as not finding enough interest to move forward.
Please continue discussion where there is continuing interest in seeing ninja integrated into Opentoonz github.

**Comment by RodneyBaker** [comment]
As far as I can tell, this has been implemented.

**Pull request closed without merging**
