### PR TITLE
Fix saving mesh levels problem + Modify style sheet for mesh columns

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This fix is for resolving the issue #124 
Also modifying style sheets suitable for displaying mesh columns in xsheet for each style.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins, test this

**Comment by kogaki** [comment]
It works in my OSX. LGTM.

**Comment by blurymind** [comment]
It still crashes on windows 7

**Comment by kogaki** [comment]
@blurymind Sorry for confusing announce, but nightly build for windows was just updated just a few minutes ago. Could you try latest one? 

This is because build for windows takes longer than that for OSX.

**Comment by blurymind** [comment]
@kogaki Ah I see. No worries. After reinstalling again I can confirm that mesh saving works on windows7 now!

**Comment by kogaki** [comment]
Good!

**Comment by blurymind** [comment]
@shun-iwasawa unfortunately this seems to introduce a new  bug:
Once you make a mesh, you can not exit the mesh level.
As a result opentoonz gets locked in the plastic tool completely.

to reproduce:
1. create a mesh level
2. click on any other non-mesh level
3. select the brush tool and try to draw on the canvas

**Comment by blurymind** [comment]
To understand why this is going to be a problem, consider this approach:
https://github.com/opentoonz/opentoonz/issues/134
opentoonz-glithch
when you attach multiple vector levels to the same mesh level. With this regression now we wont be able to edit the shape of the eye level drawings and see the head at the same time in the camera stand view.

**Comment by blurymind** [comment]
@shun-iwasawa appologies - this is not a regression - the previous versions of opentoonz had this issue too. It is not a bug , but a limitation of the software.

**Comment by Rayek** [comment]
@Blurymind: the mesh-controlled level can still be edited when you click the thumbnail in the level strip.

**Comment by blurymind** [comment]
@Rayek I found out about it a week ago, then totally forgot and thought this is a bug again.
It just feels counter-intuitive to no longer be able to access the current frame active drawing through level when there is a mesh applied. I guess that this limitation would stop some technical problems from occurring at least.

There are slight limitations:
- You cant draw directly on the deformed by a mesh level - while the deformation effect is visible
- if you have attached more than one levels to the same mesh, you can not see the others while you make changes to one of them.

I guess that when the level is warped by a mesh, it's coordinate space becomes warped, so if the user tries to edit it through the warp, the software has trouble translating where the cursor is

**Comment by Rayek** [comment]
@blurymind As far as I can tell, once you apply a mesh, the drawing is converted to a texture (you can test this by moving the content: notice the black background surrounding the image). 

Here is a nice workflow:
- create your object/character which will be deformed later with a mesh. Use as many columns (layers) as you like.
- save all levels, and save the scene. For example, "character".
- then create a new scene, and select the frame you would like to import the character. Then choose :Load Level". 

This will load the entire character scene as a subsheet.in your x-sheet. It is also possible to just drag a scene from the file browser into your x-sheet frame(s).

- now apply a mesh, and start animating with mesh deformation.

- if you wish to make a colour change, or edit the character content, just right-mouse click on the column header title, and open the sub sheet. When you have finished with edits, close the sub sheet again.

This is a very powerful workflow. You can really tell that OT has "studio production" written all over it.

**Comment by blurymind** [comment]
@Rayek the black background surrounding the mesh is a nasty regression bug. Toonz harlequin didnt have that problem. 
It's a bug - not a feature or design. 
I explained how it can hinder workflow in my bug report #134 
blackbgregressionmesh

**Pull request merged**
