### PR TITLE
MyPaint brushes for OpenToonz raster levels

### PR DESCRIPTION
**Pull request by blackwarthog**
This it implementation of this feature request #417 

You can see its demonstration in the video below:
[MyPaint brushes in OpenToonz](https://www.youtube.com/watch?v=2_lD654uAZ4)
https://www.youtube.com/watch?v=2_lD654uAZ4

You can test this feature using these binary builds:
https://gumroad.com/l/opentoonz

### CODE REVIEW

**Comment by blackwarthog** [comment]
This feature tested on Linux and Windows (MinGW #1092)

**Comment by lordadamson** [comment]
I think I'm in love.

**Comment by Number0001** [comment]
@shun-iwasawa  @konero @ksk575 @Nico-Duduf @mitchfoo @mqudsi @photopea @abuhenasobuj
I would like to hear your opinion.

**Comment by abuhenasobuj** [comment]
@Number0001, How you gotten my username?

**Comment by Number0001** [comment]
Common acquaintances. @abuhenasobuj

**Comment by blurymind** [comment]
Indian guys, can we stay on topic please

**Comment by mqudsi** [comment]
Please don't spam random mentions.

**Comment by turtletooth** [comment]
I just used the newest version from the Morevna site- and holy cow.  It works great, nice and fast and very fluid.

**Comment by turtletooth** [comment]
@blackwarthog  Once the last mingw PR is merged, should I be able to build this and test this with MSVC?  Are there any additional steps I would need to test this?

**Comment by blackwarthog** [comment]
@turtletooth no, when mingw PR will merged we also should to implement MSVC and OSX support. For now i'm working on OSX, and after that on MSVC.

**Comment by turtletooth** [comment]
@blackwarthog Sounds good.

**Comment by blackwarthog** [comment]
I've added build support for OSX and MSVC.
For OSX you need to install libmypaint via brew.
For MSVC copy DLLs from thirdparty/libmypaint/dist/{32|64}/*.dll into Release directory after compilation.

**Comment by turtletooth** [comment]
@blackwarthog Thanks so much for doing this.  It works great with MSVC and is a HUGE improvement to the software.

**Comment by shun-iwasawa** [comment]
It seems that `brew install libmypaint` is needed in [travis-install.sh](https://github.com/opentoonz/opentoonz/blob/master/ci-scripts/osx/travis-install.sh) in order to run the travis CI.
[travis-install.sh for linux](https://github.com/opentoonz/opentoonz/blob/master/ci-scripts/linux/travis-install.sh) should be updated as well.

**Comment by blurymind** [comment]
I tested it on one of @turtletooth 's preview builds. Works like a charm!

Is it possible to create new mypaint brushes within Open toonz, or do we still require mypaint to do that?

It will be kind of nice if it is possible to save a brush as a new preset, not sure how it's thumbnail would be created, as OT has no brush thumbnail editor like Krita and mypaint :)

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by morevnaproject** [comment]
@blurymind 

> Is it possible to create new mypaint brushes within Open toonz, or do we still require mypaint to do that?

At the moment you can configure new brushes using styles. Please see the "Improved styles management" section here - https://morevnaproject.org/2017/04/09/open-toonz-builds-updated/

**Comment by blurymind** [comment]
But can you save a style as a new style and reset to default values?

On 2 Aug 2017 17:33, "Konstantin Dmitriev" <notifications@github.com> wrote:

@blurymind <https://github.com/blurymind>

Is it possible to create new mypaint brushes within Open toonz, or do we
still require mypaint to do that?

At the moment you can configure new brushes using styles. Please see the
"Improved styles management" section here - https://morevnaproject.org/
2017/04/09/open-toonz-builds-updated/

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/opentoonz/opentoonz/pull/1124#issuecomment-319727159>,
or mute the thread

**Comment by morevnaproject** [comment]
> But can you save a style as a new style and reset to default values?

Please read the link I referenced above. It explains everything. ^__^

**Comment by shun-iwasawa** [comment]
@blackwarthog 
Confirmed that it works fine on both on Windows and OSX. Thank you for the great contribution on this!

My only and big concern for this PR is about licenses of DLLs you are including in `thirdparty/libmypaint/dist/{32|64}/`. Could you please provide a list of links to the licenses of them?
In short, I just would like to confirm that they are not under GPL licenses. 
Thanks!

**Comment by blackwarthog** [comment]
Thank you for your notify. I've found that libgettext licensed by GPL, but it was easy to eliminate this dependency and i did it.

For all other libraries I've added license files. Thank you again.

**Comment by shun-iwasawa** [comment]
@blackwarthog 
It's so fun to paint with this. Thank you very much for the great work done so far!
lgtm

**Comment by shun-iwasawa** [comment]
@blackwarthog 
Again, thank you for your huge contribution.
We'll be happy if you could improve OpenToonz continuously and would like to assign you as a collaborator.

**Comment by lordadamson** [comment]
I have built this on linux but in the mypaint brushes tab I only find No Brush.
Are there any files that I should place somewhere in order to get the brushes?

**Comment by blackwarthog** [comment]
Much thanks :)

**Comment by blackwarthog** [comment]
@lordadamson you need to update your "stuff" directory. Just copy "./stuff/library/mypaint brushes" to "\~/.config/OpenToonz/stuff/library/"

Also check variables in ~/.config/OpenToonz/SystemVars.ini:
 \- TOONZLIBRARY should be like "/home/USERNAME/.config/OpenToonz/stuff/library";
 \- TOONZFXPRESETS should be "/home/USERNAME/.config/OpenToonz/stuff/fxs".

**Comment by lordadamson** [comment]
yaaay it worked :D 
brb I'll be updating the build instructions for linux accordingly :D

**Comment by blackwarthog** [comment]
It's actual only when you have previous version of opentoonz installed. Build on the clean system works fine.

**Comment by morevnaproject** [comment]
Actually this mess with stuff directory on Linux/OSX needs some rework. Default stuff directory should be a part of OpenToonz data files and overridden by data in user home directory (if any). Of course this is a topic for separate discussion. ^__^

**Pull request merged**
