### PR TITLE
pen/touch device support

### PR DESCRIPTION
**Pull request by tomosu**
support touch-scroll device, change wheel-scroll movement to be based on marker interval.

### CODE REVIEW

**Comment by tomosu** [comment]
Jenkins

**Comment by tomosu** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins

**Comment by tomosu** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins

**Comment by tomosu** [comment]
Jenkins

**Comment by tomosu** [comment]
This PR is related to https://github.com/opentoonz/opentoonz/issues/148

**Comment by tomosu** [comment]
Jenkins

**Pull request merged**
