### PR TITLE
Fix Style Editor HSV rounding

### LINKED ISSUE #4651: Colours are shifting their values when switching styles
### Description

When changing the values of a colour style in the style editor for HSV, after switching to another style and back again the digit has decreased by 1 or 2.

If I entered a lower number, then it would decrease by 2. If I entered a higher number it would decrease by 1.

### Steps to Reproduce

1. Make two styles
2. Edit one of the HSV fields
3. Switch to another style
4. Switch back to the style that was modified
5. Notice the value has changed

### Expected Behavior

For the values to remain when switching styles.

### Screenshots, Video & Crash Logs

https://user-images.githubusercontent.com/55353161/207823330-4f0aa443-e5f4-4d77-ae2b-71bdf2002c12.mp4

### OpenToonz Version

Nightly (Specify below)

### OpenToonz Version Information

Latest

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will fix #4651

Now the converting between HSV and RGB becomes more precise so that the rounding error won't occurs.

### CODE REVIEW

**Comment by KaseyFarron** [comment]
Thanks for tackling the bug! I tested and unfortunately I can still reproduce the issue at least with Hue slider, it happens if I single click somewhere, click and drag, use the buttons or type a number manually. I tested using AppVeyor. I haven't reproduced it with Saturation or Value sliders so far.

https://user-images.githubusercontent.com/55353161/229275757-d07e4894-6c6c-4374-a39d-f2124470a49f.mp4

**Comment by RodneyBaker** [comment]
Will hold off merging this for additional testing purposes and to verify results reported by @KaseyFarron

**Comment by shun-iwasawa** [comment]
@KaseyFarron
Regarding the Hue slider, I think it would be difficult to fix the problem completely.

The color information of a style is stored in 8 bits (255 steps) in RGB channels.
Since the Hue slider is finer (360 steps), it is possible that the same RGB is calculated from two HSV that differ only by 1 Hue.
When the style is switched, HSV is reproduced based on the RGB channel values.
At this time, they will converge to one of the Hues. I think this is why only Hue sometimes shifts by one.

This problem is separate from the accuracy issues of the Saturation and the Lightness sliders.
If the Hue sliders were to snap to discrete positions, the problem of shifting Hue would be solved, but the movement of the slider would be unnatural.

**Comment by KaseyFarron** [comment]
Oh I see, thank you for the explanation! I won't hold up merging this.

**Comment by RodneyBaker** [comment]
Thanks for the feedback @KaseyFarron  Much appreciated.
And...

Thank you @shun-iwasawa for the fix to HSV color rounding!
LGTM

**Pull request merged**
