### PR TITLE
Added libmypaint to Travis CI setup

### PR DESCRIPTION
**Pull request by shun-iwasawa**
Updated from #1364 , solving the conflicts.
Also changed the names `COPYING.LIB` in the thirdparty folder to `COPYING_LIB` in order to make Git LFS to work properly.

### CODE REVIEW

**Comment by turtletooth** [comment]
Thanks for looking into this.  I was having issues with COPYING.LIB too.  I couldn't switch to any other branch.

**Comment by turtletooth** [comment]
Is this ready to be merged?

**Comment by shun-iwasawa** [comment]
Yes, please. Thanks!

**Comment by turtletooth** [comment]
LGTM.

**Comment by damies13** [comment]
@shun-iwasawa @turtletooth 

I pulled this into my branch from master, now i'm getting this on running "CMAKE_PREFIX_PATH=~/Qt5.6.0/5.6/clang_64 cmake ../sources" on OSX:
-- Checking for module 'libmypaint'
--   No package 'libmypaint' found

At i'm assuming this is what is causing my build errors? anyone know how to add 'libmypaint' module to OSX? I gather it's something similar to the boost library?

**Comment by damies13** [comment]
never mind "brew install libmypaint" fixed it

**Pull request merged**
