### PR TITLE
Fill Tool - Picker+FH

### LINKED ISSUE #4404: Auto Pick Style when using Fill Selection Types
### Is your feature request related to a problem? Please describe

After using the paint bucket tool, usually there are small unfilled areas left over and if there are many different styles we need to select the style picker tool, then the rectangular fill tool and fill them. This is a lot of clicks!

### Describe the solution you'd like
I would like to see an option for the fill tool (rectangular, for ex.) that automatically picks the style under the cursor, so that when you drag over the area you want to fill, it fills with that style, then after releasing the mouse button it goes back to the style you had selected before.

- When you first click with the Freehand/Rectangular fill types it remembers what style you currently have selected and then selects the style under the cursor position **_temporarily_**
- You drag where you want to fill and release
- It switches back to the style that was selected before this command happened

I made a [AutoHotkey script](https://github.com/KaseyFarron/AutoPickColourAndFill) for this if you want to actually try what it feels like, the current version I have on GitHub will only work with a mouse.

### Example:
113505841-33d1e400-9539-11eb-9cc5-f84753b405cf

### PR DESCRIPTION
**Pull request by justburner**
Resolves #4404 <- Please check the link to understand how this tool works.

This new tool can be located in the Fill tool at "Type:" under the name of "Pick+Freehand"
By default it only sample the `Area`, by holding CTRL on first click it will sample both `Line+Area`.

### CODE REVIEW

**Comment by KaseyFarron** [comment]
Wow thank you; it works just like my script! 😮 

I have a little feedback if it's OK.

When setting a hotkey to `Fill Tool - Picker+FH`, it works fine pressing the hotkey but if holding it to activate it temporarily then it makes it unable to make a selection, the cursor also flickers slightly and there's a bit of CPU usage spike.

When adding the `Type` command to the command bar, clicking it repeatedly cycles between `Normal` and `Pick+Freehand`, I'm not sure if that is intentional or not.

I think the names of the commands could be a bit clearer, for example:
|Current|After|
|-----|-----|
|Pick+Freehand|Freehand (auto pick style)|
|Fill Tool - Picker+FH|Fill Tool - Freehand (auto pick style)|
|Type - Picker+FH|Type - Freehand (auto pick style)|

Thank you again! 💞

**Comment by justburner** [comment]
> When setting a hotkey to `Fill Tool - Picker+FH`, it works fine pressing the hotkey but if holding it to activate it temporarily then it makes it unable to make a selection, the cursor also flickers slightly and there's a bit of CPU usage spike.
> 
> When adding the `Type` command to the command bar, clicking it repeatedly cycles between `Normal` and `Pick+Freehand`, I'm not sure if that is intentional or not.

Please test all those with "Freehand" type since that's what the tool is based of.

It's been known that temporary on OT has some flaws: #4556

> I think the names of the commands could be a bit clearer, for example:
>
> Current | After
> -- | --
> Pick+Freehand | Freehand (auto pick style)
> Fill Tool - Picker+FH | Fill Tool - Freehand (auto pick style)
> Type - Picker+FH | Type - Freehand (auto pick style)

`Pick+Freehand` was a compromise of keeping the text small while still being clear enough, the longer the name the bigger the combobox will be and will push all widgets of the toolbar to the right, requiring more screen size to the toolbar overall.

`Picker+FH` was the initial name which i've forgot to replace to the final name... ops.

**Comment by KaseyFarron** [comment]
> Please test all those with "Freehand" type since that's what the tool is based of.

Ah yes, seems all freehand tools are affected, shame... was not aware.

**Comment by openanim** [comment]
@justburner @KaseyFarron  Thanks for this feature.

I tested it quickly on the vector level. I can't get it to work like on toonz Raster level. It seems that depending on the boundary I have a different result. My vector level is fillable normally.

pick+FH

**Comment by konero** [comment]
Works nicely. Is there a reason to have this available for vector levels? I can't imagine the scenario.

**Comment by justburner** [comment]
> I tested it quickly on the vector level. I can't get it to work like on toonz Raster level. It seems that depending on the boundary I have a different result. My vector level is fillable normally.

Doubt they are fillable normally... vector filling issues has been a very old problem that still persists on OT.
I've noticed that closed shapes are significantly more problematic than open ones... anyway all of this is unrelated to the PR.

> Works nicely. Is there a reason to have this available for vector levels? I can't imagine the scenario.

Not much really, since this tool at core behaves the same as "Freehand" so vector levels support came out for free.

**Comment by RodneyBaker** [comment]
I hadn't even thought to test with vector levels.
Very happy to see it works there as well.

It's outside the scope of this PR but an option to 'Ungroup All' on a specific frame or selection of frames would likely resolve some of the issues observed here and elsewhere.  Grouping is something of a beast however as there is a lot of other features (and potential features) that connect to that.

I can see some uses for vector fill with pick+freehand but at present they are fairly fringe processes due to the nature of fill/grouping.

> By default it only sample the Area, by holding CTRL on first click it will sample both Line+Area.

Very nice.  Thanks for adding this option!

**Comment by RodneyBaker** [comment]
Posting intent to merge (later tonight).

**Pull request merged**
