### PR TITLE
Update Translation Files

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for updating .ts files, reflecting recent changes before V1.2 release.

@gab3d 
If you already finished Spanish translation with the previous TS files, please push a PR.
I'll merge that then update this PR including your work. Thanks!

### CODE REVIEW

**Comment by gab3d** [comment]
great, thanks!
already did it 👍

**Comment by masafumi-inoue** [comment]
LGTM

**Comment by shun-iwasawa** [comment]
@jcome Sorry for merging this late. Will you be able to update Chinese translation based on this?

**Comment by jcome** [comment]
@shun-iwasawa Sorry for a bit late to send the pull request, if it is too late to merge it into version 1.2.0, I am Ok to wait till 1.6.1 release. Thanks.

**Comment by jcome** [comment]
>>> 1.6.1 release

I mean 1.2.1 version 😅

**Comment by gab3d** [comment]
@shun-iwasawa 
I'm sorry but I haven't had time to experiment with GIT to make the PR the right way.
for this time (and to be on time for 1.2 release) I am sending the .ts and .qm files attached into a zip file here.
sorry for that and thanks for understanding. 🤒 
[new_spanish_files.zip](https://github.com/opentoonz/opentoonz/files/1543486/new_spanish_files.zip)

**Comment by manongjohn** [comment]
@gab3d I can submit it for you shortly.

**Comment by gab3d** [comment]
@manongjohn 
thank you so much!

**Pull request merged**
