### PR TITLE
Fix multiple warnings

### PR DESCRIPTION
**Pull request by rozhuk-im**
Fix simple C warnings  during build on FreeBSD with clang and gcc.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
@manongjohn Could you add this to the next OTX build?
I know OTX isn't building for FreeBSD but there are so many changes in this PR it would be good to have additional validation on other OSs that there are no adverse effects.  
Everything looks good here I just don't want to see anything get missed.

**Comment by rozhuk-im** [comment]
This is not FreeBSD specific changes (except malloc.h replace) - I can build #3231 without this, after change ```#include <malloc.h>``` in few files.

There is many changes in ```if()``` conditions, that clang show as suspect to wrong.
Also this includes: https://github.com/opentoonz/opentoonz/pull/925 - it was from gcc warnings/suggestions.

Please review this PR before merge.

**Comment by RodneyBaker** [comment]
In testing thus far I've yet to see something that doesn't work and have seen some improvements.
Some of which I can't quite explain.
For instance, with this PR inserting a Color Emboss FX pipes the flow of the schematic correctly into the xsheet node whereas the regular release of Opentoonz does not... leaving the user to connect the node manually.  

Other minor improvements noted as well.

**Comment by RodneyBaker** [comment]
After running through the 160 files effected by this PR multiple times...
Posting intent to merge this.

#925 should no longer be needed although specific instances of abs/fabs may need to be reviewed on case by case basis.  The majority of cases are handled by std::abs.

**Pull request merged**
