### PR TITLE
Move to stringstream

### PR DESCRIPTION
**Pull request by janisozaur**
std::strstream is deprecated, stringstream is the suggested replacement.

### CODE REVIEW

**Comment by andreygursky** [comment]
> strstream has been deprecated since C++98

Oh, yeah. It's time to get rid of this.

**Comment by janisozaur** [comment]
Any chance to have this merged?

**Comment by kogaki** [comment]
Can one of the admins verify this patch?

**Comment by kogaki** [comment]
merged #169, Thanks!

**Pull request merged**
