### PR TITLE
Camera Capture (former Pencil Test) improvement

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for some items listed the issue #626

1. Added the maximize button.
1. Enter/Return key is now available as shortcut key for capture.
1. Default resolution is changed to the camera's highest available value. 
1. Added checkbox to save images as they are captured. Note that the default state of this check box is ON (= do save images).
1. Command name and popup title are changed to "Camera Capture"
1. "Interval timer" option is added. It enables to automatically capture frames every specified seconds. Note that if you set "Interval(sec)" value to 0, OpenToonz try to capture frames as frequent as possible (=real time).
1. When the interval timer is activated, countdown is shown on the bottom-right corner of the finder area.
1. Default file type is changed from PNG to JPEG in order to reduce file size.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
LGTM - Thank you for the great changes.  It works great and the added functionality is wonderful.

**Comment by Rayek** [comment]
素晴らしい !

**Comment by RodneyBaker** [comment]
I need to test again but it appears to me that when the checkbox "Upside Down" in the Image Adjust section is turned on, the Countdown in the bottom right corner also flips and then displays in the upper left corner with numbers inverted upside down.  I'm sure this side effect wasn't intended and is a bit hard to read.  

Regardless, you know I'm a fan of these enhancements.  Many thanks!

**Comment by shun-iwasawa** [comment]
@RodneyBaker Thank you for pointing the "upside down" bug! I'll fix it right away.

**Pull request merged**
