### PR TITLE
Fixed gif import

### PR DESCRIPTION
**Pull request by turtletooth**
I broke gif import on #827 

This fixes it.

### CODE REVIEW

**Comment by ideasman42** [comment]
Since there are 4x `QRegExp` 's, wouldnt it be better to make a static function? `filepath_clean_for_ffmpeg` or something like this?

**Comment by turtletooth** [comment]
@ideasman42 There you go again making sense.

**Comment by turtletooth** [comment]
@shun-iwasawa This is a pretty simple PR.  Would you mind doing a quick look.  I would hate for the next release to have broken gif import.  (Sorry I broke it in the first place)

**Comment by shun-iwasawa** [comment]
Confirmed that GIF files can be imported properly now. Jenkins

**Comment by shun-iwasawa** [comment]
LGTM. @turtletooth thank you for the fix!

**Pull request merged**
