### PR TITLE
Reduce Footprint of Style Editor

### PR DESCRIPTION
**Pull request by turtletooth**
This is for #1502 

This moves the status to the title bar of the style editor - in keeping with other panels.
The apply button is moved next to the auto apply button.
The toggle buttons are moved to the bottom of the editor.

style_small

### CODE REVIEW

**Comment by gab3d** [comment]
ohh... man
that's awesome! 🎉 
you made my day 😋

**Comment by Agnyy** [comment]
I propose to do so.
1) the settings should be higher.
2) The bottom bar stole a lot of space, so it must be removed.

**Comment by shun-iwasawa** [comment]
> The bottom bar stole a lot of space, so it must be removed.

The bottom bar is not always empty, but used for styles containing multiple color settings such as colored cleanup styles and some special vector styles.

**Comment by gab3d** [comment]
@Agnyy 
I see two problems with what you propose:
1. Even if I "visually" like the location of the two settings buttons, the zone where you propose to place them does not fall inside the area what changes when you change tabs (that area is everything below the tabs area).
2. If you propose to remove the bottom bar (which I'm not against of) you must propose where to locate the various color swatches that usually show in this bottom bar. In your mockup you currently don't show this.

**Comment by openanim** [comment]
Sorry but I don't see the benefit of this set up. It requires more clicks than before when you had direct access to different modes. The size problems are still there despite the layout of the space, the reason why I don't understand. Unless I have not understood everything.

**Comment by gab3d** [comment]
@openanim it's true 1 more click is now required to toggle different slider sets or wheel.
On the other hand we need to consider how often things are used, to see what's the impact of each thing.
1. a panel which size is big and cannot be reduced without losing features.
2. a set of buttons to toggle the visualization of sliders/etc that is seldom used anyways.

To me the answer is clear: 
The big footprint penalty is suffered everyday, everytime a user needs to select a color and that panel occupies that much dpace of the UI.
The extra click needed to hide sliders would rarely be suffered, just by a user wanting to hide sone set of sliders (that, what orher reasin vould that user possibly have to want to hide a set of aliders, than to reduce the footprint of the panel?).
So... in all the scenarios I imagine, the reduced footprint is a winning situation, even at the cost of having to make 1 more click to hide the sliders fron the panel)

**Comment by artisteacher** [comment]
Personally I agree with @gab3d that the extra click is worth the smaller footprint. I often have to use a computer with a small screen. Once I’ve adjusted the sliders to make the style editor fit better on that small screen, I leave the settings alone. At least for me, the extra click really wouldn’t impact my workflow.

What about something like this?
32f3086a-853e-4445-a792-a55d47bdde5c

**Comment by turtletooth** [comment]
I'm not a big fan of putting the color samples in the wheel area simply because if you change to a vector style, you are currently given an immediate visual cue that there are more colors to change.  If they are hidden in the wheel, a viewer might switch the vector style but not understand why it's not working right.

**Comment by artisteacher** [comment]
In that case, what about putting the color samples to the side of the color swatches?

**Comment by openanim** [comment]
Another problem for me, When we reduce the style editor panel, the cursor for the options is grayed out, we must readjust the panel again to access it.

**Comment by adamearle** [comment]
Perhaps the option to choose between a square and circular wheel will also help reduce the size of the UI. the "hue value" slider could be easily added in instead of a color picker or a switch feature for fine-tuning.

Personally, a zoom feature into the color picker would be awesome so fine tunning was easier. normally when picking a color you start you search range rather large and then it progressively becomes
 smaller and smaller.

Just a thought.

Ad ;D

**Comment by gab3d** [comment]
@openanim as I see it, the problem with the Options tab is deeper than what you expose. The bigest problem with the Options tab is that there's no good way of having it open at the same time you are switching brushes. This is specially evident when trying to access the MyPaint brushes, along with their options.
I've tried opening more than one Style editor, one showing the Options tab in front, another one showing the MyPaint brushes, and a third one showing the color wheel.
The problem with that setup is that:
1. it takes a LOT of screen space, as all of the versions of the editor show the bottom part (auto, apply buttons, swatches, etc)
2. when you try to make a new room with all these panels docked, and the open OT again, all of the panels have the same tab (Color I guess) selected.

So, is clear that there currently is no planned workflow in OT for working with all of these panels exposed at the same time.

To me it'd be good to rethink it a little bit, by allowing brush Options and Color picker to live in its own separate panels.

Also, perhaps in the long run, the brush Options panel should turn into a generic " Selected Item" Options panel, to hold options for whatever is currently selected in OT. But that would naturally take a lot of work to do and exceeds by far the discussion here.

**Comment by adamearle** [comment]
Wonder if we start using something pie menu system or a pop-up window system in the viewport if this would help take care of the overuse of UI real estate. 

What is some more possible way that we could do this? krita color and brush pop-up well is one of the best I have ever used.

If I am using photoshop (not much these days because opensource) pretty much just work in full-screen mode and access everything via a hotkey ie f5 and f7

So how can we minimise the space? 
Floating windows?

Ad

**Comment by turtletooth** [comment]
@openanim I fixed the resize issue.  Thanks for pointing it out.  I realize that the options are one extra click, but I think it is worth the space saved.  I would wager that most people set the options they prefer and just leave it.  I'm a color wheel and alpha person myself.

@artisteacher Thanks for the suggestion for the color samples, but there are some vector styles that have as many as 4 (I think) color samples, so I'm not sure there is a better place for them right now.

Either way.  This is as far as I have time to take this change for now.  It saves three rows worth of space- which I think will really help those with smaller screens.

**Comment by gab3d** [comment]
@turtletooth 
Thank you so much!
Your work was indeed much effective and appreciated. 👍

**Comment by gab3d** [comment]
Could this improvement be revised for inclusion?
Thanks!!

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM Thank you @turtletooth for the improvement!

**Pull request merged**
