### PR TITLE
Drawing Substitution - Works Now

### PR DESCRIPTION
**Pull request by turtletooth**
I am trying to build the ability to use a keyboard shortcut and switch the drawing at the current frame for the next or previous drawing in the layer.  The current shortcuts are [ and ].  I think I have the basic functionality there, but I am getting linker errors.  Can anyone take a look and tell me what I am missing?  I am still somewhat new to C++ so it is probably something basic I am missing.

This functionality would make it very fast to switch out mouths or eyes without having to drag the drawing to a frame or use the skeleton tools drawing change (which is where I am using the code from).

Please help.  I realize the pull request is not working yet, but it is so close.
Thanks.

### CODE REVIEW

**Comment by kogaki** [comment]
This error happens because you have inplemented the `DrawingSubTool::drawingSub` on `skeletonsubtools.cpp`(part of toonz/sources/toonztools) which is not compiled together with `mainwindow.cpp`(part of toonz/sources/toonz). This means that skeletonsubtools are not intended to manipulated directly from main window.

**Comment by shun-iwasawa** [comment]
As far as I can see, "Substitute Next/Previous Drawing" commands are to increment/decrement the drawing number (fid) of specific cell at the current column and the current frame in the xsheet. 
It would better to extract these operations from ChangeDrawingTool::changeDrawing(), and create a new function in XshCmd namespace (in xsheetcmd.cpp) since they are exactly editing Xsheet data.
In xsheetcmd.cpp you can refer some functions to see how to assign shortcut by subclassing MenuItemHandler class.
In addition, please change the command id type of these commands from tool command (starting from "T_") to menu item command (starting from "MI_", maybe with MenuXsheetCommandType).

**Comment by blurymind** [comment]
That would be incredibly useful to have. Thank you!

**Comment by turtletooth** [comment]
This works now.  The shortcut keys are , and .
Demo:
https://youtu.be/BW60JcFkYn0

Thanks @shun-iwasawa  and @kogaki for all your help.

**Comment by blurymind** [comment]
This awesome. Cant wait to try it :B

**Comment by turtletooth** [comment]
New video showing all the features:
https://youtu.be/Pcimh8367AI

**Comment by blurymind** [comment]
Drawing substitution does not work with drag and drop in the x-sheet. You have to literally  remove a drawing before you can drop another in it's cell. Otherwise the dropped frame is created on a new level. Is there a reason for that? I think it would be nice if we can drop drawings over cells with other drawings to replace them.

This functionality can really help alleviate the issue and speed up workflow.

**Comment by Rayek** [comment]
@Blurymind: hold down the <ALT> key while dragging and dropping a drawing in the Xsheet.

@turtletooth : many thanks for this incredibly handy feature. Is this functionality available in the latest builds?

**Comment by turtletooth** [comment]
@blurymind also if you hold down shift, it will insert it.
@Rayek not yet.  I don't know what the timeframe for new pull requests being used is.

**Comment by blurymind** [comment]
Thanks guys. I guess it's now up to @kogaki  or someone else from the Dwango team to review it. It is certainly extremely useful. As a matter of fact all the pull requests made by @turtletooth so far have been amazing. I hope to see them all merged.
They may seem like small features to some, but in a workflow where you have to do these steps many times, getting them done faster is really important even if that means removing only one or two extra steps.

I think software designers should always think - how many steps does that take? How can I take this to less steps. How can I make the software guess what the artist wants in most cases, but also leave the option for a change.

**Comment by Rayek** [comment]
@blurymind : Hear, hear. I do hope @turtletooth's pull requests will be merged as soon as possible. Relatively small workflow changes which improve the overall workflow substantially.

**Comment by shun-iwasawa** [comment]
For now this branch conflicts to master branch since we applied clang-format on v1.0.3 release.
Sorry to trouble you but could you please apply clang-format (with [toonz/sources/.clang-format](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/.clang-format)) to your PR or rebase your commits to the current master?
Thank you for your contributions.

**Comment by tomosu** [comment]
Jenkins

**Comment by turtletooth** [comment]
Updated for 1.0.3

**Comment by skitaoka** [comment]
Jenkins, test this, again.

**Comment by skitaoka** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins, again

**Comment by skitaoka** [comment]
LGTM

**Comment by animking** [comment]
This is just awesome. Thank you :)

**Comment by turtletooth** [comment]
Glad to help.

**Comment by animking** [comment]
now only wish if we can get real time sound playback like other software :)

**Comment by turtletooth** [comment]
If you submit an issue.  That will remind to to look into it.

**Comment by Rayek** [comment]
@animking OT has three ways to scrub audio: 

1. Drag the xsheet frame cursor up or down to scrub all the audio columns whose Camera Stand toggle is active.
2. Drag the frame cursor in the viewer framebar to scrub all the audio columns whose Camera Stand toggle is active. (this does NOT work in the comboviewer - only the viewer)
3. Windows only: click and drag on the dashed vertical strip available on the right of the audio column cells: the selected section will be automatically played back.

**Pull request merged**
