### PR TITLE
(WIP) Missing icons

### PR DESCRIPTION
**Pull request by areckx**
This is for PR #2111 

 I started to add some of the missing icons. I started with the tool modifiers, the seem to work as intended. It seems the `const char *iconName` will need to be added to the other actions in order to use the original functions. I found the additional icons in issue #1526 but I will need to create more or modify existing for the menu actions, etc.

### CODE REVIEW

**Comment by areckx** [comment]
I added `const char *iconName`  to what (I think) is all of the functions needing icons. I am using `"broken"` for everything so I can either remove or replace with a relevant icon and keep track of where I am. Expect commits to come in over the next few days.

**Comment by areckx** [comment]
it might be the first commit shun-iwasawa  mentioned that the setWindowFlag is used in QT5.9 but apparently that line can be removed entirely. I will try building without it. 

This also may be relevant. https://stackoverflow.com/questions/33743493/why-visual-studio-2015-cant-run-exe-file-ucrtbased-dll

**Comment by openanim** [comment]
Hi,
Thank you for your interest and have already started a solution, however I would like to be certain that others in the community have not yet started work on it, I think especially artisteacher. This is important for the consistency of the visual identity of the icons already available. Of course it is quite possible to modify along the way. Do you have any suggestions ?
Btw, I did not get this error message.

**Comment by areckx** [comment]
If others have already made icons I can add them in. It doesn't seem like there are any in progress so I'd like to head from them because if at all possible it would be better to use custom icons to match the spirit of OT

**Comment by areckx** [comment]
> Of course it is quite possible to modify along the way. Do you have any suggestions ?

While the first step is to make sure all the tools and options have at least the option of having an icon, there should be an option to use either text _or_ the icon with for each entry. Right now all the icons have to be hardcoded in (it seems) and a custom icon loader would be pretty useful.

**Comment by artisteacher** [comment]
I’ve been brainstorming some potential options for a few of the icons. Now that school is out, I can actually get started. I do think it’ll be important to propose the icons in the issue first & get feedback before actually adding them in so that there can be revision if it’s necessary. Also, it will take some serious time to make icons for all of the commands. It would be great to make a few lists to help prioritize. What commands are the highest priority? What commands would be helpful but are secondary? Are there commands that are low priority?

**Comment by openanim** [comment]
This seems like good ideas, but for the second point how to prioritize? Should we post here and on the forum the different commands that everyone uses the most ? Then group and synthesize those that come back more ? or arbitrarily? I imagine that depending on the workflow of each it can be different.

**Comment by artisteacher** [comment]
I think we should post both here & in the forum & then synthesize.

**Comment by areckx** [comment]
Well what should I do? I feel like I'm not going to be able to make any income but I found bountysource and it looked like there was hope for me. I thought this project would be a good challenge for me and I would be able to get some money to pay the bills. I've worked on this for several days and it looks like it's for nothing...

**Comment by Agnyy** [comment]
@areckx Hey. I have some projects for OT that I need to implement, but there is no programmer. I can offer you a part-time job. For convenience, I will give an advance payment. Here is my Email: Agniyya@gmail.com

**Comment by openanim** [comment]
@areckx 

First of all, no one said that you could not have this bounty. It should not turn to drama unnecessarily. However, it must meet the expectations initially defined namely the creation of icons consistent with the current design. Do not see it, a reproach, but it would have been nice to set the expectations again, before you commit, I think.

I'm not a programmer, so I do not have any notion of the time, the difficulty, or any other parameters that are needed to put that in place. Although I suspect that it will take time, given the large number of commands, I know that the creation was not going to happen overnight. Even targeting the most commonly used.but you seem in a hurry.

Honestly, I was thinking first of all about the creation of icons with this request as suggested by @artisteacher. But, it turns out that it takes a lot of work to implement the code you did. On top of that, I would especially like the approval of the current main OT developers  (@shun-iwasawa  @manongjohn @turtletooth ) to know if this will be accepted and necessary since it is they who decide. Basically, to find out if your work is consistent/coherent since the goal is that it be incorporated into OT, later. If everything is OK then you will have the bounty.

And if necessary, I'll create another bounty for creating Icons to integrate with your work if approved because the goal is not to go through a database of icons.

**Comment by areckx** [comment]
Sorry I'm just starting to feel like I'm not going to be able to earn a living. It's really nerve-wracking.

**Comment by 711GM** [comment]
as I understand it we need to prepare a list of icons and draw and then vote for them? If so, why have not we created this list yet and started working?

**Comment by artisteacher** [comment]
@711GM, please let us know the commands you most want icons for in #2111.

**Comment by RodneyBaker** [comment]
This PR appears to have been abandoned.

**Comment by RodneyBaker** [comment]
There is still a $45 bounty assigned to this one.
@openanim I think that is all funded by you so the decision to close this PR is yours.  If you do decide to pull support make sure you transfer your bounty. Also, IMPORTANTLY while it may not apply in your specific case as the bounty hasn't been awarded and yet unclaimed, in those cases fees may apply after 90 days.  As such it will be good to read up on recent change to policy by BountySource.

**Comment by openanim** [comment]
Well, i dont have possibility to close or not this PR (be free to do it)). As said before, this was pending review. I do not know where things are right now. I had an agreement with areckx for this PR and I was planning to create another bounty for the other complement that had started artisteacher as said. But no news since that day. I suppose an abandonment too.

**Comment by RodneyBaker** [comment]
Will close pending renewed activity.

**Comment by openanim** [comment]
About that ... Alex told me that he could not work on Opentoonz anymore, and he moved on to something else.

**Comment by RodneyBaker** [comment]
Thanks for the update @openanim  and good luck to Alex as he moves on.

Perhaps we can examine and summarize where this effort left off so we can better identify what still needs to be done.

**Comment by RodneyBaker** [comment]
Reopening on the chance this might make it in to the pending release.
Somewhat doubtful and lower priority but... hope springs eternal.

**Comment by turtletooth** [comment]
Closing.  I think we need to look at proposed icons and work them in as they get support.

**Pull request closed without merging**
