### PR TITLE
Add "Hide Selected" Command to the Function Editor Spreadsheet

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will add "Hide Selected" command to the context menu in the column header area of the Function Editor spreadsheet.
It enables users to hide all selected channels without toggling in the tree view. 

hide_function_sheet_columns

### CODE REVIEW

**Comment by RodneyBaker** [comment]
LGTM.  
I almost merged this but thought I would mention this:

Is this hiding/unhiding something that can be added to History/Undo/Redo?
After Hiding a few columns I instinctively hit Undo and noted that History skipped all of the hiding/unhiding and did undo on previous events.  

It doesn't take long to cure ourselves of doing this of course but the thought occurs to me that if we accidentally hide some columns it would be useful to them them back via Undo before moving on.

**Comment by shun-iwasawa** [comment]
@RodneyBaker 

> Is this hiding/unhiding something that can be added to History/Undo/Redo?

Hiding / unhiding the channels is not a change to the scene data, but rather a change to UI. The states of channel visibility are stored in each Function Editor panel. Basically the changes to UI are not stored in the History, just like you cannot undo the change of the brush size.
So, I think we need to take another way to revert the operation.

**Comment by hayoko** [comment]
I would merge as is, looks good.

You don't want to add history to non-destructive changes, exactly in the way Shun Iwasawa has already described, let's not even think about it.

There are already three points of action, selecting, opening a menu and hitting confirm. If the user did the wrong thing that's totally their mistake, so just re-open the columns, no biggie.

**Comment by RodneyBaker** [comment]
Agree.  The Undo History was an itch I had to scratch and I appreciate the feedback and explanations.
LGTM

**Pull request merged**
