### PR TITLE
Add Weblate widget into README

### PR DESCRIPTION
**Pull request by Savraska2**
Adding Weblate widget, web-based translation tool.
Снимок экрана от 2020-09-21 18-22-31
https://hosted.weblate.org/engage/opentoonz/

### CODE REVIEW

**Comment by RodneyBaker** [comment]
LGTM
@shun-iwasawa Over to you for any questions regarding the link/widget before we merge.

**Comment by RodneyBaker** [comment]
As this is just going into the readme file it will be easy to remove or revert if desired.
Will merge.

**Comment by shun-iwasawa** [comment]
@Savraska2 @RodneyBaker 
Sorry but I'm very new to this service.
Please let me know, what will happen when a contributor submit changes in OT's translations via Weblate?
Will it push the changes to the repository automatically? 
And do you need any management on it, like as requested in #3519 ?

**Comment by Savraska2** [comment]
@shun-iwasawa Weblate is currently configured to send changes to weblate branch of my OT fork so that later I can manually create a PR to OT master branch but it doesn't work correctly now.

**Comment by shun-iwasawa** [comment]
@Savraska2 
Understood. Thank you for your help!
Please let me know if there will be anything that I can help with.

**Pull request merged**
