### PR TITLE
Translation files update for v1.3

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR does the following:
- Run `lupdate` and updated .ts files for all languages
- Update Japanese translation .qm files

@Savraska2 @morevnaproject @beeheemooth @gab3d @jcome @haminu0108 @deruji
We would appreciate it if you could update the translation, thanks!

### CODE REVIEW

**Comment by beeheemooth** [comment]
@shun-iwasawa I edited the downloaded .ts translation files (downloaded from Goolge Forum) Can I download them for editing in Linguist, or does it need to be done here? (Sorry, I am not very familiar with github, I need an example or instruction)

**Comment by RodneyBaker** [comment]
@beeheemooth   Here is the current instruction on translation for Opentoonz (it's short!):

https://github.com/opentoonz/opentoonz/blob/master/CONTRIBUTING.md#translations

**Comment by shun-iwasawa** [comment]
I'll merge this by myself as it only changes the translation files.

@beeheemooth 
Thank you for your kind proposal!
If you are not familiar with github, you can just download the zipped .ts files below, add translations by using Qt Linguist, overwrite them, zip them, and upload here. I'll include them to the software on behalf of you.

[russian.zip](https://github.com/opentoonz/opentoonz/files/2715363/russian.zip)

**Comment by jcome** [comment]
@shun-iwasawa I am working on Chinese translation right now. will create a pull request once done.

**Comment by Savraska2** [comment]
@shun-iwasawa Аttached archive below contain files of the russian translation OT v.1.3 edited by @beeheemooth  and me, could you merge them? Thank you.
[OT 1.3 russian translation.zip](https://github.com/opentoonz/opentoonz/files/2730782/OT.1.3.russian.translation.zip)

**Pull request merged**
