### PR TITLE
use nullptr instead of Q_NULLPTR

### PR DESCRIPTION
**Pull request by otakuto**
This project uses C++11.

### CODE REVIEW

**Comment by otakuto** [comment]
Jenkins

**Comment by otakuto** [comment]
I'm sorry.

**Comment by shun-iwasawa** [comment]
@otakuto Thank you for your contribution and terribly sorry for my late response!
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM Thank you @otakuto for refactoring!

**Pull request merged**
