### PR TITLE
Rooms Selection

### PR DESCRIPTION
**Pull request by turtletooth**
I added a preferences option to select from different room layouts.  It reads the folders in the stuff/profiles/layouts/rooms folder and creates options.  This allows users to have multiple room presets if they want.  The changes take place once OpenToonz in restarted.  

Right now, the default rooms are based off of the ones @blurymind shared in #80.  I added a basics room to the front. The rationale for the basics room is that I think a complete beginner should be able to open the program and have the ability to get started right away without having to dig into different rooms.  

Obviously, there is room for lots of discussion here, but I think that UI is the biggest hurdle to user adoption of this program and I want everyone to see the potential in this right easily.
preferences_options

new_toolbar

basics_window

### CODE REVIEW

**Comment by kogaki** [comment]
Jenkins, confirm this.

**Comment by kogaki** [comment]
It looks good solution. Thanks.
It will check the behavior soon.

**Comment by turtletooth** [comment]
Just a few more notes- 

- I made sure that if someone deleted the currently selected roomset, it would default to the first roomset in the folder.  
- I also added files that were not part of roomsets to a new settings folder inside profiles/layouts.  
- All user specific information about a roomset is in profiles/layouts/personal.

**Comment by kogaki** [comment]
It might be perfect if users can save current roomset as new roomset. But it's not necessary.

**Comment by kogaki** [comment]
I feel it's a little bit dangerous to overwrite user's custom roomset without alert. How about pop-up alert when user try to change the roomset?

**Comment by turtletooth** [comment]
> I feel it's a little bit dangerous to overwrite user's custom roomset without alert. How about pop-up alert when user try to change the roomset?

Right now, when a user changes a roomset, it calls a MainWindow::WriteSettings() to keep their current windows in place in case they switch back.  Each custom roomset is stored in its own folder- profiles/layouts/personal/OpenToonz, profiles/layouts/personal/StudioGhibli, etc. . . .  It doesn't lose the customizations to a roomset when the option is changed.

**Comment by kogaki** [comment]
@turtletooth 

Wow, sorry for my careless look. Yes, it works as you explained. Now all of the behaviors looks OK. 

My another suggestion is about the name of the roomset. The name `OpenToonz` might prevent developers from requesting other type of roomset. As you already mentioned, there must be lots of discussion about roomset. So it might be better to change the name to `Basic`, `Beginer` or as you intended.

**Comment by turtletooth** [comment]
What do you think of Standard?  I think that makes sense since these rooms are based off of Harelquin.

**Comment by AyameLee** [comment]
What about **Default**?

For new users experimenting with OT it might be handy having a button that can revert back to Default Roomset if a user feels they've perhaps done too much tweaking, this gives a baseline for community to negotiate technical assistance and for any kind of instructional documentation to refer to.

> Default
> Studio Ghibli

**Comment by turtletooth** [comment]
I like default.  
Right now there is a Menu option to reset default rooms.  Should that create the new rooms or the StudioGhibli rooms like it does now?

**Comment by kogaki** [comment]
Default seems good. Thank you.
I think `Reset` should be work as resetting `profiles/layouts/personal/{current selected rooms}` to it's original layout.

**Comment by turtletooth** [comment]
> I think Reset to Default Rooms should work as resetting profiles/layouts/personal/{current selected rooms} to it's original layout.

Done.  Reset to Default Rooms now simply deletes the personal folder for the corresponding roomset.  The next time its run, it will copy the roomset from the rooms folder giving a fresh start.

**Comment by turtletooth** [comment]
This leaves the other roomsets and their customizations in place.

**Comment by kogaki** [comment]
Great! We'll confirm it.

**Comment by kogaki** [comment]
Jenkins, test this, please

**Comment by kogaki** [comment]
Jenkins

**Comment by blurymind** [comment]
brilliant commit! Does it also include the room menus?
I can share the default room menus from toonz harlequin too

**Comment by turtletooth** [comment]
Right now it doesn't have the room menus.  Can you share them as a response to #329 ?  I don't think I'll make them part of this pull request, but I will do them separately.

**Comment by blurymind** [comment]
@turtletooth Toonz harlequin used the same menus in all rooms. I sat down and created a setup that can revert the old room menus from harlequin, while also adding the new toonz ghibli added features:
[room1_menubar.zip](https://github.com/opentoonz/opentoonz/files/294019/room1_menubar.zip)

To revert the default toonz harlequin menu layout, just use this menubar for all the rooms. You are of course free to further edit it and remove some of the entries on some of the rooms. That is something I am doing myself on further edits.

I also added it to #80

**Comment by blurymind** [comment]
For the default setup you can get rid of:
"basics" , "xsheet" and "cleanup. Those are a part of ghibli's.
Here is how the default room sets look like in toonz:

defaultroomsharl
"
It is much less cluttered than
https://cloud.githubusercontent.com/assets/4576381/15639603/122366e8-25eb-11e6-81a3-58b4af081ba9.png

and you still get all the features.

**Comment by kogaki** [comment]
OK, discussion about default room settings are useful, but we now merge this great commit first. Plz open another PR for changing default room settings. 
Thanks again @turtletooth for your great contribution.

**Pull request merged**
