### PR TITLE
Fix workflow_windows.yml

### PR DESCRIPTION
**Pull request by andeon**
Co-Authored-By: manongjohn <19245851+manongjohn@users.noreply.github.com>

Fix the workflow to generate a portable version and make mypaint brushes work correctly, this is based "windows_build.yml" and Batch Script files from tahoma2d repository create by @manongjohn .

Since this isn't working properly, I tried adjusting it another way, now the "mypaint brushes" are working as they should. I'd appreciate it if Windows users could test the artifact.

Edit: I used the GitHub web interface, I believe there could not be message text in the commit only author, so I'll use an application to add git commit --amend --author= to fix the co-author.

### CODE REVIEW

**Comment by andeon** [comment]
@RodneyBaker  Is there a way to rerun the job https://github.com/opentoonz/opentoonz/actions/runs/10133321074, this failed because it ran multiple jobs at the same time because I resubmitted --amend right after to fix the co-author.

**Comment by RodneyBaker** [comment]
Yes, I can restart the github workflows.
I can't do the same with Appveyor though.

The github action build is restarted.

**Comment by andeon** [comment]
I tried to update some code just to make a commit, it's strange because It's worked on the previous artifact https://github.com/opentoonz/opentoonz/actions/runs/10132928231

**Comment by andeon** [comment]
Thanks @RodneyBaker, it's live after restarting on the last commit, now I believe the portable Windows Artifact is working.

I tested it extensively yesterday and today. We now know that this can happen due to a connection issue: "`Unable to connect to source 'https://community.chocolatey.org/api/v2/':`", it's rare, but it can happen now that this was observed is mapped ;)

**Pull request merged**
