### PR TITLE
Fix build with clang 13: no member named 'copy' in namespace 'std'

### PR DESCRIPTION
**Pull request by rozhuk-im**
https://github.com/opentoonz/opentoonz/issues/4170

### CODE REVIEW

**Comment by RodneyBaker** [comment]
This looks good to me.  Simple and straightforward.
@shun-iwasawa Any thoughts?

**Comment by shun-iwasawa** [comment]
jenkins

**Comment by shun-iwasawa** [comment]
Hmm macOS jen.kins seems to need restarting.  I'll check it tonight.

**Comment by shun-iwasawa** [comment]
LGTM thank you @rozhuk-im for the fix!

**Pull request merged**
