### PR TITLE
Ability to execute Toonz scripts from commandline by blackwarthog (modified)

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is based on #2659 , adding a little modification attempting to run scripts without opening GUI .
I also added lines to revert the current project at the end, if OT switches it while running the script.

@blackwarthog @morevnaproject Can you please check if it does not harm original functionality of the feature? Thanks!

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Can anyone please test this PR and see if at least it does not affect the conventional workflows?
Then I can include this feature in v1.4 RC for user trial. Thanks!

**Comment by morevnaproject** [comment]
I will test it now. Thanks! ^__^

**Comment by morevnaproject** [comment]
I have tested and it works as expected. 

Here I am attaching a project, that anyone can use for testing this feature - 
[test.zip](https://github.com/opentoonz/opentoonz/files/4064893/test.zip)

The project has scene "test.tnz", which has one layer with one frame.
screenshot_001

It also has `test.toonzscript` file in `scripts` dir.
So, I am executing following commandline:

```
$ OpenToonz /path_to_your_project/scripts/test.toonzscript
```

After that I am re-opening the test scene and it looks like this:
screenshot_003

**Comment by shun-iwasawa** [comment]
Thank you @morevnaproject  for testing. I'll merge this.

**Pull request merged**
