### PR TITLE
Fix Travis CI with Linux Environment

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for fixing the Travis CI failure with Linux environment.
Trial and error will be needed as I'm quite new to this.

### CODE REVIEW

**Comment by turtletooth** [comment]
Perhaps this line:
> QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')

From here:
https://github.com/travis-ci/travis-ci/issues/6503

Might be useful somewhere.  I have no idea what I'm doing though.

**Comment by turtletooth** [comment]
The easiest thing seems to be to configure a travis.yml with
"dist": "precise" set for the build environment.

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you for your help.
According to the following error message;
>The following packages have unmet dependencies:
>libsdl2-dev : Depends: libegl1-mesa-dev
>               Depends: libgles2-mesa-dev
I added `libegl1-mesa-dev` and `libgles2-mesa-dev` to `sudo apt-get -f install` . It seems to work now.
I don't know why it used to have no problem without installing them.

After Travis CI is completed, I'll remove "[WIP][TEST]".

**Comment by shun-iwasawa** [comment]
Confirmed that Travis linux build completed!

**Pull request merged**
