### PR TITLE
WIP: EnumProperty: translation and icon

### PR DESCRIPTION
**Pull request by podsvirov**
Add support to translate EnumProperty items and
show icon.

Tested on `Active Axis` property for `Edit` tool.

Any feedback welcome!

### CODE REVIEW

**Comment by Agnyy** [comment]
@turtletooth @shun-iwasawa Look at this request. We need this to continue our work.

**Comment by Agnyy** [comment]
That's what we're doing right now.

**Comment by turtletooth** [comment]
I'm a big fan of this.  I think it can minimize clicks - and bringing back the combo edit tool as an option seems great!

There are two things that I want to make sure aren't lost.  The benefit of the dropdown was the word to help clarify what the user was selecting.  Will there be a tooltip on hover to say what the tool does?  Will the different modes still be accessible via shortcut keys?

As long as those two things are there, I am totally on board.

**Comment by gab3d** [comment]
I really like that idea too.
It's more intuitive, as it shows the user all available transforms (and with shortcuts and tooltips for each transform), I think it's the best choice!

The downside, of course is that it takes a little more screen real estate, but this leads me to another topic that bothers me and at the same time could help regain the lost space:

It always seemed weird to me that the selected item appeared inside the tool options itself, when the selected item is something more of "general use" to say something.
Of course, we need to know what item we are transforming (and there's no other easy way of selecting items that don't appear in the xsheet, like the camera), so we do need that combo-box in some place, but perhaps that place could be in a more permanent location, like in the header of the visor, for example.
(Please note that I don't know the technical possibilities of doing so, but I'm just trying to think outside of what we currently have.)

Keep up the good work!!

**Comment by artisteacher** [comment]
On smaller screens, especially with the combo-viewer, the tool option bar might get a little crowded. @gab3d suggested moving the selected item dropdown to make more room. I wonder if the xsheet toolbar would be an appropriate place for it?  Either way, this will be a fantastic timesaver for tablet users. I'm looking forward to it!

**Comment by matitanimata** [comment]
I've used Toonz for paperless productions since 2006 (some tv series for rai italian television) so I can say that the  combo edit tool is really an helpful and timesaving tool, so please let it come back! At the end of the day is a lot of time saved, trust me!

**Comment by turtletooth** [comment]
@podsvirov Any news on this?

**Comment by podsvirov** [comment]
Hello @turtletooth, unfortunately, I did not have time to improve these changes.

**Comment by turtletooth** [comment]
@podsvirov Do you plan on coming back to this, or should this be closed?

**Comment by podsvirov** [comment]
@turtletooth, I plan to return to these changes and work on improvement when I have free time.

**Comment by DoomDesigner** [comment]
@podsvirov 
Hey. I'm really looking forward to continuing the work. Ready to give money. I think many are ready to give money.

**Comment by podsvirov** [comment]
Money is a good incentive, but it seems that I really do not find any free time for this project. I will be happy if someone continues this work.

**Comment by Agnyy** [comment]
Hello everybody. Who can do this? It would be very good if it would be realistic.  I will be very happy with your help. @turtletooth  @manongjohn  @caryoscelus

**Comment by shun-iwasawa** [comment]
Thanks @podsvirov for this. I'll try to continue your work.

**Comment by Agnyy** [comment]
Icon (SVG) 
image

[Animate.tool.SVG.zip](https://github.com/opentoonz/opentoonz/files/1796500/Animate.tool.SVG.zip)

**Comment by podsvirov** [comment]
@shun-iwasawa, good news! Good luck!

**Comment by turtletooth** [comment]
Done in #1863

**Comment by podsvirov** [comment]
Thanks to all!

**Pull request closed without merging**
