### PR TITLE
Remove `delete`s with some refactoring

### PR DESCRIPTION
**Pull request by skitaoka**
- remove `delete`
- remove `delete[]`
- use _WIN32 instead of WIN32
- remove `register` keywords
- remove `using namespace std;` from headers
- remove `using namespace DVGui;` from headers

This PR contains modifications of PR https://github.com/opentoonz/opentoonz/pull/176

### CODE REVIEW

**Comment by kogaki** [comment]
Jenkins, test this, please

**Comment by kogaki** [comment]
Jenkins, test this, please

**Comment by kogaki** [comment]
Jenkins, test this, please

**Comment by kogaki** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins, test this

**Comment by skitaoka** [comment]
Jenkins, plz

**Comment by skitaoka** [comment]
Jenkins, plz

**Comment by skitaoka** [comment]
Jenkins, test this

**Comment by tomosu** [comment]
LGTM

**Pull request merged**
