### PR TITLE
Icons from @konero

### PR DESCRIPTION
**Pull request by turtletooth**
These are the icons submitted by @konero to replace the icons in the top of the viewer and combo viewer as well as the style panel.

### CODE REVIEW

**Comment by konero** [comment]
I just noticed the original icons are 16x16, whereas mine are 18x18, not sure how that happened, they should be 16x16 as that is an icon size standard.

If you hold for a bit, I'll re-make them as vectors (I was lazy and only did raster before so I can't just resize them outwith ruining their crisp edges) and give you the svg and png files, which might help later down the road if UI scaling is supported etc, that way you can change the colors if you're not happy as well.

Already got some done.

t1

Apologies! :+1:

**Comment by turtletooth** [comment]
@konero - it actually works with the current icons.  The original icons were placed 2px down in the window to meet the bottom and give the tabbed effect.  The new ones don't need the space above them.  SVG could be good for the future, but the size actually works well with the layout.

**Comment by konero** [comment]
I see, fair enough. How about turning this WIP and posting a preview for now? That tab idea sounds interesting. I'd like to fix some errors in the icons and add some clarity, I'd feel bad not giving it a good once over since the original batch were from a quick concept.

**Comment by turtletooth** [comment]
@konero I can post a preview in Motion Monster.  Would that work?  I don't know when it will be looked at on the OpenToonz side.

**Comment by turtletooth** [comment]
@konero - You can try it here:
https://github.com/motionmonster/motionmonster/releases/tag/v1.1.1.3.1

**Comment by konero** [comment]
Ok, I've deliberated a bit and done some testing. I see what you mean by tabbing the icons, but I think it makes life a little easier for us if for now we use 16x16 so they remain compatible with the original themes (see image) and align them in the original margin. I think a new spacing of 3px and 10px between the icons will work well (3px | 10px | 3px | 3px | 10px | 10px | 3px).

orig

I did some contrast tests and decided the negative space is too dark - if used on a light theme the icons in the off state are nearly impossible to see, same goes for inactive title bars on the original themes. The only way to fix this is to use high contrast, so I had to drop my dark theme bias. The negative space isn't pure white, it's 232 RGB.

dark_icons light_icons

If you can place the svg files in the resource folder (42.8kb) then this can be changed later.

As for the widget pane buttons, we were missing the minimize button which is found on the Flipbook panel so I created one. Since the close button suffered from similar issues as above I created a new one. Unfortunately if we want to have the 'good looks' this needs to be moved to qss because the buttons only work for one theme color (white buttons on black themes and vice versa, like in the images above). So we might need to leave these ones out.

Aside from that, these new icons are a lot sharper, I also changed the on state yellow color to match the one found in Toonz elsewhere.

I think you should split this into multiple PR's. I changed the save icon in the palette window originally because we had this funny moment where someone didn't understand why save icons were generally floppy disk icons, so I had a look at what 'mobile' icons use, but the Toonz members might want to decide on that.

- PR for Viewer Icons
- PR for Palette Icons
- PR for Pane Icons

I'll make a new issue so I have somewhere to post them.

**Comment by konero** [comment]
New icons posted in #810.

:+1:

**Comment by turtletooth** [comment]
@konero - That makes sense.  Would you mind if I use the old icons in Motion Monster?

**Comment by konero** [comment]
Go for it. :+1:

**Comment by konero** [comment]
@turtletooth I took some feedback on board and the icons have been updated. 

newv2_viewericons

### Viewer Icons V2: [OpenToonz_Icons_Viewer_Vector_V2.zip](https://github.com/opentoonz/opentoonz/files/474915/OpenToonz_Icons_Viewer_Vector_V2.zip)

**Comment by turtletooth** [comment]
@konero It looks like I won't need the icons for MotionMonster- I no longer need it with the PR that was merged last night.  :)

**Comment by blurymind** [comment]
Wow the updated version is even more gorgeous! Well done konero

**Comment by adamearle** [comment]
I would check out the new design of Maya's interface and icons. I hate to
admit it but they did some really apealing work.

It makes you just want use it.  Compared to what it use to look like its a
fantastic bit of art.

It would be kool to be an equal in that regard or top it.

Link to example
https://www.youtube.com/shared?ci=oDIvy1h55J8

I love that they have icons in the menu system because it helps people in
other languages to follow along with training.

Just some thoughts

Adam

**Comment by konero** [comment]
Hi @adamearle, thanks for the advice.

These new icons currently 'tidy up' the original ones, I thought an icon change may affect the UX for regular users so I was very conservative.

Here is a quick mock-up, taking inspiration from that Maya example, but not sure if that's what you meant.

tnz_mayastyle
tnz_mayastyle2
tnz_mayastyle3

**Comment by turtletooth** [comment]
@konero Wow!  Those look great.  I realize that there are potential issues for light themes, but I love the dark/transparent background on those icons.

**Comment by adamearle** [comment]
WOAH dude! You basshed those out so fast.
Those icons look sooooo great.

I can't even imagine if you did a redisgn how good it would look. Serisouly
well done.

Adam

**Comment by Emasoft** [comment]
Very good, but icons by themselves are still too cryptic. 
If we want to improve usability, the best and simple improvement would be to add a LABEL below each Icon. LABEL+ICON would allow to make OpenToonz UI finally understandable. Currently is completely impossible to grasp.

**Comment by blurymind** [comment]
@emasoft
I dont agree - if all labels are always visible it will make the interface
distracting and cluttered!

Hovering over an icon should bring the label of the button

**Comment by turtletooth** [comment]
@konero - What do you think about using the new icons instead (your Maya inspired icons) - they look sleek and beautiful

**Comment by turtletooth** [comment]
@shun-iwasawa What are your thoughts on me not making new themes, but updating the current themes with some of the changes that have been shown over the past few months?

**Comment by blurymind** [comment]
@turtletooth  Is it possible to have themes use different icon sets?
 @konero has produced a number of really nice sets to choose from now, It's hard to decide which to pick. Would be nice if the users could pick between them

**Comment by shun-iwasawa** [comment]
@konero Thank you for the great design work done so far! 
Regarding the Maya inspired ones, I like the vertical lines inserted before and after three "view mode" buttons. It is more intuitive that these buttons are **exclusive**.

@turtletooth IMO updating the current theme would be reasonable since they are in resources for now. I'll ask some users about look-and-feel of the new icons as soon as this PR is updated with the latest ones. Thanks!

**Comment by konero** [comment]
A little difficult to get those icons to look functional _(so they don't look like status icons)_ with the current titlebar aesthetic. One way to rectify this would be to increase the titlebar height from 18px to 20px, 22px, or 24px, but not sure what the appetite is for doing that.

Also, this would be a good time for extra feedback.

tnz_icons_feed

We use Nuke in the office, they use a Pause icon for their Freeze function, I liked it because it was a lot more minimalist, less of a 90's feeling. The 3D Cam icon (between Table and Cam) is meant to represent a digital multi-plane in isometric. The original doesn't work so well at 16x16 in white. The sub-camera Preview icon I'm not settled on, I took inspiration from After Effects for this one, since it's a feature I use a lot, it's also similar to Nuke's proxy low-resolution render button.

What do you think? Suggest/scribble any changes.

I will say though, if you notice the 'theme' I'm using here, there is a reason it's dark _(technically all I did was darken the outset style and switch style from outset to solid)_. The white from the original room tabs and the white from the titlebar outset border is enough to 'crush' these icons if they are Maya 'floating' style.

tnzcrush

If you compare these two images, you can clearly see the change in contrast. Since the room tabs are still new, perhaps we can re-design those though.

Seems to be an either/or at the moment.

**Comment by adamearle** [comment]
The work and comments on here are great.  The only thing that I would say
is this an opertunity for the the UI to become equal to better than current
tech.

I would say hold in your mind when designing and thinking about this are
some abstract ideas

1.Users will be looking at UI for a long time so keep it 'easy on the eyes'
yet 'distinguishable' from part of the interface to the next.

2. Inviting. Users want to click on things and not feel like they are going
break something ruin the work that they have done.

3. Sophisticated subtle and simple. This will enable users to keep there
mind free from the UI and focused on the task that needs to be achieved.
This also enable artist to feel like they can dive into tools when they
real need.

An old proverb says many words cause much confusion. So lets keep it simple
but that doesn't childish or stupid.

Loving the work being done here so much.

**Comment by VidelXi** [comment]
@adamearle I concur!

@konero I love the latest icons you posted so much, they're readable even without my glasses on.

Could you try them on a more flat theme style? I'm in the same boat as @adamearle that Maya, DragonBones and Resolve are easy on the eyes without all the bevels.

Thanks for all the hard work everyone, OT is great. 💛

**Comment by konero** [comment]
Flat (with @shun-iwasawa 's character):

tz_flt_dog

**Note:** Titlebar would need to be increased in height to 22px **not including** the top and bottom borders, including them would be 24px. It depends where we would put those borders, as part of the titlebar, as part of the dock widget or as part of the dock separator.

Would look better with #772 merged.

Might be hard to see on GitHub due to all the white washing out the grays, if you're on Windows 10 you can download the image and view it with the Photos App.

**Comment by Emasoft** [comment]
Those icons are too criptic. I don't understand what they mean. 
We need OpenToonz to have the option to display a text label below every icon, like many professional programs do. Usability can be improved only with a "label+icon" UI. OpenToonz UI is already very hard to learn and understand. Having also Icons without labels is a very stupid way of shooting ourselves in the feet.

**Comment by turtletooth** [comment]
> We need OpenToonz to have the option to display a text label below every icon

I totally disagree.  Most programs (including OpenToonz) use tool tips when you hover over an icon to show the tool name or description.  Adding text to the UI just adds to the clutter.  I do think there are places where tool tips should be added, but I don't think adding the text to the UI will make the user experience better.

**Comment by turtletooth** [comment]
@konero  I like the latest version.  I especially like the green better than the red.  The one icon that I think is a little vague is the 3d camera.  To me it comes across more as something to do with layers (which I realize you can visualize in the 3d camera), but I think the icon from the maya style icons more clear about what that button would do.  But all in all, I really like the updated icons.  I think they will be a great enhancement to the UI of OT.

Earlier you posted sreenshots of a theme you were working on, but then removed them.  I really like the direction you were going with that and think it would make for a nice default theme.  I think we need to hear from @shun-iwasawa and the team, but instead of adding new themes, I think it makes sense to update the current themes, and I think your theme would be a great direction to go.  Are you willing to share the theme?  You have already been a great voice here for UI and UX- thank you for all your help and input.

**Comment by turtletooth** [comment]
@konero @shun-iwasawa As soon as icon files are added, I will close this PR and submit a new one with the updated icons.  

@konero What do you think should be done with the style editor icons you submitted?  Do you want to stick with those or do they need tweaking as well?

**Comment by blurymind** [comment]
@Emasoft it seems like you are the only person in the entire world that has trouble understanding what a brush icon mean and a bucket icon mean.
These are very standard icon designs that are obvious to anyone who has had any experience with basic graphics software. 
I don't understand why you are unwilling to just let your brain accept and file it in your memory when you hover over it and read the tooltip. Just clicking on it and trying it even.
Nobody is on board with the idea of even having the option to clutter the entire interface with labels

Yet  you created an issue for it on the tracker..
https://github.com/opentoonz/opentoonz/issues/864

If it's so important to you, why dont you create a proper mockup of the interface with the labels?

**Comment by blurymind** [comment]
@konero I like the green better than the red because,
1. it has more contrast
2. green fits the color of the OT logo

**Comment by konero** [comment]
Hi @Emasoft, wherever I can I try to follow widely established standards when doing UI work, which is why in the case of these icons I've taken note with what is used by the big players as more than likely committees will use them in some combination with Toonz.

In regards to labels I don't think I've seen any professional software that has them next to icons. They may never all be considered universally known but icons used by multimedia software are definitely conventional. If in any doubt, then that is what tool tips were designed for.

**Comment by konero** [comment]
@turtletooth TBH I had the same opinion about the 3D icon, it's one I've had trouble with. I'll experiment again with the previous Maya-esque one and the original one. Maybe a cube, a looping isometric arrow or simply the acronym "3D" like in Storyboard Pro, 16x16 is unfair at times. 👺 

Sure, I can share the theme I was working on, I'm surprised you caught it, I thought it distracted from the PR. Once we finish this PR we can discuss it in a new thread and I'll upload all the resources.

**Comment by konero** [comment]
@blurymind I made a jsfiddle where you can choose the color for active controls if you want to give it a go.

**Link:** https://jsfiddle.net/konero/x4Lw8pj2/

Simply change the hex value (#000000 etc) in line 8 `background-color` under the CSS box and click run.

If you type "hex color picker" in Google it should give you an embedded widget to use.

**Comment by blurymind** [comment]
@konero  thank you for adding the option! Now if we could only get it exposed to the preferences in OT - perhaps @turtletooth  will know how to :)

Please don't allow one loud voice to bully you in implementing a feature nobody wants. There is a good reason other graphics software does not use labels under icons - we need a minimalist user interface that gives as much screen estate as possible to the drawing area!

**Comment by konero** [comment]
What about something like this?

3dico2

**Comment by konero** [comment]
I made a batch of different icons for the 3D View. Unfortunately the space is too small for that Maya one from previously to work well.

all_3d_icons

1 = Original
2 = Position Axis
3/4 = Cube
5 = Position Axis with Cam
6 = Parallax
7 = Acronym

The only reason I deviated from the original was because it looks terrible in white, btw.

What do you think? 👂

**Comment by turtletooth** [comment]
I like 1 because it shows what the view will be for the user
I like 7 because it is clear that clicking it will bring up something related to 3d
I think 2 and 5 may only be understandable for those who have used actual 3d software and seen the gizmos in Maya or Blender.
3, 4 and 6 seem a little vague to me about what is going to happen when I click the button.

I still like the Maya one a lot.  Do you prefer any of these ones or is there a change that need to happen for the Maya 3D camera icon to work?  It looks like the icon itself is 11 x 22- what dimensions are you trying to keep it under?  

Thanks for all your work on this.  It is really  going to help freshen up the UI.

**Comment by turtletooth** [comment]
@konero  - Would you mind sharing the icons you feel are stable so I can start building a PR for them?
Thanks.

**Comment by yamisama** [comment]
I think the camera icons from the Maya-type three-color example were the clearest by far. The shared iconography between the 2D camera and the 3D camera makes it absolutely clear that both are different types of camera views and that both are different options for the same setting. Same thing with the two eyes for "Preview" and "Sub-camera preview". Having these icon pairs resemble each other makes the functionality and the fact that they are mutually exclusive infinitely more clear and easy to understand.

As for the freeze icon – I think the pause icon makes it too easy to mistake for some kind of playback or background process control and a user might also expect it to change to something like "play" when toggled. My suggestion would be to use a padlock icon instead – it's immediately associated with locking something (in this case the view if I understand the feature correctly). It's also commonly used in other software in this way, including After Effects, which many animation professionals are familiar with.

**Comment by adamearle** [comment]
I really like 1,2,5,6 & 7

Maybe if 2 was tweaked somemore than I think I would be really sold on it

WOW this is realy tough choice

what about a combination of 1 and 2

What good job 7 and 6 to me are the most clear when i think of other
languages as well

Yikes it will be interesting to hear what people say




*Adam Earle*
*Phone:* 0431799431
*Google Hangout: * MrAdamEarle@Gmail.com
*Email:* MrAdamEarle@Gmail.com

**Comment by turtletooth** [comment]
Closing.  I believe and updated interface would be beneficial, but this PR is no longer the direction the icons seem to be going.

**Pull request closed without merging**
