### PR TITLE
Use ~/.config on Linux/Unix

### PR DESCRIPTION
**Pull request by ideasman42**

### CODE REVIEW

**Comment by kogaki** [comment]
Can one of the admins verify this patch?

**Comment by kogaki** [comment]
Can one of the admins verify this patch?

**Comment by skitaoka** [comment]
Jenkins, test this.

**Comment by skitaoka** [comment]
This PR has a compile error on osx.

```
tenv.cpp:84:24: error: incomplete type 'QDir' named in nested name specifier
                QString settingsPath(QDir::homePath());
```

**Comment by ideasman42** [comment]
Hopefully OSX error is corrected now.

**Comment by skitaoka** [comment]
Jenkins, test this, again.

**Pull request merged**
