### PR TITLE
Remove some using declaration of std

### PR DESCRIPTION
**Pull request by otakuto**

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
@otakuto 
Thank you for the refactoring. Jen.kins for Windows seems to have following errors:
```
  C:\Users\opentoonz\.jenkins\workspace\OpenToonz project PR-auto\toonz\sources\stopmotion\stopmotion.cpp(445): error C3861: 'max': ?????????????? [C:\Users\opentoonz\.jenkins\workspace\OpenToonz project PR-auto\toonz\build\toonz\OpenToonz.vcxproj]
  C:\Users\opentoonz\.jenkins\workspace\OpenToonz project PR-auto\toonz\sources\stopmotion\stopmotion.cpp(457): error C3861: 'min': ?????????????? [C:\Users\opentoonz\.jenkins\workspace\OpenToonz project PR-auto\toonz\build\toonz\OpenToonz.vcxproj]
```

**Comment by otakuto** [comment]
Thanks for reviewing my trivial commits as always. 😂

**Comment by otakuto** [comment]
If fix commit needs rebase, I'll do.

**Comment by RodneyBaker** [comment]
@otakuto This is looking good to move forward with the exception of the removal of `using std::filebuf`.

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
@otakuto 
Jen.kins claimed errors for sources which was modified recently (vectorerasertool.cpp) like as follows:

```
/Users/opentoonz/.jenkins/workspace/OpenToonzOSXPR-auto/toonz/sources/tnztools/vectorerasertool.cpp:1286:20: error: use of undeclared identifier 'max'; did you mean 'fmax'?
```
There seem to be several usages of `max` and `min` in it.

I'm so sorry for asking additional work, but can you please resolve the error?
Or if you could squash your commits, I'll resolve the error add post another PR based on this.
Thanks!

**Comment by otakuto** [comment]
@shun-iwasawa 
I flxed it.

**Comment by RodneyBaker** [comment]
A lot has changed since April so we may need to restart this one to regenerate Travis and Appveyor checks.

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
Thank you @otakuto for refactoring ! LGTM

**Pull request merged**
