### PR TITLE
Add locking stroke functionality in cutter and pump tool

### PR DESCRIPTION
**Pull request by pojienie**
This PR allows you to "lock" a stroke when using cutter and pump tool by holding control key.

video: https://www.youtube.com/watch?v=frl7fsuCZok

I created this because using pump tool on eyelash stroke is a pain if there is another stroke(e.g. hair) at the end of the eyelash.

### CODE REVIEW

**Comment by beeheemooth** [comment]
Very useful! Thanks!

**Comment by openanim** [comment]
Thanks, works fine for me !

**Comment by jrhyme** [comment]
Let's merge, I want to use on Linux ahah)

**Comment by beeheemooth** [comment]
@pojienie What about the Pinch Tool? He also likes to jump from one vector to another.
It is absolutely impossible to select the edge of the desired vector in a place where several lines converge.

**Comment by turtletooth** [comment]
I'll look at this soon.

**Comment by gab3d** [comment]
@pojienie 
nice job! it will increase productivity of the tool 👍 

perhaps, now that you've discovered the power of the hardcoded Ctrl key variant 😉 is there any chance of adding it to #3194 too? it'd be just the same, really. pretty please! 💟 

one way or te other, thanks for all of your contributions to OT, you're doing a very good job lately!

**Comment by pojienie** [comment]
@beeheemooth I don't use pinch tool at all so I missed it...

@gab3d The reason why I hardcoded this was because it makes no sense to have a GUI element for this functionality and, without a GUI element, I have no idea how to add it to shortcut menu. So, no.

**Comment by gab3d** [comment]
@pojienie 
I get the point, and certainly you're free to develop as you understand is the best way.

In spite of this, at least to me, workflow's priority is higher than UI, or having many options; so if I insisted with this was just to raise the case for a focus on workflow, over having many options 'per se' (even though having options is always good, of course).
In brief, what I say is that it might not be enough for us to add a lot of options in OT to make it a good solution, if the usage of each one of them is not well though out and optimized in the best way possible.

I'm certainly grateful for you're efforts, please don't take it as a bad criticism, but I'd certainly like you to consider other poins of view as well.
Thanks

**Comment by RodneyBaker** [comment]
Thanks @pojienie  This will make a nice addition to the Cutter and Pump Tools.

This is just waiting on @turtletooth's review, otherwise it looks good to move forward.

Aside:  This is one of those features that may be hard to discover.
Short of word of mouth and documentation I'm not sure how to promote it more in users minds.

**Comment by RodneyBaker** [comment]
Pressing forward with this as Jeremy has a lot going on right now.

**Pull request merged**
