### PR TITLE
Make More UI Texts Translatable

### LINKED ISSUE #2020: Some strings cannot be translated v1.2.1
### --Issue Summary--
There are currently some strings in OT's UI that cannot be translated.
Some of them of newly added features, which are of very high exposure inmediately after release.
So it'd be great if they could be addressed

### --System Information--
+ OpenToonz Version:
1.2.1 release candidate (sort of...)

Here I post a prioritized list of found untranslatable strings, as of the last nightly build.

**HIGH**
- Animate Tool: "All", "fld" (in Z Position input field)
- Fill Tool: "Maximum Gap"
- Style Editor: drop down menu (Wheel, H, S, V, A, R, G, B)
- Preferences > Tools:  Cursor Options both drop down menus options (all)

**MEDIUM**
- Brush Tool: "custom" (brush preset)
- Style Editor window title: the word "Palette" still shows only in English
- "Xsheet" / "Timeline" toggle button in Xsheet
- Ruler Tool: X, Y, W, H, A, L strings
- Tape Tool: "current" (in Style Index option) 
- Rotate tool: "Rotate On Camera Center"
- Scene Cast window: "Cast", "Audio"

**LOW**
- New Level dialog "Type" drop down menu options: (Toonz Vector Level, Toonz Raster Level, Raster Level, Scan Level)
- Level Settings dialog: "Vector level", "Ink&Paint level", "Raster level", and DPI drop down menu options (Image DPI, Custom DPI)
- Camera Settings dialog:  "inch", "A/R", "custom" (camera presets)
- Export Level dialog > Export Options > Vectors Export Box: "Width""Height" (strings are there in the PO file, but apparently disabled).
- Replace Level: warning, when nothing is selected "Nothing to replace: no cells or columns selected."
- Adjust Levels: drop down menu options (RGB, Red, Green, Blue, Alpha)
- Color Fade:  "R", "G", "B", "A"
- Canvas Size: Units drop down menu options (pixel, mm, cm, field, inch)
- Replace Parent Directory: File browser title

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58981421-some-strings-cannot-be-translated-v1-2-1?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F33713530&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR resolves #2020 .

Most of the texts listed are now translatable, other than items as follows;

- Animate Tool: "fld" (in Z Position input field)   -  It's linked to core unit system of OT and will need some time to change.
- Scene Cast window: "Cast", "Audio"   - They seem to be part of scene data rather than UI texts. I need some time to make them translatable as well, in order keep compatibility among multi language environment.

**PLEASE NOTE**
For "current" text (in Style Index option of Tape Tool) , you need to set the same translations to both of the following: 
 - "current"  of `DVGui::StyleIndexLineEdit` in toonzqt.ts
 - "current" of `RasterTapeTool` in tnztools.ts

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
I'll merge #2025 before this.

**Comment by shun-iwasawa** [comment]
Rebased to the current master.

Jenkins

**Comment by shun-iwasawa** [comment]
Added more text listed in [the comment](https://github.com/opentoonz/opentoonz/issues/2020#issuecomment-393725105) by @gab3d .

Note that the following item is not added : 

- FX Schematic: "Source", "Matte", "Light", "Reference" connector names in effect nodes.

It needs some time to include keeping consistency between languages since they seem to be saved in the scene file.

Jenkins again

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
The context menu commands in all text/number input fields (Undo, Redo, Cut, Copy, Paste, Select All) are now translated. Please note that they will be translated according to the current locale of your computer, regardless of the OT preferences.

Jenkins again

**Comment by masafumi-inoue** [comment]
LGTM

**Pull request merged**
