### PR TITLE
Camera Capture feature : Save scene in the subfolder checkbox

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is demanded by some Japanese animation studio.

Adding a checkbox in the SubFolder popup in the Camera Capture feature.
If this checkbox is activated, following two operations will be done automatically along with creating the sub folder.

- Current scene will be saved in the sub folder.
- Output path in the output settings will be set to the sub folder.

Please note that this checkbox is available only when the current scene is untitled.

In Japanese animation industry, the pencil test workflow is quite independent from other flows. And it would be convenient to put the scene file and captured image files in the sub folder together just like QuickChecker.

**UPDATE:** 
Additionally, I made the "Save in" folder to be saved in the scene file.
This feature is useful when users open existing scene and continue capturing.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Additionally, I made the "Save in" folder to be saved in the scene file.
This feature is useful when users open existing scene and continue capturing.
Jenkins

**Comment by shun-iwasawa** [comment]
@masafumi-inoue 
Can you please take a look on this?

**Comment by masafumi-inoue** [comment]
LGTM

**Pull request merged**
