### PR TITLE
Fix for Full Screen Mode on X11 with Multiple Monitors

### PR DESCRIPTION
**Pull request by BloodyMess**
I took [my own suggestion](https://github.com/opentoonz/opentoonz/issues/3700#issuecomment-781927440) and implemented it.

I was right about Qt always putting the window at (0,0), but I was initially looking at the wrong class and method. I implemented the fix in FullScreenWidget::toggleFullScreen() in imageutils.cpp in my fork.

It seems to be working fine, but I only have a Linux system to test it on. So I'm hesitant to create this pull request. Also, my coding style is a bit different from what's in OpenToonz, you might prefer to just look at my fix to see what I did (don't worry, it's super easy to read and very well commented.).

### CODE REVIEW

**Comment by BloodyMess** [comment]
BTW: In case the code looks funky displayed in the web browser: I always edit using tabs for indentation, with a tab width of 3.

**Comment by le-dragon-dev** [comment]
Hi! Thank you, I'll try this fix later today!

For the tabs/width 3: isn't it better to keep the same code aspect for all the project? (spaces, width 2)
I don't know if the script ./beautification.sh in the sources folder still works.

**Comment by BloodyMess** [comment]
> For the tabs/width 3: isn't it better to keep the same code aspect for all the project? (spaces, width 2)
> I don't know if the script ./beautification.sh in the sources folder still works.

Yes, probably. I wasn't trying to suggest that the project change it's style, just giving a heads up as to why my code might look funky in your browser. That's one of the reasons that I mentioned you guys might want to just read it to see what I did to fix it.

I hadn't heard other users complaining about the full screen mode, which made me think there wasn't much demand for a fix for it, so I originally only intended the fix to be for myself. Once I found that I only needed to change a single function, I figured it couldn't hurt to make it available, and you guys could just do whatever you want with it in your project.

**Comment by shun-iwasawa** [comment]
Thank you @BloodyMess for the fix, I'll check if your modification would work on Windows as well.

Sorry for troubling you, but it would be helpful if you could resolve the conflict. Thanks!

**Comment by BloodyMess** [comment]
> Thank you @BloodyMess for the fix, I'll check if your modification would work on Windows as well.
> 
> Sorry for troubling you, but it would be helpful if you could resolve the conflict. Thanks!

Sorry, I didn't realize that that was an edit field on the Resolve Conflicts page. lol. I know C++ like the back of my hand. But I'm fairly new to using git and github for anything more than building projects from source.

**Comment by shun-iwasawa** [comment]
I don't have multi monitor environment for MacOS but at least confirmed that it works with no problem with single monitor.

Regarding Windows I found another way to fix the problem and will post separate PR later.

LGTM thank you @BloodyMess for the fix!

**Pull request merged**
