### PR TITLE
(WIP) Brush straight line tool2

### PR DESCRIPTION
**Pull request by se7enstar25**
Co-Authored-By: jeremybullock <79284068+jeremybullock@users.noreply.github.com>

### CODE REVIEW

**Comment by manongjohn** [comment]
Thanks for properly crediting.

**Comment by RodneyBaker** [comment]
Not sure why the github action builds don't have the feature working but the appveyor build at least does.
For those that haven't been keeping up...

This feature works with raster levels only.

> Holding shift using the brush on normal raster levels will make a straight line.
Holding control will snap to vertical, horizontal or diagonal lines.

image

**Review by konero — CHANGES_REQUESTED** [review]

**Comment by RodneyBaker** [comment]
@konero Thanks for taking the time to look into this PR.
While I fear your time has been wasted... no review of code is wasted when it helps us see problems in code.
As such.. again thanks.

I have been informed a replacement PR  will be posted soon that will make this PR obsolete.

@se7enstar25 We do thank you for the contribution and hope you will be able to contribute again in the future to Opentoonz development.

I will make this PR a draft but please note that it will soon be closed.

**Comment by konero** [comment]
If modifications are being made why not just push them to this branch? You don't need to keep opening new pull requests.

**Comment by RodneyBaker** [comment]
I'm not sure what the plan there is but I assume/d a new PR was being prepared because it's a completely different developer...  adds code for the other level types... etc etc etc.

Translation:  I don't really know.

**Pull request closed without merging**
