### PR TITLE
Onion skin default color changed

### PR DESCRIPTION
**Pull request by turtletooth**
This is a resubmit after I broke the last one trying to get that branch up to master.

Most animation programs use green and red for onion skin colors. This helps the animator have a better visual cue what is happening.

There is definitely room for debate, but I thought it might make a good default.

### CODE REVIEW

**Comment by blurymind** [comment]
Green is better than blue

**Comment by kogaki** [comment]
I think this should be controled by qss.

**Comment by turtletooth** [comment]
@kogaki If I change it in qss, will the user still be able to change it in preferences?  I thought the styling in qss is relatively permanent.  This simply changes the initial values but the user can change them at any time on their own.

**Comment by shun-iwasawa** [comment]
For now this branch conflicts to master branch since we applied clang-format on v1.0.3 release.
Sorry to trouble you but could you please apply clang-format (with [toonz/sources/.clang-format](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/.clang-format)) to your PR or rebase your commits to the current master?
Thank you for your contributions.

**Comment by tomosu** [comment]
Jenkins

**Comment by turtletooth** [comment]
Updated for 1.0.3

**Comment by kogaki** [comment]
Jenkins

**Comment by skitaoka** [comment]
LGTM

**Pull request merged**
