### PR TITLE
Organizing the Tool option bar layout

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for the issue #427 
In this branch I did some modifications as follows in order to improve usability and to clear space for future additional functions:
- All sliders are set maximum widths.
- All input boxes and combo boxes are set maximum/fixed sizes according to their content.
- Layouts' stretch values are optimized.
- Icons in tool option of the Selection tool are now style-sheet-aware so that they are visible in dark background color.

Please note that you need to replace the style sheet and corresponding image files in $TOONZCONFIG/qss folder before you run the software built from this branch.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins, check again

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins, check again

**Comment by shun-iwasawa** [comment]
Jenkins one more

**Comment by skitaoka** [comment]
Jenkins

**Comment by kogaki** [comment]
OK, now it seems to work. LGTM

**Pull request merged**
