### PR TITLE
Update more macOS Build Instructions

### PR DESCRIPTION
**Pull request by MrBlockCat**
Updates the rest of boost from 1_69_0 to 1_72_0 and tweaks some other more minor things.

Sorry! I thought I'd caught everything from the recent PR but I noticed there were still a couple outdated commands, so this should fix that, and some minor typos as a bonus!

### CODE REVIEW

**Comment by manongjohn** [comment]
The build instructions should show the minimal requirements to build. Boost 1_69 is still valid so i would not update that.

**Comment by MrBlockCat** [comment]
I agree it should show the minimum requirements to build (and I kept the minimum required version for boost the same) but as boost was recently changed to 1_72_0 elsewhere in this doc and that’s the version you have by following the directions it seems to make sense to update these commands to follow what does happen when you download boost, especially as following the build instructions involves redownloading boost every time you build, meaning you’d be working with their most updated version

**Comment by manongjohn** [comment]
Then we'd be updating these instructions every time they released a new version.

I think the only reason I even had it there was because that is what I built with at the time I drafted these instructions as an example.

Not a big deal if its updated.

**Comment by artisteacher** [comment]
The last tested version (which I updated) doesn't necessarily need to match the version number in the build steps themselves. However it'll temporarily save us a step, so I don't mind the update.

Is the official release still built with QT 5.9.2? It would be nice to update the cmake file at some point.

**Pull request merged**
