### PR TITLE
Fix timeline key-scrolling

### PR DESCRIPTION
**Pull request by manongjohn**
This PR fixes the following scrolling issues when using keys to navigate the timeline.

1) When you use Down-arrow to reach the bottom of the timeline, the current frame is selected but the bottom level is not scrolled into view requiring the user to use the scroll bar to see it.

Added logic to account for the height of the bottom level when scrolling to the last column.

2) Using END key to get to last frame was jumping to a frame way past the last exposed frame.

Added logic to factor in timeline zoom factor to correctly calculate the last exposed frame.

### CODE REVIEW

**Comment by manongjohn** [comment]
Looks like QT version for OSX builds changed again. Now at 5.12.2.  I'll submit a PR to fix

**Comment by turtletooth** [comment]
Restarted the build.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
It works fine. Thank you @manongjohn for the fix! LGTM

**Pull request merged**
