### PR TITLE
Fix level create popup units

### PR DESCRIPTION
**Pull request by turtletooth**
Fixes the issue with #3261

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Looks like a Jenkins refresh is required.

**Comment by turtletooth** [comment]
Oh Jenkins

**Comment by RodneyBaker** [comment]
cc:  @shun-iwasawa @manongjohn

**Comment by manongjohn** [comment]
Let's see if this works...probably won't...but let's tey anyway...  Jenkins

**Comment by manongjohn** [comment]
As usual. Jenkins build won't start when I want it to but does when I don't expect it to.

**Comment by turtletooth** [comment]
I'm going to merge this since the current level creation is broken.

**Pull request merged**
