### PR TITLE
New option for Toonz Raster Brush Tool : Draw Order - Palette Order

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will introduce a new option to Toonz Raster Brush - ~~"Selective : Style Order".~~
**UPDATE:** This item is renamed to "Draw Order", with 3 options `Over All` , `Under All` and `Palette Order` .

We already have "Selective" option for the Toonz Raster Brush tool, which allows the drawing operation without affecting already drawn lines.
**UPDATE:** `Over All` and `Under All` options correspond to deactivate and activate the conventional "Selective" option, respectively.

The ~~"Style Order"~~ "Palette Order" option will be added to it. If the ~~"Style Order"~~ "Palette Order" is selected, stacking order of the stroke will be the same as the order of the styles in the palette. Therefore, style order in the palette will act as pseudo-layers.

Please note that the "style order" means the order in the palette page, regardless of the style index.
Which means that you can control the stacking order of the new stroke by moving the current style in the page before drawing.

This option is useful especially for drawing with switching between solid (black) ink and self-colored (red/blue) inks. You can draw solid lines always on top without any care of "Selective" option.
This feature was requested by some Japanese animation studio.

style_order

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by DarrenTAnims** [comment]
Quick question - Is it too late to suggest a change to the text shown to make it easier for new people to recognise and use it?
How about changing the title of the dropdown to "draw order".
And change the options to: "Under all", "Over all", "Palette order" .

**Comment by gab3d** [comment]
@DarrenTAnims 
sounds good to me

**Comment by masafumi-inoue** [comment]
LGTM

**Comment by blurymind** [comment]
For a moment I thought that you have implemented this:
https://github.com/opentoonz/opentoonz/issues/1616
gradientindexes
multishadebrush

It's a brush mode that uses the palette order to change pixel colors.
It would be perfect for OT's raster brush!

**Comment by shun-iwasawa** [comment]
@blurymind 
Yes, now I'm thinking of introducing something similar to this feature.
Not as the special brush, but as some kind of extension of palette data which specifies the relation of gradient between styles.

**Comment by blurymind** [comment]
@shun-iwasawa This would be an incredible addition to OT and seems like a good fit for the brush tool - as a mode.
But if you are looking into desigining it into the palette data, I think that your implementation will probably be even better than the one in Pro Motion

They describe the multishade mode like this:

> Multi Shade
> Works the same as Shade but uses mor than a single gradient at a time. It only works for gradients that are set up for multi shade paint mode. Because you might want to have gradients that are not touched by the multi shade you must enable a gradient that may be used. Just go to the gradient editor and activate multi shade paint mode for the gradients that may be used for this paint mode.
> 
They also have a window to set an independent indexing order for multishade painting btw
https://www.cosmigo.com/promotion/docs/onlinehelp/GradientEditDlg.htm

**Comment by blurymind** [comment]
@shun-iwasawa  oh god, I just realized that I have already posted about this here. Sorry for spamming you. I have totally forgotten

**Comment by beeheemooth** [comment]
@shun-iwasawa I've got small but useful suggestion: to add also reverse order of the palettes Thus you can easily draw intertwining patterns.
ezgif-3-4b322d78ff

**Comment by RodneyBaker** [comment]
Adding a postmortem note based on some feedback and testing.

The copy/paste process does not appear to respect palette order which is reasonable.
It just pastes the copied selection over the target.
It would be very useful to be able to paste UNDER the target.

I'm mainly thinking in terms of anime usage where a face might be on one level and a mouth on another and while merging and match lines is an option a quicker way can often be to simply copy/paste one into the other.  

In most cases a Merge TLV Levels will work here but in those cases column order is important.
It makes me think that there might need to be an option to Merge Up or Merge Down where to the user it's all pretty much the same but in the code the columns would flip stacking order.

**Pull request merged**
