### PR TITLE
Fix Assistant Tool Slowness

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will partially fix the slowness mentioned in #4852 and #4957 .

- Reverted the update method of tool options bar, from re-building whole options from scratch to show/hiding the relevant fields. Which will
  - remove unwanted "Size" field in the tool option of Toonz Raster Brush, and
  - will resolve the slowness when dragging on the color wheel in the style editor.
- Made the twizzler shape to be available only in the debug builds.
- Reverted the `SceneViewer::tabletEvent` to modify the slowness when using tablet

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
I think it would be better if the Assistant tool becomes more like the Shift and Trace, which will activate a special tool when active.
And if the assistant column can be narrower and placed next to the camera column..? Well, I think I need more investigation.

**Comment by RodneyBaker** [comment]
Thank you so much for addressing this current problem.
Your fix does indeed appear to address the extreme slowness brought on by the addition of Assistants Tool.

The appveyor build failed and checks didn't pass and I see that as critical especially as when testing prior things worked fine under github build but then not after appveyor build of the nightly release.  While I see many errors reported, the main culprit appears to be failure to link up with a DLL file.

**Comment by shun-iwasawa** [comment]
UPDATE:
- Fixed the debug build error
- Reverted the `SceneViewer::tabletEvent` to modify the slowness when using tablet

**Comment by RodneyBaker** [comment]
Thank you @shun-iwasawa for the fix... update... and the refresh.
LGTM

**Pull request merged**
