### PR TITLE
Assistants for Toonz Vector brushes

### PR DESCRIPTION
**Pull request by blackwarthog**
Implementation of assistants for the ToonzVectorBrush.
Completely implements this feature #1349
Related PRs: #2656, #4852, #5039

Also assistants are visible with all tools now (solves this https://github.com/opentoonz/opentoonz/pull/5039#issuecomment-1687866603)

Note: This PR is based on code from PR #4852 what is not merged yet. So i've included a whole code from previous PR here. And this PR can be merged instead of previous PR #4852. Or i'll just update this pull request after previous will be merged (i've non-sqashed commits and it will be easy)

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Looking very good @blackwarthog
I've started to test but short of one problem I ran into that has absolutely nothing to do with Assistants I haven't found any issues thus far.

Vector levels really allow Assistants to shine.  :)

Thanks also for the fix to allow us to see the guides in Animate Mode and other places.   So good!

Also, I hadn't realized that the direct drawing of motion paths works with Assistant guides... and it works really well.
I'll share more information/feedback as I find time.

**Comment by konero** [comment]
I'd rather the other PR get merged, so we can see what changed in this one specifically for vector levels, or split the commit. Just need a little patience.

**Comment by RodneyBaker** [comment]
Agree with @konero's assessment of keeping the PRs for each level type separate.
I will merge the Toonz Raster Assistants PR and the focus can then shift to this PR.

**Comment by blackwarthog** [comment]
Ok. I've splitted this PR by two commits for now.

**Comment by blackwarthog** [comment]
I've updated PR to solve collisions with previously merged one

**Comment by blackwarthog** [comment]
I've fixed some warnings in tgeometry.h what flooded the appveyor log and possibly crashes the appveyor

**Comment by RodneyBaker** [comment]
@blackwarthog (and others testing)

As I have time to do some testing I'm looking toward merger of this PR and plan to dive in as deeply as possible to spot anything we've overlooked thus far.

If there are compeling reasons to delay please advise.

**Comment by RodneyBaker** [comment]
Pressing forward with this next stage of Assistants.
Thank you @blackwarthog for vector Assistants to Opentoonz users.
LGTM

**Comment by blackwarthog** [comment]
thanks

**Comment by RodneyBaker** [comment]
Jitter with vector...

image

**Pull request merged**
