### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
`std::max_element`: http://ideone.com/SQV86b

**Comment by skitaoka** [comment]
Jenkins, test this.

**Comment by ideasman42** [comment]
These could be separate PR's, also would be good to use less vague title.

**Comment by skitaoka** [comment]
I'm merging this, because there are no problems to implement functions; however I also prefer that single PR contains modifications for single issue.

**Pull request merged**
