### PR TITLE
Cmake should be able to be run in other directories

### PR DESCRIPTION
**Pull request by kogaki**
Removed path dependency from cmake. This enabled me to build OpenToonz easily on my IDE(CLion)

### CODE REVIEW

**Comment by kogaki** [comment]
Jenkins

**Comment by ideasman42** [comment]
Why not use `${CMAKE_SOURCE_DIR}/../install/SystemVar.ini`?

`CMAKE_SOURCE_DIR` is typically used for the root-source dir.

**Comment by kogaki** [comment]
Right, thanks.

**Comment by kogaki** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins

**Pull request merged**
