### PR TITLE
SelectTool minor code improvements

### PR DESCRIPTION
**Pull request by caryoscelus**
Just a few minor improvements i did while working on https://github.com/opentoonz/opentoonz/issues/2920

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by caryoscelus** [comment]
@shun-iwasawa ?

**Comment by Agnyy** [comment]
When will it be taken? It will be good if quickly. So that we can do everything faster.

**Comment by RodneyBaker** [comment]
@Agnyy You can use this now.

If you are familiar with how to make any (windows) release a portable this can easily be done with the following:

[Link to appveyor build](https://ci.appveyor.com/api/buildjobs/y7p4f64l04jpmc7m/artifacts/toonz%2Fx64%2FOpenToonz.zip)

The Opentoonz.exe will work fine 'as is' but will work better in most cases if making it a 'portable'.
Let me know if you need me to walk you through the process.

**Comment by jpturcotte** [comment]
@caryoscelus "Jenkins" is used to trigger a special CI build.

**Comment by shun-iwasawa** [comment]
@caryoscelus 
Sorry for confusing you. As @jpturcotte pointed it was a chant to trigger Jenkins CI.
I'll add your name to the whitelist so that CI will start automatically on posting PRs in the future.

**Comment by shun-iwasawa** [comment]
LGTM Thank you @caryoscelus for the improvement!

**Pull request merged**
