### PR TITLE
Function Editor Display Options

### PR DESCRIPTION
**Pull request by turtletooth**
This allows the function editor to have two additional view options.

Right now the spreadsheet is the default view and the graph opens in a popup.
This adds the ability to make the graph the default view and the spreadsheet open in a popup. 
It also adds the ability to toggle between the graph and spreadsheet without any popup.

If you have the toggle option selected, it will remember the state between sessions.

### CODE REVIEW

**Comment by bobbybutterfly** [comment]
@turtletooth very cool! Thanks a lot!

**Comment by Orphanlast** [comment]
Looks cool

**Comment by gab3d** [comment]
wow!
clap clap clap

**Comment by artisteacher** [comment]
I'm looking forward to the toggle without any popup. At least in OS X, the curves pop-up ends up behind the program window after clicking elsewhere in the program.

**Comment by bobbybutterfly** [comment]
@artisteacher same issue here: on the 1.2 Version (not OTX) window disappeares behind the main progam window randomly

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
@shun-iwasawa Is this ready to go?

**Comment by shun-iwasawa** [comment]
LGTM Thank you @turtletooth for adding this!

**Comment by blurymind** [comment]
thank you @turtletooth 
This makes the graph editor a little bit more user friendly

**Comment by bobbybutterfly** [comment]
Thank you, i installed the latest build but cant find the Funktion Editor options in the preferences/ interface

**Comment by RodneyBaker** [comment]
@bobbybutterfly 
Once the new nightly with this merge finds its way to the release page you'll be able to find the settings for this feature halfway down this items on the page.
While I see the others operating systems listed the windows executable for this one hasn't posted as of this moment.  That was 2 hours ago ofas of this writing and you've posted about 6 minutes ago according to your post.  Give it a little time and it'll be there.

**Comment by shun-iwasawa** [comment]
@bobbybutterfly @RodneyBaker 
Thank you for your notification. This time I found that Jen.kins CI failed to deploy the nightly build.
I cleared the cache and ran the build again. Please try again after a while.

**Comment by bobbybutterfly** [comment]
Great! Thank you:)

**Comment by gab3d** [comment]
I miss a fourth option in the Preferences panel for the function editor:
1. Graph Editor Opens in Popup
2. Spreadsheet Opens in Popup
3. Toggle between Graph editor and Spreadsheet (i.e. Graph Editor as default)
4. Toggle between Spreadsheet and Graph editor (i.e. Spreadsheet as default)


or perhaps this could be split into two options.
- Function Editor Default View: 
     Spreadsheet
     Graph Editor
- Function Editor Open Views:
     Popup
     Toggle / Switch?

...either one would do, altough the latter seems more clean to me.

**Comment by jpturcotte** [comment]
This PR has already been merged. You would be better posting this on the forums.

**Comment by turtletooth** [comment]
@gab3d I don't think this needs to be done since it will remember the view you last used when you restart OpenToonz.

**Comment by gab3d** [comment]
@turtletooth
that seems fine to me.
thanks!

**Pull request merged**
