### PR TITLE
Spanish UI - updated strings, now on par with Japanese ones.

### PR DESCRIPTION
**Pull request by gab3d**
I've used lupdate to update Spanish strings from Japanese ones.
I hope all went well. :)

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
LGTM Thank you @gab3d !

It seems that you are working on `master` branch. It would better to checkout your working branch from the current master before you start a new translation work in order to cleanup the history.

**Comment by shun-iwasawa** [comment]
I'll ignore Travis's timeout and skip Jen.kins since it is only translation update.

**Comment by gab3d** [comment]
@shun-iwasawa 
I'm sorry for that. I've noticed that too (but didn't know how to do it differently)
Fact is I'm new to GIT and I really don't know what I'm doing :)

Could you please give me a hint on how should I do that "checkout"? (I'm using Tortoise GIT on Windows)
Thanks!

**Comment by shun-iwasawa** [comment]
@gab3d Sorry I'm not using Tortoise GIT, [here](https://github.com/opentoonz/opentoonz/blob/master/CONTRIBUTING.md) is a description how-to on command line console (Git bash). 

Here is a workflow for you;

## Preparation (to be done once for the first time)



1. `fork` OpenToonz to your GitHub account from `opentoonz/opentoonz`.

   - click the `fork` button at the top-right corner of https://github.com/opentoonz/opentoonz

1. `clone` the repository.

   - Launch Git Bash.
   - Move to the folder you would like to make your local repository.
     `$ cd C:path/to/the/parent/folder`
   - Clone
     `$ git clone https://github.com/gab3d/opentoonz.git`
     The folder `opentoonz` will be created under the current folder.
   - Move into opentoonz local repositry
     `$ cd opentoonz`
   - Set the `upstream` , in order to synchronize your repository with the latest version.
     `$ git remote add upstream https://github.com/opentoonz/opentoonz.git`

## Workflow (to be done each time you modify the code)



First , launch Git Bash and move to `opentoonz` folder using `cd` command

1. Synchronize the local repository with the latest code from `upstream` 
    - Change the current branch to `master`
      `$ git checkout master`
    - Obtain the latest code
      `$ git pull upstream master`
    - Synchronize your `origin` with the local repository
      `$ git push origin master`

1. Checkout the branch and modify the code
    - `$ git checkout -b your-branch-name`
       `your-branch-name` is a name of your modifications, say, `spanish_translation` or something.
    - Fix codes (for translation work, they will be .ts and associated .qm files) , then test them.
    - `$ git status` can show a list of files you have modified
    - `$ gitk` can show details of modification

1. Commit
    - Do one of the followings:
      - `$ git status` to see the files you have modified.
         `$ git add path/to/file` for all the files you would like to register in the commit
         `$ git commit -m "some_good_commit_message"`
      - Use `-a` option to commit all the modified files
         `$ git commit -a -m "some_good_commit_message"`
    
1. Push your branch
    - `$ git push origin your-branch-name`
      Please note that I will omit the description about resolving conflicts as it will occur rarely in the translation files.

1. Make a pull request.

**Comment by gab3d** [comment]
@shun-iwasawa 
Thank you! that's very detailed!
I promise I'll study it carefully :)

**Pull request merged**
