### PR TITLE
New Spanish UI translation.

### PR DESCRIPTION
**Pull request by gab3d**
Hi there,

I'm starting a new Spanish translation for the UI.
As a test I've copied and reverted the whole Italian folder translations to a "suggested" status, and will start from there.
I've already translated 100% of two of the small files in there (tnzcore and tnztools).

I hope is all well and could continue with this.
If I made some mistake, please just let me know (I'm new to GIT and it's perfectly possible I've made something wrong).

Cheers!

p.s. I'm currently also the Spanish translator for Blender and Kdenlive.

### CODE REVIEW

**Comment by justinclift** [comment]
Cool, that should help spread this once the build issues are smoothed out. :smile:

**Comment by Xmoggo** [comment]
Hi Gab3d. I'd like to collaborate in the translation, but I've no idea how to edit the files (I'm new in GIT too).

**Comment by justinclift** [comment]
@Xmoggo This might be helpful: https://github.com/opentoonz/opentoonz/issues/76

**Comment by EIREXE** [comment]
Have my translation of colorfx.
[colorfx.zip](https://github.com/opentoonz/opentoonz/files/191819/colorfx.zip)

**Comment by 3Rton** [comment]
oh cool I could contribute like this too although I can't code. Then again I wonder how big need there is for Finnish translation..

**Comment by justinclift** [comment]
@3Rton It all helps.  It's also good for marketing/advocacy purposes around the project.  eg "OpenToonz has been translated into x number of languages".  The higher x is for things like that, the better. :grin:

**Comment by gab3d** [comment]
@EIREXE Welcome and thanks!
Got it and merged it. :)

Please be sure to:
- maintain leading/trailing spaces in strings, where original string does so.
- maintain leading lowercase letter in strings, where original string does so.
- leave untranslated/unsure strings in "question mark" state.
- use Spanish accents and leading question/exclamation marks where you should.
- use uppercase letters only in the first letter of each string (except when a word refers to the name of something).

Cheers!

**Comment by gab3d** [comment]
Hi @roentgen 
Please, if you have a moment review this request (it represents about 30% of the translation of all the application's UI into Spanish).
If everything is OK I'll tackle the "toonz.ts" file, to complete the rest of the translation.
(I just want to make sure all is well and welcome, before commiting myself to do the bigger part of the job.)

Thanks!!

**Comment by roentgen** [comment]
Hi @gab3d,
Thank you for your attention,

It's a big work.
I made sure that there are no reason we deny the fix.
We will thank your help.

Best,

**Comment by gab3d** [comment]
@roentgen 
great! :)
I'll go for it...

Best,

**Comment by kogaki** [comment]
Can one of the admins verify this patch?

**Comment by kogaki** [comment]
Can one of the admins verify this patch?

**Comment by kogaki** [comment]
we merged #171 and now it works. You can use spanish translated interface with `nightly build`. Thanks for your big work.

**Comment by gab3d** [comment]
Thank you!
I´m still working on it.
But will soon be complete. :)

Now it can be tested, which is great!!

**Comment by justinclift** [comment]
@kogaki Hmmm, the location for people to grab the nightly builds isn't on the README.md.  Want to add it? :smile:

**Comment by kogaki** [comment]
I put a pointer to nightly build on the README ( #208 ). Thanks.

**Pull request closed without merging**
