### PR TITLE
Fix customize commands tree structure

### LINKED ISSUE #2857: Shortcut/command bar configuration windows based on old menu organization
### Issue Summary

It's a little confusing using the old menu structure to organize commands in both the "Configure Shortcuts" window and in the "Customize Xsheet Toolbar" window.
### Screenshot or Video Reference

Screen Shot 2019-10-24 at 5 55 46 PM
Screen Shot 2019-10-24 at 5 57 04 PM
Screen Shot 2019-10-24 at 6 03 41 PM

### Expected Results

The command organization to be the same as the current menu.
### Actual Results

The command organization is still based on the old menu. At least when configuring shortcuts, there is a search option to easily find what you are looking for. The command bar customization relies completely on knowing where to find the different commands - that's difficult when the menu doesn't match.
### System Information
* **OpenToonz Version**: 
* **Operating System**: 
* **CPU**: 
* **Memory**: 
* **Graphics Card**: 
* **Graphics Tablet**:

### PR DESCRIPTION
**Pull request by manongjohn**
This PR fixes #2857 

This updates the command tree lists by updating the assigned group for commands that were rearranged by #2545 to where they are currently in the default menu layout.

This affects the following dialog boxes
- Customize Menu Bar of Room
- Customize Xsheet Toolbar
- Configure Shortcuts

In addition to this, the entries in Customize Menu Bar of Room and Customize Xsheet Toolbar are now being sorted alphabetically like it is in Configure Shortcuts.

### CODE REVIEW

**Comment by gab3d** [comment]
@manongjohn 
is this alphabetical order based on the original English strings, or it takes into account translated strings also?

**Comment by manongjohn** [comment]
I'm not sure? I would assume it is based on translated strings. I believe the translation are applied before the tree is populated. Sorting occurs after the tree is populated.

Currently the Configure Shortcuts tree is ordered alphabetically, so however that is sorting now is how it will look in the other 2.

**Comment by gab3d** [comment]
@manongjohn 
Thanks. Currently in the Shortcuts Editor the list appears ordered by the translated strings, so I'll assume it'll be that way in the menus too.

**Comment by RodneyBaker** [comment]
LGTM
Thanks @manongjohn!

**Comment by artisteacher** [comment]
Thanks @manongjohn for such a fast fix!

**Pull request merged**
