### PR TITLE
Fix Tool Option Checkbox

### LINKED ISSUE #1562: Tool Option Checkbox Does not Work
For now, clicking any of the check box in the Tool Options does not work.
It seems to be because of my previous PR related to the tool options shortcut.
Sorry for the trouble. I'll fix it right away.

### PR DESCRIPTION
**Pull request by shun-iwasawa**
Fixes #1562

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
Confirmed the fix.  Sorry for not catching that.  I will be asleep before Jenkins finishes- but this is ready to merge.

**Comment by shun-iwasawa** [comment]
Thank you @turtletooth for confirmation.
I think we must not wait for the Travis-OSX in this case since the OSX build is already succeeded with Jen.kins. 
@masafumi-inoue can you please merge this?

**Comment by turtletooth** [comment]
I got it.  Thanks!

**Pull request merged**
