### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by SaeedSS3**
Created CODE_OF_CONDUCT.md. This includes an adoption of the Contributor Covenant

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Welcome to the Opentoonz Community @SaeedSS3 
At this time we do not plan to add a code of conduct but this is a great place to discuss what one would/should look like.

In the meantime we do have the following documents that relate to general community guidance, licensing and code contributions:
- https://github.com/opentoonz/opentoonz/blob/master/README.md
- https://github.com/opentoonz/opentoonz/blob/master/CONTRIBUTING.md
- https://github.com/opentoonz/opentoonz/blob/master/LICENSE.txt

**Comment by SaeedSS3** [comment]
> Welcome to the Opentoonz Community @SaeedSS3 At this time we do not plan to add a code of conduct but this is a great place to discuss what one would/should look like.
> 
> In the meantime we do have the following documents that relate to general community guidance, licensing and code contributions:
> 
>     * https://github.com/opentoonz/opentoonz/blob/master/README.md
> 
>     * https://github.com/opentoonz/opentoonz/blob/master/CONTRIBUTING.md
> 
>     * https://github.com/opentoonz/opentoonz/blob/master/LICENSE.txt

Hi Rodney,

Thank you for those links. I went through them before submitting a code of conduct file. Is the only method of communication the Google Groups forums? I was thinking that maybe a Discord server would be a better way to have discussions about this sort of thing. However, I understand if there is no appetite for it.

**Comment by JPUser1** [comment]
@SaeedSS3 why not add something to the repo of value before making a set of rules? especially considering we have never encountered these kind of problems here before. Just my 2cents?

**Comment by SaeedSS3** [comment]
> @SaeedSS3 why not add something to the repo of value before making a set of rules? especially considering we have never encountered these kind of problems here before. Just my 2cents?

Hi JP,

Thaks for the question. And it is a fair question. The Contributor Covenant is well known and has been adopted by over a hundred thousand open source communities and projects. The reason I am proposing that we adopt it is because I did not see any comprehensive code of conduct document in the repo.

However, I concede that I should have discussed it with others in the Google Groups forum before trying to add it. In any case, it will be up to the community if they would like to adopt it. 

Thanks

**Comment by JPUser1** [comment]
Fair enough. Also u can find an OpenToonz discord here its not official but you'll find many OT community users and contributors.  https://discord.gg/Kpm7NPaa

**Comment by SaeedSS3** [comment]
> Complete cancer, include at your own peril.

This was used to fulfill an assignment requirement...nearly 6 months ago.

**Comment by RodneyBaker** [comment]
Feedback is a wonderful thing.
Thanks for closing the loop on this one.

**Comment by SaeedSS3** [comment]
> Feedback is a wonderful thing. Thanks for closing the loop on this one.

Not a problem! This totally slipped my mind, sorry for having it open for so long.

**Pull request closed without merging**
