### PR TITLE
Auto Input Cell Number command

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This implements #783 , which is almost the same feature available in Retas and QuickChecker.
From the specification described in #783, I've changed in the following two points:

- "Level frame intervals" is changed to "Level frames increment". And behavior is as follows:

  - If the increment is set to 1, frames will be placed with no interval (1,2,3,4... , just like the interval is set to 0).
  - If the increment is set to 2, frames will be placed every other frame (1,3,5... , just like the interval is set to 1).
  - And, if the increment is set to 0, every existing frames in the level will automatically be picked and placed. (This is new and default value. The description can be found in the tool tip of the field)

- Enabled to select the placing behavior from "Insert" and "Replace".

As this command is available when cells or columns are selected, I added this command to the right-click menu of the xhseet cell area and column-head area, as well as to the "Cells" menu in the main menu bar.

image

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by gab3d** [comment]
@shun-iwasawa, at least from my point of view, the words "frame" in the dialog from above should be better placed to the left of the number fields:
  From frame 0001
  To frame 0006

...at least in Spanish (and I think English too) it makes more sense.

**Comment by shun-iwasawa** [comment]
Text fixed. Thanks @gab3d .

image

Jenkins again

**Comment by masafumi-inoue** [comment]
LGTM

**Pull request merged**
