### PR TITLE
Remove license and edition defines and code

### PR DESCRIPTION
**Pull request by ss23**
Previously, old code to support various editions of Toonz, as well as license activation code, was cluttering the repository.

I'm not in a good position to determine whether this way of doing it is correct. While most of the code seems to *exclude* features based on the edition, there are a few places with different/new code relevant to only a specific version.
That being said, given these features are already disabled in the current opentoonz release, it won't be missed.

I've checked compilation and running on Windows only.

### CODE REVIEW

**Comment by kogaki** [comment]
Can one of the admins verify this patch?

**Comment by skitaoka** [comment]
Jenkins

**Comment by kogaki** [comment]
Of course, activation is completely useless feature. Thank you for your work.
But I feel it is too early to remove some features of `Linetest`. 
They might be bundled into OpenToonz in the future. 
How about reverting some changes and keep codes for `Linetest` ?

**Comment by blurymind** [comment]
I agree with @kogaki - disabled features that have value to the workflow should be kept.
Only software licensing features should be removed.

**Comment by ss23** [comment]
I'll make the change to include `Linetest` this week :)

**Comment by kogaki** [comment]
Can one of the admins verify this patch?

**Comment by ss23** [comment]
@kogaki I've gone through and made sure the LINETEST support is there again. There are a few places where it seems LINETEST had features specifically removed, so I've left them enabled.
Is this okay like this, or did you want me to ensure 100% compatibility with how it used to be?

**Comment by kogaki** [comment]
Thanks. I think it is OK if key features are preserved. I will test your PR.

**Comment by kogaki** [comment]
Jenkins

**Comment by kogaki** [comment]
This commit was merged with #291 . Thanks a lot, @ss23 !

**Pull request closed without merging**
