### PR TITLE
Fix source typos

### PR DESCRIPTION
**Pull request by luzpaz**
Follow-up to #4000 but with possible breaking API changes

### CODE REVIEW

**Comment by RodneyBaker** [comment]
I haven't had time to look deeper but the failed checks pointed to the possibility of errors in Ninja (for Linux) and... perhaps... something related to the render farm (tfarmserver).  That may be a false flag though.   I'm not sure why the ;ast commit would be failing (Misc. typos) as that seems to be a pretty simple typo update.

**Comment by shun-iwasawa** [comment]
The error message is as follows:

```
/Users/runner/work/opentoonz/opentoonz/toonz/sources/toonz/toolbar.cpp:181:44: error: no member named 'collapsable' in '(anonymous namespace)::(anonymous struct at /Users/runner/work/opentoonz/opentoonz/toonz/sources/toonz/toolbar.cpp:35:1)'; did you mean 'collapsible'?
    if (!m_isExpanded && buttonLayout[idx].collapsable) continue;
                                           ^~~~~~~~~~~
                                           collapsible
/Users/runner/work/opentoonz/opentoonz/toonz/sources/toonz/toolbar.cpp:37:8: note: 'collapsible' declared here
  bool collapsible;
       ^
```

**Comment by luzpaz** [comment]
Shall i revert 260776b ?

**Comment by luzpaz** [comment]
please advise

**Comment by luzpaz** [comment]
Updated in fa906ebf4e40eb5f015e617b2cba330ea023bb7c  
No more results for `collapsable`in the source source AFAICT

**Comment by RodneyBaker** [comment]
Thanks @luzpaz That seems to have done it.
While waiting for the Mac and appveyor checks to finish I've been testing the Windows build.
So far so good.  :)

**Comment by RodneyBaker** [comment]
Thank you @luzpaz for the typo fixes.
LGTM

**Pull request merged**
