### PR TITLE
Initialization Wizard and 3rd party interface adjustments

### LINKED ISSUE #3911: Reset to Default Rooms Command: Inform User
**Is your feature request related to a problem? Please describe**
Seems some users don't realize you need to restart the program for the command to take effect.

Command: `Windows > Workspace > Reset to Default Rooms`

**Describe the solution you'd like**
Have a popup message displayed after clicking telling the user the action will take effect next time OpenToonz is launched.

### LINKED ISSUE #4384: Crash when loading MP4/GIF into default Cleanup or Schematic room
Attempting to load an MP4 or GIF file into Opentoonz while in either the default Cleanup or Schematic room results in a crash.  Other rooms do not result in a crash.  I tested this in a fresh install of Opentoonz with default settings.

**To Reproduce**
1.  Go to the Cleanup or Schematic room
2.  Load an MP4 or GIF file either by dragging it into the program or through Load Level
3.  Opentoonz hangs, some panels go blank, and crashes

**Expected behavior**
Loading in any room without crashing

**Screenshots**
image

https://user-images.githubusercontent.com/60277069/160992205-1914bef2-abab-40f6-9524-94132633281e.mp4

Device Information:

    OS: Windows 10 Pro 64-bit
    OpenToonz Version: 1.6 Nightly build 2022-03-31 05:36:38 UTC
    CPU: AMD Ryzen Threadripper 2990WX 32-Core Processor
    GPU: NVIDIA GeForce RTX 3070 Ti
    Graphics Tablet: Wacom Cintiq Pro 24

### LINKED ISSUE #4537: 'Reset to Default Rooms' doesn't update rooms tabs without restart
### Description

When hitting Windows --> Workspace --> Reset to Default Rooms nothing visually happens. The same custom room tabs stay active and seem to even still work. No warning to restart or whatsoever.

Only after a restart of OpenToonz the default rooms tabs are shown instead of the custom setup.

This is obviously confusing as it seems like something went wrong and nothing happened. And is prone to errors as the visual state isn't matching the actual state?

### Steps to Reproduce

1. Change rooms tabs
2. Windows --> Workspace --> Reset to Default Rooms
3. See that the changed room tabs layout is still active. Nothing visually changed
4. Restart OpenToonz
5. Suddenly now there the default tabs are

### Expected Behavior

Immediately update the rooms in the GUI after resetting to default.

### Screenshots, Video & Crash Logs

_No response_

### OpenToonz Version

1.6

### OpenToonz Version Information

built Apr 4 2022 10:30:14

### Operating System

Windows

### GPU

NVIDIA

### Graphics Tablet

Wacom

### PR DESCRIPTION
**Pull request by justburner**
This PR helps users (specially for newcomers) to setup OpenToonz after an install, it will setup:
- Language - note this PR doesn't update the Qt language files! Once they are updated the wizard will change text on the fly.
- 3rd party locations - it also show the user where to download them.
- Rooms and Theme - includes a tiny preview, dark icon is set automatically.
- Project locations - now is easier to setup multiple custom folders too!

       

Also it adds `thirdparty.cpp` to handle locations and launch of all 3rd party, if those are sub-directories in OpenToonz folder then those will be non-absolute paths to allow OT to be fully portable.
Additionally it will auto-detect the following paths: `./ffmpeg`,  `./ffmpeg/bin`, `./FFmpeg`, `./FFmpeg/bin`, `./rhubarb`, `./rhubarb/bin` and `./Rhubarb-Lip-Sync` inside OT folder (Auto detect happens when Wizard launches).

Once the Wizard is finished, it will never run again and will launch OT as normal from now on, to re-run again, check the box `[ ] Run Initialization Wizard Next Launch*` under `Preferences... > General` and restart OT.

`Preferences...` remains unchanged despite the enhancements of the settings in the wizard. (Another PR can address this if those get requested)

Last but not least, importing MP4s or similar FFmpeg formats will not be asynchronous anymore, this fixes #4384 but that also means OpenToonz will be fully frozen and unresponsive until all frames are imported... exports are unaffected and remains async.

Forgot to mention but this also warn the user when pressing "Reset All Rooms" or "Reset to Default Rooms" in OT: Resolves #3911, resolves #4537

### CODE REVIEW

**Comment by openanim** [comment]
_"Rooms and Theme - includes a tiny preview, dark icon is set automatically."_

I have a question about this. Will it still be possible to choose the neutral theme with white icons, as it is now ? I mean like this :
neutral_theme_white_icons

**Comment by justburner** [comment]
@openanim Thanks for your feedback, now you can select which icon shade to use:

InitWiz3new

<hr />

Additionally I've added a button to reset rooms.

Resetting rooms now ask user confirmation, (both in wizard and in OpenToonz), because when I tried that feature I've got really confused because nothing happened but weird stuff started to happen when i shuffled rooms and other things, only after a restart the rooms were back to default.

**Comment by openanim** [comment]
Thank you so much for this !

**Comment by openanim** [comment]
@justburner 

I don't know if this is normal but when testing the appveyor I couldn't load the rooms and themes. I don't know if it's related to the fact that it's via the appveyor.

https://user-images.githubusercontent.com/29790512/184553885-32af6261-500d-4266-9c36-96e53c89375f.mp4

It also seems that it is impossible to change the room via this appveyor. It is the Ghibli rooms that are the default. Even if you reset the rooms and restart. And in the preferences, there is no access to the themes (the little triangle is not accessible for the themes) and to the rooms either.

https://user-images.githubusercontent.com/29790512/184553921-0908a2f7-480d-40af-9a49-0e356b084da7.mp4

(Question) Not directly related to this PR, but since some people often mention the rooms of previous versions (like basics) why not give access to the rooms of previous versions alongside the ghibli configuration and default of the current version.

**Comment by justburner** [comment]
In the Appveyor the Stuff directory is on the root of the zip as `OpenToonz stuff`... you have to put it inside the OpenToonz folder and rename it as `portablestuff` so OT runs as portable.

I'm surprised OT loaded without any stuff directory, i've expected several errors or a crash o_O

Hmm, maybe I should detect in the wizard if a stuff folder exist and throw an error if it doesn't... 🤔 

> (Question) Not directly related to this PR, but since some people often mention the rooms of previous versions (like basics) why not give access to the rooms of previous versions alongside the ghibli configuration and default of the current version.

Unless you click "Reset Rooms" your user rooms from previous versions will remain there (assuming your using the Stuff directory from previous versions).

As for certain rooms that got deleted like "Basics"... hmm... i guess maybe we can create another group for beginners? Or specialized rooms? Or maybe even import presets of rooms like in Blender, that could be something to think in another PR.

Ghibli rooms aren't useful for the common OT users, in fact it has several features missing.

**Comment by RodneyBaker** [comment]
It is my understanding that if OT does not see a portablestuff directory it uses the default (for Windows) at C:\Opentoonz stuff.   If that is not present then we should get the message about reinstalling to resolve the problem.

**Comment by openanim** [comment]
> In the Appveyor the Stuff directory is on the root of the zip as OpenToonz stuff... you have to put it inside the OpenToonz folder and rename it as portablestuff so OT runs as portable.

Ahh thank you, that's why the reset rooms didn't work before but with portablestuff everything i tested works fine. 👍 

> Or maybe even import presets of rooms like in Blender, that could be something to think in another PR.

Yes I was thinking of something like that, what I meant was that maybe giving access to the previous room configurations to those who are used to it something like that. 

Sans titre

Eventually other types of configurations can be made more specialized but I was just thinking about the rooms of the previous versions because as you said, few new people use the Ghibli rooms. But certainly a discussion for another PR.

**Comment by justburner** [comment]
I've addressed the issue of finding the stuff folder, it even do a very tiny validation to see if the folder is okay. 😅 

> Yes I was thinking of something like that, what I meant was that maybe giving access to the previous room configurations to those who are used to it something like that.

There's been no default rooms changes on the few last versions, doubt it will be in the future.

The only problem now is the issue of the new menu entries not showing up in already existing rooms but that's a problem that will be tackled in the future.

**Comment by RodneyBaker** [comment]
I'm a little concerned about translations for the Initialization Wizard.
Does anyone have any thoughts on that aspect?

**Comment by justburner** [comment]
> I'm a little concerned about translations for the Initialization Wizard.
> Does anyone have any thoughts on that aspect?

I'm curious too... personally i think this should be addressed before the merge since changing the language has no visual effect due to the missing translation entries and people might think that is a bug.

Anyway I'm not the right person to update the language files.

**Comment by openanim** [comment]
I confirm that with the latest changes it works for me without turning it into a portable version. Thank you.

**Comment by gab3d** [comment]
@justburner 
sorry I come late to the party.
great job! thanks! 👍 

> I'm a little concerned about translations for the Initialization Wizard.
> Does anyone have any thoughts on that aspect?

How's that translations being handled?

Also, is this affecting the whole installer? I mean, currently the installer only supported a few languages and I've been wanting to translate it into Spanish for ages.

**Comment by RodneyBaker** [comment]
> How's that translations being handled?

Currently it isn't being handled.  Hence my concern.  :)

The intializer isn't related to the installer... other than it performs functions that can be done via various installers.  The regular (Windows) installer is created via Inno Setup whereas this initializer is created via Qt tools.

**Comment by gab3d** [comment]
Thank you @RodneyBaker 
I have absolutely not problem in translating the wizard. 
What seems to not be defined there yet, though, is a way to select the language of the wizard.

Regarding Innosetup, what would it take, then, to be able to offer a Spanish instalation in OT, and in such case where could I find the needed texts for translating them? 🤔

**Comment by RodneyBaker** [comment]
The Windows Inno Setup installer for Opentoonz has its on repository located here:

https://github.com/opentoonz/opentoonz_installer_windows

**Comment by artisteacher** [comment]
This is a helpful addition!

The button alignment/padding is off on macOS Monterey.
Screen Shot 2022-08-29 at 10 23 24 PM
Screen Shot 2022-08-29 at 10 25 24 PM

I tried to select an external rhubarb installation but it wouldn't select for some reason. Browsing could get to the parent directory. However the only option is to open or cancel. Opening doesn't let me select the rhubarb executable.
Screen Shot 2022-08-29 at 10 34 49 PM

**Comment by justburner** [comment]
> I tried to select an external rhubarb installation but it wouldn't select for some reason. Browsing could get to the parent directory. However the only option is to open or cancel. Opening doesn't let me select the rhubarb executable. Screen Shot 2022-08-29 at 10 34 49 PM

That's very odd. Does the same apply to FFmpeg? What attributes rhubarb executable have for Mac to make it non-selectable as opposed to other files? 🤔

**Comment by RodneyBaker** [comment]
I want to ask the question...

Given that we are (approximately) half way to the v1.7 rekeasem, should we proceed with merging this PR and allow the translations to catch up later?  I ask primarily because the initialization wizard does appear to be a useful and appropriate addition to Opentoonz and until the full release only those using the nightly release will encounter it.

It would be good to know what the consensus is on pressing forward, delaying or setting the initialization wizard aside for the present.  

If not moving forward (and merging) what specifically needs to be addressed to allow the feature to move forward?

Thanks in advance for any and all feedback.

**Comment by konero** [comment]
> [...] should we proceed with merging this PR and allow the translations to catch up later? [...] It would be good to know what the consensus is on pressing forward, delaying or setting the initialization wizard aside for the present. [...] If not moving forward (and merging) what specifically needs to be addressed to allow the feature to move forward?

There are outstanding issues noted within the PR already, is it confirmed they are fixed?

**Comment by RodneyBaker** [comment]
@konero No, sorry I wasn't clear.  the question I was asking is only relates to the issue of translation.
This PR should not go forward until other primary issues have been resolved.

It was my understanding that we would not be pushing this forward until such a time as those translation issues could be addressed and I want to gauge whether or not user (presumbably of other languages than english) can accept the intialization wizard being in Englsh in the nightlies until such a time as that gets adressed.

Thanks for that feedback.
It's important to confirm any y outstanding issues prior to merging this PR.

Aside:  I do think that once the Initialization Wizard is part of the program others will want to update it with additional options (as they see the need) but that of course would be in other PRs.

**Comment by RodneyBaker** [comment]
@gab3d 
Did you discover anything more related to translation for the Initiallzation Wizard?

**Comment by RodneyBaker** [comment]
In addition to tranlation issues I will recommend additional research be conducted to see how the initialization wizard can be further leveraged... even customized... by users to meet specific needs of installation and configuration of Opentoonz.

Some of this likely just needs a path to decision making such as how best to update and manage the installation wizard.
Also, best approaches to maintain and add new wizardly processes.  For example, to address those feature requests currently open that can best be resolved via this initialization wizard.  I will try to add those reports to this discussion but generally speaking they could include:

- Ability to create a portable version of the program currently being installed
- Ability to archive current stuff directory and create a clean installation
- Others thing not currently itemized

Many of these areas relate more to the current installer which is not cross platform (using Innosetup for Windows).

@justburner Regarding the following:

> Last but not least, importing MP4s or similar FFmpeg formats will not be asynchronous anymore, this fixes https://github.com/opentoonz/opentoonz/issues/4384 but that also means OpenToonz will be fully frozen and unresponsive until all frames are imported... exports are unaffected and remains async.
> 
> Forgot to mention but this also warn the user when pressing "Reset All Rooms" or "Reset to Default Rooms" in OT: Resolves https://github.com/opentoonz/opentoonz/issues/3911, resolves https://github.com/opentoonz/opentoonz/issues/4537
> 

I am curious about these changes and if they might be able to move forward separately from this Initialization Wizard PR.

**Comment by justburner** [comment]
I've decided to break up this PR into 2 parts:
A) 3rd party interfacing adjustments + miscellaneous extra fixes
B) The Initialization Wizard itself

This decision will allow to merge part A while we are still unsure about the future of part B.

> Ability to create a portable version of the program currently being installed
> Ability to archive current stuff directory and create a clean installation (with or without a copy of current OT program included as a portable)

Both best left for the installer.

> I am curious about these changes and if they might be able to move forward separately from this Initialization Wizard PR.

Yes, this is why I'm separating this PR, there's no point to delay those bug-fixes because of the Init Wizard itself.

**Comment by RodneyBaker** [comment]
Thanks @justburner, I think yours is a good decision and the best possible approach to seeing all of .your effort/code move forward.

While the Initialization Wizard is experiencing a delay it's a good idea and I'm confident the extra time will be well worth the wait.  

I do hope other developers/users and those with interest will consider testing the Initializaton Wizard and provide feedback as that is vital at this early stage.  Perhaps that feedback will start to flow after the separate PRs are created.

Your thoughtful consideration is appreciated!

**Pull request closed without merging**
