### PR TITLE
WIP: Fix for Shaders and Switch to QOpenGL

### PR DESCRIPTION
**Pull request by turtletooth**
This is still pretty buggy, but shaders don't instantly crash OT anymore.  It works, but throws a lot of assert errors.

shaders

@shun-iwasawa I have no experience doing OpenGL programming and would love some help.

### CODE REVIEW

**Comment by turtletooth** [comment]
So here's the limit of what I can find:

I keep getting a "cannot send events to objects owned by a different thread" error around lines that contain:
```
m_imp->m_context->create();
m_imp->m_context->makeCurrent(m_imp->m_surface);
```
Ignoring this doesn't crash the program.  I have tried a variety of fixes but my limited knowledge of threading and/or opengl isn't able to fix the problem.

There is also a problem in the destructor if sceneviewer when trying to clear out l_proxy and l_contexts.

I am going to stop here and hope someone is able/willing to pick up the pieces since I seem to be at a dead end.

**Comment by turtletooth** [comment]
@blackwarthog - would you have any time to take a look at this?  Having usable shaders is so close, but I can't figure out the last bit.

**Comment by blackwarthog** [comment]
At my system I've seen only warnings about wrong thread of context.

Seems you was at the right way, i just removed two other MACOSX preprocessor condiditions to call moveToThread in ShadingContext destructor and in ShadingContext::doneCurrent too:

https://github.com/blackwarthog/opentoonz/commit/1213cfb37b6e7e730f828befbd443de9860aa119

And I've no more warnings about context thread. I've checked it linux, please, tell me how it works at windows.

Also at windows and linux uses OpenGL 2.0 (by default) but for MacOS uses version 3.2. If some shaders requires OpenGL 3, then we may to select OpenGL 3.2 for all platforms (in function ShadingContext::Imp::format()).

**Comment by turtletooth** [comment]
With the new changes I get an instant crash, no assert errors or anything.  It doesn't even trigger Visual Studio where it crashed.  It just goes down hard.

**Comment by blackwarthog** [comment]
ok, i'll try to check it on Windows.

**Comment by blackwarthog** [comment]
I cannot test MSVC build at PC with graphics accelerator. I've tested MinGW build and it works at Win7 64 and GeForce 9600GT. You may to download it from from here: https://dev.icystar.com/downloads/OpenToonz-1.1.3-morevna-2017.08.08-3ea6d-win-64bit.exe

**Comment by blackwarthog** [comment]
May be latest changes in master affects shaders behavior. You may try to do rebase to latest master.

**Comment by RodneyBaker** [comment]
@blackwarthog  This is off topic and I apologize for that.  I'm not sure where exactly to post this.

When installing the Morevna Project version of OT I always get a message that I have to uninstall the previous installation of OT, and I can't install without doing so.  This is problematic in several ways as you might imagine.  Can we get the Morevna build to install into another directory or in such a way as not to interfere with other installations of OT?  This largely prevents my use of the Morevna branded OT because I don't want to uninstall the official release (or for that matter any other install).

**Comment by turtletooth** [comment]
@blackwarthog I checked your build and it works on the first 6 shaders, but the blur ones cause an instant crash still.  I did a build rebased with master and added your changes and if I run a release build, it works, but if I run a debug build, shader preview instantly takes OT down.  I'm not sure why debug would be different than release.

Thanks for your help with this.  I really appreciate it.

**Comment by shun-iwasawa** [comment]
I still do not the way to fix the problem, but confirmed that this PR as-is will fix the issue #1081 (crash with full screen mode on OSX) .

**Comment by artisteacher** [comment]
If this could fix all the fullscreen crashing, including #1396, that would be so amazing!

**Comment by turtletooth** [comment]
Closing - Updated in #1517

**Pull request closed without merging**
