### PR TITLE
Improved convert command from non AA raster images to painted tlv

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for the issue #852 and is improving "Convert" command which can be triggered from the right-click menu of File Browser.

- Enabled to input palette when "Painted tlv from non AA source" option.
- Added an option to remove unused styles from input palette.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
@turtletooth 
Could you please review this?
Since this is very specific, here I uploading the sample files in order to try this feature:
[convert_sample.zip](https://github.com/opentoonz/opentoonz/files/550044/convert_sample.zip)

Please do the following:

1. There are three files in the package "convert_sample.zip":
     - colormodel_sample.tlv
     - colormodel_sample.tpl
     - level_sample.tga

1. The level "colormodel_sample" was converted from PNG to TLV and then organized palette. "level_sample.tga" is a sample of drawing data painted with PaintMan (Non-AA, TGA format). 

1.  In File Browser, right click "level_sample.tga" > click "Convert..." command.

1. In the Convert popup, do as follows;

     - Select "File Format" to "tlv"
     - Set "Mode" to "Painted tlv from non AA source"
     - Click "..." button next to the "Palette" field and specify the path to "colormodel_sample.tpl"
     - Ensure that "Remove Unused Styles from Input Palette" option is ON
     - Click "Convert" button.

1. After a while, "level_sample.tlv" will be generated.

1. Load "level_sample.tlv" and see the contents of the level palette.

Please note that the level palette are already organized, named according to the input palette.
Also please note that the unused styles in the level (in this example, green colors for clothes) are removed and a color found only in the level is added to the first page of the palette, as an "additional color".

convert

**Comment by turtletooth** [comment]
@shun-iwasawa I'm sorry I haven't looked at this yet.  I will try and get to this tonight or tomorrow.

**Comment by turtletooth** [comment]
@shun-iwasawa It looks like it works as expected.  I am totally unfamiliar with the workflow, so thank you for the detailed instructions on verifying it working.  

One think I noticed- when I clicked on the ... for the palette location, it stalled and finally popped up with the path set to my project/Create new palette.  It looks like a bug similar to the load level bug.  I think it can be a different PR, but it does seem to be a bug.

Do you want me to wait on merging this until the osx build is passing?

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you for checking the feature.
I modified `FileField` not to browse the initial path on first launch of the popup if the description text (=non file path, like "Create new palette") is input.
Jenkins

**Comment by turtletooth** [comment]
LGTM.  Thanks @shun-iwasawa

**Pull request merged**
