### PR TITLE
Fix crash on arrows using eraser

### PR DESCRIPTION
**Pull request by turtletooth**
#1209 

This takes care of arrow presses changing the frame, but doesn't take care of shortcuts for next frame, next drawing. . .

@shun-iwasawa Any idea how to get those shortcuts recognized in the eraser tool to block them?

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
When the current frame is switched, `EraserTool::onImageChanged()` will be called.
So, how about performing the erase-finishing process in such function just like I implemented in `EraserTool::onDeactivate()` , instead of blocking the frame switching operation?

**Comment by turtletooth** [comment]
It seems that by the time onImageChanged has been called, finishing is no longer available (the next image is the active image).  Thoughts?

**Comment by shun-iwasawa** [comment]
Sorry, you're right!
I remember that I once fixed the same problem in the raster eraser.
Please see [here](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/tnztools/rastererasertool.cpp#L1175-L1176),  I made the tool to remember the current working FrameId during the mouse dragging from `leftButtonDown()` to `leftButtonUp()`. How about doing the similar approach, holding the FrameId or pointer to the current working image (`TVectorImageP`) in the `EraserTool` class?

**Comment by turtletooth** [comment]
@shun-iwasawa What do you think of this?

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Thank you @turtletooth it works fine. LGTM

**Pull request merged**
