### PR TITLE
Issue #1125 Linux configfarmroot.txt path

### PR DESCRIPTION
**Pull request by damies13**
Issue #1125 Linux configfarmroot.txt path

### CODE REVIEW

**Comment by damies13** [comment]
This pull request resolves Issue #1125 for me.

Builds successful, which is good cause the were successful on my machines (Mac, Windows & Ubuntu) too.

I am closing this pull request for now, I have nothing else to add, i'll reopen if anyone wants further changes to this.

**Comment by konero** [comment]
Are you only closing because you're working off master? Have you tried working with branches?

https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Comment by damies13** [comment]
No I'm closing so I can merge the next branch into master, I have 2 more branches ready to merge but for clarity I think they are better as seperate pull request as they are for seperate issues.

**Comment by damies13** [comment]
I'm hoping these pull requests will get merged into main.

Unfortunately after Easter I will be working long ours in my job for a few months, so I am trying to submit as many useful contributions as I can before then.

Dave.

**Comment by turtletooth** [comment]
@damies13 Closing a pull request says that the request is no longer valid/relevant.  Any pull requests you want reviewed and merged should stay open.  Thanks for all the work you are doing around the farm stuff.

**Comment by damies13** [comment]
@turtletooth Thanks, I was wondering how the process worked, so should I be submitting all my changes in a single pull request then?

As you can see the pull request I just submitted (currently building) address a different issue to this one. I just cant see any way to submit seperate pull requests with out closing an open one.

I do notice however that all my changes from this pull request and the previous one appear in the next one.

I am not an animator, but I hope that my contributions can assist creative people produce animations more quickly, I do enjoy watching them :)

Dave.

**Comment by turtletooth** [comment]
Each issue should be its own PR.  Each PR should be a new branch based off of master.

To create a new branch you can use:
git branch -b name_of_branch

Then commit your changes and push them up with
git push origin name_of_branch

Then create a new PR for the issue.

To get back to master on your machine:
git checkout master

**Comment by damies13** [comment]
ah, I see so instead of merging the branch where I have been working into master on my fork (as I have been doing), I push the branch from my fork into the main repository.

I will have a look tonight and see if I can figure that out.

Thanks,

Dave.

**Comment by damies13** [comment]
@turtletooth, Big Thank You!!! I think I have it figured out now. I have 2 open pull requests, cause I had made a bit of a mess, It was easier to just send 1 PR with all the things I had previously send PR's for as It was going to take ages to split them back up again. 

I then I cleaned up my fork master restored it back to a clean copy of of the opentoonz master, and recreated my change for the new fix as a new branch and created a PR for it.

Again, thanks for your help.

Dave.

**Pull request closed without merging**
