### PR TITLE
Fix build issues for OpenToonz on Windows (CMake, header, yml ,bat and markdown updates)

### PR DESCRIPTION
**Pull request by Abel032**
Small Changes

### CODE REVIEW

**Comment by Abel-8** [comment]
Build successed
So Close

**Comment by Abel-8** [comment]
CMake Warning (dev) at CMakeLists.txt:557 (find_package):
  Policy CMP0167 is not set: The FindBoost module is removed.  Run "cmake
  --help-policy CMP0167" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

**Comment by Abel-8** [comment]
TODO:
- [ ] change to new behavior of find_package(Boost) for cmake upper or equal 3.30

**Comment by Abel-8** [comment]
TODO:
- [ ] Change to new behavior of find_package(Boost) for Cmake upper and equal 3.30

**Comment by Abel-8** [comment]
Ready for review

**Comment by Abel-8** [comment]
- Configuration Bat Getting Wrong 
https://github.com/Abel-8/opentoonz/issues/2

- [ ] Solve

**Comment by Abel-8** [comment]
### Ready For Review

**Comment by Abel-8** [comment]
no more commits

**Comment by Abel-8** [comment]
if build successfully,then no more commits

**Comment by Abel-8** [comment]
if build successfully,then no more commits

**Comment by andeon** [comment]
If you are going to use an auxiliary script, place the .bat file inside ci-scripts/windows to maintain the pattern. Although they haven't been used recently since the efforts have been focused on yml files.

**Comment by Abel-8** [comment]
> If you are going to use an auxiliary script, place the .bat file inside ci-scripts/windows/ to maintain the pattern. Although they haven't been used recently since the efforts have been focused on yml files.

Opentoonz was able to  correctly recognize stuff folder after commit 69cbf32b494c83871df6c910aa3aa6803414d460,but might be used in the future.

Moving it to ci-scripts/windows……

**Comment by Abel-8** [comment]
The yml make online works more fluent ,but it's better for local machine to use a auxiliary script.
Might someday update these scripts.

**Comment by RodneyBaker** [comment]
I still have to look through the commits but this stood out on initial look and is of interest:

```temporarily ,workflow_windows.ymls be maded NOT to cp stuff to portablestuff, but [Opentoonz stuff],
because the portablestuff funtion seem goes wrong(Need Fix After)```

We do want the main builds to be portables as that allows for builds to be easily tested without interfering with current installation(s) of Opentoonz and allows multiple builds to be tested simultaaneously, compared, etc.  It may be that we want to expand this to build the portable AND the installation releases but the portables are important to maintain.  The Tahoma2D port of Opentoonz does built full installation as well as portables so that might be worth investigating.

All this to say the "Need Fix After" part of this PR is of interest.

**Comment by Abel032** [comment]
- [x] make .github/workflow/workflow_windows.yml back to generate portablestuff

The "Need Fix After" already fixed , after four commits start from [398f1b2](https://github.com/opentoonz/opentoonz/pull/5656/commits/398f1b22cf64e8c209a72b1f8a2b0779178fd829)

**Pull request merged**
