### PR TITLE
Stop Using Global OpenGL Context

### LINKED ISSUE #1674: Blank Viewer/Combo Viewer after installing V1.2
A user on google groups originally reported this issue under V1.1.3 recently and saw the same issue after recently isntalling V1.2. (https://groups.google.com/forum/#!category-topic/opentoonz_en/yV8uVafZBxY)

I didn't have the problem with V1.1.3, but when I installed V1.2 today, I noticed the problem also.

We are both running Win7 64 bit.

However, it should be noted that, when I build V1.2 locally with the latest OT master code, the executable that is generated is Opentoonz_1.1.exe and it works normally, but if I renamed it to Opentoonz_1.2.exe the viewers are blank.

Unfortunately, if I rename the officially installed Opentoonz_1.2.exe back to Opentoonz_1.1.exe, it doesn't fix the issue.

Is something in the compiling process not accounting for the executable name change?  Are we missing some registry setting?

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This will fix #1674 and #1774 
This is WIP as I still do not verify the fix.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
It seems to work almost OK - except when rendering plastic deformed scenes with tcomposer.

**Comment by shun-iwasawa** [comment]
Unfortunately I couldn't fix the problem with tcomposer so far. I think the problem can be separated to another issue, as rendering on GUI can be workaround of using tcomposer.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
@shun-iwasawa I tested this and it seems to work fine on my machine.  If you are ready to merge this, please do.  Thanks for working on this.

**Pull request merged**
