### PR TITLE
Remove tgraphicss.cpp

### PR DESCRIPTION
**Pull request by otakuto**

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Let me check Jenkins CI for Windows is alive.

Jenkins again

**Comment by shun-iwasawa** [comment]
Hmm it seems to hang. I'll fix it tonight.

**Comment by RodneyBaker** [comment]
There is some interesting code in tgraphics.cpp.
For instance, the ability to draw specific vector shapes; diamonds, cross, etc. in addition to standard shapes.  While I must assume it was deprecated... it's not clear to me why this code (as well as some other used code) was dropped.

**Comment by shun-iwasawa** [comment]
LGTM Thank you @otakuto !

**Pull request merged**
