### PR TITLE
New Feature: Separate Colors

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will add a new feature "Separate Colors" which is for separating single drawing by colors of pencils.

This feature was originally developed for the production of [”The Tale of the Princess Kaguya”](https://gkids.com/films/the-tale-of-the-princess-kaguya/) (2013, directed by Isao Takahata).
In the movie, characters were drawn in sketch-like styles with subtle faint pencil lines.
Together with the black "main" lines of the character, animators drew delicate patterns of Japanese Kimono with colored pencils in the same paper. 

(© 2013 Hatake Jimusho – Studio Ghibli – NDHDMTK)

This feature was developed and utilized in order to separate such colors and make it easier to use them in subsequent workflow of compositing.

Unlike the conventional threshold-based algorithm, this feature can obtain more natural result since it separates pixels in more flexible way in HLS color space.

Please note that for now this feature is a sort of "utility" feature, which means that it is independent from the current scene or project. It just works on selected raster image files in the File Browser.

Please see [the video](https://youtu.be/O9JnYWtP5Ro) for detailed description of this feature.

------

### UPDATE:
I revisited and modified the output image:
Now the output image has alpha channel equal to the line intensity.
You can composite the line by just loading the separated levels, or you can connect the level to MatteInFx with some color card if you would like to alter the line color.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by RodneyBaker** [comment]
Looking very good.  Many thanks for this feature.
I've already spotted some useful workflow to pursue using this.

Do you have a recommended FX to be used to merge the results of this Color separation together again in OpenToonz?  

Ran across two minor issues:
The file selector (via Browser) may want to test for valid file formats as trying to Color Separate incompatible file types will result in a crash.

Upon initial use the window opened very tiny and had to be made larger manually.  Once set to larger size it seemed to stay (this is likely related to appveyor release and therefore won't appear in full build)

**Comment by shun-iwasawa** [comment]
@RodneyBaker 

> The file selector (via Browser) may want to test for valid file formats as trying to Color Separate incompatible file types will result in a crash.
> Upon initial use the window opened very tiny and had to be made larger manually. 

Thank you for testing the feature and prompt feedback. I'll fix it.

**Comment by RodneyBaker** [comment]
Looks like fixed both of those Shun.
Window opens up with nice size and centered and I don't even have the option to select the wrong type of file from Right Click menu in Browser any more.
Nicely done.

**Comment by shun-iwasawa** [comment]
@RodneyBaker 

Thank you for the verification! 

I revisited and modified the output image: 
Now the output image has alpha channel equal to the line intensity.
You can composite the line by just loading the separated levels, or you can connect the level to MatteInFx with some color card if you would like to alter the line color.

I'm thinking of adding the TLV format to the output options in the future.

Jenkins again

**Comment by shun-iwasawa** [comment]
Added "Show Alpha" button for previewing the alpha channel of output image.



Jenkins again

**Comment by RodneyBaker** [comment]
All checks have passed and this PR appears ready to merge.
I'll be glad to do so as appropriate.

**Comment by RodneyBaker** [comment]
No problem here Shun.
I'd rather have someone knowledgeable.

**Comment by masafumi-inoue** [comment]
LGTM

**Comment by gab3d** [comment]
Just for reference...
I've added an [entry](https://opentoonz.readthedocs.io/en/latest/working_in_xsheet.html#separate-colors) for this feature in the **Working in Xsheet** section of the Manual

**Pull request merged**
