### PR TITLE
"Save All" menu which saves current scene and all the levels. (modified from pr#153)

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This modification is for the issue #123 , and is based on walkerka's resolution https://github.com/opentoonz/opentoonz/pull/153

Major changes from walkerka's commit are as follows:
- Saving levels used in the scene is done in SceneResources::save().
- OpenToonz is now available to customize menu bar. The default menu bar will be built from template file (if it exists) when first launched. So I put "Save All" command in menu bar template files as well.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins, test this

**Comment by shun-iwasawa** [comment]
Jenkins, test this again

**Comment by kogaki** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins

**Comment by blurymind** [comment]
works like a charm,thank you.

**Pull request merged**
