### PR TITLE
[WIP] Migrate to Qt 5.9

### PR DESCRIPTION
**Pull request by shun-iwasawa**
In the investigations done in #1517 , we found that `QOpenGLWidget` + Qt5.6 + high-dpi environment causes strange artifacts in the main window and in the viewer. Using Qt5.9.2 seems to resolve such problem. 
I think migrating to Qt5.9 series would be somewhat reasonable as [Qt 5.9 becomes a Long Term Supported release](https://blog.qt.io/blog/2017/05/11/introducing-long-term-support-qt-5-9/).

Please do not merge this PR as this is WIP. I already noticed some problems as follows:

- `QGLWidget` does not work properly under high-dpi environment.
- Some SVG images does not show properly. (It seems to be fixed by overwriting them with Adobe Illustrator.)

I pushed this for checking the behavior of Appveyor and Travis.

UPDATE: I think I mistook something regarding `QGLWidget` . It seems to work fine with no specific modification.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
@turtletooth Is it possible for you to download Qt5.9.2 and try this ? I'm updating Jen.kins to Qt5.9.2 as well.
After merging this I'll modify #1517 regarding the offset problem with `QOpenGLWidget` .

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by turtletooth** [comment]
@shun-iwasawa I tested this and confirmed that everything look good with Qt 5.9.2- with one exception - the schematic.  It looks like this on a display scaled to 150%:
schematic

And I can't select any nodes.  I don't if it's related to the offset. 

Thanks for all your work on this.  I think 5.9 is a good move, especially with the LTS support.

**Comment by turtletooth** [comment]
Update- I don't think my previous comment is an issue.  I may not have used a clean stuff folder with my previous test.  I just tested it on my home computer and didn't have the issues.  They I tried it on my work laptop again - with a new stuff folder, and didn't seem to have the issues there.

So I think this is ready.  LGTM.  Are you ready for this to be merged?

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you for checking this!
I'm still configuring Jenk.ins and will let you know as soon as it is finished.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
Jenk.ins is completed, but I found that there is a display problem in OSX version, when opening the viewer and the style editor in the same main window.

**Comment by shun-iwasawa** [comment]
@turtletooth 
I combined this PR into #1517, as each of them seems not to work properly alone. 
I'll close this.

**Pull request closed without merging**
