### PR TITLE
Add Missing Icons for Vectorize Popup

### PR DESCRIPTION
**Pull request by konero**
@Savraska2 reported there were missing icons in vectorize popup window, this takes care of it.

image

_I also fixed the plus icon for the style name editor button here._

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Thanks for the quick fix @konero!

**Comment by openanim** [comment]
@konero 

Is there any chance to get the icons for zero thickness and guided drawing control panel ?

By the way, nothing disturbing but the 3 icons in timeline mode remain black with the neutral theme set to white icons in the preferences. But maybe this is intentional ?
no full white icons

**Comment by konero** [comment]
@openanim Yeah, I intended for dark icons to be used on Neutral (those icons are actually controlled by stylesheets, if you really wanted to you could swap them in your stuff folder).

> Is there any chance to get the icons for zero thickness and guided drawing control panel ?

Hmm, I didn't do the commands I couldn't visualize personally, or since I didn't work with anyone that used them. If you'd like to you could make them though and I or someone else can submit a PR. They can be up to 20x20px SVG made with pure black color, but using lower alpha for some shapes is fine for alternate colors, try to snap shapes to the pixel grid so they render sharp, or a new issue could be made for other commands.

Sorry I'm not able to help more.

**Comment by openanim** [comment]
@konero No problem, I understand, thanks for the explanations. On another note, feel free to accept the bounty related to the command bar icons request.

**Comment by openanim** [comment]
@konero

I tried to make the icons for the

- Guided drawing control

- Vector guided drawing

- Zero thickness

by following your instructions. I did several tests for the zero thickness icon.

Let me know if there is anything to change. Thanks

[Assets.zip](https://github.com/opentoonz/opentoonz/files/5250815/Assets.zip)

**Pull request merged**
