### PR TITLE
Issue #1131 toonz farm & open toonz on different platforms 

### PR DESCRIPTION
**Pull request by damies13**
This PR doesn't completely fix Issue #1131, however combined with PR #1141 the as long as you can find a common network file path then it will enable cross platform farms.

- Without PR #1141, this PR ensures cross platform operation for Windows & Linux. 
- PR #1141 is required for Mac OSX as the tfarm binaries are not currently included in the OSX Application package (OpenToonz_1.1.app)

### CODE REVIEW

**Comment by damies13** [comment]
it seems I don't have this right yet, will reopen after more testing...

**Comment by damies13** [comment]
Ok this PR should now be complete.

Added bonus, I noticed that the current version on OSX using batch render in local mode also doesn't work, but combining this PR and PR #1141 should fix that too.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Confirmed this fix will enable batch rendering on OSX, in combination with #1993 and #1994 .
Thank you @damies13 for the fix ! LGTM

**Pull request merged**
