### PR TITLE
Add button video capture filter control to Camera Capture (only for Windows) 

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will add access to DirectShow video capture filter properties to the Camera Capture Popup.

Some USB cameras (such as [HOZAN L835](http://www.hozan.co.jp/E/catalog/Optical/L835.html)) have auto white balance and auto focus features. Such features are unwanted for pencil test work, since they lose consistency between frames.
However, disabling these features are not well-supported in Qt for Windows, as written in [here](http://doc.qt.io/qt-5/qtmultimedia-windows.html).

> **Qt Multimedia on Windows - Limitations**
> ... Basic features such as displaying a viewfinder and capturing a still image are supported, however, majority of camera controls are not implemented. ..

As a workaround, I added a "gear" button for opening DirectShow video capture filter properties dialog. Please note that this feature is available only in Windows version.

I marked this PR as WIP since I'm new to COM programming and would like to check if Jenkins can build it properly.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by turtletooth** [comment]
I tested this and it works great-  I wanted a way to have greater control over exposure and focus.  Thank you for doing this.  Is this still work in progress or ready to be merged?

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you for testing this. I think it's ready to be merged.

**Comment by turtletooth** [comment]
Thanks for this addition!  LGTM.

**Pull request merged**
