### PR TITLE
Xcode IDE support for macOS builds

### PR DESCRIPTION
**Pull request by manongjohn**
This PR provides macOS developers the ability to code, build and debug OpenToonz through the Xcode IDE. This will hopefully make it easier to debug code for macOS issue.

Minor modifications to the CMakeLists.txt allows the use of a cmake feature to generate a project file for Xcode.

Instructions have been updated to clarify the environment setup process and provide steps to set up for either command line builds or Xcode project creation.

These instructions were developed on a macOS VM running Mojave (10.14). I was able to successfully build OT using Xcode 10.2, boost 1.69.0, qt 5.12.2, cmake 3.14.2.

### CODE REVIEW

**Comment by artisteacher** [comment]
I like the organization!  This is a really helpful update.

I'm pretty sure that lines 57 & 58:
`$ mv ~/Downloads/boost_1_69_0.tar.bz2   #or whatever the boost filename you downloaded is#
   $ tar xvjf boost_1_69_0.tar.bz2 .`
need to be:
`$ mv ~/Downloads/boost_1_69_0.tar.bz2 .   #or whatever the boost filename you downloaded is#
	$ tar xvjf boost_1_69_0.tar.bz2`
On a related note, the latest version of boost is boost_1_70_0.tar.bz2 

It might be helpful to make a change here:
> Edit the /Users/yourlogin/Documents/opentoonz/toonz/sources/CMakeLists.txt file at line 160 (64bit OS) or 172 (32bit OS) and modify the root path for the QT lib directory

To specify that cmake.txt only needs to be updated if the QT version/path is different from
`/usr/local/Cellar/qt/5.12.2/lib`

Also, this:
> Uncheck: Run -> Options -> Document Version

should say: Uncheck: Run -> Options -> Document Versions

**Comment by manongjohn** [comment]
@artisteacher Thanks for the corrections! I shall make them soon.

Boost 1.70.0 i believe is still considered a beta, so I didnt use that one. Travis builds are using 1.65.1. Not sure what the official and nightly builds use.

**Comment by artisteacher** [comment]
This works perfectly - for both terminal and Xcode. I did notice a couple minor typos:

> If installing via this method, be sure to install the **depricated** QT Script libraries.�

should say **deprecated**


> If built **using via** command line, run the following:

probably should be either **using** or **via**

**Comment by artisteacher** [comment]
Sorry, one last typo:

> "Qt **instlattion** directory"

**Comment by artisteacher** [comment]
These instructions do help to build successfully on macOS and are much better than the current directions. Is there any reason to hold off on merging?

**Comment by RodneyBaker** [comment]
I think that just no one with a Mac has stopped in to confirm.
Since this is a little old let's give @manongjohn a chance to respond.
As these are only text and .md files... instructions... I'll be glad to merge based on your approval and his validation that no other obstacles stand in the way.

**Comment by manongjohn** [comment]
There are changes to CMake files, not just instructions.

@shun-iwasawa should make sure this doesn't somehow break Jenkin builds used to create the macOS releases.

**Comment by manongjohn** [comment]
Apparently a close/reopen of a PR doesn't retrigger a Jenkins build. Not really expecting an issue, but was as hoping to check impact to Jenkins build that way as a sanity check. ☹

@shun-iwasawa Please trigger a Jenkins build on this when you have a moment.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by manongjohn** [comment]
As expected, Jenkins builds appear to be ok with these changes and there are no linkage issues in any of the AppVeyor/Travis logs.

Since this was tested and confirmed by @artisteacher a while ago I think it's safe to merge.

**Comment by RodneyBaker** [comment]
Thanks @manongjohn as soon as all checks are in and validate will merge.

**Pull request merged**
