### PR TITLE
Function Curves Window Usability - Option 1

### PR DESCRIPTION
**Pull request by turtletooth**
This is my preferred option- remove the need to press the control key for modifying positions/values.
The current setup is almost impossible to discover.
#159

### CODE REVIEW

**Comment by Rayek** [comment]
Agreed - I know of no other graph editor in either 2d or 3d software that requires a control key to modify the curves.

Definitely prefer this option.

**Comment by shun-iwasawa** [comment]
I added the "Ctrl key condition" to Ghibli Edition reflecting demands from the studio in order to avoid changing values by mistake. I agree that it is no longer a necessary feature, in consideration of usability for first-time users.
I prefer the option 1 too.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by blurymind** [comment]
@turtletooth  thank you!! :)

**Comment by shun-iwasawa** [comment]
LGTM

**Pull request merged**
