### PR TITLE
Refined Icons

### PR DESCRIPTION
**Pull request by konero**
Refines some icons.
- Improved detail, bigger sub-glyphs for high dpi displays
- Improved pixel snapping for higher clarity on low dpi displays
- Updated designs for some icons (see below)
- Added icons for some commands that didn't have any (see below)

**Updated Designs**

image

**New**
- Tape Tool:
- - Endpoint to Endpoint
- - Endpoint to Line
- - Line to Line
- - Rectangular
- - Freehand
- - Polyline
- - Normal
- Macro
- Connect/Disconnect from X-Sheet
- Collect Assets
- Preset
- Paste Color
- Paste Name
- Paste Color & Name
- Link
- Unlink
- Cache FX
- Uncache FX
- New Project
- Save Default Settings
- Project Settings
- Reset Zoom
- Reset Rotation
- Zero Thick Lines

**Swaps**
There were one or two swaps, most common probably the Render > Render icon.

**Used**
Made more commands use some icons, like Reset View, etc.

### CODE REVIEW

**Comment by openanim** [comment]
@konero any chance to have  a zero thick lines (right click menu command) icon ?

**Comment by konero** [comment]
@openanim Added zero thick lines icon, hope the design is OK. 👍 

image

**Comment by openanim** [comment]
That look great ! Thanks a lot !

**Comment by RodneyBaker** [comment]
Nightly builds for Windows haven't been generating of late so expect a little delay in merging of PRs.

**Comment by konero** [comment]
> Nightly builds for Windows haven't been generating of late so expect a little delay in merging of PRs.

No worries, all of a sudden got merge conflicts, hopefully resolved now.

**Comment by justburner** [comment]
All your icons are always top-tier, keep up the good work! :)

**Comment by RodneyBaker** [comment]
I believe I will press my luck and see if the WIndows nightlies are building again...

Thank you @konero for the refined icons!
LGTM

**Pull request merged**
