### PR TITLE
New Note Level

### PR DESCRIPTION
**Pull request by turtletooth**
This adds a note level column type to OT.  It was already there without much functionality and was only visible when a magpie file was imported.

You can enter text on any frame by double clicking.  You can move and hold frames like other frame types.  I believe @manongjohn will be doing the header UI since he is already tackling the timeline PR. Thank you @manongjohn  (I don't know if these notes should be visible in the timeline) 

This is useful for mapping dialog, noting specific actions, marking keys and breakdowns or anything you want.

notelayers

Similar requests have been made, including #325 #368

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Thank you for this.  I had downloaded the Scene file you posted before and was encouraged to see the capability.  

Features that empower the xsheet make using it even more useful and OT's xsheet is already a joy to use.  :)

**Comment by turtletooth** [comment]
Drawing substitution will work for these levels too in #1286

**Comment by 2dvision** [comment]
I have an idea, Is it possible to have [AyameLee idea](https://github.com/opentoonz/opentoonz/issues/368#issuecomment-222079551) 

action note

and save/load cells like sprite sheet?

action note sprite sheet

**Comment by turtletooth** [comment]
@2dvision 

> I have an idea, Is it possible to have AyameLee idea

Short answer: Probably not.

Long answer: Only if a dev really wants to build it.  There are a lot of pieces to build for that to happen.  And the payoff may not be that great.  The text column was already in OT- it just a took a few hundred lines of code to make it work a little more flexibly.  This will involve building new brush and eraser tools, a way to save them/load them, a way to display them in the xsheet, figuring out how to size an image that has no definite end to its length, edge/activation detection etc. . .

The text column will do maybe 60-90% of what people were hoping to do with drawing on the xsheet.

One of the problems with open source is that unless there is funding, development is not guaranteed.  As a teacher, I generally build things that I think will help my students out, with a few extra little things here and there.  

Krita has a good model using kickstarter to get the features built and I think it could be a good way for OT to go if there are certain features that the community really wants to see happen.

**Comment by openanim** [comment]
Ty Turtletooth, nice work like always  !

"One of the problems with open source is that unless there is funding, development is not guaranteed. As a teacher, I generally build things that I think will help my students out, with a few extra little things here and there.

Krita has a good model using kickstarter to get the features built and I think it could be a good way for OT to go if there are certain features that the community really wants to see happen."

I saw a bounty system about Mypaint tool request, can i know how this system works ? I don't know where should i go to find information about that.

**Comment by turtletooth** [comment]
@openanim You can go to https://www.bountysource.com/ and post the url of any issue here on GitHub to post a bounty.  Developers can accept the bounty at the value or determine that the bounty is too low for the amount of work.  If it is too low, the bounty waits until more people come along to contribute.

**Comment by openanim** [comment]
fine, ty for the link :)

**Comment by manongjohn** [comment]
@turtletooth Just a thought...consider changing the column header icon to something other than the dialog balloon since this column is becoming more than just a soundText (magpie) column. Maybe change it to something that looks like a notepad or a piece of lined paper?

**Comment by turtletooth** [comment]
@manongjohn Good idea.  @2dvision @artisteacher @konero Do either of you want to give it a shot?
@manongjohn Do you know the dimensions of the current header icons?

**Comment by manongjohn** [comment]
The current thumbnail icon is 63 x 42px.  If the new layout ever comes to pass, the thumbnail icon will be 73 x 43px.

**Comment by artisteacher** [comment]
Are these too complex? The actual file types are svg so resizing won't be a problem.
screen shot 2017-08-06 at 1 57 59 pm
screen shot 2017-08-06 at 2 01 25 pm

**Comment by yamisama** [comment]
I think the "+" icon popularized by Apple over the last few years could be used instead. I think it's a bit more logical and obvious for novices than the Microsoft-style blank sheet of paper, especially since a Level in Toonz usually consists of multiple frames and therefore multiple sheets of cel or paper in traditional animation. Moreover, the piece of paper iconography is already used in Toonz to mean "Memo" and could thus be slightly confusing.

Therefore, if we were to redesign these icons, my suggestions would be to use a completely different icon for each level type with a "+" in the top right corner. For example:

- Rectangular stylized landscape "picture" icon with a "+" in the top right corner to indicate "New Raster Level", as raster levels are mostly used for painted backgrounds.
- Some sort of extremely blocky pixelated filled shape like a circle with a "+" in the top right corner for "New Toonz Raster Level", as these levels are usually used for filled foreground objects.
- The same shape in sharp with Bézier handles or anchor points and a "+" in the top right corner to indicate "New Vector Level"
- Speech bubble with that same "+" for the "Notes" level type

The lack of piece-of-paper frame would maximize the space that's left for the element that's actually differentiating the icons, and the "+" would link them visually and make it clear that they all add something to the XSheet.

**Comment by 2dvision** [comment]
What do you think about these?

megaphone
ot megaphone 
pencil
ot note

preview-ot-megaphone preview-ot-note

[Download SVG](https://my.pcloud.com/publink/show?code=XZI7xcZOFgiwovUzJmuzEHHbwJbAmny0a77)

**Comment by manongjohn** [comment]
@artisteacher Looks nice. Needs a pencil I think.

@2dvision I like the pencil one. I wonder if the pencil one would make a nice looking icon on the xsheet toolbar for adding a new note level.

**Comment by artisteacher** [comment]
With pencils...
note_icon2
note_icon1

**Comment by turtletooth** [comment]
I personally prefer the pencil by @2dvision.  I created a svg version with the same dimensions as the original speech bubble icon, but it looks bad with the current dimensions of the icons in the header.  
@manongjohn Would you mind either working this into your xsheet layout PR or letting me know what dimensions I should be using for icons.
[magpie.zip](https://github.com/opentoonz/opentoonz/files/1255120/magpie.zip)

**Comment by manongjohn** [comment]
@turtletooth I'll work the image change into my xsheet layout PR.  Don't let the thumbnail hold it up. This is far more useful to have regardless of whatever thumbnail is showing.  I'll post dimensions in that PR (might already be there in a prior comment)

**Comment by turtletooth** [comment]
Thanks @manongjohn

**Comment by manongjohn** [comment]
@turtletooth Since this hasn't been promoted yet, if you want to add this, I've updated your magpie.svg to the thumbnail dimensions for my PR and it still looks good in current thumbnail dimensions as well.

[magpie.zip](https://github.com/opentoonz/opentoonz/files/1272997/magpie.zip)

**Comment by shun-iwasawa** [comment]
@turtletooth 
Sorry for my late response on this. Here are some notes:

- OT crashes when you create a note level then try to create a new level (such as Toonz Raster Level) at the same column.
- When dragging the note level across columns, IMO it would better to make the column name (e.g. `NoteLevel1` ) to accompany with it just like the zerary fx columns.
- I think it would better to move the right-click menu `New Note Level` command from the cell area to the column area, since it will insert a new column just like when inserting a new zerary fx.

**Comment by turtletooth** [comment]
> When dragging the note level across columns, IMO it would better to make the column name (e.g. NoteLevel1 ) to accompany with it just like the zerary fx columns.

I have no idea how to do that.  I'll take care of the other two right now.

**Comment by shun-iwasawa** [comment]
> I have no idea how to do that.

The zerary fx seems not to allow us to drag cells across columns. It only accepts dragging column or dragging cell within the same column, so that it can maintain the column name. How about taking the same restriction?

**Comment by turtletooth** [comment]
Got it.  Thanks for the feedback @shun-iwasawa.  My fix for the crash pushes the newly created level to an inserted column-  this also fixes levels created on an audio column.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM Thank you @turtletooth for the addition!

There is a small problem that the note levels fail to be loaded properly if the text is written in Japanese. I think it can be fixed on my side.

**Pull request merged**
