### PR TITLE
Spanish UI update to 1.1 strings

### PR DESCRIPTION
**Pull request by gab3d**
I hope all is right

### CODE REVIEW

**Comment by gab3d** [comment]
Hi,
This is still pending, right?

Thank you! :)

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
@gab3d 
First of all, thank you very much for your contribution on Spanish translation.
Sorry for the late notice, but could you please produce QM files out of modified TS files and put them into opentoonz/stuff/config/loc/Español ? They are needed to create the installer.
Thanks!

**Comment by gab3d** [comment]
@shun-iwasawa 
Hi Shun, sorry for the delay.
I'll do it asap. :)

**Comment by gab3d** [comment]
@shun-iwasawa 
how could I translate the installer strings into Spanish?
i don't know where they're found

**Comment by shun-iwasawa** [comment]
@gad3d
Thank you very much for your proposal for Spanish translation of strings used in the installer.
But I'm so sorry to tell you that the installer is managed in the private repository of Dwango for now. We're thinking of bring it to public or at least enable to add translation of another language in the future, but it is not prepared yet.

**Comment by shun-iwasawa** [comment]
Can one of the admins verify this patch?

**Comment by shun-iwasawa** [comment]
@gab3d Sorry for keep you waiting so long. I fixed conflicts and posted another PR based on yours. Thanks!

**Pull request merged**
