### PR TITLE
Fix/playaudio linux #863

### LINKED ISSUE #863: Load WAV level -> Get creepy sound.
Hi!

When I load a **WAV sound**, I always get a continuous creepy very loud sound (for example, when I play it from the level in the x-sheet).

I suppose that it must be related with the **frequency** or something related (maybe only happens in GNU/Linux), but I don't get one good WAV (and I think that must be accepted all of them).

I am using Opentoonz and ffmpeg in GNU/Linux.

One I tried was this: https://dl.dropboxusercontent.com/u/58974111/11SecClub_May_Competition.wav

Thanks and greetings.

### PR DESCRIPTION
**Pull request by jabarrera**
Hi.

This resolve #863 issue.

### CODE REVIEW

**Comment by ideasman42** [comment]
Note, it looks like removing braces around `TThread::ScopedLock sl(MutexOut);` would change its behavior when un-commented (probably it should be removed entirely, or left in with braces).

Would prefer fixes be completely separated from superficial changes, so they can be reviewed more easily.

@mmuman would you be able to check this patch?

**Comment by mmuman** [comment]
Indeed, since it's constructed on stack its scope is that of the enclosing braces, so if you remove the braces the lock will stay until the end of the method.
I didn't really look into it though.

**Comment by jabarrera** [comment]
@ideasman42, you are absolutely right about the braces. I prefer, too, to recover them and let the fix isolated.

I revert the deleted braces/block in the last commit (https://github.com/opentoonz/opentoonz/pull/930/commits/15bf4faa8488a44172205eed0c6a54137bb31544).

Thanks to @mmuman, too, for the point.

**Comment by mmuman** [comment]
For such small changes you can squash your commits and force push the branch btw.

**Comment by jabarrera** [comment]
It seems the **OSX Travis** check failed with a _timeout_.

Could someone run again that check?

Thanks!

PS: I know that it is not a real problem, but I hate see the red cross. I want my green mark! : ))

**Comment by ideasman42** [comment]
Merged with minor edits, let `#if defined(i386)` block in, better handle this separately.

**Comment by jabarrera** [comment]
I'm sorry, @ideasman42 , but if you let the define(i386) block the sound is not fixed for 32 bits.

I'm using 32bits compilation, and in my tests the operation maden for 16 bits sounds in 32 bits platform is not need (make noisy). So the same operation for 32 and 64 bits are enough.

Is not it better goes in the same fix?


Thanks.

**Comment by ideasman42** [comment]
@jabarrera, ah, thought this was part of some cleanup,
thanks for the heads up - I can't i386 easily, so taking your word for it,
committed e8ad7771865125fcdd5def005c5742cd7fc98c2a

In the future it would be good to give a bit of info on each change, just a few lines explaining what a change is needed - if its not totally obvious.

**Comment by jabarrera** [comment]
@ideasman42 , you are absolutely right. My PR wasn't too much (in fact, anything at all  :)) well explained. My fail.

Thank you very much for this and for the work you made with the Linux compilation.

**Pull request closed without merging**
