### PR TITLE
Support Visual Studio 2015

### PR DESCRIPTION
**Pull request by skitaoka**
https://github.com/opentoonz/opentoonz/pull/307

- fix conflicts
- support Visual Studio 2013 for CI
- use GIT-LFS for *.lib and *.dll

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins

**Comment by janisozaur** [comment]
Before this gets merged, can you please *please* at least squash the changes? This will somewhat reduce amount of binaries needed to be stored in history, if you really have to store them in this repository (see https://github.com/opentoonz/opentoonz/issues/69). They are changed multiple times in this PR and each such binary has to be stored in git. This PR alone adds 22MB to the repository.

**Comment by skitaoka** [comment]
Jenkins

**Comment by ideasman42** [comment]
This PR looks to have changes in application logic (whats hole filling for example), that should probably be separate PR's.

Basically any fixes or improvements _not_ related to MSVC2015 support, should be applied separately.

**Comment by ideasman42** [comment]
Regarding binary files, think it would be good if these used GIT-LFS or at least make `thirdparty` an external repository.
Long terms this will make the git repository large (everyone will store every binary library version for every platform).

**Comment by skitaoka** [comment]
Jenkins, again.

**Comment by kogaki** [comment]
Jenkins

**Comment by kogaki** [comment]
using Git-LFS looks good idea.

**Comment by turtletooth** [comment]
Thank you for this.

**Pull request merged**
