### PR TITLE
ClangFormat

### PR DESCRIPTION
**Pull request by skitaoka**
https://github.com/opentoonz/opentoonz/pull/249

```
BasedOnStyle: Google
Standard: C++11
UseTab: Never
AccessModifierOffset: -2
AlignAfterOpenBracket: true
AlignConsecutiveAssignments: true
AlignEscapedNewlinesLeft: false
AlignTrailingComments: true
IndentCaseLabels: false
BreakConstructorInitializersBeforeComma: true
PointerAlignment: Left
```

This PR follows https://github.com/opentoonz/opentoonz/pull/291.

### CODE REVIEW

**Comment by janisozaur** [comment]
let me update #249

**Comment by janisozaur** [comment]
I updated #249 but github says there is a conflict. When you merge #291, I will update it once again, should be without problems then.

**Comment by skitaoka** [comment]
thank you for your continuous contributions. we have considered `.clang-format` style options.

**Comment by skitaoka** [comment]
We are going to apply this ".clang-format" at the last minute of the next release (v1.0.3).

**Comment by janisozaur** [comment]
Please apply it over all of the headers as well.
```
git ls-files toonz/ | egrep \\.\(c\|cpp\|h\|hpp\)$ | xargs clang-format -style=file -i
```

**Comment by skitaoka** [comment]
Yes. I'm going to do that. thanks.

**Comment by ideasman42** [comment]
Am skeptical of applying auto-formatting on an entire code-base, there are enough examples where the auto-formatter (arguably) makes the formatting worse.

- https://github.com/opentoonz/opentoonz/pull/249/commits/3c2ccab846850e639f830f39041a585dd6f0d740#diff-4f5c703be76be15688bd8368c891cd61R724
- https://github.com/opentoonz/opentoonz/pull/249/commits/3c2ccab846850e639f830f39041a585dd6f0d740#diff-e02362f455652f7208216ab2dd66e226R302
- https://github.com/opentoonz/opentoonz/pull/249/commits/3c2ccab846850e639f830f39041a585dd6f0d740#diff-e02362f455652f7208216ab2dd66e226R610

Especially in breaking visual alignment across multiple lines.
It would be good to keep lines which are intentionally split, instead of joining into a single line.
However it seems the only way to do this currently is to disable clang-format for those lines: http://stackoverflow.com/questions/33656800/clang-format-line-breaks

**Comment by skitaoka** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM

**Pull request merged**
