### PR TITLE
Updated Mac Build Instructions

### PR DESCRIPTION
**Pull request by turtletooth**
This updates some of the build instructions for the Mac.

### CODE REVIEW

**Comment by damies13** [comment]
@turtletooth After libmypaint was added we also seem to need to it to the brew command, can I suggest changing:
_$ brew install glew lz4 libjpeg libpng lzo pkg-config libusb cmake git-lfs_
to:
_$ brew install glew lz4 libjpeg libpng lzo pkg-config libusb cmake git-lfs libmypaint_


Dave.

**Comment by blackwarthog** [comment]
@damies13, oops, i've forgot to do this. Thank you for notice.

**Comment by damies13** [comment]
@blackwarthog Can you add instructions for Linux as well (I use Ubuntu) as I haven't figured out where to get a libmypaint for Linux that cmake will recognise as being installed.

FYI I tried this but it didn't work (https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing)

Dave.

**Comment by damies13** [comment]
@blackwarthog actually I just figured out what is needed:

If add-apt-repository is missing install it using:
   $ sudo apt-get install software-properties-common python-software-properties

Then add this repository:
   $ sudo apt-add-repository ppa:achadwick/mypaint-testing
   $ sudo apt-get update

Then install libmypaint-dev and it's dependancy libjson-c-dev:
   $ sudo apt-get  install libmypaint-dev libjson-c-dev

Now cmake ../sources completes without error, now about to try make.

**Comment by blackwarthog** [comment]
Is `make` works with errors?

**Comment by damies13** [comment]
@blackwarthog yes it did, when I started it it was about midnight here and I had a 9am meeting at work, so I couldn't watch it.

BTW I also made the QT 5.6.2 changes to my branch and tested these instructions on OSX, I can confirm they worked for me once the libmypaint bit is added.

Dave.

**Comment by turtletooth** [comment]
Added libmypaint to brew.  Thanks @damies13

**Comment by shun-iwasawa** [comment]
LGTM, thank you @turtletooth and @damies13 for this update!

**Comment by damies13** [comment]
I just noticed that the script "ci-scripts/osx/travis-build.sh" is still qt5/5.6.1-1, does this need to be updated for the automated builds to be use this change?

**Comment by shun-iwasawa** [comment]
Yes, actually.
I just couldn't find a proper commit id of homebrew for backtracking it and obtaining Qt 5.6.2 package.
( See `ci-scripts/osx/travis-install.sh` )

**Pull request merged**
