### PR TITLE
More Spanish Translation for v1.4 by gab3d

### PR DESCRIPTION
**Pull request by shun-iwasawa**
Updated Spanish translation by @gab3d .

@gab3d 
I hope you will be able to prepare the [What's New](https://opentoonz.readthedocs.io/es/latest/whats_new.html#v1-4) page in the User Manual by the day of official release. Thank you!

### CODE REVIEW

**Comment by gab3d** [comment]
😁 hehe I'll do...
What's the date?

**Comment by shun-iwasawa** [comment]
It's (hopefully) by the end of this month. 📆

**Comment by gab3d** [comment]
...much more time than I thought I had. 😂

**Comment by shun-iwasawa** [comment]
LGTM Thank you @gab3d

**Comment by gab3d** [comment]
In #3047 news about **What's New** manual page.

**Comment by gab3d** [comment]
@shun-iwasawa @RodneyBaker @DarrenTAnims 
Both English and Spanish versions of What's New page are now ready for release.

(English I had to create to be able to have the Spanish translation thereafter, but of course if you happen to like to also link the English version of the Help menu to it, it's ready too). 😺 

*Still, later on, the page should evolve to contain links to other parts in the manual, where some of the new features would be explained in further detail.

**Pull request merged**
