### PR TITLE
New Icons

### PR DESCRIPTION
**Pull request by turtletooth**
This introduces icons for:
- undo
- redo
- clone sub x sheet level
- merge levels
- canvas size
- touch (not yet added to a command.  Waiting for #1621)
- load level
- preferences
- timestretch

Most of  these are from @artisteacher, with some help from @orphanlast - thank you for your contributions.

### CODE REVIEW

**Comment by 2dvision** [comment]
I do not agree with undo/redo icon. I suggest something like this for:

undo / redo

undo_redo

load level
load_level

Timestretch
timestretch

Sorry, I do not have free time for make svg file.

**Comment by turtletooth** [comment]
I updated the timestretch, clone and load level with ideas from @2dvision - Thanks!

I also added the touch to the command.

I played with undo and redo, but I didn't feel they read as cleanly as the originals at 18 x 18px.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Thank you @turtletooth, @artisteacher and @Orphanlast for this ! LGTM

**Pull request merged**
