### PR TITLE
Stop Motion Improvements by jeremybullock (OpenCV for all builds)

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is based on #3221 by @jeremybullock with some modifications & additions.
(The changes is to make GitHub Actions to work and to remove unnecessary files such as Travis settings.)

This will introduce OpenCV for all builds and enables to use OpenCV-related features like OpenCV-based camera capture and Bloom Iwa Fx in all platforms.

Please note that this PR is WIP since I'll setup a new Jenkins machine to build this PR properly with the latest environment and libraries.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins (the first trial of a new machine)

**Comment by shun-iwasawa** [comment]
Jenkins (testing a new machine)

**Comment by shun-iwasawa** [comment]
Jenkins (testing a new machine)

**Comment by shun-iwasawa** [comment]
Jenkins (testing a new machine)

**Comment by shun-iwasawa** [comment]
Jenkins (testing a new machine)

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
I think this PR will be ready to be merged after replacing Jen.kins machine.
You can ignore the failure test result reported by the previous machine (osx).

**Comment by shun-iwasawa** [comment]
I'll merge this so that the potential problem can be found through user testing with the nightly and RC releases.

**Comment by RodneyBaker** [comment]
Thank you @shun-iwasawa (and Jeremy Bullock!).

A question:  Does this suggest that the Dwango plugins can also be added to the v1.5 release?
That would certainly be a highlight of the release.  :)

**Comment by manongjohn** [comment]
@shun-iwasawa Something I just stumbled upon a few minutes ago... according to opencv.org, the opencv license changed from BSD-3 to Apache 2, starting with version 4.5.0.

Might want to check with the legal team if it can still be included with OpenToonz.

If it's still ok, you'll probably want to update your LICENSE_opencv.txt to the Apache 2 verbage as it still has the BSD-3 verbage.  If it's not, you're going to need to drop back to opencv 4.4.0 which is still under BSD-3 license.

**Pull request merged**
