### PR TITLE
Spritesheet Export

### PR DESCRIPTION
**Pull request by turtletooth**
Features: 
- Crops transparent area from images (if other images will use a space, it is left) - See ball example below.
- Set output format (Grid, Vertical, Horizontal)
- Scale output
- Set padding for top, bottom, left, right
- Export text file along with spritesheet with info about image sizes, padding etc. . .

Note- this is not an image atlas where every layer is exported into its own area of an image.  This is a traditional spritesheet.  Tested with Game Maker Studio.

Settings box:
sprite_settings

Examples of output:
example_spritesheet

Text file contents:
sprite_text_output

### CODE REVIEW

**Comment by blurymind** [comment]
Would it be possible to make the trimming optional in this case? It works
for atlases but for spritesheets it may cause issues if different frames
are a different size and centering each frame.

On 24 Aug 2016 04:22, "Jeremy Bullock" <notifications@github.com> wrote:
>
> Features:
>
> Crops transparent area from images (if other images will use a space, it
is left) - See ball example below.
> Set output format (Grid, Vertical, Horizontal)
> Scale output
> Set padding for top, bottom, left, right
> Export text file along with spritesheet with info about image sizes,
padding etc. . .
>
> Note- this is not an image atlas where every layer is exported into its
own area of an image. This is a traditional spritesheet. Tested with Game
Maker Studio.

**Comment by turtletooth** [comment]
>Would it be possible to make the trimming optional in this case? It works
for atlases but for spritesheets it may cause issues if different frames
are a different size and centering each frame.

I can make the trim optional, but it already accounts for different sized frames and equalizes the frame size based on the most extreme drawing in each direction.  It calculates the area that is used by the entire animation and makes the image size match.  Each drawing is in its relative space within that area.

**Comment by blurymind** [comment]
Ah i see..sounds like it will work on. Need to try it out

**Comment by turtletooth** [comment]
You can try it here: https://github.com/motionmonster/motionmonster/releases/tag/v1.1.1.1

**Comment by turtletooth** [comment]
Here is a better example- here is a partial spritesheet from this gif:
animated-parrot-gif-2

untitled70

**Comment by RodneyBaker** [comment]
Sweet.   Very nice.

**Comment by blurymind** [comment]
very nice indeed! :) Looking forward to seeing it merged. Thank you @turtletooth

**Comment by shun-iwasawa** [comment]
Can one of the admins verify this patch?

**Comment by RodneyBaker** [comment]
This spritesheet option for output still hasn't been added to OpenToonz yet but would certainly be a welcome addition.

Here's a quick sequence of frames/sketches rendered with it:

bunnyspritesheet_sm

**Comment by turtletooth** [comment]
@RodneyBaker good point.

**Comment by blurymind** [comment]
@turtletooth Now if we only had dragonbones json animation data file export :)
https://github.com/opentoonz/opentoonz/issues/173
That would be amazing!

Btw ndee has had success with writing an exporter for blender in python
https://github.com/ndee85/coa_tools/issues/26

**Comment by turtletooth** [comment]
@blurymind COA Tools is so powerful - I'm not sure I see the benefit of duplicating the features here.  What do you see as something that OpenToonz has the potential to offer that COA Tools doesn't support?

**Comment by turtletooth** [comment]
@shun-iwasawa Would you mind looking at this next when you have the time?  

On a side note, there is an Android game that was created using this feature:
https://groups.google.com/forum/#!category-topic/opentoonz_en/share-your-work/Y3Xoaa2dSik

**Comment by turtletooth** [comment]
@shun-iwasawa I made a copy of the image in the same function the buffer was created in.  QImage only has the memory problem on images created with a buffer, so the copy is easy to delete later.  Instead of figuring out a way of passing the pointer to the buffer to the destructor, this seemed like an easier fix.  I tested the memory usage and memory usage drops back to the right place after spritesheet export.

**Comment by shun-iwasawa** [comment]
The memory problem seems to be fixed.
However, from this version the transparent region in the rendered image seems to be replaced by semi-transparent light gray color. Please see the attached image:
dwanko_ss_test

Please note that I added 20 pixels padding which are still transparent in this result.

**Comment by turtletooth** [comment]
Thanks for catching that.  I'm sorry I didn't catch that in my fix.  I am testing a fix right now.

**Comment by shun-iwasawa** [comment]
I confirmed that the problem was fixed. Thank you!
Jenkins

**Comment by shun-iwasawa** [comment]
Now I agree with @RodneyBaker that this feature would be helpful not only for game creators, but for animation studios. Lining up the animation drawings is so beneficial to overview whole actions.
@turtletooth thank you for adding the nice feature. LGTM

**Pull request merged**
