### PR TITLE
Flip and rotate toolbar options

### PR DESCRIPTION
**Pull request by manongjohn**
A requested port from T2D which will add the following:

- Selection Tool Flip and Rotate Buttons
image

- Animate Tool Flip and Rotate Buttons

image

- Shortcuts for new Flip and Rotate buttons

image

- Behavior of buttons:
   - `Flip Selection/Object Horizontally`: Multiplies H value by -1
   - `Flip Selection/Object Vertically`: Multiplies V value by -1
   - `Rotate Selection/Object Left`: Adds 90 to rotation value 
   - `Rotate Selection/Object Right`: Subtracts 90 from rotation value

### CODE REVIEW

**Comment by manongjohn** [comment]
Linux build failures due to something with the Linux build environment and not related to these changes. May be a transient thing with Azure. Someone can try restarting the builds later.

**Comment by F-Burning** [comment]
Thank you!

I was looking for the rotate icon on the bar, and the flip option to the selection is very useful.

**Comment by RodneyBaker** [comment]
@konero has mentioned via discord that he will add the missing icons involved in this feature set to his list.

**Comment by RodneyBaker** [comment]
Will press forward with this PR as although the Mac runner should be working again it isn't essential for buildiong the nightly release.

Thanks @manongjohn for the feature port/code!

**Pull request merged**
