### PR TITLE
Improvement of direct inputting feature in Xsheet

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is to improve the feature for defining animation level directly in xsheet cell. ( Issue #721 ) 

- For now all the selected cells are input at a time. In order to use this feature, press shift key on double-clicking the cell in order to avoid releasing the cell selection.
- When inputting number into the empty cell, if the next upper cell is empty, search upper cells and use the nearest level.
- Enabled to type '0' which makes the target cell empty.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
@skitaoka could you please review this?

**Comment by skitaoka** [comment]
These improvements are very useful!

**Comment by RodneyBaker** [comment]
Can anyone provide something of a how-to or demo for this.
I can't seem to get it to work.

If this has not yet been implemented please disregard.

**Pull request merged**
