### PR TITLE
Colored assistants

### PR DESCRIPTION
**Pull request by blackwarthog**
This PR allow you to choose color and transparency of assistants level (for whole level, not for individual assistants).

Now assistant-level takes color and transparency values from column options as like as other levels.

Also i've modified behavior of line assistant handles. For now the first handle moves a whole line, and the secondary handle changes line length and direction.

### CODE REVIEW

**Comment by blackwarthog** [comment]
colors

**Comment by blackwarthog** [comment]
Related PRs #2656, #4852, #5039, #5069, #5100 and issue #1349

**Comment by Ahl76** [comment]
@RodneyBaker @blackwarthog  Appebeyor seems failed to try it.

thanks for the additionals features.

**Comment by DarrenTAnims** [comment]
This is fantastic!
Thanks for your work on this. This will really help plenty of us.
I've one request (I didn't know where the best place to ask was): Could you add a command in the menu to create a new assistant level: Level > New > Assistant Level.
And also add 2 buttons to the timeline & xsheet toolbar to create an Assistant level & a Notes level?
You may already have this on your list to do, but I wanted to ask.
Thanks again buddy.

**Comment by blackwarthog** [comment]
@DarrenTAnims thanks for your feedback. I'll add an action and buttons. No, it was no in my to do list before :) I think for bug reports and feature requests related with assistants we can create new separate issues. Just mention me in issue, so i'll receive a notification.

**Comment by DarrenTAnims** [comment]
> @DarrenTAnims thanks for your feedback. I'll add an action and buttons. No, it was no in my to do list before :) I think for bug reports and feature requests related with assistants we can create new separate issues. Just mention me in issue, so i'll receive a notification.

Thank you. I appreciate that.
And yes, I'll do that if I have any other suggestions. I'm trying to formulate a suggestion for an improvement atm, but I'm not sure what's best. It's about selecting assistants without moving them. Perhaps a dropdown listing them all, showing the currently selected one, to make it easier to choose between them.
These assistants are really shaping up to be soooo useful. Thank you for implementing them.

**Comment by RodneyBaker** [comment]
@blackwarthog 
@shun-iwasawa has updated the build environment so if you refresh your PR the appveyor build should successfully pass all tests.

Apologies for the delay!

**Comment by RodneyBaker** [comment]
Looking good here.

image


Posting intent to merge.

**Comment by RodneyBaker** [comment]
And merging.
Thank you @blackwarthog for your continued improvements of the Assistants.
Much appreciated.

**Pull request merged**
