### PR TITLE
Change eraser tool cursor icon

### PR DESCRIPTION
**Pull request by manongjohn**
This PR addresses a request to remove or replace the eraser cursor icon of the eraser tool.

The "eraser" icon is a little intrusive when you are trying to erase something that happens to be where the icon actually is.  I also find it a bit distracting.

I have the replaced the Toonz Vector and Toonz Raster cursor icons from an "eraser" to the "plus" sign, that the regular Raster eraser uses.  Please note, the eraser type text and the line/area text that is part of the Toonz Raster cursor icon has also been removed.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
> The "eraser" icon is a little intrusive when you are trying to erase something that happens to be where the icon actually is. I also find it a bit distracting.

Can you make this change optional ? Since I'm not sure if all users think so.
IMO cursor icon can be helpful for users to know what type/option of tool they are using without moving eyes from where you are working to the tool options bar.

**Comment by manongjohn** [comment]
I can make it optional, though keep in mind the Raster eraser is not an "eraser" icon like the other ones and I personally like that better.  I feel it should be consistent across the board.

I toyed with the idea of just temporarily hiding it while actively erasing just in NORMAL mode (it's ok to keep it in other modes).  Perhaps that is a better compromise rather than creating yet another preference setting?

**Comment by shun-iwasawa** [comment]
The inconsistency in cursor icon between the raster eraser and other ones seems to existed in Toonz Harlequin and I hadn't modified it since Ghibli staffs had little chance to use the raster eraser.

> Perhaps that is a better compromise rather than creating yet another preference setting?

I agree with you !

**Comment by shun-iwasawa** [comment]
Well but now I'm bit afraid that the quick show/hide of icons according to the mouse action may become bothersome..

**Comment by konero** [comment]
That would indeed be bothersome. In ClipStudio you can disable cursor icons if you use a Cintiq or choose a specific cursor icon for each tool type including its orientation for certain cursors, this can be done within its own preferences menu area, which would be OK.

clipcursor

I'm actually left-handed, so in most programs when I use a tablet, cursors are usually backwards for me. In Clip, I use a top-right facing triangle. 👍 

In DigiCel FlipBook, it's just two options. Simple Cursors means a cross, Left-handed means flip the cursor horizontally.

digicursor

**Comment by manongjohn** [comment]
Preferences it is! 😊

I will cancel this PR and incorporate a cursor preference feature into PR #1960, probably something similar to the DigiCel Flipbook example.

Thanks @shun-iwasawa and @konero for the feedback.

**Pull request closed without merging**
