### PR TITLE
Updates to the Windows Build Instructions

### PR DESCRIPTION
**Pull request by DoctorRyan**
Submitting some changes to the Windows Build Instructions.  Sorry about the other crap.  All I wanted was to send the MD file.  All the others are just merging I made to my OT-Black Repository from the main branch so it shouldn't hurt anything.

### CODE REVIEW

**Comment by manongjohn** [comment]
Not sure what you did, but you have extraneous merge commits in your branch.  Granted, they do not appear to be merging any new changes, but makes for a messy commit history.

**Comment by DoctorRyan** [comment]
Yeah sorry.  Next time I think I just have to make a new branch with just the one changed file.  And send it over.  That's why I sent it over as a draft to make sure.

**Comment by manongjohn** [comment]
I would suggest using branches instead of updating your master directly so that your next branch from your master doesn't contain extra stuff that might not be going to OT. If you have several PRs in the works, that could become a problem if you don't.

**Comment by DoctorRyan** [comment]
Yes sir.  I am actually in the process of rearranging all that.  Thank you.

**Pull request closed without merging**
