### PR TITLE
add segment mode in eraser tool

### PR DESCRIPTION
**Pull request by pojienie**
This PR allows you to remove segments when using eraser tool

video: https://youtu.be/Nspvo_WSOs8
related PR: #3178

name choice: since @beeheemooth mentioned that "segment" is already used in fill tool

Algorithm:

1. find all strokes intersect with eraser and where they intersect
2. find closest intersection for each intersection with eraser to form a range
3. merge all ranges of the same stroke by using interval merging algorithm
4. make complement range
5. actually do the erasing and construct undo data

It doesn't support invert and frame range yet. It doesn't support raster level. Since freehand mode is already in place, I used its code to do everything except actually erasure.

note that the problem where it wouldn't be able to detect intersection like this still exist. Because the root cause wasn't fixed yet.
 a

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Looking good thus far.

segment erase

I confirm our old enemy the old Case 1 non-interesection registering segment.
That certainly is a pain.
For a workaround I'm currently using the Cut Tool to go in and quickly dissect the line at that intersection so that segment erasing will remove the troublesome segment.

I'm running into an issue where a small section of the segment that is erased remains.
My current theory is that it is the little hook that tends to appear at the end of a vector line in many cases. Reference #2526 and #2861 for more information on that.

Here's the PLI file if you want to use that.
[horse.zip](https://github.com/opentoonz/opentoonz/files/4401344/horse.zip)

**Comment by RodneyBaker** [comment]
Experiencing a lot less problems as I get use to the workflow...

horse

**Comment by pojienie** [comment]
@RodneyBaker Thank you for testing!

About the "case 1" problem: As I said it in the PR, I didn't solve the root cause (actually, I couldn't). But this PR should mitigate such problem as you can now remove two strokes at once, like so:

test 0001

The red line indicates where I use the eraser. In the top row, if you remove strokes one by one, you'll encounter the problem. However, if you remove two strokes at once as in the bottom row, it will correctly detect the intersection and remove the strokes you want to remove.

About the other problem: Your theory is probably right since those "hooks" also appeared in your horse.pil file. I'm sure this issue should be solved when the line is drawn instead of in this PR.

**Comment by RodneyBaker** [comment]
Posting my intent to merge this as is.
Open call for testing!  :)

Here's a link to the appveyor build (for Windows) for those so inclined that do not build locally:

https://ci.appveyor.com/api/buildjobs/jtva65vp3k2n1eps/artifacts/toonz%2Fx64%2FOpenToonz.zip

You'll want to rename the Opentoonz stuff directory as 'portablestuff' and drag/drop it into the Opentoonz directory.  That will ensure you are getting everything built from this PR.

**Comment by jrhyme** [comment]
Maybe Shun will come and combine it into a night build?) Or I misunderstood ..

**Comment by RodneyBaker** [comment]
It can be put into a nightly build right now but... testing... testing first.  ;)

**Comment by jrhyme** [comment]
Nightly builds will be updated and this function hangs in the list like the rest) as you wish) In any case, we will test everything, otherwise there will be no version 1.5.

**Comment by RodneyBaker** [comment]
Time to get this into the hands of more users.

**Comment by beeheemooth** [comment]
@pojienie Great job! Thanks!
Users ask if the Eraser Tool can be switched to Segment mode while holding down the Ctrl or Alt button. If not, will there be a hotkey for the "Segment" type?

**Comment by jrhyme** [comment]
I think everything will be with time)

**Comment by pojienie** [comment]
@RodneyBaker Thank you for testing and merging!

@beeheemooth Thank you! I've thought about adding the shortcut but it will take me some time to study the shortcut system.

**Comment by gab3d** [comment]
@pojienie 
I know I'm late, but just didn't want to miss the opportunity to say a big thank you for this feature.
It's amazingly good, and much certainly one of the top requested features by users since long ago.
So, kudos to you! 🥇 
It's so refreshing to have you onboard!

Regarding @beeheemooth suggested "Ctrl" feature, it'd certainly be a great way of using it on the fly.

**Comment by pojienie** [comment]
@gab3d Thanks!

I have added all shortcuts in #3213 so hard-coded control key is not needed now.

**Comment by gab3d** [comment]
@pojienie 
thanks, I've just seen that PR and surely it adds more workflow possibilities than just the Ctrl variant suggested, and also for a lot of other tools.
you've done a great work! :)

one question I'd like to make is (although perhaps I didn't fully understand the workflow of using the new shortcuts available), as far as I understood if, for example, you use the assigned "Eraser - Segment" shortcut to erase some stroke segments; then you use the Brush tool shortcut (B) to draw some more strokes; and finally you use the (E) shortcut to be able to manually erase some parts of a stroke. 
What would be the state of the Segment option when you activate the Eraser tool through the E shortcut in the last step?

if the Segment option is to remain active, this could slower the workflow (because the user would need to deselect the option, before being able to use the standard erasing mode). 🤔

**Comment by pojienie** [comment]
@gab3d Yes, after 3rd step (pressing E to switch to eraser tool) the eraser will be in segment mode. But you can always use other shortcuts to change that (I added shortcuts to all modes so you can always, say, use "Eraser - Normal" shortcut to switch back to normal mode)

I am against the temporary switch (holding control and it is segment mode, otherwise it's the previous mode) because of two reasons:

1. I don't want to hard-code it
2. why does only segment mode have this special treatment? And what if other users think it's more intuitive to have rectangular mode when holding control? How about users who wants "freehand" mode when holding control? Whose opinion is more important?

The above, of course, is just my opinion. But I'm the developer of this PR so I get to call the shots :stuck_out_tongue: That said, if other developers want to do it, I won't intervene :wink:

**Comment by gab3d** [comment]
@pojienie 
Thank you for the explanation.
Yes, undoubtedly from a functionality standpoint the possibilities are all there, and are almost endless for a lot of tools, and not just Eraser, and that's certainly great. :)

Having said that, and viewing it now from a pure workflow (and also from a new user's) perspective though, I think the solution offered right now is a little cumbersome.
Basically, two main things to consider:
- Standardization. The new "Eraser - Segment" function has no default shortcut assigned.
- Simplicity. I predict the standard shortcut for Eraser will be "Eraser - Segment", so 'E' shortcut would be effectively superfluous, as it offers less functionality (it activates the tool, but it doesn't change the Segment option).

So I think that either we should make the 'E' shortcut control de "Eraser - Segment" function or preserve it like it is right now, but enable a modifier key (such as Ctrl) to temporarily activate the Segment option to have a strong performance while using this awesome new feature.

I would like to know what others think about it as well...

**Comment by RodneyBaker** [comment]
Having 'E' be the default for Erase - Segment wouldn't work for the default level type; toonz raster.

**Comment by RodneyBaker** [comment]
Just a follow up note to announce that segment erase for raster levels (smart raster) can now be tested via Tahoma appveyor artifact:

https://ci.appveyor.com/project/turtletooth/tahoma2d/builds/36395193/artifacts

**Pull request merged**
