### PR TITLE
Update and upload all files for AOTz v0.5!

### PR DESCRIPTION
**Pull request by andeon**
Add new brushes and fixes!

Reorder some brushes, watercolor texture split into two new texture brushes ground and stone.

Initially I had locked the surface brushes to work only with grayish color, but I decided to enable it to all color models. Now quick paint is gonna be easier.

https://user-images.githubusercontent.com/11843239/170346340-81850fb3-5f7e-4900-a1ef-3f26b55df571.mp4

#4437 

PS, Test it on appveyor artifact; Windows and Linux still broken, not sure about macOS.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Thanks @andeon for the update.
I've started testing brushes.
Due to the fact that the github action artifacts won't be useful in testing I won't delay merging too long so that users can dive in more deeply via the nightly release and push the updated brushes to thier limits.

Rather unrelated to this brush update...
I am just now noticing the options to compare removed/deleted images to added images via github and these brush icons make that a very useful feature.  Options include 2-up, swiping (slider comparison) and onion skin (that blends the two images to varying degree).  Quiet useful.

image

**Comment by RodneyBaker** [comment]
I'll delay merging of this PR for a while as the windows nightly builds are not being generated and that is an important aspect of merging this.

**Comment by andeon** [comment]
I'm convert the brushes to work in OpenToonz built with libmypaint v1.3.0 too. The Impasto brush had to be redone to work, but it I tried kept the concept.

**Comment by andeon** [comment]
@RodneyBaker I'm checking it again, you can ignore the last commit or I need reset or revert it? I see the libmypaint-1-4-0 is what is come and is used with OpenToonz, right?

If I try keep compatible brushes it lose a lot functions, anyway all them working at Opentoonz 1.6.0 version.

**Comment by artisteacher** [comment]
I get a crash on open on macOS Monterey when I try to use the action build. I can open the action build from #4388 without issue. Here's the crash report:
[mac-open-crash.txt](https://github.com/opentoonz/opentoonz/files/8818967/mac-open-crash.txt)

It looks like there's a missing library.

**Comment by andeon** [comment]
> I wonder if it's a problem with the action build settings rather than the PR itself?

@artisteacher  That's probably it. But could you download the brushes and test in your environment? https://github.com/andeon/aotz/archive/refs/heads/master.zip, just to make sure there are no issues with the brushes.

**Comment by artisteacher** [comment]
Why do some have the raster icon? Most of those do work on toonz raster levels...

**Comment by andeon** [comment]
I put the "raster level" icon as a big recommendation to use that level, and when it comes with a red border too, it's flag for users that it doesn't work in "Raster Level Toonz". Fully painted potential only works at "Raster level", so I hope it helps users to see the reason for the recommendation that Mypaint brushes must be used primarily on the Opentoonz "Raster Level".

**Comment by RodneyBaker** [comment]
@andeon Unless you have a specific reason to delay further I plan to press forward with this PR.
The primary concern I have is not with the PR but the current build environment and that appveyor isn't fully propagating the nightly releases (for Windows).  That has nothing to do with you or your changes however.

**Comment by andeon** [comment]
@RodneyBaker Go ahead, I tested the brushes on Linux and Windows and since the Artisteacher test it macOS I believe that not have any issues.

**Comment by RodneyBaker** [comment]
Thank you @andeon for the excellent brushes and the time and thought you've put into this update.
LGTM

**Comment by RodneyBaker** [comment]
As anticipated the nightlies didn't get pushed out so...
In the interim those that would like to use these updated mypaint brushes are encouraged to download the zip file and place them in the appropriate location in the opentoonz stuff/library/mypaint/aotz directory.  The link to the zip file is posted above but here it is again for convenience:

https://github.com/andeon/aotz/archive/refs/heads/master.zip


cc:  @shun-iwasawa

**Pull request merged**
