### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hnhparitosh**

### CODE REVIEW

**Comment by hayoko** [comment]
What is this?

**Comment by hnhparitosh** [comment]
Hello
I am a engineering student and an animator.
Currently I plan to make a lite version of opentoonz for old computers.
Paritosh

**Comment by manongjohn** [comment]
If you are making a separate repo for a Lite version of OT, you do not need to push those changes to the main OT repo.

You may want to copy, not fork, OT's repo as a separate repo in your account that is not linked to the main one so you can make all the changes you want.

**Comment by RodneyBaker** [comment]
@hnhparitosh  Please keep us informed on your progress.
I've toyed with the idea of creating an OTLite for a long time but don't really have the programming skills to tackle it.  Having a lite version of Opentoonz will be very educational and much appreciated.

**Pull request closed without merging**
