### PR TITLE
Startup Popup: Highlight "Open Recent Scene" items on mouse hover

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR modifies Startup Popup, changing background color of "Open Recent Scene" items on mouse hover in order to make it clear for users that they are clickable. Also added a tool tip showing the full scene path.

### CODE REVIEW

**Comment by turtletooth** [comment]
Tested and works well.  All this needs is a Jenkins.  Thanks @shun-iwasawa

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
LGTM- thanks @shun-iwasawa

**Comment by artisteacher** [comment]
In Mac OS X El Capitan, the tooltip works but the changing background color on hover is not working.

**Pull request merged**
