### PR TITLE
remove tArrayCount macro by otakuto

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is based on #2427 by @otakuto , with resolving conflicts.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by RodneyBaker** [comment]
This PR still has some conflicts:  [Link](https://github.com/opentoonz/opentoonz/pull/2688/conflicts)

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
LGTM Thank you @otakuto for refactoring!

**Pull request merged**
