### PR TITLE
Modified: Linked styles enabled and style right click menu organized by turtletooth

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for the issue #520 and based on the PR #628 by @turtletooth 

@turtletooth did almost everything so I just modified minor parts as follows:

- Use TStyleSelection::removeLink() instead of TStyleSelection::eraseToggleLink(). The former function takes care of removal of "original name" which is newly added from Ghibli Edition.
- Show these commands without right-clicking the linked style. Which makes easier to apply these commands to all styles in the palette.
- Removed default shortcut for "Toggle Link to Studio Palette" as it can be added by users afterwards.
- Removed confirmation dialog on save studio palette, asking whether to update linked styles.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
@blurymind 
Regarding this problem you reported in #628 :


Sorry for my late response, but IMO this was not a bug. Please check whether the styles "test" and "color_2" in the studio palette were created with "New Style" command or copy&pasted from another studio palette.
If the styles are created with "New Style" command, it becomes a "parent" of the link. If the color is copy&pasted from another studio palette, it becomes a "child" of the copied one even if they are pasted in the studio palette. And the update of linked color is only available from "parent" to "child".
To identify "parent" or "child" of the link, change the palette display mode to "Large Thumbnails View" and "Both Names". The style name of the parent (="original name") will appear on the top-left corner only in the "child" styles.
A diagonal line on the style chip means that it is the style with reference to studio palette, but its color is changed from the "parent" style in studio palette.

**Comment by turtletooth** [comment]
Thanks for looking at this @shun-iwasawa I didn't quite understand all that was going with the links and got stuck.  Thanks for taking care of the rest.

**Comment by turtletooth** [comment]
@shun-iwasawa When I right click a project palette and select "Load into Current Palette" the new colors in the level palette don't update when I choose "Toggle Link to Studio Palette" or "Get Color from Studio Palette" - I think this is the issue that @blurymind was talking about above.  My styles are original to the project palette (not copied from elsewhere). 
Also, what do you think about hiding the option to update the link, get color, and remove reference for styles that are not linked to a color?

**Comment by turtletooth** [comment]
Ok, I can make it easy to duplicate:
1. Have a Project Palette with some colors
2. Create a new level
3. Load Project Palette into Studio Palette
At this point- toggling the link works and getting the color works.
4.  Make a change to the project palette (change a color to something else)
5.  Save the project palette
6.  Linking and gettting color don't work anymore.

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you for the reviews, I'll fix it right away.

**Comment by shun-iwasawa** [comment]
- Hide commands from context menu if there is no linked style in the selected styles.
- Fixed problem that the style link becomes unavailable after using "Load into Current Palette"

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by blurymind** [comment]
@shun-iwasawa  this is big to me. Thank you for the fixes!
Will test it asap 
:+1: 
@turtletooth  thank you for explaining the problems with linking

**Comment by turtletooth** [comment]
That seems to have fixed it.  Thank you so much @shun-iwasawa - It is very useful.
Looks like the mac build on Travis stalled.  It is ready to merge though.

**Comment by turtletooth** [comment]
LGTM.  Merged.  Thanks so much for fixing this @shun-iwasawa

**Comment by blurymind** [comment]
AWESOME! Thank you guys :)

**Pull request merged**
