### PR TITLE
Refresh the current folder items of the File Browser automatically

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for the issue #375 
I made mainly two modifications as follows:
- Monitor the current folder path with QFileSystemWatcher and refresh the item viewer panel  whenever the folder contents is modified or removed.
- Add a button for "Refresh Folder Tree" command on the buttons bar of the File Browser.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by kogaki** [comment]
Wow! It works OK, and I feel it's very convenient. 👍

**Comment by kogaki** [comment]
But.. `Refresh Folder Tree` button is not intuitive to me. Is it cost to watch `tree` folders and tell new children are created or not? At least, we can't understand it's function by only word `Refresh`.

**Comment by shun-iwasawa** [comment]
I modified the points as follows:
- Making the folder tree to be monitored as well. Please note that only the expanded folders in the tree will be monitored in order to minimize the consumption of system resources. I tried to monitor 300 directories at the same time and it seemed not causing notable delay in my environment.
- Removing the "Refresh" button which I added in the previous commit. "Refresh Folder Tree" command may become unnecessary as the folder tree is now made to be updated automatically.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by kogaki** [comment]
@shun-iwasawa Those changes make this UI more better. Thanks. It works nice in my OSX.

**Pull request merged**
