### PR TITLE
add linux desktop data

### PR DESCRIPTION
**Pull request by eszlari**

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by shun-iwasawa** [comment]
I can't check how this works on Linux but I'll merge this anyway, as I could at least verify that this PR seems not to cause any problem on Windows and OS X versions.
Thank you @eszlari for addition ! LGTM

**Comment by eszlari** [comment]
Thank you! Could you update `<releases>` when there is a new version?

**Comment by shun-iwasawa** [comment]
> Could you update `<releases>` when there is a new version?

Updating [this part](https://github.com/opentoonz/opentoonz/blob/master/toonz/sources/xdg-data/io.github.OpenToonz.appdata.xml#L29-L31) ? Understood. :+1:

**Pull request merged**
