### PR TITLE
Use ninja to build on Travis

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
AppVeyor failed because LFS exceeded rate limit:
> `Error downloading object: thirdparty/tiff-4.0.3/lib/LibTIFF-4.0.3_2015d.lib (c4dfbbc): Smudge error: Error downloading thirdparty/tiff-4.0.3/lib/LibTIFF-4.0.3_2015d.lib (c4dfbbc0a9446626227bd6ea2a930b5b3dc83d2295c08459bc3b6f6920e288d7): batch response: Rate limit exceeded: https://github.com/opentoonz/opentoonz.git/info/lfs/objects/batch`

**Comment by RodneyBaker** [comment]
@janisozaur  Any words of wisdom related to this request?
Is this something more likely to slip to the 2019 release cycle?

**Comment by RodneyBaker** [comment]
Inclusion of this enhancement appears to have slipped to the 2019 development cycle.
Also:  see branch conflicts.

**Comment by RodneyBaker** [comment]
@janisozaur  Can you provide some additional information on benefits of using Ninja for Travis builds.
I know these may seem obvious to developers that use Ninja but this is an attempt to see if we can add this now (along with v1.4 release) as opposed to later.

I'll add a note to the other recommendation to add ninja to Appveyor as well.
I'll add a link to here for informational purposes.

Thanks!

**Comment by janisozaur** [comment]
Ninja provides faster build times over nearly any other build system, especially over the slow as a snail msbuild. Additionally, it brings sanity to compiler output, outputting messages next to relevant status line. See a snippet from another project (using msbuild)
Before:
```
  LHVMViewer.cpp
C:\projects\openblack\src\LHScriptX\FeatureScriptCommands.cpp(240,24): warning C4244:  '=': conversion from 'double' to 'float', possible loss of data [C:\projects\openblack\_build_vs-16-2019-win64-cxx17_Debug\openblack.vcxproj]
C:\projects\openblack\src\LHVMViewer.cpp(171,54): warning C4267:  'argument': conversion from 'size_t' to 'int', possible loss of data [C:\projects\openblack\_build_vs-16-2019-win64-cxx17_Debug\openblack.vcxproj]
  MeshViewer.cpp
  Renderer.cpp
C:\projects\openblack\src\LHVMViewer.cpp(213,109): warning C4267:  'argument': conversion from 'size_t' to 'int', possible loss of data [C:\projects\openblack\_build_vs-16-2019-win64-cxx17_Debug\openblack.vcxproj]
```
After:
```
[32/50] Building CXX object CMakeFiles\openblack.dir\src\LHVMViewer.cpp.obj
..\src\LHVMViewer.cpp(171): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
..\src\LHVMViewer.cpp(213): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
```

**Comment by RodneyBaker** [comment]
Thanks for the additional detail @janisozaur 
A cursory review suggests Ninja would be a useful addition to v1.4 builds for both Travis and Appveyor.

I've pull this out of 'hiatus' for review and decision making by @shun-iwasawa @turtletooth @manongjohn 

See also:  #2765

**Comment by manongjohn** [comment]
Please resolve the conflicts. In both cases, it seems the master changes should be kept

**Comment by RodneyBaker** [comment]
Adding ninja for appveyor and travis builds appears to be slipping to 2020 Development Cycle.

**Comment by RodneyBaker** [comment]
Closing (for now) as not finding enough interest to move forward.
Please continue discussion where there is continuing interest in seeing ninja integrated into Opentoonz github.

**Pull request closed without merging**
