### PR TITLE
Introducing $scenefolder Alias

### PR DESCRIPTION
**Pull request by shun-iwasawa**
Implemented #1488 

- Introduced a new alias `$scenefolder` . If you put it at the head of file path, when the file is actually saved/loaded such alias will be replaced by a path to "parent folder of the current scene file" .

- Added a new preference option to specify which alias will be prioritized between the project folder aliases (e.g. "+drawings", "+extras", etc.) and the `$scenefolder` alias.
  - Let’ say that the current scene is saved in `C:/myproject/scenes/foo/bar/myscene.tnz` under the project with the alias `+scenes` is set to `C:/myproject/scenes`. When you save a level "A" at `C:/myproject/scenes/foo/bar/baz/A.tlv` , such path can be expressed in two ways - `+scenes/foo/bar/baz/A.tlv` and `$scenefolder/baz/A.tlv` . So, this option can specify which aliases will be taken on this alternative.
  - There are 3 options as follows; Prioritize `Project Folder Aliases`, `Scene Folder Alias`, and `Use Project Folder Aliases Only` . The default value is `Use Project Folder Aliases Only`, which will never use the `$scenefolder` alias on coding the path, and can be used as the same condition as the existing version.

- Added a new tree node "Scene Folder" in the File Browser. It will give direct access to `$scenefolder` .

- Please note that saving with the `$scenefolder` alias and the "Scene Folder" node is only available when the scene is already saved (i.e. not "untitled"). If you save some level using the alias in some untitled scene, a warning popup appears with a message saying "Save the Scene First".

### Disadvantage of $scenefolder

- If you use `Save Scene As` command and save the current scene in the different folder, levels specified with `$scenefolder` alias will lose access to file and will not open properly when you load the scene later. I made a warning popup to open for such situation to prompt users to update the level path.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by turtletooth** [comment]
> If you use Save Scene As command and save the current scene in the different folder, levels specified with $scenefolder alias will lose access to file and will not open properly when you load the scene later. I made a warning popup to open for such situation to prompt users to update the level path.

I don't know if this is practical, but could all loaded levels be saved in the new location as well?

**Comment by shun-iwasawa** [comment]
> I don't know if this is practical, but could all loaded levels be saved in the new location as well?

Well, I intentionally made the levels not to be saved in the new location automatically, because there may be a case that some another file already exists in the new location. 
By adding the dirty flags, you can choose the option to save all of them in the new location from the warning popup on closing the scene. I think `Save All` command will also work for saving them in the new locations.

**Comment by shun-iwasawa** [comment]
@turtletooth 
I realized that it is difficult to save the levels afterwards if there is no image cache left.
So, I changed my mind and modified the behavior based on your idea. (thanks!) 
On using Save Scene As command and saving the current scene in the different folder, the question dialog will appears asking to choose from the options as follows:

image

Jenkins

**Comment by shun-iwasawa** [comment]
Conflicts resolved. 
Jenkins again

**Comment by masafumi-inoue** [comment]
LGTM

**Pull request merged**
