### PR TITLE
Enable MyPaint Brush for Toonz Raster Levels

### PR DESCRIPTION
**Pull request by shun-iwasawa**
image

This PR will enable MyPaint brushes on Toonz Raster levels.

- For now, only "additive" brushes are available. Brushes which erase or blur existing drawing can be selected, but will not work.
- The class `BrushTool` is separated into `ToonzRasterBrushTool` and `ToonzVectorBrushTool` for clarification.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by gab3d** [comment]
I didn't think this would be possible! 😋 
thanks!!

**Comment by artisteacher** [comment]
I’m looking forward to trying this out! Will it be possible to add the blur/blending styles later on?

**Comment by turtletooth** [comment]
Try it out here: https://github.com/turtletooth/OpenToonzPortable/releases/tag/0.0.0.1

I've also included @manongjohn 's updated schematic controls and the sound enhancement from @morevnaproject

**Comment by turtletooth** [comment]
I absolutely love this.  Thank you so much @shun-iwasawa

**Comment by shun-iwasawa** [comment]
Just like PhotoShop and other software, I'm thinking of separating the MyPaint brush shape information from the styles and the Style Editor in the future development... Which means that some new widget for selecting / registering user's preferred brush shape will be introduced and you can select color and brush shape independently. It's just an idea so please let me know what you think.

@artisteacher 
> Will it be possible to add the blur/blending styles later on?

Well, since the pixel data is totally different between raster and toonz raster, I don't come up with how to realize blur/blending. Erasing would be simpler.

Jenkins again

**Comment by beeheemooth** [comment]
This is so cool!!!

But I have a lot of questions.
1. Will the brushes MyPaint in Toonz Raster level be categorized as lines or areas?
2. How will I fill in styles where there are semitransparent pixels or antialiasing, and can the Fill Tool be configured to produce different results?
3. Will the options be  "Lock Alpha " and  "Eraser "?
4. How will the Tape tool, Finger tool behave? (In case the brushes MyPaint will draw lines)
5. Will this innovation affect the current workflow in Toonz Raster levels?
6. What will be the conversion of the Toonz Raster level to Vector level and back in the case of "Preserve painted areas "? 
7. How will the styles of common border be mixed?

This is only a small part of the questions raised.

Thank you very much for your work! You have no idea how happy I am about this news!

**Comment by shun-iwasawa** [comment]
@beeheemooth 

> 1.Will the brushes MyPaint in Toonz Raster level be categorized as lines or areas?

Lines.

> 2.How will I fill in styles where there are semitransparent pixels or antialiasing, and can the Fill Tool be configured to produce different results?
> 4.How will the Tape tool, Finger tool behave? (In case the brushes MyPaint will draw lines)
> 6.What will be the conversion of the Toonz Raster level to Vector level and back in the case of "Preserve painted areas "?

The other tools and features remain unchanged, so some of them will not work as you imagined when you use them to mypaint-generated lines, especially ones with large semi-transparent regions.

> 3.Will the options be "Lock Alpha " and "Eraser "?

They are currently omitted for the brush on toonz raster level. Probably introduced in the future development.

> 5.Will this innovation affect the current workflow in Toonz Raster levels?

Well, I hope this will extend a range of expression of animation drawings.

> 7.How will the styles of common border be mixed?

When you draw lines over the existing drawing with the same style, the stroke will be multiplied. 
When you draw lines over the existing drawing with different style, each pixel in the new stroke will compare the line opacity and change the ink index if the one of the new stroke is higher. 
Note that it's exactly the same behavior as the conventional brush tool.
Please see [here](https://github.com/opentoonz/opentoonz/blob/fef87023bf991d99912b2c951efded6d3f1b6f0d/toonz/sources/tnztools/mypainttoonzbrush.cpp#L27-L35) in the source for details.

**Comment by openanim** [comment]
Wow ! :D

Thank you for this improvement!

> Which means that some new widget for selecting / registering user's preferred brush shape will be introduced so that you can select color and brush shape independently. It's just an idea so please let me know what you  think.

Great ! If I understand correctly, the brushes that are saved with the drop-down menu will be available on a dockable panel ?

Another suggestion for future development also would be to have customizable tips and dynamic parameters.

**Comment by RodneyBaker** [comment]
@turtletooth   Just a heads up.
I attempted to use this latest OTX and I get an error on trying to start.
Another user got that same error.
Perhaps this suggests a different release of QT being installed/used on your system?

otx error

**Comment by openanim** [comment]
by testing this PR, I noticed that changing its settings does not work.
test_mypainttlv

**Comment by turtletooth** [comment]
@openanim I think that has to be that way since the Toonz Raster can't handle hue shift within a single color.

**Comment by turtletooth** [comment]
@RodneyBaker Thanks for catching that.  I'm using a new version of Qt and forgot to replace some of the DLLs with the new ones.

**Comment by RodneyBaker** [comment]
For those interested the appveyor release works:

https://ci.appveyor.com/api/buildjobs/cdgbfk7up17fy27o/artifacts/toonz%2Fx64%2FOpenToonz_1.2.zip

**Comment by shun-iwasawa** [comment]
@openanim 
@turtletooth 's explanation is perfect. It only uses the alpha channel of stroke. Color of the stroke is ignored and the current style is used instead.

**Comment by manongjohn** [comment]
Any chance that unusable settings on Toonz Raster levels can be grey'd out to avoid confusion?

**Comment by turtletooth** [comment]
The link to the testing version is up and working now.  Please test out the new schematic features my @manongjohn and the improved scrubbing change by @morevnaproject 

https://github.com/turtletooth/OpenToonzPortable/releases/tag/0.0.0.1

**Comment by artisteacher** [comment]
The brushes themselves work great! I think how fills work with the mypaint brushes could use some refinement with the more transparent brushes:
screen shot 2018-08-23 at 10 37 12 pmscreen shot 2018-08-23 at 10 37 19 pm
On a related note, the paint brush tool (when set to areas) paints over translucent mypaint lines:
screen shot 2018-08-23 at 10 47 35 pm
I'm also getting a crash when switching to the vector tab of the style editor.
[mypaintcrash1.txt](https://github.com/opentoonz/opentoonz/files/2316880/mypaintcrash1.txt)
[mypaintcrash2.txt](https://github.com/opentoonz/opentoonz/files/2316881/mypaintcrash2.txt)

Less importantly, the toonz color blending fx gets interesting results with areas of transparency too:
screen shot 2018-08-23 at 10 41 42 pm

> I'm thinking of separating the MyPaint brush shape information from the styles and the Style Editor in the future development

Would the vector brushes be separated out too? That could add more clarity especially since the generated vector brushes and vector fills are not always obviously different to new users. 

When using the mypaint brushes, I like to set my colors in the level palette & then I keep switching between the different brush types. Having brushes separated out could work well for my own workflow  - especially if I could keep both the colors and brushes visible at the same time. 

Separating out the brushes could also be a great opportunity to add better organization to the mypaint brushes. At minimum, we really need a way to favorite brushes (for quick access) or for the most recently used brushes to display on top.

**Comment by shun-iwasawa** [comment]
@manongjohn 
> Any chance that unusable settings on Toonz Raster levels can be grey'd out to avoid confusion?

It seems to be possible, but will be a future development. I'm not yet so familiar with how each parameter of mypaint brush affects to the appearance of the stroke...

@artisteacher 
Thank you for testing the build. As you can see, painting area with the paint brush tool would be a practical workaround when you fill inside of the lines with large semi-transparent area.

> I'm also getting a crash when switching to the vector tab of the style editor.

I couldn't reproduce the crash yet. 
Does the crash seem to be related to this PR? Or can you reproduce the crash with the nightly build as well? 

> Would the vector brushes be separated out too?

For now, I don't think so. Vector is quite different from the other two types.
I guess you need to alter the level file format to achieve the separation for vector brushes.

**Comment by openanim** [comment]
@turtletooth @shun-iwasawa, I understand, thanks for explanations. I guess also that's why my dynamic color brushes do not work on toonz raster level.

But it would be amazing if the changes could be supported to take advantage of raster toonz styles, in the future. Now that you have unlock their huge potential on this level :)

dy_brush

> Which means that some new widget for selecting / registering user's preferred brush shape will be introduced so that you can select color and brush shape independently. It's just an idea so please let me know what you think.

Just to correct me because I think I made a counter sense on this issue. I understand it better with the artisteacher answer. I really like the idea that you are tackling this question even though I have a hard time pronouncing myself.

Personally, I can not get too far on this issue. Although at first I will tend to think that it will ultimately depend on the implementation of this widget.

Will this window behave similarly to current windows ? 

Will it save space ? Because unlike others softwares it is not as easy to hide windows quickly or to embed them in other windows, in opentoonz. And, having tabs in the style editor saves space, in my case.

Will it be in the end, different to have 2 styles editor in one room one to change the color and the other for brushes or settings ?

**Comment by shun-iwasawa** [comment]
@openanim 

> Will it be in the end, different to have 2 styles editor in one room one to change the color and the other for brushes or settings ?

It may not be so different if you work on Raster levels, since they share the same palette `Raster Drawing Palette` and users can use it as a "customizable tool box".
For the Toonz Raster level, a palette belong to each level. So I think there should be an another way to register the brush shape settings outside of the level palette in order to keep consistency in line appearance among the levels. I think using the studio palette would be a practical measure until the separation.

**Comment by norrinra** [comment]
Dreams come truee

**Comment by artisteacher** [comment]
I'm not getting a crash with the nightly build, so it may be a problem with my build setup. That aside, my students and I have gotten similar crashes before so I do think there is a pre-existing issue - but it's usually one of those seemingly random crashes.

> painting area with the paint brush tool would be a practical workaround when you fill inside of the lines with large semi-transparent area.

If the paint brush tool is going to continue painting over translucent mypaint lines, I don't really see it being a helpful workaround for filling those areas. That's not the behavior with the standard translucent lines.

So is the proposed new brush widget just a change on the coding side and not the addition of a brush window or change in UI?

**Comment by shun-iwasawa** [comment]
Conflicts resolved and rebased. Jenkins again

**Comment by shun-iwasawa** [comment]
Conflicts resolved and rebased. Jenkins again

**Comment by norrinra** [comment]
oh my god it s coming !

**Comment by masafumi-inoue** [comment]
LGTM
ToonzRasterレベルの筆は一種類だったのが激増します

**Comment by norrinra** [comment]
Is there going to be .pkg for this release ?

**Comment by manongjohn** [comment]
Yes. It's in the latest nightly release you can get from this page: https://github.com/opentoonz/opentoonz/releases

**Comment by norrinra** [comment]
Thank you !

**Comment by norrinra** [comment]
Hello, I just tried the nightly(.pkg) from the link above and mypaint brushes didn't work on Toonz Raster. Since It didn't appear on nightlies listing yet (https://github.com/opentoonz/opentoonz_nightlies/releases)  I guess it needs time to get fully implemented on mac ?

Thank you

**Comment by shun-iwasawa** [comment]
@norrinra 
I found that Jen.kins had failed to generate the latest nightly build (including this change) for OS X. The build will run again on tomorrow morning. Thank you for your patience.

**Comment by norrinra** [comment]
@shun-iwasawa  I'm so grateful you're working on this. Thank you so much.

**Pull request merged**
