### PR TITLE
New Wide Screen Resolutions

### PR DESCRIPTION
**Pull request by DoctorRyan**
A request to add more wide screen resolutions to Opentoonz.

Co-Authored-By: Kite <konero@users.noreply.github.com>

### CODE REVIEW

**Comment by DoctorRyan** [comment]
Hello, once again.  Submitted for your approval are requests for more widescreen resolutions within Opentoonz.  Konero was kind enough to put together a list for me so he will be listed as a co-author for this.  As always I encourage discussion, feedback, and suggestions on this topic.  Do we need to take away from this list or add to it?  I look forward to hearing from you guys.  Also @shun-iwasawa I would appreciate your take on this as well.  Thank you very much.  Here are the entries for review:
WFHD, 2560x1080, 2.37037
WFHD+, 2880x1200, 24x10, 12/5
WQHD, 3440x1440, 43/18
WQHD+, 3840x1600, 12/5
UW 1800, 4320x1800, 12/5
WUHD, 5120x2160, 2.37037
UW 5K, 5760x2400, 12/5
UW 6K, 6880x2880, 43/18
UW 7K, 7680x3200, 12/5
UW 8K, 8640x3600, 12/5
UW 9K, 9600x4000, 12/5
UW 10K, 10240x4320, 2.37037

**Comment by jrhyme** [comment]
I told him (konero) that 3440x1440 UWQHD, That is Ultra WQHD - I even threw off the link to Wikipedia...

**Comment by konero** [comment]
In the articles they say "no single name is agreed upon" and list both, it doesn't bother me either way, feel free to modify the abbreviations.

One point though, you should move the changes to the bottom of the list since these are very uncommon for now, and keep the common formats at the top.

Maybe 5K, 6K, 7K, 9K and 10K is a bit much (very rare), could think about removing those ones (but keeping 8K). 😸

**Comment by RodneyBaker** [comment]
Yes, please don't have the average user wade past the highest resolutions to get to those that are more common.

**Comment by jrhyme** [comment]
> Yes, please don't have the average user wade past the highest resolutions to get to those that are more common.

It is logical that they need to be put below

**Comment by DoctorRyan** [comment]
I have moved the entries to the bottom of the list.  Sorry about that.  Please don't beat me @RodneyBaker

**Comment by shun-iwasawa** [comment]
@DoctorRyan 
If there is any online document you referred to for adding the new entries, can you please post the link for it ?

**Comment by DoctorRyan** [comment]
@konero did you get the entries from somewhere online?  If you did can you please post so @shun-iwasawa can take a look.  Thank you.

**Comment by DoctorRyan** [comment]
@ shun-iwasawa Here it is.  Let me know if you need anything else.  https://en.wikipedia.org/wiki/Ultrawide_formats#Ultrawide_Cinema

Annotation 2020-07-17 110050

**Comment by gab3d** [comment]
Let's add newer resolutions, it seems right.

At the same time I'm wondering myself if OT has troubles supporting the bigger ones, or if it works OK with everyone of them. 🤔

**Comment by DoctorRyan** [comment]
@gab3d I think I will be removing the 5k and above entries.  Only rich people have those.  Lol.  As for the others, it is for people with ultra-widescreen monitors.  While it will correct the ratios, I am not sure about the quality.  I only own a 1080p screen.  But there have been people asking.

**Comment by RodneyBaker** [comment]
@DoctorRyan Should we retitle this OR with (WIP) or set to hiatus?
Not trying to rush but progress seems to have at least temporarily stalled.

**Comment by DoctorRyan** [comment]
I would set to hiatus for now @RodneyBaker.  Probably not up there on the priority list right now.

**Comment by RodneyBaker** [comment]
@DoctorRyan Perhaps we don't need to set to hiatus here and can close this PR if we just add the text files in question with various screen resolutions added?  Then the user just has to download and put the files in place in order to have those resolution options in Opentoonz.

**Comment by RodneyBaker** [comment]
For anyone that wishes to use these particular resolutions the following two files (which are exactly the same except filename) can be downloaded and placed into the Opentoonz stuff/config directory.

[cleanupreslist.txt](https://github.com/opentoonz/opentoonz/files/5067333/cleanupreslist.txt)
[reslist.txt](https://github.com/opentoonz/opentoonz/files/5067334/reslist.txt)

**Comment by RodneyBaker** [comment]
tagging with 'resource'

**Comment by RodneyBaker** [comment]
Closing as a PR but please note the attached files that can be added and/or customized in previous post.

**Pull request closed without merging**
