### PR TITLE
CMake: Test for endian instead of guessing based on the platform

### PR DESCRIPTION
**Pull request by ideasman42**
Setting endian was making an arbitrary guess, this sets the value correctly.

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins, test this.

**Comment by ideasman42** [comment]
Any info on why this fails for OSX? This is basic stuff that should work fine on all platforms.

**Comment by janisozaur** [comment]
And OS X works on travis, the jenkins tests are super confusing as they sometimes seem random.

**Comment by kogaki** [comment]
So, it's OK to be merged.

**Pull request merged**
