### PR TITLE
(Hiatus) Apply clang's suggestions about grouping || and && operators

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by ideasman42** [comment]
General +1 for avoiding possible ambiguous `and/or` operators.

Did you check this produces identical Binary/ASM output?

Otherwise with large changes like this human error can cause bugs.

**Comment by janisozaur** [comment]
I applied `clang-tidy -fix`, so this must be what clang compiles anyway, regardless of parentheses being there or not.

Feel free to walk through the changes to inspect their correctness.

**Comment by ideasman42** [comment]
Nice, wasn't aware clang had this feature. LGTM then.

**Comment by ideasman42** [comment]
Could you post the command used to generate this patch?

Its currently conflicting, but its easier to re-apply the automated changes then to resolve.

**Comment by damies13** [comment]
@ideasman42 it looks like @janisozaur did give you the correct command line (see https://clang.llvm.org/extra/clang-tidy/index.html#using-clang-tidy)

clang-tidy appears to be part of clang extra tools, but I haven't figured out how to install them on osx.

Hope that helps.

**Comment by ideasman42** [comment]
@damies13 not using brew but have clang-tidy, did you try running it to get same/similar results?

**Comment by damies13** [comment]
No I didn't get that far,

It took me a while to find the command to install it on OSX, so I just ran --help and checked the options, That was all I had time for that day.

**Comment by RodneyBaker** [comment]
Initiated a review of PRs to determine which are still active and desired.
I tagged this PR as 'roadmap' back in March assuming it is still being worked on but that may no longer be the case.

As one of the oldest PRs still open it's been active since Nov 2016.
Any updates, insights or discussion to bring this up to date?

**Comment by RodneyBaker** [comment]
Not sure of the current status of this PR.
@janisozaur Is this still being pursued?

**Comment by RodneyBaker** [comment]
Closing as abandoned.

**Pull request closed without merging**
