### PR TITLE
v1.1.2

### PR DESCRIPTION
**Pull request by shun-iwasawa**

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Thanks so very much for this latest release.
It is pulling so many useful features, fixes and enhancements into it it's
hard to count them all.

Of note regarding installation on Windows 10 (and presumably other Windows
installations)::
Users will likely have to rename or remove the file "t32bitsrv" in he SRV
directory where OpenToonz is installed.
I simply renamed the file "t32bitsrv(bad)" but that might not be optimal
for everyone.

**Comment by shun-iwasawa** [comment]
@RodneyBaker Thank you for the quick report. 
I found that the necessary file (32bit version of QtGui.dll) is missing in "srv" folder. Sorry to trouble you but please wait until the hot-fix will be released.
Removing or renaming "srv" folder is a good workaround if you do not need QuickTime MOV export.

**Comment by RodneyBaker** [comment]
@shun-iwasawa
Thanks much for the quick fix as well as information about what the renaming workaround disables (I had forgotten).  As I do use .MOV I much prefer the full fix.  :)

I know others will appreciate the 32bit QtGui.dll fix as well!

**Comment by RodneyBaker** [comment]
This t32bitsrv.exe issue appears to have returned in latest nightlies.

cc:  @shun-iwasawa

**Pull request merged**
