### PR TITLE
Fix Raster Tool Bar Plastic Tool Icons

### LINKED ISSUE #3154: Plastic Tool Icon is Pixelated
I noticed despite being an SVG this icon in the tool bar is pixely, but it turns out it's just an SVG with a raster image in it...

### Issue Summary
The plastic tool's icon in the toolbar is pixelated, unlike all the other tools there

### Screenshot or Video Reference
Screen Shot 2020-03-16 at 2 45 17 AM

### Steps to Reproduce
Look at the icon on a high resolution display, or zoomed in on its file in the code

### Expected Results
It to be vector graphics

### Actual Results
It's raster (aka pixely)

### System Information
* **OpenToonz Version**: 1.4.0, nightly
* **Operating System**: macOS Catalina
* **CPU**: i5
* **Memory**: 8 GB DDR4
* **Graphics Card**: 
* **Graphics Tablet**:

### PR DESCRIPTION
**Pull request by MrBlockCat**
Fixes #3154

Despite being an SVG, the Plastic Tool's icons in the tool bar were raster, making them pixely on high resolution displays. This makes the SVG file use only vector graphics, as the other tools in the tool bar do.

### CODE REVIEW

**Comment by MrBlockCat** [comment]
Unfortunately, I can't test that this works since I haven't set up a build environment, I just have the nightly build. I doubt this causes issues since both files were .svg before, but it would be great if someone could make sure!

Also, this is my first pull request here, thus the slightly messy commits to this... Sorry! The resulting files should be fine though

**Comment by RodneyBaker** [comment]
I'll check the change out once the appveyor build completes.

Aside:  It currently hasn't moved forward but the proposal to add github actions would automate builds for windows, mac and (I think) linux.  That might be something we can leverage in the future.

**Comment by MrBlockCat** [comment]
Thanks!

And automating the building would be great, it looks like it would take a long time for me to set up as it stands, haha. Any idea when those GitHub actions might be pushed?

**Comment by RodneyBaker** [comment]
The checks have to pass before I can do any testing but I've already reviewed the code change and all looks good.  If the checks fail... then conflicts that caused it to fail would need to be addressed.
Look for the checks at the bottom of every PR.

**Comment by MrBlockCat** [comment]
Oh sorry, I'd meant when #3031 might be pushed, not one of mine

**Comment by MrBlockCat** [comment]
For some reason when the tests finished GitHub decided both files had a conflict, but I think I fixed it? Hope so, I'm fairly new at using GitHub so I may have messed something up though.

**Comment by MrBlockCat** [comment]
@RodneyBaker It appears the conflicts are finally gone and the checks passed!

**Comment by RodneyBaker** [comment]
LGTM

**Pull request merged**
