### PR TITLE
Current time timeline indicator

### PR DESCRIPTION
**Pull request by manongjohn**
This PR adds a current time indicator to the Timeline mode.  This is similar to the indicators found in other software and will become more useful once the ability to zoom in/out of timeline is added.

Notes:
-  This currently does not apply to the Xsheet mode.
- The indicator can be turned off via a preference setting or by right-clicking in frames area and using option in context menu.
- The indicator is initially off by default 
- Line appears behind cell text to maintain readability.

Here is what it looks like with and without Onion Skin mode turned on:

image

This was requested as part of the timeline enhancement proposed by @Angyy (Issue #1422, Change # 6)

### CODE REVIEW

**Comment by bobbybutterfly** [comment]
Very cool and handy! I missed this!

**Comment by Agnyy** [comment]
Good!

**Comment by gab3d** [comment]
nice!
it makes it easier to spot at a glance where the current frame is at.

**Comment by turtletooth** [comment]
Tested a bit and it works well.  I actually think it should be on by default.

**Comment by manongjohn** [comment]
@turtletooth Thanks for testing it out. I know you guys are busy with the upgrade to 5.9.

I was recently thinking the same thing and see no harm in defaulting it to on either. I will change it shortly.

**Comment by manongjohn** [comment]
@bobbybutterfly You need to turn on Onion Skin under Preferences.

**Comment by manongjohn** [comment]
Oops, i meant you need to turn it off to see the blue marker.

**Comment by bobbybutterfly** [comment]
Ok, found it:) Thanks @manongjohn

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM Thank you @manongjohn for adding the useful feature!

**Pull request merged**
