### PR TITLE
Fix antialiasing

### PR DESCRIPTION
**Pull request by blackwarthog**
This PR fixes anti-aliasing for strokes.
Issues #1166 #2285
Driver independent AA for regions not implemented yet.

### CODE REVIEW

**Comment by blackwarthog** [comment]
Our previous PR https://github.com/opentoonz/opentoonz/pull/1218

**Comment by shun-iwasawa** [comment]
I'm a bit concerned about performance of your method.
Have you try measuring computation time in comparison with the conventional one?

**Comment by ave4** [comment]
I in my repository put these patches on the last master branch of opentoonz, after which I tested.

I rendered the project on vanilla master opentoonz and opentoonz with fix antialiasing patch, got the following results: (Project https://github.com/ave4/aircraft )
Vanilla OpenToonz: 100 frames - 48 seconds, the whole project is 1:32 minutes.

Patched opentoonz: The result is almost one to one!



But what's the difference in rendered images!

**Comment by RodneyBaker** [comment]
Very interested in this but can't test because the AppyVeyor didn't pass all checks.

**Comment by jpturcotte** [comment]
@RodneyBaker It is ready.

**Comment by RodneyBaker** [comment]
Thanks for the heads up @jpturcotte 

I'm checking it out but in my initial tests I'm not seeing much of a difference.
I'll relook at the original PRs to make sure I'm on the right track.

Here's a direct link to theappveyor release for those on WIndows who want to test:

https://ci.appveyor.com/api/buildjobs/t3vrq2bulerk72eg/artifacts/toonz%2Fx64%2FOpenToonz_1.2.zip

**Comment by shun-iwasawa** [comment]
I also confirmed that it works fine on Windows without any notable delay. Jenkins

**Comment by shun-iwasawa** [comment]
Thank you @blackwarthog for the fix! Also thank you @ave4 and @RodneyBaker for checking the PR!
LGTM

**Pull request merged**
