### PR TITLE
Remove hard-coded lines around panels

### PR DESCRIPTION
**Pull request by turtletooth**
This removes the hard-coded line around the style editor that @konero mentioned in #1043 

It doesn't show up as distinctly in the normal themes, but is very apparent in the new theme.

### CODE REVIEW

**Comment by konero** [comment]
There's also a black outline around the Schematic window. Again not prominent with the original themes but it sticks out like a sore thumb with anything else.

**Comment by turtletooth** [comment]
@konero Got em.

**Comment by konero** [comment]
@turtletooth Found them also in **Scene Cast** and **FlipBook** windows.

👍

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM. Thank you @turtletooth and @konero for the precise adjustment of UI!

**Comment by turtletooth** [comment]
@konero - The FlipBook one was taken care of with the Color Model, and I just submitted for the Scene Cast.  Thanks for pointing them out.

**Pull request merged**
