### PR TITLE
Show pinned center keys on Xsheet row area 

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is for the issue #282 
On the frames where the pinned center of the current skeleton is changed from the previous frame (= pinned center keyframes), blue square are displayed in the Xsheet row area.
Look and feel of this feature is based on @psychoanima 's proposal in the issue #282 but I made some changes as follows:
- This UI is displayed whenever the skeleton tool is selected, regardless of the current mode. 
- Index of the column which contains the pinned center object is displayed in the squares.
- Tooltip is set for this UI.

Since the row area is limited, this UI may obscure the frame numbers if the display mode of frame numbers is set to other than "Frame". This inconvenience might be another issue.

pinned_center_keys

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by psychoanima** [comment]
Wooooooooow!!! <3

@shun-iwasawa 
Is it possible to move them up&down as a regular keyframes or for now they are just indicators?

**Comment by shun-iwasawa** [comment]
@psychoanima 
For now they are just indicators and have no feature to adjust position of them.

**Comment by kogaki** [comment]
OK, it works in my OSX. LGTM.

**Pull request merged**
