### PR TITLE
Translation files for v1.7

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR updates translation files (.ts) for all languages.
Also added Japanese translation.

### CODE REVIEW

**Comment by gab3d** [comment]
Hi @shun-iwasawa 

Here's the Spanish translation: [spanish.zip](https://github.com/opentoonz/opentoonz/files/11241196/spanish.zip)


Also, while doing an overall check of the translations in the UI, I've detected some strings that are either not showing (although they are translated), as well as other ones that are not available for translation.
(** strings marked with a double asterix are translated but not showing in the UI)


Export OCA dialog:
(all strings) **

Xsheet/Timeline > right click over interpolation line between keyframes: 
"Interpolation on 1's"
"Interpolation on 2's"
"Interpolation on 3's"
"Interpolation on 4's"


Scan & Cleanup > Define Scanner... :
"Internal"
"unable to get handle to scanner"

Scan & Cleanup > Scan Settings... :
"[no scanner]" **
"A4 paper"

**Comment by shun-iwasawa** [comment]
@gab3d 
Thank you for Spanish translation! I'll post a separate PR after merging this.
Also thank you for checking the missing translations. I'll check and modify them.

@deruji @jcome @morevnaproject @beeheemooth @Savraska2 @haminu0108 @pafri @kimpd @toybrand
Again*3, your cooperation on updating translation is highly appreciated!
Here is a zip version of ts files needed to be translated:
[translations.zip](https://github.com/opentoonz/opentoonz/files/11246235/translations.zip)
You can either post a PR or just upload the translated .ts files here. Thank you.

**Comment by shun-iwasawa** [comment]
Fixed missing translations other than the followings:
- Scan & Cleanup > Define Scanner... : `unable to get handle to scanner`  : It seemed kind of hard to make it translatable now.
- Scan & Cleanup > Scan Settings... : `A4 paper`  : It's hard-coded in the settings files in `$TOONZCONFIG/pap`

**Comment by shun-iwasawa** [comment]
I'll merge this.

**Comment by toybrand** [comment]
This is Korean translation

2023년 4월 18일 (화) 오전 10:06, shun-iwasawa ***@***.***>님이 작성:

**Comment by IvanLvov** [comment]
Перевод на русский язык.  Translation into Russian.

**Comment by gab3d** [comment]
@shun-iwasawa 
Are the recent updates you made upon my report included in the translations.zip [file up above](https://github.com/opentoonz/opentoonz/pull/4828#issuecomment-1510686651)?

**Comment by shun-iwasawa** [comment]
@toybrand 
Thank you for you contribution, but I can't seem to find the attachment.
Can you please try again ? I think posting via web browser (instead of via email) should work. Thank you! 

@IvanLvov 
Thank you for the translation! I will post a PR.

@gab3d 
>Are the recent updates you made upon my report included in the translations.zip?

YES! 👍

**Comment by RodneyBaker** [comment]
@shun-iwasawa @toybrand (aka @kimpd on discord) uploaded his translation files to discord so I'm attaching it here.

[korean.zip](https://github.com/opentoonz/opentoonz/files/11295787/korean.zip)

**Comment by gab3d** [comment]
@shun-iwasawa 
Here's the final update for the Spanish translation, including the newly added strings to toonz.ts, as well as some modifications to a few toonzqt.ts strings.
Thanks!

[spanish_newUpdate.zip](https://github.com/opentoonz/opentoonz/files/11303081/spanish_newUpdate.zip)

**Comment by jcome** [comment]
@shun-iwasawa the Chinese Translation is here #4861. Sorry for a bit late.

**Pull request merged**
