### PR TITLE
Add shortcuts for MyPaint Brush toolbar options

### PR DESCRIPTION
**Pull request by manongjohn**
User request for shortcuts for the following MyPaint brush toolbar options:

1. `Eraser` - No default shortcut assigned.
2. `Lock Alpha` - No default shortcut assigned.
3. `Pressure` - Uses default shortcut Shift+P
4. `Size` - Uses default shortcuts U/I.  Increments value by 0.06

### CODE REVIEW

**Comment by artisteacher** [comment]
Nice! On a related note, the lock alpha option could also use a shortcut.

**Comment by manongjohn** [comment]
@artisteacher Sounds good. I can modify this PR to include it.

Dare I ask.....are there any other "useful" toolbar option shortcuts that are needed?

Please try not to say all of them :)

**Comment by artisteacher** [comment]
Great! The only one that I really miss is the ability to change the size of the raster brush. Right now it ignores all of the brush size shortcuts - (alt-Ctrl, U, I, H, J).

On a related note, but maybe not the scope of this PR, I'd love to see the ability to set a tool's shortcut to one of it's tool options. Ie. pressing G switches to the Geometric tool. Continuing to press G again would let me toggle through the different shapes. Similarly A switches to the Animate tool. Continuing to press A could toggle through the modes - to scale, rotate, or etc. It would be fewer shortcuts to remember...

Similarly, at some point I'd love to see some resolution for #1327, but that's probably out of scope too.

**Comment by gab3d** [comment]
@artisteacher 
I agree. 
Although the basis of a good workflow is there with the possibility of assigning shortcuts for Animate Tool's **Active Axis:** option, and the **Mode:** and **Type:** options of various other tools, there are still some shortcomings such as the **Mode** shortcut not allowing to cycle the Skeleton or Plastic tools' Mode dropdown menu options.
Achieving that would make assigning a shortcut to Tool Modifiers > Mode much more useful.

Still, I think that having the possibility of using the own tool shortcut to change the main tool "mode" (whatever that is called for that tool) would be extremely handy.

**Comment by manongjohn** [comment]
> Great! The only one that I really miss is the ability to change the size of the raster brush. **Right now it ignores all of the brush size shortcuts - (alt-Ctrl, U, I, H, J).**

So the MyPaint Brush size only has 1 brush size control. Do you want the shortcut to reuse H/J (min), U/I (max) or add a different set of shortcuts?  Where does the alt-Ctrl come into play with these shortcuts?

FYI, I also enabled the existing Pressure shortcut to work with the MyPaint Pressure toolbar option.

**Comment by manongjohn** [comment]
Actually, apparently in other tools, the Size with only 1 control uses shortcut U/I (max), so I'll make sure it uses the same for MyPaint brush size.

**Comment by artisteacher** [comment]
I'd reuse the existing shortcuts - probably U/I since the maximum brush size is used when drawing without a stylus. As far as alt-ctrl (alt-cmd on mac) #685 goes:

> Holding Ctrl + Alt and mouse up/down changes the min brush size. Left/right changes the max brush size.

**Comment by manongjohn** [comment]
I've enabled the shortcut for brush size but it currently increments by a factor of 1.0.  On other controls, this maybe ok since they tend to range from 0-100, but for Mypaint brushes, they go from -3 to 3.  What increments should this go by? 0.1? 0.25? 0.5?

**Comment by artisteacher** [comment]
Maybe .25?

**Comment by manongjohn** [comment]
0.25 seemed too much of a jump. 0.1 wasn't too bad, but I decided to keep consistent with the other size options requiring 99 keypresses to go from 100 to 1, therefore the step is 0.06.   It's actually not that bad since you can hold the button down til you get close to the size you want.

Aside: I still don't get why the mypaint brush size ranges from -3 to 3.

**Comment by artisteacher** [comment]
I don’t get the range myself. It would be nice to have consistency in the brush sizes.

**Comment by gab3d** [comment]
AFAIK the MyPaint brushes size is intended to be changed inside the Settings of each selected brush (i.e. **Radius** parameter), and not in the OT brush. In this way each MP brush can have its own independent size.

**Comment by turtletooth** [comment]
LGTM.  Thanks @manongjohn for the update.

**Pull request merged**
