### PR TITLE
Remove tcg_function_types.h

### PR DESCRIPTION
**Pull request by otakuto**

### CODE REVIEW

**Comment by RodneyBaker** [comment]
All checks passed but I get a crash with Plastic Tool upon creation of mesh that may or may not be related to this PR.

There are some very interesting things going on in this refactoring.
Prior to encountering the crash I had questions formulating regarding the function objects (functors) but this is well out of my comfort zone.  I will assume those are deprecated in the refactored code.

Steps I use to repeatedly get the crash are:
- Using #2772 Appveyor release ([LINK](https://ci.appveyor.com/api/buildjobs/k0jefnehu2744ljt/artifacts/toonz%2Fx64%2FOpenToonz.zip))
- Create vector level and draw some brush strokes
- Using Plastic Tool to create plastic mesh
- Attempt to enter xsheet with stylus (to extend range of exposed cell)
Opentoonz freezes and then crashes

**Comment by RodneyBaker** [comment]
I've spent some time with this PR and all looks and works good.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Hmm I got following errors while compiling `plasticskeletondeformation.cpp` :

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2903	'result': symbol is neither a class template nor a function template	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
Error	C2039	'result': is not a member of 'PlasticSkeletonDeformation::skeletonIds::<lambda_fbe33b688680c8cd4b9981b3d4811dab>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
Error	C2504	'result': base class undefined	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
Error	C2143	syntax error: missing ',' before '<'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
Error	C2039	'type': is not a member of 'boost::detail::ia_dflt_help<Reference,boost::result_of<const UnaryFunc (boost::bimaps::relation::structured_pair<TA,TB,Info,boost::bimaps::relation::normal_layout> &)>>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\iterator\transform_iterator.hpp	50	
Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'T', expected a real type	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\iterator\transform_iterator.hpp	59	
Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'Reference', expected a real type	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\iterator\transform_iterator.hpp	69	
Error	C2039	'result': is not a member of 'PlasticSkeletonDeformation::vertexDeformations::<lambda_d283034b7200cb92eeb1686e93a45ec1>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
Error	C2039	'type': is not a member of 'boost::detail::ia_dflt_help<Reference,boost::result_of<const UnaryFunc (const `anonymous-namespace'::VDKey &)>>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\iterator\transform_iterator.hpp	50	
Error	C2039	'result': is not a member of 'PlasticSkeletonDeformation::vdSkeletonVertices::<lambda_f30f7c6bd28b5e66174ad65792e86a2f>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
Error	C2039	'type': is not a member of 'boost::detail::ia_dflt_help<Reference,boost::result_of<const UnaryFunc (std::pair<const _Kty,_Ty> &)>>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\iterator\transform_iterator.hpp	50	

```

I have no idea why I got the errors while it passes all CI checks...

**Comment by RodneyBaker** [comment]
As this isn't a pressing PR going into v1.4 recommend picking it up again in 2020 development cycle.
This to better allow for focus on v1.4 Release Candidate.

**Comment by otakuto** [comment]
> Hmm I got following errors while compiling `plasticskeletondeformation.cpp` :
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2903	'result': symbol is neither a class template nor a function template	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
> Error	C2039	'result': is not a member of 'PlasticSkeletonDeformation::skeletonIds::<lambda_fbe33b688680c8cd4b9981b3d4811dab>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
> Error	C2504	'result': base class undefined	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
> Error	C2143	syntax error: missing ',' before '<'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
> Error	C2039	'type': is not a member of 'boost::detail::ia_dflt_help<Reference,boost::result_of<const UnaryFunc (boost::bimaps::relation::structured_pair<TA,TB,Info,boost::bimaps::relation::normal_layout> &)>>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\iterator\transform_iterator.hpp	50	
> Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'T', expected a real type	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\iterator\transform_iterator.hpp	59	
> Error	C3203	'type': unspecialized class template can't be used as a template argument for template parameter 'Reference', expected a real type	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\iterator\transform_iterator.hpp	69	
> Error	C2039	'result': is not a member of 'PlasticSkeletonDeformation::vertexDeformations::<lambda_d283034b7200cb92eeb1686e93a45ec1>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
> Error	C2039	'type': is not a member of 'boost::detail::ia_dflt_help<Reference,boost::result_of<const UnaryFunc (const `anonymous-namespace'::VDKey &)>>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\iterator\transform_iterator.hpp	50	
> Error	C2039	'result': is not a member of 'PlasticSkeletonDeformation::vdSkeletonVertices::<lambda_f30f7c6bd28b5e66174ad65792e86a2f>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\utility\result_of.hpp	186	
> Error	C2039	'type': is not a member of 'boost::detail::ia_dflt_help<Reference,boost::result_of<const UnaryFunc (std::pair<const _Kty,_Ty> &)>>'	tnzext	D:\s-iwasaw\work\opentoonz\opentoonz\thirdparty\boost\boost_1_55_0\boost\iterator\transform_iterator.hpp	50	
> ```
> 
> I have no idea why I got the errors while it passes all CI checks...

Maybe these errors occur on older MSVC.
What version are you using?

**Comment by shun-iwasawa** [comment]
@otakuto 

```
Microsoft Visual Studio Express 2015 for Windows Desktop
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.8.03752
Installed Version: Desktop Express
```

Version of boost library is 1.55.0.

I think I'm using the same version of MSVC in Jen.kins CI as well. I'll double-check later.

**Comment by shun-iwasawa** [comment]
Here's the version info used in Jen.kins machine:

```
Microsoft Visual Studio Express 2015 for Windows Desktop
Version 14.0.25425.01 Update 3
Microsoft .NET Framework
Version 4.6.01055
インストールされているバージョン:Desktop Express
```

Version of boost library is 1.61.0.

I'll try updating boost version in my office tomorrow. Thanks!

**Comment by shun-iwasawa** [comment]
I updated the boost library to 1.72 and confirmed that the errors resolved !

**Comment by shun-iwasawa** [comment]
Confirmed it works fine. Thank you @otakuto for refactoring ! LGTM

**Comment by RodneyBaker** [comment]
Congratulations also as I believe this is (or will be once it gets built) the 1000th PR merged into a nightly release!  <insert standing ovation here>

**Pull request merged**
