### PR TITLE
Update Translation Files for V1.5

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR updates the translation (.ts) files for all languages to the latest version.

Just in case, here is a zip version of ts files needed to be translated:
[translations.zip](https://github.com/opentoonz/opentoonz/files/5994707/translations.zip)

@gab3d @deruji @jcome @morevnaproject @beeheemooth @Savraska2 @haminu0108 @pafri @kimpd
Again, your cooperation on updating translation is highly appreciated!
You can either post a PR or just upload the translated .ts files here. Thank you.

### CODE REVIEW

**Comment by beeheemooth** [comment]
@shun-iwasawa I have updated the Russian translation. Unfortunately, I do not know how to load it into the code, I ask you to do this, please. 
[russian.zip](https://github.com/opentoonz/opentoonz/files/6012012/russian.zip)

**Comment by pafri** [comment]
Hi,
here is zipped archive with updated files - Czech translation update.
Greetings, Pavel Fric

    On Friday, February 19, 2021, 7:05:07 PM GMT+1, beeheemooth <notifications@github.com> wrote:  
 
 


@shun-iwasawa I have updated the Russian translation. Unfortunately, I do not know how to load it into the code, I ask you to do this, please.
russian.zip

**Comment by gab3d** [comment]
@shun-iwasawa 
Here are the Spanish files.

[spanish.zip](https://github.com/opentoonz/opentoonz/files/6020042/spanish.zip)

**Comment by gab3d** [comment]
@shun-iwasawa 

I've found some issues while completing the task:


Palette Editor:
"Freeze" (in English)

Level Strip:
"INBETWEEN" text over icons, when about to do an inbetween (in English, when in vertical mode)

Keyboard Shortcuts panel:
Some Stop-Motion options (in English)

Stop-motion panel:
Some options (in English)

Camera Settings window:
"inch" (in English) (...this one is long lasting)

Weird accented characters while text is correctly translated (I double checked it) 🤔 
only happens in this two menu options (both in the main menu, and the right click one):
imagen
imagen
imagen

**Comment by shun-iwasawa** [comment]
@beeheemooth 
Thank you for updating Russian translation! I'll include it to this PR.

@pafri 
Sorry but I couldn't find the attachment of Czech translation files. Can you please upload it again? Thanks!

@gab3d
Thank you for Spanish translation! I'll include it to this PR too.
Also thank you for notification of the issues. Some words (related to Stop Motion feature) were newly added after this PR was posted, others seems to be failed to register in the translation list.
I think I'll post another PR for mending them after introducing this, in order to avoid conflict.
I have no idea regarding the weird accented characters at the moment... I'll take a look.

**Comment by pafri** [comment]
Hi,
here is the tar.gz archive. Attached.
Greetings, Pavel Fric

    On Tuesday, February 23, 2021, 12:13:40 AM GMT+1, shun-iwasawa <notifications@github.com> wrote:  
 
 


@beeheemooth
Thank you for updating Russian translation! I'll include it to this PR.

@pafri
Sorry but I couldn't find the attachment of Czech translation files. Can you please upload it again? Thanks!

@gab3d
Thank you for Spanish translation! I'll include it to this PR too.
Also thank you for notification of the issues. Some words (related to Stop Motion feature) were newly added after this PR was posted, others seems to be failed to register in the translation list.
I think I'll post another PR for mending them after introducing this, in order to avoid conflict.
I have no idea regarding the weird accented characters at the moment... I'll take a look.

**Comment by shun-iwasawa** [comment]
@pafri 
I'm sorry I didn't notice immediately. You posted the comment via e-mail and seems to attach the translation files on it. GitHub seems to just ignore e-mail attachment on posting your comment.
So sorry to bother you again, but can you please visit https://github.com/opentoonz/opentoonz/pull/3717 and post a comment with attached files ? You can attach the file by drag & drop it on the comment field. Thanks!

**Comment by pafri** [comment]
Hi,

here is the tar.gz archive. Attached.

Greetings, Pavel Fric
[czech.tar.gz](https://github.com/opentoonz/opentoonz/files/6038127/czech.tar.gz)

**Comment by shun-iwasawa** [comment]
Thank you @beeheemooth , @gab3d and @pafri for updating translations!
I'll merge this. I will post another PR when it is needed for introducing other languages.

**Comment by beeheemooth** [comment]
@shun-iwasawa I checked the translation in the latest opentoonz_nightlies and found several annoying mistakes made by me (the names of the interpolations were confused). Please update this translation.
 My apologies. 
Thank. 
[russian(2).zip](https://github.com/opentoonz/opentoonz/files/6046890/russian.2.zip)

**Comment by jcome** [comment]
@shun-iwasawa sorry for a bit late, and hope #3736 is still can be included.

Wkr
Yu Chen

**Pull request merged**
