### PR TITLE
Audio Recording Popup

### PR DESCRIPTION
**Pull request by turtletooth**
This feature allows recording of audio through the system input devices.
- You can choose to have the animation play as you record and playback
- Audio meter to indicate input levels
- Add recorded audio into the scene

recorded
recording

### CODE REVIEW

**Comment by Rayek** [comment]
Wow, that is actually quite a helpful addition indeed. I wonder why other animation application developers haven't thought of this before :-)

Will you be supporting export to WAV as well?

**Comment by turtletooth** [comment]
> Will you be supporting export to WAV as well? edit Ah, I just noticed the audio export thread you worked on. Thanks so much!

Just to clarify- I saw that you saw the wav export PR too, but this also saves the sound to a wav file before importing it to a level.

**Comment by 2dvision** [comment]
Maybe need to add "pause" button too.

**Comment by blurymind** [comment]
That would be super useful too! :)

**Comment by blurymind** [comment]
Adobe flash lets you record.multiple takes in one sound clip and then
select the play range that the audio clip will use in order to pick the
right take

**Comment by shun-iwasawa** [comment]
Can one of the admins verify this patch?

**Comment by turtletooth** [comment]
Here is the latest:
newaudio

**Comment by turtletooth** [comment]
Found a few things that need to be tweaked.  Changed name to WIP

**Comment by turtletooth** [comment]
I think this is ready- removed the WIP.

**Comment by shun-iwasawa** [comment]
It seems to work fine. Jenkins

**Comment by shun-iwasawa** [comment]
@turtletooth I think the fix #928 would help this feature, which enables to display the Level Settings and the Info Viewer for sound levels.

**Comment by turtletooth** [comment]
Thanks for #928

**Comment by shun-iwasawa** [comment]
LGTM

**Pull request merged**
