### PR TITLE
[WIP] Curve Animation - animating individual strokes

### PR DESCRIPTION
**Pull request by manongjohn**
This PR introduces a new timeline-only feature allowing the animation of individual vector curves (strokes).  This is similar to the feature found in After Effects.

This work was requested and overseen by @Agnyy, initially developed by @jaros3 and currently maintained by me.

## Feature Description

This feature adds the ability to unfold vector layers into sublayers.  Each sublayer contains a single curve (stroke).  Each curve can be independently animated at the control point level.  This is in addition to normal level keyframing.

To create a curve keyframe:

1) Click on the key icon on the sublayer (recommended where you want to start the curve animation).
2) Move the timeline indicator to where you want to have the next curve keyframe to be.
3) Switch to Control Point Editor tool or other supported tool.
4) Modify a control point on the curve as desired.

curveanimation

When a curve is animated, it's keyframes can be modified in the Function Editor.

curveanimationfunctioneditor

NOTE: Internally, what is being animated are the control point handles (1 if at end, 2 otherwise) that determines position and orientation of the control point and the curve between control points.

## Caveats

1) When saving a scene with any animated curves, the scene cannot be opened in prior versions of OT.

   In order to open the scene in older versions, you must remove all curve keyframes before saving.

2) The following tools are currently not supported in curve animation.

      Cutting Tool
      Eraser Tool (except when deleting the entire stroke)
      Tape Tool (only when joining lines is checked and only when an animated curve is selected)

   NOTE: These tools will currently block the tool from working on an animated curve.  You'd need to turn off curve animation on that stroke for it to work.

3) Curve keyframes cannot be modified directly from timeline.  Need to use Function Editor to modify or delete

## Known Issues

1) Undo of stroke changes also clears curve animations permanently
2) Adding/removing control points with control point editor someones loses animation
3) Selection Tool's pump does not work when curve animation enabled. Should work like pump tool
4) Visualize as raster does not apply path animations
5) Image bounding box doesn't always adjust in viewer's preview mode, cutting off aninmation at the boundries.
6) Moving cells with active curve keyframes does not move curve keyframes with it.
7) Timeline sublayer refresh issues

   - When playing back in viewer, the xsheet does not always resize properly. Initial attemps to do so causes extreme performation issues during playbak.
   - When erasing in "Normal" mode, cannot refresh xsheet size area until you are done erasing.

## TODO

Before this PR can be merged we need to

1) Fixing any critical issues listed above or found while testing
2) Test this heavily.

## Possible Future enhancements

1) Add more control over curve keyframes from timeline.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Exciting times!
Congratulations on hitting this important milestone.

**Comment by manongjohn** [comment]
@shun-iwasawa I was wondering if you (or anyone really) can help me figure out why the curve animation is not previewing or rendering to file. Debugging shows it passes through the tcolumnfx code I added that applies the stroke keyframe data that normally allows it to preview in viewer/comboviewer correctly. However, it seems to ignore the results somewhere down the road and uses the original stroke data when it builds the final render/preview. Any idea where that might be happening?

**Comment by shun-iwasawa** [comment]
@manongjohn 
I haven't investigate the source yet, but it's probably due to the alias.
In advance of rendering, each frame makes a string in which whole content of the scene is written (= alias). And if there is a frame which have an alias identical to another frame, rendering will be executed only once and the result will be reused for them in order to save computation time.

So, I think you need to modify `TLevelColumnFx::getAlias()` to return different string if any strokes in vector level are animated.

Thank you @manongjohn and @jaros3 for the great feature!

**Comment by manongjohn** [comment]
@shun-iwasawa I got curve animations to render/preview! Thanks for your advice! It was exactly what I needed to do.

**Comment by artisteacher** [comment]
Would it be difficult to add a visibility toggle to help identify the strokes?

**Comment by manongjohn** [comment]
@artisteacher Not sure how difficult it would be, yet. Though I have it as a future enhancement, it's definitely something  I want to see added in sooner than later.

**Comment by gab3d** [comment]
@manongjohn 
Thank you for adding this incredible feature to OT!!
Undoubtly this one will make people to start considering OT as a motion graphics authoring alternative.

Could you please clarify a bit the terminology seen in your example?
I see it (and interpret it) as:
--Path Animation
----Col1 --> column name
------U1 --> level name
--------Circle1 --> curve/stroke/shape name
----------Handle1 --> control point number
------------p0
------------p1
------------p2 --> CP handle number (which of them is the actual CP position?)
---------------x --> horizontal coordinate of CP handle
---------------y --> vertical coordinate of CP handle
---------------thickness --> ...as in stroke thickness?? if that, it's so cool! (but still wonder why CP's tangent handles have it and not only the one corresponding to the CP position itself)

all in all, I think terminology could be made a bit more clear, perhaps like:
Column > Level > Curve > Control Point (or just CP) > Handles (CPpos, T1, T2)  >  x, y, thickness
(also, alternatives for "curve" could be "stroke" or "shape").

So (following your own example) in the Function Editor I would display things as:
--Path Animation
----Col1
------U1
--------Circle1
----------cp1
------------pos
---------------x
---------------y
---------------thickness
------------t1
------------t2
----------cp2
...
----------cp18
--------Rectangle1

Finally, some questions:
- Could curve names be edited after creation?
- (as a future addition) Would it be possible to make the control points of a stroke "trackable" (i.e: be able to use the track tool on them)?

Thanks again for this wonderful new posibilities! 😋

**Comment by manongjohn** [comment]
@gab3d et al...

You have the terminology correct up until Handle.

Internally the code uses the terminology "Chunk".  To me, they seemed to equate to the control point tangent handles so I named them "Handle" for user clarity.  The only reason I use Handle, is because every control point typically has 2 tangent handles (1 if it's at the end of an unclosed stroke).  Those seemed to coincide with the number of "chunks" that each stroke contained internally.  Chunks didn't really have any meaning to me other that "what the hell is that?"

Honestly, I don't quite understand the p0 - p2 labels either.  That's what it is used internally.  I'm not quite sure why there are 3 for ever handle. And  I can only assume that "Thickness" is the thickness of the line at that point though I have not really played with that.

Perhaps @shun-iwasawa can explain these items better and maybe we can use that explanation to get more user friendly labels?

Currently the curves cannot be renamed. In most cases the stroke is initially named by the tool that created it. Otherwise they are named "Shape". The name is not saved unless you animated the curve.  If the stroke is not animated, the name of the stroke will be "Shape" when the scene is reloaded. It should also be noted that the stroke may be renamed to "Shape" if you do something that, in essence, replaced the stroke like taking a circle and erasing part of it. (Circle -> Line). 

As for being "trackable". That will likely have to be someone else and maybe a lot further  down the road.

**Comment by RodneyBaker** [comment]
I wonder if 'Segment' might be more appropriate than Handle.
Handles could at least theoretically be used for the shaping Curves via the Bias Handles (ala Bezier Handles).
The terminology is generally point, line, segment and ray (or perhaps more often in this context 'array').   At that point we are likely discussing Groups of any assortment of those below.

I have to say, I do like the idea of being able to put a descriptor on any of these.
That would likely be in the realm of Groups that is a separate abstraction over the top of these that allows reference to things inside a container.  That container (a group) can then be named.  What is is in that group can then change.  So a shape named "Flat Car Tire" such as you've described (taking a circle and erasing part of it) would still contain the points of that shape.  It would just no longer contain the erased points.  (But this is an update to Groups in general... another feature enhancement).

https://en.wikibooks.org/wiki/Geometry/Points,_Lines,_Line_Segments_and_Rays

**Comment by RodneyBaker** [comment]
> Possible Future enhancements
> When hovering over a sublayer, highlight the curve in the viewer.

I can confirm that this works!

Other things looking very good at this point.

**Comment by gab3d** [comment]
@manongjohn 
After solving a doubt ( #1893 )  regarding the placement of shapes' fills over other shapes' strokes in a same cell (by using the Grouping feature), I´ve realised that shape Groups should probably be taken care of, for making curve animation more useful.
I don't mean to animate grouping, but just to take them into account while animating strokes, and probably to show them in some way in the timeline too.

Thanks!

**Comment by RodneyBaker** [comment]
@gab3d   I can confirm that selections of shapes are taken into account and the movement of any selected grouping gets animated correctly.  

The actual identification of the Groups is something a little deeper and it may be that Groups first need to be exposed to the user in such a way as to allow seeing them.   To my knowledge this is not currently the case as there is no place where the user can see or organize the Groups that are created.

As such this may be a separate Issue/PR that needs to be addressed first before @manongjohn can add those Groups into the Timeline.

**Comment by gab3d** [comment]
@RodneyBaker 
Well, there was previously no place in the Timeline where to see the individual shapes drawn in a cell, so I assume it should be a similar work as the one done to show them there,
Groups could be shown as "folders" inside which the shapes exist. (if they where grouped, of course).
That should be sufficient, I guess.

**Comment by RodneyBaker** [comment]
@gab3d  I follow what you are saying.  I'm just suggesting that navigating through code that already has some defined conditions might be a little more hazardous because of how things already work.  @manongjohn is certainly knowledgeable of what is going on there it's just adding another level of difficulty into the mix.  

As a for instance, these new Groups would of a necessity need to be created on the fly versus those that are intentionally created and that can be nested inside one another currently.  

When I suggest that a separate PR might be created to expose the current Groups it's with this transparency in mind.   The problem is that because those Groups aren't presented to the user now they themselves would need to be developed in order to get to that stage.

I imagine the individual strokes don't carry this added weight of established overhead with them.

**Comment by manongjohn** [comment]
@gab3d I managed to get it so that when you select strokes in the viewer with Selection tool or Control Point Editor, the sublayer name of the stroke you selected turns red, similar to when selecting a column.  Additionally, when hovering over a sublayer in the timeline, the stroke in the viewer turns red temporarily so you can see where it is.

As far as groups are concerned, when you select a group all the individual strokes turn red in the timeline sublayers.  The reverse is not true, however.  When you hover over the sublayer, only that individual stroke is highlighted even though it is part of a group.

Currently strokes in a group animate individually.  That has an interesting effect and could be useful, I suppose.  As of right now, the only way to curve animate all the strokes in the group, you will need to enable it for each stroke in the group.

**Comment by beeheemooth** [comment]
Tell me, please, this thing can be converted into frame-by-frame, for example by merging the levels (how can this be done with the key animation)? And is it possible to edit it afterwards?

**Comment by manongjohn** [comment]
@beeheemooth Can't convert to frame-by-frame. At least not any time soon.

Merging levels should still work and keep key animation provided the stroke information, internally, doesn't change.  I would have to confirm that because I'm not sure internally what a vector merge does to stroke information.  If it creates a copy in the new level and destroys the original after merge, then I'll have to add that to the list of things to do at some point in the future.

**Comment by manongjohn** [comment]
@Agnyy 
I'll address the "Move keys" probably in a future PR as that is a bit involved since I also need to work on being able to delete and create keys without having to use a tool to do it.

As for the "Change the vector lines.", I'm not sure what you are requesting in that image.  Can you elaborate?

FYI,

I've been working on getting most of the tools to work with curve animation.  I have the non-destructive tools (pump, pinch, magnet, blender, iron) working now.  I currently have destructive tools (cutter, eraser) blocked from working on animated strokes.  They'd need to turn off stroke animation of that stroke to modify it with these 2 tools.  The tape tool will currently be blocked only if endpoints are joined to form a new line. Still have to fix adding/removing control points in the control point editor tool so it doesn't wipe out existing animation.

**Comment by Agnyy** [comment]
@manongjohn  Correction. The first point is "to change the curves in places" or "to change layers in places". I have problems with English.

**Comment by openanim** [comment]
In my opinion, being able to modify points directly (like moho) would make this feature more complete. In a particular cut-out animation. the sublayers created here are sometimes too numerous, just for a layer. In this situation, being able to animate by point without opening the layer of sub-layers is faster and simpler. Sub layers being more oriented for details in my opinion. If this is possible, a function next to the small "plus" symbol that would activate all the keys of all the layers present would be a bypass option. Or an animate mode with the editor tool. renaming sub layers would be cool too.

**Comment by manongjohn** [comment]
@openanim Thanks for the suggestion. I will definitely look into that.

**Comment by 711GM** [comment]
but what else will be finalized? when will it be finished?

**Comment by manongjohn** [comment]
@711GM  I stopped to focus on the changes I wanted to include in the 1.2.1 release plus a few other changes.  I now have to sync all those changes back into this repository as well as fix Known Issues (No 1-4 in the PR description) before I am comfortable to say it's ready for user testing and review.

I do not have a specific time table as to when this will be ready.

If you are on Windows and wish to play around with it in the mean time (See Caveats i PR description), feel free to download the Appveyor build.

**Comment by Agnyy** [comment]
And how to download the assembly in Appveyor ?

**Comment by RodneyBaker** [comment]
The short answer is... here's the link:

**Comment by manongjohn** [comment]
@RodneyBaker Thanks for providing the link. I will put a PR to update our instruction sets to include

**Comment by 711GM** [comment]
Users can somehow help speed up the work?

**Comment by RodneyBaker** [comment]
@711GM 
The best way we can support the work is to provide useful and constructive feedback and educate ourselves along the way so that when the features arrive we'll be better equipped to use them.

Have you downloaded the Appveyor release and played with the feature?  For those that have not that would be a very good first step.  (Disclaimer:  I'm not sure it is available at this exact moment as it is in the build cycle)

**Comment by konero** [comment]
Or learn C++? 😛

**Comment by RodneyBaker** [comment]
@konero said:

> Or learn C++? 

LOL  I'd love to learn C++ but I'm not sure there is anyone alive that is patient enough to teach me.  ;)

Every now and then I take a stroll through the OpenToonz source code with the expectation that some of it will sink in well enough that in the far flung future I'll be able to use that knowledge wisely.  Hey, don't laugh!  It could happen.

**Comment by phillycheese007** [comment]
This Is amazing and will really add sooooo much to the power of opentoonz.
If the functionality of what you are working on(this pull request) could be added to a peg and have that pegs control points & handles control the pegs child  ...i really wouldnt know what more to ask for, besides the kinks you already mentioned above.

**Comment by RodneyBaker** [comment]
@phillycheese007 
You should investigate the Curve Editor (and Function Editor) as the Curve Editor presents keyframes of more things that the xsheet/timeline can and likely ever will.

The way I look at this is one of ease of the UI for average users versus those with greater need.  Users with greater need should peel back the layers of the Function Editor, Curve Editor and other UI entry points to more complex data.  This includes leaning in to the various tools available via expressions, File interpolations, etc.

With regard to the Peg bars... any changes to Peg Bars automatically transfer to their children.  Empty columns in the xsheet can function similarly to Pegs in this regard.

**Comment by phillycheese007** [comment]
if you look at how the deformers are implemented in toonboom it is really quite simple/ straightforward.  you have the option(which is almost essential in cutout) to add the deformation to peg bars...so you can leave the drawing intact.   i understand the inheritance pegbar/ child thing..and I realize that there is a bunch of control in function editor..but when I imagine using this animated vector functionality on a pegbar to control a child drawing level..the best i can come up with is some complex network of expressions connecting the two...in addition it does not look like in its current iteration you would be able to apply this to a peg.  if you havnt already take a look at a video on applying a deformer to a peg in toonboom..very simple..and keeps drawing and animation separate.  if you have a solution that would approach that level of simplicity...pleasetell..i can use any excuse not to use toonboom..also cus I'm broke

**Comment by openanim** [comment]
I do not know if this was reported but when you used the point editor with this PR, it is not possible to delete points or move a group of points in the usual way because the selection is no longer maintained as soon as you release the mouse or your stylus.

Another problem that I have encountered is the loss of the point editor tool when I maintain ctl, to add several points. It seems a little random but it happened to me quite often. After a while, the tool is usable again and it is possible to select the vector.

**Comment by phillycheese007** [comment]
rodney i can barely comprehend the extent of the possibilities this pull request opens up..i am so excited about this.  Im trying to figure out how i will handle all this data..i can see the timeline being refined further from this pr so that when you expand the column you have the shape you are manipulating at the top but this is just a copy or something which clicks to expand the actual drawing which could be dragged out of the shape copy(typical timeline parenting so this would cover what i was talking about earlier with peg style parenting)   and i suppose you could add the whole file tree that is currently in the function editor for "Curve Animation>Col" but i really dont know how much clicking into hierarchys in the timeline i would want to do.... a couple levels i n..and i want to bang my head against a wall.

  So i guess the 2 big things i would like to see on the timeline for this type of pull request would be 

1) the shape copy so you drag original shape in and out of it copy which functions as a parent supplying all animation data.  this would be super useful i think..

2)  one line that controls the line thickness for all lines in the shape at same time....(this issue of animating line thickness as drawing moves to and from camera to maintain same thickness...is something i figured would inevitably be fairly annoying to deal with at times......but this pull request is so close to making it amazingly easy.  Ughh it can be done right now!!! but :(( in the function editor...which is exhausting to look at..

..im also thinking about making a bounty to work on the function editor interface so that columns can be collapsed by hierarchy and rows at intervals of users choice...little blocks that fit on screen... to all the data in a couple clicks....and some other stuff to allow a easier management to this window.  ....Also thinking of opening a bounty for  something that would require more work than cleaning up the function editor and adding some toggle buttons...   This bounty would be for adding ability to add specific columns from function editor or specific curves from the function curve editor ..to their own node in schematic...maybe that would look like just the function curve editor inside of a node to be expanded for editing or its own little UI with dials and such. 

anyway i suppose i will keep this sort of discussion to topics i open to not clutter this thread up.

**Comment by phillycheese007** [comment]
One last thing...am i right to assume that this thread should be  for working out kinks as put forth by the developer...and feature requests for this either wait till this is official..or start my own thread about this PR? like im not trying to annoy anybody by posting tons of stuff in the wrong place.

**Comment by manongjohn** [comment]
@phillycheese007 keep it on this thread for now though bugs will take priority. Feature requests will likely be held until after unless it's simple enough and make sense to include now.

**Comment by phillycheese007** [comment]
Some weird issue with fills...
fraz3

**Comment by phillycheese007** [comment]
above fill issue seems to only be when adding control point to already filled shape

**Comment by phillycheese007** [comment]
sorry i cant really decifer what the new commit is...but i got a notification that says a commit was pushed from this PR?  i looked at the files but couldnt really make sense of the jist of the commit.....the new commit is pertaining to "Animating Strokes" no?  Are there new toys to play with?

When this is finally official im gonna need some klonapin on hand to calm the fuck down

**Comment by RodneyBaker** [comment]
@711GM No need to wait.  You can use curve animation right now (on Windows).
Just download, unzip and run the OpenToonz.exe.

https://ci.appveyor.com/api/buildjobs/iffia8tcc5802k0o/artifacts/toonz%2Fx64%2FOpenToonz_1.2.zip

The AppVeyor release will use your current Stuff directory.
Files created with curve animation from this release will not be compatible with other releases.

P.S.  You should always be disappointed.  Then when things work out you will be amazingly happy!  :)

**Comment by RodneyBaker** [comment]
Color test...
curveanimation_colorfilltest

curvefilltest

**Comment by RodneyBaker** [comment]
This PR is confirmed by @manongjohn to move on to the 2019 development cycle.
In the meantime OpenToonz users can access this feature set by building or via Appveyor release ([Link to Appveyor zip download](https://ci.appveyor.com/api/buildjobs/iffia8tcc5802k0o/artifacts/toonz%2Fx64%2FOpenToonz_1.2.zip))

**Comment by Agnyy** [comment]
This PR has become my personal Moby-Dick.

**Comment by Agnyy** [comment]
I don't know what to say, it still looks damp. I do not know what to do. https://youtu.be/CwE7VdSop9c  No one wants to revise this project. I don’t have a lot of money, but even expensive programmers also refuse this project. I have been looking for a way to continue working on this PR. 

This project is very important for me, as well as other improvements that I would like to make further. But this frozen PR symbolizes that everything is very bad. Apparently I need help, but I do not know who could help with this project.

**Comment by RodneyBaker** [comment]
Hang in there.
Control Point animation is no small effort and the work done thus far is worthy of praise.
You say the PR is frozen whereas I was seeing this pronouncement that Curve Animation wouldn't make it into the January release in a positive light.  It's not ready yet.  It is waiting for the rest of the open source code in OpenToonz to catch up.  Given that, here's what I think:

OpenToonz needs a lot of work under the hood in order for the infrastructure to be in place for effective control point animation to be fully functional and to meet users high expectations.  This is no easy task given that even the best programs in the category don't the whole control point animation process particularly well.

Especially given that additional developers don't seem to want to take this challenge on, this is one of those PRs that fits the 'how do you eat an elephant' rule in that incremental steps must to be taken in order to get the whole thing done.

Curve animation is a huge endeavor.  Who in their right mind would want to take it on?
One thing we could do publicly describe the obstacles so that they better be tackled each one in turn and in the process of describing those obstacles bite sized progress can be made.

**Comment by RodneyBaker** [comment]
@konero just referenced this PR and it reminded me that the Appveyor artifact for Curve Animation is expired.  

@shun-iwasawa Is there a simple way to trigger appveyor into building this PR again so that there is a release to download for another 6 months?  Thanks!

**Comment by manongjohn** [comment]
I can retrigger it, but not sure it will work because there are conflicts that need to be resolved.

**Comment by RodneyBaker** [comment]
Thanks @manongjohn 
I know I have a copy buried locally that I turned into a portable so if it doesn't work I can search that out.

**Comment by konero** [comment]
@manongjohn Could I suggest cleaning up this page? It's difficult to get across to people what this does with all the chatter. I'd just delete every comment here unless it's reviewing the code and direct people to an open issue for chatting and posting usability bugs.

Tips: https://help.github.com/en/articles/managing-disruptive-comments

I asked one guy to take a look but that was his first response... "I'm not reading this".

**Comment by manongjohn** [comment]
I've Hidden all the old comments as `Outdated`, for now, except a few that showed an issue that I don't believe I looked into or resolved.  

When I have time and motivation, I will see what nightmare it will be to resolve the conflicts so I can get the AppVeyor to build.

**Comment by Agnyy** [comment]
Hello! When will this request be resolved? Just this request is very important in my work. I would like to continue to help OT, but without solving this problem, it is very difficult for me to do all this.

**Comment by RodneyBaker** [comment]
This PR can be used as is as a portable on Windows using the following release:

**Comment by jpturcotte** [comment]
Would there be an opportunity for a bounty here?

**Comment by RodneyBaker** [comment]
There is great opportunity for a bounty here however, curve animation is a major undertaking so it will require programmers motivated to carry the effort foward as well.

What I think might be reasonable would be to take what is currently available via this PR and lock it down into releaseable form.  Then every Opentoonz release would have the core capability.  Others could then build from there.

The question here is whether this can be done in a meaningful way.
I know @manongjohn doesn't want to put something out there that isn't complete.
From my perspective the current Curve Animation (as it is) presents a working feature as well as a preview of what is possible.
A primary concern would be whether it causes other incompatibilities in Opentoonz file formatting.

**Comment by manongjohn** [comment]
This is not ready to be released. Not even partially.  First, all the conflicts need to be addressed and that is best done by pulling the OT master into the branch.  Resolving conflicts isn't always an easy thing to do especially if you are not familiar with what has changed for this PR vs what has changed in OT. Then...at a minimum, No. 1 and 2 under Known Issues in the description need to be fixed and that may take quite a bit of work.

I wouldn't release it, partial or full, without heavy and thorough testing or it runs the risk of breaking a lot of things.  This also needs to be regression tested. I can't guarantee that with all the code merges to resolve conflicts and bring this up to current master that something didn't break or a merged PR undone.  I also have concerns with impact to performance. 

This is a huge feature and should not be rushed. That is not a good way to develop and ensure OT's stability.

A bounty could motivate someone to finish it. Bounty or not, I'm not sure I can finish this, so if another developer wants to come along and finish it, I'm fine with that.

**Comment by RodneyBaker** [comment]
@manongjohn  Thanks.  I fully agree.  What my interest was/is with regard to portables and this PR is how that my older download of this as a portable works (and presumably still will work when I locate it because it still has all of its files intact).  The main idea being that someone with the express need to animate control points directly could use such a release for that purpose.

I may be mistaken but it seems to me there was an earlier OTX that included curve animation as well.

A slightly different question:  If this PR is not going forward should it be closed.  Closing it would signal to others that they need not consider using it in its present state.

**Comment by RodneyBaker** [comment]
Follow up:  In downloading the current test build for this PR (Curve Animation) I am not seeing any immediate issues and especially none such as that seen by @Agnyy with black windows.  That still reads as a need to create a new stuff directory to me.  This especially in light of the fact that he hasn't used Opentoonz in a long time and if present any Opentoonz stuff directory would have been from a long time ago.

**Comment by manongjohn** [comment]
OTX never had Curve Animation code.

I may do one more sync of the OT master code just to resolve the current conflicts and create a new artifact which would last for 6 months. Beyond that, I don't know that I will maintain the upkeep if I don't intend to continue.

I have debated and am leaning towards closing it until someone, if not me, decides to work on it again.

**Comment by hayoko** [comment]
I don't know about closing it, but this might be easier starting fresh, break it down into smaller battles.

If it were me, I would strip away the UI work and just dump the coordinates in the Function Editor for now and introduce UI as it becomes necessary.

I would also stress the listed caveats are perfectly normal and are not issues to be solved, this is true in other software, once you run interpolations you can no longer slice strokes or you get a compute error.

I would introduce a new mode called "shape tween", you mark along the timeline where the shape tween should happen to create a compute space that flags the strokes, the first frame is the only frame where you can add/remove points etc, proceeding frames up until the end of the shape tween space should only allow moving points, no other tools should function, except perhaps a magnet tool. Perhaps this can help solve the fill issue by preventing user error?

This would then be similar to shape tween in Flash, only in real-time. If I wanted to add more points, then I can just start a new shape tween and chain it all together. I guess a way of doing that would be to 'duplicate' frame, so you get the last frame of the last shape tween and use it to start a new one. That might sound messy but it's actually a taught working method in Flash/CACANi.

If we later want to animate strokes like CACANi does with additions, visibility, timing bias, indexing, then we can introduce a new mode called "line tween" at a later time once "shape tween" has been ironed out, because this will require some really good math.

I don't know if I can work on this since I switched to C# (thanks Unity) but if I find anyone interested I'll send them this way. You did a good job so far.

**Comment by manongjohn** [comment]
I have actually considered starting over from scratch as I was not particularly fond of how it was originally implemented. I would need time to come up with a new design now that I understand how OT does stuff and leverage some of the lessons I learned working on this.

I listed the Caveats because I know nothing can be done about those and have no intentions of trying to do anything about it in this PR. I basically just wanted to list out-of-scope items. The Known Issues are more the priority as I and most users would just expect that to work.

The fill issue is probably easilly fixable. Likely need to trigger some update to refresh when the tangent handles adjusts the control point.

This originally worked with just the Control Point Editor tool. I decided to add other tools but quickly realized why it wasn't added to those originally. It's because of how OT stored and replaces strokes for some operation and how it adds or removes points in the process. When that happens, any curve animation data is lost or essentially corrupted.  I stubbornly made it work (semi-hacked it) though not happy with that implementation either.

Sadly, Undo/Redo works in the same manner, it replaces strokes. Work needs to be done to maintain the curve animation data and resort it properly for the various tools. I would want this working before this merges.

UI wise, it's ok as it stands though some enhancements and improvment as suggested in the thread would go a long way. I wouldn't use that as a reason not to merge if it can't be done now.

**Comment by manongjohn** [comment]
I no longer intend on keeping up with resolving conflicts to keep this relevant as it gets more and more difficult as time passes by.  I have no plans to resume this work so I'm going to close this.  

When/if someone else picks it up, they can always start a new PR.

**Comment by RodneyBaker** [comment]
I want to thank you for the effort involved in this feature @manongjohn 
It's tough for me to see this feature set go but I am confident the future will see it rise again and be even more useful/powerful.

This has been a great demonstration of where Opentoonz will be given more time.

**Comment by Agnyy** [comment]
@manongjohn  Thank you very much for the work done. You have done a lot for this feature. I am extremely grateful to you. I have no words how much I really admire you, you have been following and helping this feature develop for so long. You really helped me. I am very very grateful to you. I am very ashamed that I could not find a programmer to finalize this function. Everyone is afraid to take on such a difficult task. I would really like to complete this function because only it interfered with me for further improvement of the Timeline.

Can someone help find a programmer for such a difficult task? I would be very grateful.

**Comment by RodneyBaker** [comment]
@Agnyy What I would suggest is to break down the variouis requirements for 'Curve Animation' to work so that they can incrementally be added.  Animation of Control Points in not a trivial task and Opentoonz currently lacks some of the things needed to make that happen.

An example of this is Groups.
In order for Control Point/Curve Animation to be useful those Control Points have to be grouped into one or more 'Objects'; points, lines/curves, shapes, groups... nested groups.  
Currently Groups are not exposed to the user in the UI in any visual way that assists with deeper manipulation/animation.  At a guess I'd say these grouping constructs should be initially exposed via the Stage Cast/Stage Listing and then expanded to other locations from there (i.e. Timeline).  This will allow for user interaction with the objects that will be animated.

One of the things that made the current Curve Editor implementation is the lack of ability to Group and nest groups so that Control Points could be more easily manipulated.  As such there was a limited number of 'objects' available to 'curve animate'; indificual control points (CPs), strokes, shapes being the primary ones.  Eventually this needs to be editable groups defined by the user; what I call Named Groups due to my experience with using them in 3D animation.

Just because this PR is closed doesn't mean it cannot still be developed.
In order to attract a developer however they need to know exactly what the scope of the project is.
Identifying milestones will help in that programmers can know when they achieve specific milestones... and reasonably anticipate being paid at that stage assuming there are attached bounties.

The reason I focus on Groups here is that it is a core element of the greater 'feature' of Curve Animation and yet implementing that alone  will enhance Opentoonz even without the full implementation of Curve Animation.

You have done this scope breakdown elsewhere so I'm confident we can do it here also.

**Comment by artisteacher** [comment]
I agree with @RodneyBaker that if this can be broken up into smaller, discrete tasks, eventual completion may be more likely. If smaller stages are merged as they are finished, there wouldn't be such an issue with conflicts.

@manongjohn, since you've spent so much time on this, do you have suggestions for a more manageable way to break this down?

**Comment by openanim** [comment]
While trying to practice motion design a bit from Opentoonz, I wondered if it would be difficult to have in the function editor the animation keys for the colors and the settings of the  vector brushes. To edit quickly their timing in the same way of curve animation PR's which adapts well to this type of workflow? a thought maybe @manongjohn. Currently, the timing is totally linked to the xsheet / timeline frames. Impossible to play with the curves.

**Comment by RodneyBaker** [comment]
@openanim 
One of the constraints/difficulties of exposing the color style keys in the Function Editor is that those keys are stored in a completely different location... in the palette files... and not in the scene file.

This is both bad and good.

Bad, because it makes it more difficult because it is a different keyframing process
Good, because it demonstrates how external storeage of keyframes can work.

I must assume something is similar with the FX keys but I confess I haven't investigated those.
Perhaps how the FX keys are stored holds an additional clue as to how to proceed.

**Comment by openanim** [comment]
@RodneyBaker Good to know. Although personally I think that keys not visible materially on the xsheet are difficult to use. Settings keys are somewhere fx so it may be a good way indeed.

**Comment by RodneyBaker** [comment]
I agree and I can't imagine another thinking otherwise... that those keys are better off not being visible.

I'm confident in time this will be addressed properly but it's a major undertaking.
I'm also not entirely sure what success would look like but my experimentation suggests that the current keyframing approach might best give way to that which is used by color swatches but gain the UI of the Function Editor.

My rationale is as follows (for the bigger picture that also includes what you are currently suggesting):
- The storage of keys needs to have the option of being stored in external files
An example of this can be found via loading and saving of curve data with .curve files but similar to the use of file interpolation, which demonstrates another way to connect to external (key) data, the connection isn't live (doesn't persist)... the values must be manually applied/updated for each channel.  To resolve this the connection to the data must update automatically.
The above alone would allow key values to transfer from one location to another... so that key data from color swatches could be seen in the function editor just like other data.
- Color swatches are an example of how Groups should operate in that they are customizable containers that store data.  Currently color swatches cannot be nested but that would be ideal too.  This would allow for values of one data set to be modified by the values of other color swatches resulting in a modified output.  These color swatch 'nodes' could then be seen via Schematic and added into schematic flows.  If we want to adjust another set of values by the same amount we just need to make sure they in the flow.  This could be done by either placing the node into the flow or by nesting the other data inside the node (groupings and subgroupings).
- In the end the keyframe values are all the same values... either integers or decimal/floats.
A bridging of the processes is necessary in order to 1) keep the values using the same unit of measure 2) keep the values updating automatically... unless manual activation is desired 3) view the data via the UI throughout the various visual paradigms of the program. 4) expose the data to the user to allow tailored customization.

This is a huge undertaking but if the above is properly broken down and understood I believe we can find an appropriate way forward with incremental improvements that resolve not only the desire to access keyframe data from color swatches and fx but also the standard keyframes too.  Further it will allow similar processes to be used as the interface for other processes which currently have no exposure to the user.  Finally, it will allow users to choose which UI paradigm works best for them and allow them to customize their workflow so they can solve their problems externally without having to resort to modifying the source code.

**Comment by RodneyBaker** [comment]
Took me forever to find this topic and add this follow up...

I said before that I didn't know where keyframe data from FX was stored but I had just forgotten.
Although there could be an exception, FX keyframes are exposed in the Function Editor along with 'normal keyframes'.  

Someone recently posted that this was not the case.
Now I need to find THAT post and reply to that also.  ;)

**Comment by gab3d** [comment]
I think there should be no impediment for showing Palette keyframes in the Function Editor, since the data is loaded in the scene, as the rest of key data.

It should most probably be shown in the channels tree inside its own "Palettes" folder, where there should be a sub-folder for each "Toonz Level" or "Palette file" loaded in the scene.

**Pull request closed without merging**
