### PR TITLE
Revert keyframes on xsheet cell area

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This modification is for the issue #158 
With this modification, you can choose whether to show the keyframes on the xsheet cell area just like Toonz Harlequin.
To toggle this feature, click the checkbox in Preferences popup > Xsheet category > "Show Keyframes on Cell Area". Note that the default value of this option is set to "ON", so please turn off this check box if you would like to hide them.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins, test this

**Comment by kogaki** [comment]
Jenkins

**Comment by blurymind** [comment]
Does this also bring back the tween control widgets from the x-sheet in the curves editor:
tweenwidgets-curveeditor

@shun-iwasawa thank you for this. It is really valuable. I cant wait to try it in the next nightly build! :)

**Comment by Rayek** [comment]
Is this available in the latest nightly build? The control widgets in the graph editor do work - but no option seems to be added in the xsheet preferences to turn on or off the keys display?

**Comment by blurymind** [comment]
@Rayek it's not yet merged.

**Comment by tomosu** [comment]
It works on OSX too.

**Comment by Rayek** [comment]
It works like a charm in the latest build!

THANK YOU GUYS!

**Comment by blurymind** [comment]
it works like a charm :)
Thank you kindly! 

There are a few other things left and OT will be on par with harlequin.

**Pull request merged**
