### PR TITLE
Fix some can't translate strings on UI

### PR DESCRIPTION
**Pull request by SaierMe**
- Fix some can't translate strings on UI
- Add new source strings in all language
- translate new source strings in Chinese.

### CODE REVIEW

**Comment by SaierMe** [comment]
Remove modifications of Style Picker tool & Rotate Tool because these check failed.

**Comment by SaierMe** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins, test this.

**Comment by skitaoka** [comment]
Jenkins, test this.

**Comment by SaierMe** [comment]
Jenkins, test this.

**Comment by skitaoka** [comment]
Jenkins, test this, again.

**Comment by skitaoka** [comment]
Jenkins, test this, again.

**Comment by skitaoka** [comment]
LGTM

**Pull request merged**
