### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by RoboSchmied**
fix same typo in all files but not in `thirdparty` directory.

### CODE REVIEW

**Comment by RodneyBaker** [comment]
Let's do it then... let's fix some typos.
Thanks for the exclusion of third party directory of course.

There are other typos out there for sure perhaps this quiet before the storm that is the final release of Opentoonz v1.8 is the time to get those addressed.

**Comment by RodneyBaker** [comment]
I believe the reason for appveyor failure is that behind the scenes @shun-iwasawa has to whitelist contributors.

**Comment by RoboSchmied** [comment]
> I believe the reason for appveyor failure is that behind the scenes @shun-iwasawa has to whitelist contributors.

Thank you. How can I help resolving this?

**Comment by manongjohn** [comment]
Not a white list issue. There isnt a white list for appveyor builds.

Appveyor fails builds if it takes more than 1 hour to complete. The Debug build completed successfully in 56 minutes. The Release build failed after hitting the 1 hour mark.  One of the reasons I stopped using Appveyor.

I restarted the failed build. Maybe it will finish this time.

**Comment by RodneyBaker** [comment]
Thanks @manongjohn 
The restart worked.

Thank you @RoboSchmied for the typo fixes.

**Pull request merged**
