### PR TITLE
Reverting room editing feature + Adding menu bar customizing feature

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This fix is including two major improvements:
One is reverting room editing features which were available in Toonz Harlequin. (Issue #80 ) 
Now you can add/move/rename/delete room on the room tab GUI. Please note before using such room editing feature, you need to unlock them by clicking a lock toggle button on the right of the room tab bar.
Another one is adding menu bar customizing feature. Menu bar popup opens from a context menu of the room tab. You can customize menu bar by drag&drop menu items into the menu bar tree.

N.B. For now, customizing menu bar is not available in OS X.
N.B. Please copy a template layout settings folder (stuff/profiles/layouts/OpenToonz) to your own stuff folder ($TOONZPROFILES/layouts/OpenToonz) in order to enable menu bar editing.

revert_room_feature

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins, test this

**Comment by blurymind** [comment]
Awesome! Thank you @shun-iwasawa

**Comment by shun-iwasawa** [comment]
Jenkins, test this again

**Comment by shun-iwasawa** [comment]
Jenkins, test this one more

**Comment by kogaki** [comment]
It works on OSX. Great!

**Pull request merged**
