### PR TITLE
Fix Flipbook Crash

### PR DESCRIPTION
**Pull request by turtletooth**
Fix for #1222 
Not sure if this is the best way, but it works.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you for the fix.
How about just inserting `if(!m_image) return;` at the beginning of `mousePress/Move/Release/DoubleClickEvent` in order to prevent any control before loading the image?

**Comment by turtletooth** [comment]
@shun-iwasawa That makes sense.  Changes made.

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
@turtletooth  It works fine. LGTM

**Pull request merged**
