### PR TITLE
Fix crash in ShadingContext destructor [WIP]

### PR DESCRIPTION
**Pull request by tomosu**
Make sure to get the ownership of QOpenGLContext (member of QGLPixelBuffer) in ShadingContext destructor, to avoid crash in preview-mode or rendering.

### CODE REVIEW

**Comment by tomosu** [comment]
Jenkins

**Comment by skitaoka** [comment]
This modification has an assertion error with debug build on windows.

`OpenToonz_1.0.exe` shows following messages on startup:
```
Module: 5.6.1
File: kernel\qoptnglcontext.cpp
Line: 954

Cannnot make QOpenGLContext current in a different thread
```

**Comment by tomosu** [comment]
Jenkins

**Comment by tomosu** [comment]
Already merged in #702

**Pull request closed without merging**
