### PR TITLE
Use std functions

### PR DESCRIPTION
**Pull request by skitaoka**
- replace toInt to std::stoi,
- replace toDouble to std::stod,
- replace toString to std::to_string,
- replace toWideString to std::to_wstring.

This PR follows https://github.com/opentoonz/opentoonz/pull/291 (https://github.com/opentoonz/opentoonz/pull/294).

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins, again

**Comment by skitaoka** [comment]
Jenkins

**Comment by kogaki** [comment]
@skitaoka Plz fix conflicts

**Comment by skitaoka** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins, again

**Comment by kogaki** [comment]
Jenkins, again

**Comment by kogaki** [comment]
Jenkins, again

**Comment by kogaki** [comment]
LGTM

**Pull request merged**
