### PR TITLE
Use QOpenGLWidget instead of QGLWidget

### PR DESCRIPTION
**Pull request by skitaoka**
* ImageViewer
* ~~Viewer~~ (unused)
* HexagonalColorWheel

QGLWidget is obsolete. cf. http://doc.qt.io/qt-5/qglwidget.html

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins

**Comment by kogaki** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins, again.

**Comment by skitaoka** [comment]
Jenkins, again.

**Comment by kogaki** [comment]
Jenkins

**Comment by kogaki** [comment]
Now it looks prettier. Thanks.

**Comment by kogaki** [comment]
Unfortunately, these commits caused fatal regression. OpenToonz completely doesn't work in OSX. So I will revert this.

**Pull request merged**
