### PR TITLE
Fix for OS X build error

### PR DESCRIPTION
**Pull request by yehjaemin**
Referenced in closed issues #40, #1566, and #2496, the build process outputs an error message due to toonz/cmake/FindTIFF.cmake referencing libtiff.a instead of libtiff.dylib. This causes the build to crash. I applied the change mentioned in the threads and tested it on a fresh clone opentoonz repo and was able to successfully build the OpenToonz app executable (but I'm not sure if this change causes any problems for Windows/Linux).

### CODE REVIEW

**Comment by yehjaemin** [comment]
I just checked the results of the Travis CI build and the changes work only for xcode. I'd be happy to revert the changes and edit the OS X build instructions to mention the libtiff.dylib fix.

**Comment by yehjaemin** [comment]
Thanks @manongjohn! I think this commit might solve the different platforms problem.

**Comment by yehjaemin** [comment]
@artisteacher The problem I had with the whole libimage.dylib error message wasn't from not having things installed but from FindTIFF.cmake not searching for the right file extension on mac environments. This PR is still pending, but you could test it yourself in the meantime by copying my commits into your file.

**Comment by artisteacher** [comment]
The problem is that without these commits, I can get OT to build and open - though there are issues. With these commits, I get that error when trying to open.

**Comment by yehjaemin** [comment]
@artisteacher I didn't experiment with Qt versions ( I just installed the one the guide told me to), but I did notice that installing "Sources" and "Qt Script" were necessary for me. I proposed it as a change to local build instruction in PR #2497.

**Comment by artisteacher** [comment]
QT version doesn't seem to make a difference on my end. I definitely have both sources & qt script installed. Is there something else I could be missing?

**Comment by manongjohn** [comment]
Try going to your 'build' directory, then delete the 'toonz' directory and then 'make' again and see if that helps. Changes to certain things outside of OT code does not cause some things to recompile when rebuilding OT and will continue to use old settings.

Btw, when you changed Qt version, i'm assuming you updated the scripts accordingly? If you did, you will definitely need to delete the toonz directory and reissue the CMAKE_PATH_DIR step.

**Comment by artisteacher** [comment]
I made a completely new build - so I don't think that was the problem. I took a look and I don't actually have libtiff.5.dylib installed where OT is looking for it. I found a copy in another program I have and moved a copy to usr/local/lib  - which allows me to open the build. Is there a step I could have missed or done incorrectly that should have installed libtiff.5.dylib? Or is there a missing step in the directions?

**Comment by artisteacher** [comment]
Alright, using homebrew to install libtiff makes this work. @yehjaemin, this PR is going to need an addition to the build instructions - so that libtiff is installed with the other dependent packages (Step 1).

**Comment by shun-iwasawa** [comment]
@yehjaemin 
Please confirm that you did [the step 3 in the instruction](https://github.com/opentoonz/opentoonz/blob/master/doc/how_to_build_macosx.md#3-build-tiff-in-thirdparty) .
It should generate `libtiff.a` under `opentoonz/thirdparty/tiff-4.0.3/libtiff/.libs` .

Libtiff used in OpenToonz is [slightly modified](https://github.com/opentoonz/opentoonz/blob/master/thirdparty/tiff-4.0.3/libtiff/tif_getimage_64.c) from the one you can install from Homebrew.

**Comment by artisteacher** [comment]
I’ve been able to build successfully both ways. However following the normal build instructions, I always get a crash when trying to save. I don’t get a crash when saving with this pr.

**Comment by shun-iwasawa** [comment]
@artisteacher 

> I always get a crash when trying to save.

You meant that you get a crash when you save TIF raster levels?
Can you please check if the crash occurs only with your build or also with the release version of OT ?
I tried saving raster levels and scenes in my environment of macOS Sierra and I couldn't reproduce the crash yet.

**Comment by artisteacher** [comment]
I have not had issues saving with the released version - just local builds. I always use the "Save All" command, so I wan't sure if it was the scene or a specific level type causing the crash.

**Comment by yehjaemin** [comment]
@shun-iwasawa Hi, sorry for the late response, my car broke down so I've been devoting my free time lately to getting a replacement.

I did step 3 as specified in the instructions, but I also included @artisteacher's libtiff edit because I assumed it didn't work for him. Installing without homebrewing libtiff worked fine for me.

**Comment by RodneyBaker** [comment]
This PR needs to be looked at again due to nerger of PR #2600.
Perhaps it is no longer needed?

**Comment by manongjohn** [comment]
I recommend closing this. Since we use a custom libtiff.a which is part of our normal build process, we shouldn't be using the homebrew version or there could be unintended side effects.

If the crashing problem noted here is still an issue, a new issue should be opened to track it. However, it seems related to local building and currently not in the official version. Is it possible it's due to some changes in libraries when compiling on macOS versions after Sierra (10.12)?

**Comment by RodneyBaker** [comment]
Closing.
@yehjaemin Let us know if you have any concerns.

**Pull request closed without merging**
