### PR TITLE
Flip on viewer center

### PR DESCRIPTION
**Pull request by manongjohn**
This PR changes the behavior of the Flip Horizontal and Flip Vertical commands.

Currently, the flip is performed on camera center. This poses a problem when you flip the view and are zoomed in on a section of the image not near the center. The part you are looking at is now off screen and you have to pan back to it.

This changes the flip to be done on viewer center instead.

NOTE: This PR is built on top of PR #2501 to make use of rotation tracking logic that was added there. The other PR can be canceled if this is reviewed and merged first.

### CODE REVIEW

**Comment by melieconiek** [comment]
\o/

**Comment by RodneyBaker** [comment]
Appveyor release works great (as advertised).
Recommend review and merge.

**Comment by manongjohn** [comment]
Sorry. Messed up the commit history. Will fix.

**Comment by turtletooth** [comment]
LGTM.  Thanks @manongjohn for the update.

**Pull request merged**
