### PR TITLE
Use English for 'iwa_motionblurfx' comments by ideasman42 [modified]

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is based on #927 by @ideasman42 , modified some translations in order to clarify.

@ideasman42 It would be helpful for other developers. Thanks!

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by ideasman42** [comment]
Seems fine, any reason for odd word wrapping?

I ran the patch through clang-format so thought it wouldnt need any edits in that respect, eg:

picky, but would avoid odd-line splitting.

```
        /* Calculate the inner product of 'p0' -> sampling point and 'p0' ->
         * 'p1' */
```

```
      /* Do depremultiply on sources that are premultiplied, such as regular
      * Level.
      * It is not done for 'digital overlay' (image with alpha mask added by
      * using
      * Photoshop, as known as 'DigiBook' in Japanese animation industry) etc.
      */
```

**Comment by yamisama** [comment]
Very small point: I believe the common terminology for the opposite of "to premultiply" is "to unpremultiply", not "to depremultiply". I'm not sure what term the original Alvy Ray Smith paper uses do describe that operation, but in most software today "to unpremultiply" seems to be sort of a consensus.

**Comment by shun-iwasawa** [comment]
Fixed odd word wraps caused by clang-formatting. Thanks @ideasman42 for pointing it out.
Also changed the term 'depremultiply' and 'demultiply' to 'unpremultiply' - it is true that 'unpremul-' is more common as @yamisama pointed. I learned that for the first time.
Jenkins

**Comment by ideasman42** [comment]
LGTM, note: would squish all commmits before merging.

**Comment by shun-iwasawa** [comment]
Squashed.
Jenkins

**Comment by ideasman42** [comment]
Any reason to hold off putting this in master?

**Pull request merged**
