### PR TITLE
Allow Qt 5.6

### PR DESCRIPTION
**Pull request by skitaoka**
https://github.com/opentoonz/opentoonz/pull/179

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins, test this.

**Comment by skitaoka** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins, test this, again.

**Comment by skitaoka** [comment]
Jenkins, test this, again.

**Comment by kogaki** [comment]
Jenkins

**Pull request merged**
