### PR TITLE
Fixed assert failing on project popup

### PR DESCRIPTION
**Pull request by turtletooth**
#645 
sandboxFp needed the entire file path to the project file, not just the folder.

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins, test this.

**Comment by turtletooth** [comment]
Jenkins again please.

**Comment by kogaki** [comment]
Jenkins

**Comment by turtletooth** [comment]
Any idea why windows is failing here?

**Comment by janisozaur** [comment]
It seems AppVeyor is not building some(?) PRs, can someone please check configuration?

**Comment by kogaki** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
LGTM. Thank you very much for fixing the bug!

**Pull request merged**
