### PR TITLE
Fix path to textures, effects, brushes and templates

### PR DESCRIPTION
**Pull request by blackwarthog**
Fix paths in "~/.config/OpenToonz/SystemVars.ini" for Linux

### CODE REVIEW

**Comment by morevnaproject** [comment]
Without this fix there are no presets for vector brushes and textures in Linux version of OpenToons.

**Comment by blackwarthog** [comment]
I've splitted first commit and also rename BUILD_ENV_~~GCC~~ variable to BUILD_ENV_UNIXLIKE to make it meaning more clear.

**Comment by inkapnea** [comment]
Are those two related and one of them could be redundant?
#1062

**Comment by morevnaproject** [comment]
@inkapnea The problem is that "fxs" and "library" dirs are exist (with a lot of templates), but ini file points to wrong directory, so OpenToonz looks in the wrong place.

**Comment by inkapnea** [comment]
@morevnaproject Ok, thank you! I can see that the dirs you referenced are populated with files.
I suppose I still have to understand the logic and the purpose of multiple directories and subdirectories with the same name under Stuff like:
/stuff/projects/fxs/
and
/stuff/fxs/
and such...

**Comment by shun-iwasawa** [comment]
LGTM. @blackwarthog thank you for the fix!

**Pull request merged**
