### PR TITLE
Konero svg icons (Part 1)

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR is to introduce @konero's SVG icons posted in #1159 .
It's almost a halfway and the rest will be included later.

### CODE REVIEW

**Comment by turtletooth** [comment]
@shun this is such a big change, I have no idea how to effectively review the PR.  I trust that you did great work, however.  You want me do just merge it?

**Comment by shun-iwasawa** [comment]
@turtletooth Thank you for the suggestion. I'd appreciate it if you'd try to build the software in advance and take a brief look to see if the changes will not harm the functionality.
In this PR most of `QIcon` s are replaced with svg. I'll do the rest (for other images using `Resources`) afterwards.

Jenkins

**Comment by turtletooth** [comment]
I've built it.  Looks good so far.  And the icons look really nice.

**Comment by turtletooth** [comment]
LGTM.  Thanks @shun-iwasawa for the work of getting all these added.  Thanks @konero for your amazing work with the icons.  (I especially like the new icons in the schematic window)

**Pull request merged**
