### PR TITLE
Fix issue 253-254

### PR DESCRIPTION
**Pull request by skitaoka**
Fix https://github.com/opentoonz/opentoonz/issues/253 & https://github.com/opentoonz/opentoonz/issues/254

### CODE REVIEW

**Comment by skitaoka** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins

**Comment by skitaoka** [comment]
Jenkins

**Comment by tomosu** [comment]
I tried this PR, plastic tool causes no crash in preview mode, but preview rendering comes to broken when I move the bones.
Although this problem seems to have no direct relation about this PR's change
I will create a new issue about this problem.

**Pull request merged**
