### PR TITLE
Fix OpenGL widgets in floating panels disapper on room switch

### PR DESCRIPTION
**Pull request by shun-iwasawa**
This PR will fix the following problem:

- The hexagonal color wheel in the floating style editor disappears on switching the rooms.
- Contents in the floating flipbook / color model disappear / wrongly offset on switching the rooms.
- Contents in the floating viewer / combo viewer are sometimes wrongly deformed on switching the rooms.

All the above floating panels come back to normal once you resize them.

I added lines to call `resizeGL()` on switching context, which seems to be needed to display properly.

### CODE REVIEW

**Comment by shun-iwasawa** [comment]
Jenkins

**Comment by shun-iwasawa** [comment]
Found a problem that OT crashes with 3DLUT. I'll check it right away.

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by manongjohn** [comment]
Testing the artifact, this did not fix it on my machine (Win10, Intel HD Graphics 520).

**Comment by shun-iwasawa** [comment]
@manongjohn Thank you for testing. I found the probable cause and will modify this right away.

**Comment by shun-iwasawa** [comment]
Jenkins again

**Comment by manongjohn** [comment]
I verified the latest fix corrected the issue.

**Comment by shun-iwasawa** [comment]
Conflicts resolved. Jenkins again

**Comment by shun-iwasawa** [comment]
Thank you @manongjohn for verifying. I'll merge this.

**Pull request merged**
